const common = {
  faq: { title: 'Domande Frequenti', badge: 'FAQ', description: 'Trova risposte alle domande più comuni sui nostri servizi.' },
  contact: { title: 'Contattaci', subtitle: 'Parliamo del tuo progetto strategico', name: 'Nome completo', email: 'Email', phone: 'Telefono', company: 'Organizzazione', message: 'Messaggio', submit: 'Invia', sending: 'Invio in corso…', success: 'Messaggio inviato con successo!', error: 'Si è verificato un errore.', address: 'Indirizzo', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Il tuo partner strategico in consulenza, audit finanziario, governance e trasformazione digitale', quickLinks: 'Link Rapidi', services: 'Servizi', about: 'Chi Siamo', blog: 'Blog', contact: 'Contatti', legalLinks: 'Legale', privacy: 'Privacy Policy', terms: 'Termini di Utilizzo', followUs: 'Seguici', rights: 'Tutti i diritti riservati.' },
  common: { learnMore: 'Scopri di più' },
  cta: { diagnostic_free: 'Diagnosi gratuita', diagnostic_subtitle: 'Risposta entro 2h · Senza impegno' },
  leadMagnet: { whitepaper: { title: 'Scarica il nostro White Paper', description: 'Analisi approfondita e raccomandazioni pratiche.', button: 'Scarica White Paper' }, webinar: { title: 'Partecipa al nostro Webinar', description: 'Scambia opinioni in diretta con i nostri esperti.', button: 'Iscriviti al Webinar' }, diagnostic: { title: 'Diagnosi Strategica Gratuita', description: '30 minuti con un esperto per analizzare la tua situazione.', button: 'Inizia la Diagnosi' }, newsletter: { title: 'Ricevi la nostra Newsletter Strategica', description: 'Analisi esclusive direttamente nella tua casella.', button: 'Iscriviti alla Newsletter' } },
  monitoring: { title: 'Monitoraggio Tecnico', subtitle: 'Errori 404 e tempi di risposta', loading: 'Caricamento dati…', retry: 'Riprova', timeRange: { '24h': '24h', '7d': '7 giorni', '30d': '30 giorni' }, stats: { total404: 'Errori 404', total404Sub: 'Pagine mancanti', totalErrors: 'Errori HTTP/JS', totalErrorsSub: 'Richieste e script', avgResponse: 'Tempo API medio', avgResponseSub: 'ms', avgPageLoad: 'Caricamento pagina', avgPageLoadSub: 'ms' }, notFound: { title: 'Principali URL 404', subtitle: 'Pagine più frequentemente mancanti', url: 'URL', count: 'Occorrenze', empty: 'Nessun errore rilevato' }, performance: { title: 'Tempo di Risposta API', subtitle: 'Media e massimo', tooltipAvg: 'Media', tooltipMax: 'Max', tooltipCount: 'Richieste', empty: 'Nessun dato' }, topErrors: { title: 'Errori principali', subtitle: 'Errori più frequenti', empty: 'Nessun errore' }, errorLog: { title: 'Registro errori', subtitle: 'Errori recenti', type: 'Tipo', message: 'Messaggio', url: 'URL', date: 'Data', empty: 'Nessun errore recente' }, navigation: { title: 'Navigazione', subtitle: 'Tempi di caricamento', empty: 'Nessun dato' } },
  dashboard: { login: { title: 'Dashboard', subtitle: 'Accesso amministratori', passwordLabel: 'Password', passwordPlaceholder: 'Inserisci la password', loginButton: 'Accedi', incorrectPassword: 'Password errata' }, header: { title: 'Dashboard', subtitle: 'Monitoraggio conversioni e performance', timeRange: { '7d': '7 giorni', '30d': '30 giorni', '90d': '90 giorni', all: 'Tutto' }, refreshButton: 'Aggiorna' }, loading: 'Caricamento dati…', kpis: { totalLeads: { title: 'Totale Lead', subtitle: 'nuovi' } }, pipeline: { title: 'Pipeline di conversione' }, sources: { title: 'Fonti di acquisizione' }, formTypes: { title: 'Performance per tipo di modulo', ofTotal: 'del totale' }, recentLeads: { title: 'Lead recenti', table: { date: 'Data', contact: 'Contatto', organization: 'Organizzazione', type: 'Tipo', score: 'Punteggio', status: 'Stato', source: 'Fonte' } }, status: { new: 'Nuovo', meeting_scheduled: 'Riunione programmata', qualified: 'Qualificato', converted: 'Convertito', lost: 'Perso' }, formType: { contact: 'Contatto', diagnostic: 'Diagnosi', expert: 'Esperto', newsletter: 'Newsletter' }, metrics: { toolCompletions: { title: 'Strumenti Completati', subtitle: 'Diagnosi' } }, diagnostics: { title: 'Diagnosi Recenti', table: { date: 'Data', tool: 'Strumento', score: 'Punteggio' } }, downloads: { title: 'Download Recenti', table: { date: 'Data', resource: 'Risorsa', contact: 'Contatto', country: 'Paese' }, unknownResource: 'Risorsa sconosciuta' }, noData: 'Nessun dato', retry: 'Riprova' },
};

export default common;



