const regions = {
  pillar: {
    digitalTransformation: { seo: { title: 'Digital Transformation Africa: Strategic Guide for Financial Institutions | Khepra Experts', description: 'Comprehensive guide on digital transformation strategies for African financial institutions, banks, and fintech companies. Expert insights on digitalization, innovation, and technology adoption.', keywords: 'digital transformation Africa, banking digitalization, fintech innovation, digital strategy Africa, technology adoption, digital banking Africa' } },
    financialInclusion: { seo: { title: 'Financial Inclusion Africa: Strategies for Inclusive Finance | KHEPRA EXPERTS', description: 'Comprehensive guide on financial inclusion strategies, digital financial services, and inclusive finance policies across Africa. Expert insights on mobile money, agent banking, and financial access.', keywords: 'financial inclusion Africa, digital financial inclusion, inclusive finance, mobile money, financial access, agent banking, financial services Africa' } },
    fintechAdvisory: { seo: { title: 'Fintech Advisory Africa: Strategic Consulting for Fintech Innovation | KHEPRA EXPERTS', description: 'Expert guide on fintech strategy, innovation, ecosystem development, and regulatory compliance across African markets. Comprehensive fintech consulting services.', keywords: 'fintech consulting Africa, fintech strategy, fintech innovation, fintech ecosystem, fintech regulation, digital payments, mobile money' } },
    microfinanceTransformation: { seo: { title: 'Microfinance Transformation Africa: Digital Modernization Guide | KHEPRA EXPERTS', description: 'Comprehensive guide on microfinance digital transformation, modernization strategies, and innovation for African microfinance institutions. Expert insights on MFI digitalization.', keywords: 'microfinance digital transformation, microfinance modernization, digital microfinance, MFI innovation, microfinance technology, MFI digitalization' } },
    smeDevelopment: { seo: { title: 'SME Development Africa: Strategic Consulting for Small Business Growth | KHEPRA EXPERTS', description: 'Comprehensive guide on SME development, financing strategies, growth consulting, and transformation for African small and medium enterprises. Expert SME advisory services.', keywords: 'SME development consulting Africa, SME financing, SME growth strategy, small business Africa, SME transformation, entrepreneurship Africa' } },
  },

  regions: {
    westAfrica: { seo: { title: 'West Africa Strategic Consulting | UEMOA ECOWAS Fintech | Khepra Experts', description: 'Khepra Experts supports West African institutions in their digital and strategic transformation. UEMOA expertise, Nigerian fintech ecosystem, regional payment systems. 16 countries, 411M population.', keywords: 'consulting West Africa, UEMOA financial services, fintech Nigeria Ghana, mobile money West Africa, BCEAO compliance, digital transformation ECOWAS' } },
    francophoneAfrica: { seo: { title: 'Francophone Africa Consulting | UEMOA, CEMAC, Maghreb Financial Services | KHEPRA EXPERTS', description: 'Strategic advisory for Francophone African institutions: BCEAO/COBAC compliance, digital transformation, regional expansion, fintech strategy. 29 countries, 430M population, $950B GDP. UEMOA, CEMAC, Maghreb expertise.', keywords: 'Francophone Africa consulting, UEMOA financial services, CEMAC banking, BCEAO compliance, COBAC regulation, digital transformation francophone Africa, microfinance UEMOA, fintech CEMAC' } },
    uemoaCemac: { seo: { title: 'UEMOA & CEMAC Compliance Expertise | BCEAO COBAC Regulatory Consulting | Khepra Experts', description: 'Specialized consulting firm in UEMOA and CEMAC regulatory compliance. BCEAO, COBAC expertise, compliance for financial institutions, microfinance, fintech. Licensing and governance support. Basel II/III risk management, prudential reporting, electronic money regulations.', keywords: 'UEMOA compliance, CEMAC compliance, BCEAO consulting, COBAC consulting, microfinance regulations Africa, financial institution licensing, UEMOA prudential standards, CEMAC banking governance, electronic money regulations, mobile money compliance, Basel II III Africa, IFRS compliance, fintech regulatory Africa' } },
    africa: { seo: { title: 'Strategic Consulting Africa | Financial Inclusion, Fintech & Digital Transformation | Khepra Experts', description: 'Khepra Experts provides strategic advisory services across Africa: financial inclusion, fintech ecosystem development, digital transformation, microfinance modernization, SME development. 54 countries, 1.4B population, $3T GDP.', keywords: 'consulting Africa, strategic advisory Africa, financial inclusion Africa, fintech consulting Africa, digital transformation Africa, microfinance Africa, SME development Africa, banking Africa, mobile money Africa' } },
    afrique: { seo: { title: 'Strategic Consulting in Africa | Presence 15+ Countries | Khepra Experts', description: 'Pan-African consulting firm specialized in governance, financial audit and digital transformation. Active presence in 15+ West and Central African countries with deep local expertise. Financial inclusion consulting Africa, fintech advisory, microfinance consulting.', keywords: 'financial inclusion consulting Africa, fintech consulting Africa, digital transformation consulting Africa, microfinance consulting Africa, SME development advisory Africa, BCEAO compliance, COBAC regulations, strategic consulting West Africa, consulting Central Africa, UEMOA CEMAC advisory' } },
  },
};

export default regions;