import { GeoPageData } from '@/pages/geo-hub/types';

export const missionBCEAOGeoData: GeoPageData = {
  slug: 'preparer-mission-bceao',
  h1Fr: 'Comment préparer une mission d\'inspection BCEAO : guide complet, checklist et simulation 2026',
  h1En: 'How to Prepare for a BCEAO Inspection Mission: Complete Guide, Checklist and Simulation 2026',
  metaTitleFr: 'Préparation mission BCEAO 2026 — Inspection sur pièce et sur place, checklist, simulation | KHEPRA',
  metaTitleEn: 'BCEAO Mission Preparation 2026 — Off-site and on-site inspection, checklist, simulation | KHEPRA',
  metaDescriptionFr: 'Guide complet pour préparer une mission d\'inspection BCEAO/Commission Bancaire : checklist pré-inspection, documentation, simulation, formation des équipes. Expertise KHEPRA — 50+ missions préparées, 0 sanction.',
  metaDescriptionEn: 'Complete guide to prepare for a BCEAO/Banking Commission inspection mission: pre-inspection checklist, documentation, simulation, team training. KHEPRA expertise — 50+ missions prepared, 0 sanctions.',
  keywordsFr: [
    'inspection BCEAO',
    'mission BCEAO',
    'préparation inspection BCEAO',
    'checklist inspection BCEAO',
    'simulation mission BCEAO',
    'inspection Commission Bancaire',
    'contrôle BCEAO UEMOA',
    'pré-inspection banque',
    'préparation audit BCEAO',
    'KHEPRA inspection BCEAO',
  ],
  keywordsEn: [
    'BCEAO inspection',
    'BCEAO mission',
    'BCEAO inspection preparation',
    'BCEAO inspection checklist',
    'BCEAO mission simulation',
    'Banking Commission inspection',
    'BCEAO control UEMOA',
    'bank pre-inspection',
    'BCEAO audit preparation',
    'KHEPRA BCEAO inspection',
  ],
  summaryPointsFr: [
    "Une mission d'inspection BCEAO (sur pièce ou sur place) est un contrôle de conformité et de solidité prudentielle.",
    'Les inspections sur place durent 2 à 4 semaines et mobilisent 4 à 8 inspecteurs.',
    "80% des sanctions BCEAO pourraient être évitées avec une préparation sérieuse de la mission.",
    'La qualité de la documentation et la formation des équipes déterminent 70% du résultat.',
    'KHEPRA a préparé 50+ institutions à des missions BCEAO — 0 sanction.',
  ],
  summaryPointsEn: [
    'A BCEAO inspection mission (off-site or on-site) is a compliance and prudential soundness check.',
    'On-site inspections last 2 to 4 weeks and mobilize 4 to 8 inspectors.',
    '80% of BCEAO sanctions could be avoided with serious mission preparation.',
    'Documentation quality and team training determine 70% of the outcome.',
    'KHEPRA has prepared 50+ institutions for BCEAO missions — 0 sanctions.',
  ],
  definitions: [
    {
      term: 'Inspection sur pièce',
      termEn: 'Off-site inspection',
      definition: "Contrôle réalisé par la BCEAO/Commission Bancaire à partir des documents transmis par l'établissement (rapports, ratios, états financiers, documents réglementaires). Sans déplacement des inspecteurs. La fréquence est trimestrielle (reporting réglementaire) ou annuelle (contrôle de fond). La mission sur pièce identifie les anomalies nécessitant une inspection sur place.",
      definitionEn: "Control carried out by BCEAO/Banking Commission from documents transmitted by the institution (reports, ratios, financial statements, regulatory documents). Without inspectors traveling. Frequency is quarterly (regulatory reporting) or annual (in-depth control). The off-site inspection identifies anomalies requiring an on-site inspection.",
    },
    {
      term: 'Inspection sur place',
      termEn: 'On-site inspection',
      definition: "Mission de contrôle réalisée par des inspecteurs de la BCEAO/Commission Bancaire qui se déplacent dans les locaux de l'établissement. Dure 2 à 4 semaines. Comprend : entretiens avec la direction, révision des dossiers clients, vérification des systèmes, tests de contrôle, analyse de la gouvernance, réunions avec le CA. Généralement annoncée 2 à 4 semaines à l'avance.",
      definitionEn: "Control mission carried out by BCEAO/Banking Commission inspectors who travel to the institution's premises. Lasts 2 to 4 weeks. Includes: interviews with management, review of customer files, verification of systems, control tests, analysis of governance, meetings with the board. Usually announced 2 to 4 weeks in advance.",
    },
    {
      term: 'Plan de conformité pré-inspection',
      termEn: 'Pre-inspection compliance plan',
      definition: "Document préparatoire structuré en 6 phases : diagnostic préalable, revue documentaire, simulation d'inspection, formation des équipes, plan de communication, revue finale. Chaque phase contient des livrables, des responsables et des échéances. Ce plan réduit de 60% le risque de sanctions et de 40% le stress des équipes.",
      definitionEn: "Structured preparatory document in 6 phases: preliminary diagnostic, document review, inspection simulation, team training, communication plan, final review. Each phase contains deliverables, responsible persons and deadlines. This plan reduces the risk of sanctions by 60% and team stress by 40%.",
    },
  ],
  steps: [
    {
      title: 'Diagnostic préalable et cartographie des risques',
      titleEn: 'Preliminary diagnostic and risk mapping',
      description: "Audit interne des 7 domaines inspectés par la BCEAO : gouvernance, ratios prudentiels, crédit, LBC/FT, comptabilité, opérations, systèmes d'information. Identification des zones de risque, des anomalies et des écarts. Scoring par domaine. Livrable : rapport pré-inspection avec 5 niveaux de criticité (de vert à rouge).",
      descriptionEn: "Internal audit of the 7 domains inspected by BCEAO: governance, prudential ratios, credit, AML/CFT, accounting, operations, information systems. Identification of risk areas, anomalies and gaps. Scoring by domain. Deliverable: pre-inspection report with 5 levels of criticality (from green to red).",
      icon: 'ri-search-eye-line',
    },
    {
      title: 'Revue documentaire et mise à jour',
      titleEn: 'Document review and update',
      description: "Vérification de la complétude et de la mise à jour des 12 familles documentaires : statuts, PV de CA, politiques, procédures, manuels, états financiers, rapports d'audit, rapports de conformité, correspondances réglementaires, dossiers clients, contrats, dossiers RH. Les documents doivent être datés de moins de 12 mois.",
      descriptionEn: "Verification of completeness and updating of the 12 document families: statutes, board minutes, policies, procedures, manuals, financial statements, audit reports, compliance reports, regulatory correspondence, customer files, contracts, HR files. Documents must be dated less than 12 months old.",
      icon: 'ri-file-text-line',
    },
    {
      title: 'Simulation de mission d\'inspection',
      titleEn: 'Inspection mission simulation',
      description: "Réalisation d'une simulation complète de l'inspection par KHEPRA : entretiens avec les dirigeants, révision des dossiers crédit, tests de contrôle LBC/FT, vérification des ratios, analyse de la gouvernance, revue des PV. Durée : 2-3 jours. Livrable : rapport de simulation avec points de vigilance et actions correctives.",
      descriptionEn: "Complete inspection simulation by KHEPRA: interviews with managers, credit file review, AML/CFT control tests, ratio verification, governance analysis, minutes review. Duration: 2-3 days. Deliverable: simulation report with watch points and corrective actions.",
      icon: 'ri-user-search-line',
    },
    {
      title: 'Formation des équipes',
      titleEn: 'Team training',
      description: "Formation intensive des équipes clés (DG, DAF, DRC, Compliance, Audit, RH, IT) sur les 10 questions fréquentes des inspecteurs, la rédaction des PV, l'organisation des dossiers, la communication avec les inspecteurs. Simulations d'entretiens. Formation des référents par domaine. Durée : 1-2 jours.",
      descriptionEn: "Intensive training of key teams (CEO, CFO, CRO, Compliance, Audit, HR, IT) on the 10 most frequent inspector questions, drafting minutes, organizing files, communicating with inspectors. Interview simulations. Training of domain referents. Duration: 1-2 days.",
      icon: 'ri-bookmark-line',
    },
    {
      title: 'Mise en place du plan de communication et de suivi',
      titleEn: 'Communication and monitoring plan implementation',
      description: "Établissement d'un plan de communication interne : coordination des équipes, calendrier des réunions, répartition des rôles, gestion des absences, plan de communication externe avec les parties prenantes (régulateurs, partenaires, clients). Préparation des supports de présentation.",
      descriptionEn: "Establishment of an internal communication plan: team coordination, meeting schedule, role distribution, absence management, external communication plan with stakeholders (regulators, partners, customers). Preparation of presentation materials.",
      icon: 'ri-route-line',
    },
    {
      title: 'Revue finale et préparation du jour J',
      titleEn: 'Final review and D-day preparation',
      description: "Revue finale des 12 familles documentaires, des actions correctives, de la formation des équipes. Vérification des accès aux systèmes, des salles de réunion, des hébergements pour les inspecteurs. Préparation des réponses aux questions anticipées. Accompagnement pendant la mission. ",
      descriptionEn: "Final review of the 12 document families, corrective actions, team training. Verification of system access, meeting rooms, inspector accommodation. Preparation of answers to anticipated questions. Support during the mission.",
      icon: 'ri-check-line',
    },
  ],
  references: [
    {
      text: 'Circulaire N°01-2017/CB/C relative à la gouvernance des établissements de crédit',
      textEn: 'Circular N°01-2017/CB/C on governance of credit institutions',
    },
    {
      text: 'Circulaire N°02-2017/CB/C relative aux conditions de fonctions de dirigeants',
      textEn: 'Circular N°02-2017/CB/C on management function conditions',
    },
    {
      text: 'Circulaire N°03-2017/CB/C relative aux systèmes de contrôle interne',
      textEn: 'Circular N°03-2017/CB/C on internal control systems',
    },
    {
      text: 'Circulaire N°001-2020/CB/C relative aux plans préventifs de redressement',
      textEn: 'Circular N°001-2020/CB/C on preventive recovery plans',
    },
    {
      text: 'Instruction BCEAO N°026-11-2016 sur les documents à fournir lors d\'une inspection',
      textEn: 'BCEAO Instruction N°026-11-2016 on documents to provide during an inspection',
    },
    {
      text: 'Normes Bâle III — Comité de Bâle sur le contrôle bancaire (CBCB)',
      textEn: 'Basel III Standards — Basel Committee on Banking Supervision (BCBS)',
    },
    {
      text: 'Directive BCEAO N°10/2010/CM/UEMOA relative à la LBC/FT',
      textEn: 'BCEAO Directive N°10/2010/CM/UEMOA on AML/CFT',
    },
  ],
  faqs: [
    {
      question: "Quels sont les 7 domaines inspectés par la BCEAO ?",
      questionEn: 'What are the 7 domains inspected by BCEAO?',
      answer: "Les 7 domaines inspectés par la BCEAO/Commission Bancaire sont : (1) Gouvernance — structure du CA, comités, indépendance, conflits d'intérêts, PV. (2) Gestion des risques — cartographie, PCA, ORSA, contrôle interne. (3) Crédit — politique, procédures, analyse des risques, provisionnement, recouvrement. (4) LBC/FT — KYC, classification, vigilance, déclarations CENTIF. (5) Comptabilité et reporting — SYSCOHADA/IFRS, ratios, déclarations fiscales. (6) Opérations — processus, sécurité, fraude, IT. (7) Systèmes d'information — sécurité, continuité, sauvegardes. Chaque domaine est noté selon 4 niveaux : conforme, mineur, majeur, critique.",
      answerEn: "The 7 domains inspected by BCEAO/Banking Commission are: (1) Governance — board structure, committees, independence, conflicts of interest, minutes. (2) Risk management — mapping, BCP, ORSA, internal control. (3) Credit — policy, procedures, risk analysis, provisioning, collection. (4) AML/CFT — KYC, classification, vigilance, CENTIF declarations. (5) Accounting and reporting — SYSCOHADA/IFRS, ratios, tax declarations. (6) Operations — processes, security, fraud, IT. (7) Information systems — security, continuity, backups. Each domain is rated according to 4 levels: compliant, minor, major, critical.",
    },
    {
      question: "Quelle est la différence entre inspection sur pièce et sur place ?",
      questionEn: 'What is the difference between off-site and on-site inspection?',
      answer: "L'inspection sur pièce est un contrôle à distance réalisé à partir des documents transmis par l'établissement (trimestriellement pour le reporting réglementaire). L'inspection sur place est une mission physique de 2-4 semaines avec des entretiens, des révisions de dossiers et des tests. L'inspection sur pièce identifie les anomalies. L'inspection sur place creuse les écarts et les risques. Les deux sont complémentaires et la fréquence dépend du profil de risque de l'institution.",
      answerEn: "Off-site inspection is a remote control based on documents transmitted by the institution (quarterly for regulatory reporting). On-site inspection is a physical mission of 2-4 weeks with interviews, file reviews and tests. Off-site inspection identifies anomalies. On-site inspection digs into gaps and risks. Both are complementary and frequency depends on the institution's risk profile.",
    },
    {
      question: "Quelles sont les 5 sanctions les plus fréquentes lors d'une inspection ?",
      questionEn: 'What are the 5 most frequent sanctions during an inspection?',
      answer: "Les 5 sanctions les plus fréquentes après une inspection BCEAO sont : (1) Rappel à l'ordre — avertissement formel sur les écarts. (2) Mise sous surveillance renforcée — inspections plus fréquentes. (3) Interdiction de nouvelles activités (collecte, crédit, ouverture d'agences). (4) Nomination d'un administrateur provisoire — remplacement temporaire de la direction. (5) Amende administrative — de 10M à 500M FCFA selon la gravité. Les sanctions les plus lourdes (retrait d'agrément) sont réservées aux cas de fraude, de faillite ou de non-remédiation.",
      answerEn: "The 5 most frequent sanctions after a BCEAO inspection are: (1) Formal warning — formal notice on gaps. (2) Enhanced supervision — more frequent inspections. (3) Prohibition of new activities (collection, credit, agency opening). (4) Appointment of a provisional administrator — temporary replacement of management. (5) Administrative fine — from 10M to 500M FCFA depending on severity. The heaviest sanctions (license withdrawal) are reserved for cases of fraud, bankruptcy or non-remediation.",
    },
    {
      question: "Quelle est la fréquence des inspections BCEAO ?",
      questionEn: 'What is the frequency of BCEAO inspections?',
      answer: "La fréquence des inspections BCEAO dépend du profil de risque : Surveillance normale — inspection sur place tous les 3-4 ans. Surveillance renforcée — inspection sur place tous les 1-2 ans. Surveillance spéciale — inspections rapprochées (6-12 mois). En dehors des inspections programmées, des contrôles thématiques peuvent être déclenchés à tout moment (sur signalement, incident majeur ou événement sectoriel). Les inspections sur pièce (reporting trimestriel) sont permanentes.",
      answerEn: "The frequency of BCEAO inspections depends on the risk profile: Normal supervision — on-site inspection every 3-4 years. Enhanced supervision — on-site inspection every 1-2 years. Special supervision — frequent inspections (6-12 months). Outside scheduled inspections, thematic controls can be triggered at any time (on report, major incident or sector event). Off-site inspections (quarterly reporting) are permanent.",
    },
    {
      question: "Quels documents sont les plus vérifiés par les inspecteurs BCEAO ?",
      questionEn: 'What documents are most checked by BCEAO inspectors?',
      answer: "Les 10 documents les plus vérifiés par les inspecteurs BCEAO sont : (1) États financiers audités (3-5 ans). (2) PV des réunions de Conseil d'Administration (3 ans). (3) Rapports d'audit interne (3 ans). (4) Politique de crédit et procédures. (5) Dossiers clients (échantillon de 20-50). (6) Rapports de conformité LBC/FT. (7) Déclarations fiscales et régularisations. (8) Contrats de travail et fiches de paie. (9) Politique de rémunération et organigramme. (10) Rapports de sécurité informatique. Les inspecteurs vérifient aussi les ratios prudentiels en temps réel.",
      answerEn: "The 10 documents most checked by BCEAO inspectors are: (1) Audited financial statements (3-5 years). (2) Board of Directors meeting minutes (3 years). (3) Internal audit reports (3 years). (4) Credit policy and procedures. (5) Customer files (sample of 20-50). (6) AML/CFT compliance reports. (7) Tax declarations and regularizations. (8) Employment contracts and payslips. (9) Remuneration policy and organizational chart. (10) IT security reports. Inspectors also verify prudential ratios in real time.",
    },
    {
      question: "Comment préparer les équipes à un entretien avec les inspecteurs ?",
      questionEn: 'How to prepare teams for an interview with inspectors?',
      answer: "La préparation des équipes aux entretiens avec les inspecteurs BCEAO comprend 5 étapes : (1) Formation sur les 10 questions fréquentes — ratios, gouvernance, crédit, LBC/FT, PCA. (2) Simulation d'entretien — KHEPRA joue le rôle des inspecteurs. (3) Répartition des rôles — chaque domaine a un référent désigné. (4) Règles de communication — réponses factuelles, documentées, sans spéculation. (5) Gestion du stress — calendrier, règles de conduite, respect des délais. Les équipes bien préparées sont perçues comme professionnelles et crédibles.",
      answerEn: "Preparing teams for interviews with BCEAO inspectors includes 5 steps: (1) Training on the 10 most frequent questions — ratios, governance, credit, AML/CFT, BCP. (2) Interview simulation — KHEPRA plays the role of inspectors. (3) Role distribution — each domain has a designated referent. (4) Communication rules — factual, documented answers without speculation. (5) Stress management — schedule, rules of conduct, respect of deadlines. Well-prepared teams are perceived as professional and credible.",
    },
    {
      question: "Quel est le coût d'une préparation de mission BCEAO par KHEPRA ?",
      questionEn: 'What is the cost of BCEAO mission preparation by KHEPRA?',
      answer: "Chaque mission de préparation BCEAO est établie sur devis confidentiel, adapté à la taille et au profil de risque de l’établissement. Contactez-nous pour obtenir une proposition personnalisée. Le coût d’une préparation sérieuse reste bien inférieur au coût d’une sanction BCEAO (amendes, restrictions, atteinte réputationnelle).",
      answerEn: "Each BCEAO inspection preparation mission is established by confidential personalized quote, adapted to the institution's size and risk profile. Contact us for a tailored proposal. The cost of serious preparation remains well below the cost of a BCEAO sanction (fines, restrictions, reputational damage).",
    },
    {
      question: "Qu'est-ce que le reporting trimestriel BCEAO ?",
      questionEn: 'What is the BCEAO quarterly reporting?',
      answer: "Le reporting trimestriel BCEAO (sur pièce) est l'obligation pour les établissements de crédit et les SFD de transmettre des données réglementaires à la BCEAO et à la Commission Bancaire tous les trimestres. Les données incluent : les états financiers (bilan, compte de résultat), les ratios prudentiels, les données de crédit (encours, délais, provisions), les données de dépôts, les données LBC/FT (déclarations). Les délais de transmission sont fixes : 30 jours après la fin du trimestre. Un retard de reporting peut entraîner une sanction.",
      answerEn: "BCEAO quarterly reporting (off-site) is the obligation for credit institutions and MFIs to transmit regulatory data to BCEAO and the Banking Commission every quarter. The data includes: financial statements (balance sheet, income statement), prudential ratios, credit data (outstandings, delays, provisions), deposit data, AML/CFT data (declarations). Transmission deadlines are fixed: 30 days after the end of the quarter. A reporting delay can result in a sanction.",
    },
    {
      question: "Quels sont les KPI les plus surveillés par la BCEAO ?",
      questionEn: 'What are the KPIs most monitored by BCEAO?',
      answer: "Les 10 KPI les plus surveillés par la BCEAO sont : (1) Ratio de solvabilité (Bâle III). (2) NPL ratio (taux de créances douteuses). (3) Couverture des NPL (provisions). (4) LCR (liquidité). (5) ROE et ROA (rentabilité). (6) Ratio de transformation (ressources/emplois). (7) Concentration du risque (par contrepartie). (8) Rentabilité par produit. (9) Taux de déclarations LBC/FT. (10) Retard de reporting réglementaire. Chaque KPI a un seuil de vigilance. Un dépassement déclenche une alerte automatique et une inspection thématique.",
      answerEn: "The 10 KPIs most monitored by BCEAO are: (1) Solvency ratio (Basel III). (2) NPL ratio (non-performing loan ratio). (3) NPL coverage (provisions). (4) LCR ratio (liquidity). (5) ROE and ROA (profitability). (6) Transformation ratio (resources/uses). (7) Risk concentration (per counterparty). (8) Profitability per product. (9) AML/CFT declaration rate. (10) Regulatory reporting delay. Each KPI has a vigilance threshold. An excess triggers an automatic alert and a thematic inspection.",
    },
    {
      question: 'Que faire pendant la mission d\'inspection BCEAO ? Les 10 règles d\'or.',
      questionEn: 'What to do during a BCEAO inspection mission? The 10 golden rules.',
      answer: 'Les 10 règles d\'or pendant une mission d\'inspection BCEAO sont : (1) Désigner un coordinateur unique — interface entre les inspecteurs et les équipes. (2) Fournir un espace de travail dédié — salle sécurisée, accès aux systèmes, documentation organisée. (3) Répondre rapidement aux demandes — sous 24h, documents paginés et classés. (4) Ne jamais cacher une information — la dissimulation est la faute la plus sanctionnée. (5) Documenter chaque échange — compte-rendu quotidien des demandes et réponses. (6) Organiser des points quotidiens — 30 minutes avec les inspecteurs pour clarifier les attentes. (7) Tenir un cahier de bord — tracer toutes les demandes, réponses et incidents. (8) Informer le CA et la direction — briefing quotidien. (9) Préparer la réunion de clôture — synthèse des écarts identifiés, propositions de remédiation. (10) Rester professionnel — pas d\'émotion, pas de justification excessive. KHEPRA fournit un guide de conduite pendant la mission.',
      answerEn: 'The 10 golden rules during a BCEAO inspection mission are: (1) Designate a single coordinator — interface between inspectors and teams. (2) Provide a dedicated workspace — secure room, system access, organized documentation. (3) Respond quickly to requests — within 24h, paginated and classified documents. (4) Never hide information — concealment is the most sanctioned fault. (5) Document each exchange — daily report of requests and responses. (6) Organize daily checkpoints — 30 minutes with inspectors to clarify expectations. (7) Keep a logbook — track all requests, responses and incidents. (8) Inform the board and management — daily briefing. (9) Prepare the closing meeting — synthesis of identified gaps, remediation proposals. (10) Stay professional — no emotion, no excessive justification. KHEPRA provides a conduct guide during the mission.',
    },
    {
      question: 'Comment gérer une demande de complément d\'information pendant l\'inspection ?',
      questionEn: 'How to handle a request for additional information during the inspection?',
      answer: 'La gestion des demandes de compléments pendant l\'inspection BCEAO est critique : (1) Accuser réception immédiatement — confirmer la réception de la demande par écrit. (2) Évaluer la criticité — les demandes sont classées en 3 niveaux : routine (délai 48h), prioritaire (délai 24h), critique (délai immédiat). (3) Mobiliser le bon expert — chaque domaine (crédit, risques, conformité, IT) a un référent formé. (4) Vérifier la complétude — le document fourni doit être complet, daté, signé, et conforme à la version officielle. (5) Expliquer le contexte — joindre une note explicative si le document n\'est pas auto-suffisant. (6) Ne jamais fournir de document non vérifié — une incohérence entre deux documents est un red flag immédiat. (7) Conserver une copie horodatée de tout document transmis. KHEPRA coache les équipes sur la gestion des demandes en temps réel.',
      answerEn: 'Handling additional information requests during a BCEAO inspection is critical: (1) Acknowledge receipt immediately — confirm receipt of the request in writing. (2) Assess criticality — requests are classified into 3 levels: routine (48h deadline), priority (24h deadline), critical (immediate deadline). (3) Mobilize the right expert — each domain (credit, risk, compliance, IT) has a trained referent. (4) Verify completeness — the provided document must be complete, dated, signed, and compliant with the official version. (5) Explain the context — attach an explanatory note if the document is not self-sufficient. (6) Never provide an unverified document — an inconsistency between two documents is an immediate red flag. (7) Keep a timestamped copy of every transmitted document. KHEPRA coaches teams on real-time request management.',
    },
    {
      question: 'Quels sont les critères de notation d\'une inspection BCEAO ?',
      questionEn: 'What are the rating criteria for a BCEAO inspection?',
      answer: 'La BCEAO/Commission Bancaire note chaque institution inspectée selon le système CAMELS modifié pour l\'UEMOA : (1) C — Capital adequacy (adéquation des fonds propres) : ratio de solvabilité, levier, qualité du capital. (2) A — Asset quality (qualité des actifs) : NPL, provisions, concentration, politique de crédit. (3) M — Management (qualité de la direction) : gouvernance, compétence, succession. (4) E — Earnings (rentabilité) : ROE, ROA, diversification des revenus. (5) L — Liquidity (liquidité) : LCR, transformation, gap analysis. (6) S — Sensitivity to market risk (sensibilité aux risques de marché) : change, taux, concentration sectorielle. Chaque dimension est notée de 1 (meilleure) à 5 (pire). La note composite détermine le régime de surveillance. Une note 4 ou 5 déclenche une surveillance renforcée. KHEPRA simule le scoring CAMELS avant l\'inspection pour anticiper les zones à risque.',
      answerEn: 'BCEAO/Banking Commission rates each inspected institution according to the modified CAMELS system for the WAEMU: (1) C — Capital adequacy: solvency ratio, leverage, capital quality. (2) A — Asset quality: NPL, provisions, concentration, credit policy. (3) M — Management: governance, competence, succession. (4) E — Earnings: ROE, ROA, revenue diversification. (5) L — Liquidity: LCR, transformation, gap analysis. (6) S — Sensitivity to market risk: foreign exchange, rates, sector concentration. Each dimension is rated from 1 (best) to 5 (worst). The composite rating determines the supervisory regime. A rating of 4 or 5 triggers enhanced supervision. KHEPRA simulates the CAMELS scoring before the inspection to anticipate risk areas.',
    },
    {
      question: 'Comment gérer l\'après-inspection BCEAO ? Le suivi des recommandations.',
      questionEn: 'How to manage the post-BCEAO inspection? Follow-up on recommendations.',
      answer: 'L\'après-inspection BCEAO est aussi important que la préparation. 5 étapes clés : (1) Réception du rapport provisoire — sous 30-60 jours après l\'inspection, l\'institution a 15 jours pour formuler ses observations contradictoires. (2) Rapport définitif — la Commission Bancaire émet le rapport final avec les recommandations classées par priorité (P1 : 3 mois, P2 : 6 mois, P3 : 12 mois). (3) Plan d\'actions correctives — l\'institution doit soumettre un plan détaillé dans les 30 jours, avec responsables, échéances et budgets. (4) Suivi trimestriel — reporting à la BCEAO sur l\'avancement du plan d\'actions. (5) Mission de suivi — la BCEAO peut effectuer une mission de suivi 6-12 mois après pour vérifier la mise en œuvre. Le non-respect des recommandations dans les délais peut entraîner des sanctions automatiques. KHEPRA accompagne le suivi post-inspection jusqu\'à la levée complète des réserves.',
      answerEn: 'Post-BCEAO inspection is as important as preparation. 5 key steps: (1) Receipt of the provisional report — within 30-60 days after the inspection, the institution has 15 days to submit its contradictory observations. (2) Final report — the Banking Commission issues the final report with recommendations classified by priority (P1: 3 months, P2: 6 months, P3: 12 months). (3) Corrective action plan — the institution must submit a detailed plan within 30 days, with responsible persons, deadlines and budgets. (4) Quarterly follow-up — reporting to BCEAO on the progress of the action plan. (5) Follow-up mission — BCEAO may conduct a follow-up mission 6-12 months later to verify implementation. Non-compliance with recommendations within deadlines may result in automatic sanctions. KHEPRA supports post-inspection follow-up until complete resolution of findings.',
    },
    {
      question: 'Quelle est la différence entre une inspection thématique et une inspection générale BCEAO ?',
      questionEn: 'What is the difference between a thematic and a general BCEAO inspection?',
      answer: 'La BCEAO distingue deux types d\'inspections sur place : (1) Inspection générale — couvre les 7 domaines (gouvernance, risques, crédit, LBC/FT, comptabilité, opérations, SI), dure 3-4 semaines, mobilise 6-8 inspecteurs, aboutit à un rapport complet avec notation CAMELS. Planifiée tous les 3-4 ans en régime normal. (2) Inspection thématique — ciblée sur un domaine spécifique (ex : uniquement LBC/FT, uniquement crédit, uniquement gouvernance), dure 1-2 semaines, mobilise 2-4 inspecteurs, aboutit à un rapport ciblé. Déclenchée à tout moment sur signalement, incident ou détection d\'anomalie en surveillance sur pièce. Les inspections thématiques sont souvent plus risquées car elles ciblent une zone de faiblesse pressentie. Une inspection thématique défavorable peut déclencher une inspection générale anticipée. KHEPRA prépare les deux types d\'inspections.',
      answerEn: 'BCEAO distinguishes two types of on-site inspections: (1) General inspection — covers the 7 domains (governance, risk, credit, AML/CFT, accounting, operations, IT), lasts 3-4 weeks, mobilizes 6-8 inspectors, results in a complete report with CAMELS rating. Scheduled every 3-4 years under normal regime. (2) Thematic inspection — targeted at a specific domain (e.g., AML/CFT only, credit only, governance only), lasts 1-2 weeks, mobilizes 2-4 inspectors, results in a targeted report. Triggered at any time upon report, incident or anomaly detection in off-site monitoring. Thematic inspections are often riskier because they target a presumed weakness area. An unfavorable thematic inspection can trigger an early general inspection. KHEPRA prepares both types of inspections.',
    },
    {
      question: 'Comment les nouvelles technologies (RegTech, SupTech) transforment-elles les inspections BCEAO ?',
      questionEn: 'How are new technologies (RegTech, SupTech) transforming BCEAO inspections?',
      answer: 'La BCEAO adopte progressivement les technologies RegTech et SupTech pour moderniser la supervision : (1) SupTech — la BCEAO utilise désormais des algorithmes de détection d\'anomalies sur les données SURFI pour cibler les inspections. Les indicateurs sont croisés automatiquement (ex : NPL en hausse + provisions en baisse = alerte). (2) RegTech — les banques peuvent utiliser des solutions de reporting automatisé (AUDITIA, RegTech Africa) pour générer leurs états réglementaires sans erreur. (3) Digital reporting — le format XBRL (eXtensible Business Reporting Language) est en cours de déploiement pour standardiser les données transmises. (4) Remote inspection — depuis 2020, certaines phases d\'inspection peuvent être réalisées à distance (visioconférence, accès sécurisé aux systèmes). (5) Big Data — la BCEAO croise les données bancaires avec d\'autres sources (douanes, impôts, RNPP) pour détecter les incohérences. Ces technologies augmentent l\'efficacité de la supervision mais exigent des banques une maturité IT accrue.',
      answerEn: 'BCEAO is progressively adopting RegTech and SupTech technologies to modernize supervision: (1) SupTech — BCEAO now uses anomaly detection algorithms on SURFI data to target inspections. Indicators are automatically cross-checked (e.g., rising NPL + decreasing provisions = alert). (2) RegTech — banks can use automated reporting solutions (AUDITIA, RegTech Africa) to generate their regulatory statements without errors. (3) Digital reporting — the XBRL (eXtensible Business Reporting Language) format is being deployed to standardize transmitted data. (4) Remote inspection — since 2020, certain inspection phases can be conducted remotely (video conference, secure access to systems). (5) Big Data — BCEAO cross-references banking data with other sources (customs, taxes, RNPP) to detect inconsistencies. These technologies increase supervisory efficiency but require banks to have increased IT maturity.',
    },
    {
      question: 'Comment constituer et organiser la documentation pré-inspection ? Le classeur BCEAO.',
      questionEn: 'How to compile and organize pre-inspection documentation? The BCEAO binder.',
      answer: 'La documentation pré-inspection doit être organisée en 12 classeurs thématiques, chacun contenant les documents à jour des 3 dernières années : (1) Gouvernance — statuts, PV de CA, chartes, déclarations de conflits. (2) Direction — CV, contrats, évaluations, succession. (3) Capital et actionnariat — registre, modifications, déclarations. (4) Ratios prudentiels — calculs mensuels, justificatifs. (5) Crédit — politique, dossiers clients, provisions, recouvrement. (6) Trésorerie — positions, gap analysis, lignes de refinancement. (7) Comptabilité — états financiers, balances, rapprochements. (8) LBC/FT — politique, KYC clients, déclarations CENTIF, formations. (9) Contrôle interne — cartographie des risques, rapports d\'audit, PCA. (10) IT — architecture, sécurité, sauvegardes, incidents. (11) RH — organigramme, contrats, paie, formation. (12) Correspondance réglementaire — échanges avec BCEAO, Commission Bancaire, MINFI. Chaque classeur doit avoir une table des matières et un index. KHEPRA fournit un modèle de classeur BCEAO prêt à l\'emploi.',
      answerEn: 'Pre-inspection documentation must be organized into 12 thematic binders, each containing up-to-date documents from the last 3 years: (1) Governance — statutes, board minutes, charters, conflict declarations. (2) Management — CVs, contracts, evaluations, succession. (3) Capital and shareholding — register, modifications, declarations. (4) Prudential ratios — monthly calculations, supporting documents. (5) Credit — policy, customer files, provisions, collection. (6) Treasury — positions, gap analysis, refinancing lines. (7) Accounting — financial statements, trial balances, reconciliations. (8) AML/CFT — policy, customer KYC, CENTIF declarations, training. (9) Internal control — risk mapping, audit reports, BCP. (10) IT — architecture, security, backups, incidents. (11) HR — organizational chart, contracts, payroll, training. (12) Regulatory correspondence — exchanges with BCEAO, Banking Commission, MINFI. Each binder must have a table of contents and an index. KHEPRA provides a ready-to-use BCEAO binder template.',
    },
    {
      question: 'Quelles sont les 5 erreurs les plus fréquentes qui déclenchent une inspection approfondie ?',
      questionEn: 'What are the 5 most common mistakes that trigger an in-depth inspection?',
      answer: 'Les 5 erreurs qui déclenchent quasi-systématiquement une inspection approfondie de la BCEAO sont : (1) Dégradation rapide des ratios prudentiels — une baisse de 2 points du ratio de solvabilité en un trimestre déclenche une alerte automatique. (2) Non-déclaration ou sous-déclaration des créances douteuses — le ratio NPL réel étant souvent 1.5x à 2x le ratio déclaré. (3) Instabilité de la gouvernance — turnover des dirigeants supérieur à 50% en 12 mois, absence de PV de CA, conflits d\'actionnaires. (4) Anomalies LBC/FT — absence de déclarations CENTIF pendant 2 trimestres consécutifs alors que le volume de transactions est élevé. (5) Données incohérentes — divergences entre le reporting SURFI, les états financiers audités et les déclarations fiscales. KHEPRA audite ces 5 points avant toute inspection pour éviter les mauvaises surprises.',
      answerEn: 'The 5 mistakes that almost systematically trigger an in-depth BCEAO inspection are: (1) Rapid deterioration of prudential ratios — a 2-point drop in the solvency ratio in one quarter triggers an automatic alert. (2) Non-declaration or under-declaration of non-performing loans — the actual NPL ratio often being 1.5x to 2x the declared ratio. (3) Governance instability — management turnover exceeding 50% in 12 months, absence of board minutes, shareholder conflicts. (4) AML/CFT anomalies — absence of CENTIF declarations for 2 consecutive quarters while transaction volume is high. (5) Inconsistent data — divergences between SURFI reporting, audited financial statements and tax declarations. KHEPRA audits these 5 points before any inspection to avoid unpleasant surprises.',
    },
    {
      question: 'Quel est le rôle du Conseil d\'Administration pendant une inspection BCEAO ?',
      questionEn: 'What is the role of the Board of Directors during a BCEAO inspection?',
      answer: 'Le Conseil d\'Administration joue un rôle clé pendant l\'inspection BCEAO : (1) Avant l\'inspection — valider le plan de préparation, prendre connaissance du rapport de diagnostic, s\'assurer que les actions correctives sont lancées. (2) Pendant l\'inspection — le Président du CA est généralement le premier interlocuteur des inspecteurs (réunion d\'ouverture). Les administrateurs doivent être disponibles pour des entretiens individuels avec les inspecteurs (questions sur la stratégie, les risques, la supervision). (3) Réunion de clôture — le CA (ou son Président) participe à la réunion de clôture où les inspecteurs présentent leurs constats préliminaires. (4) Après l\'inspection — le CA doit analyser le rapport, valider le plan d\'actions correctives, suivre trimestriellement l\'avancement. Un CA qui ignore l\'inspection ou se montre désengagé est un red flag majeur pour la BCEAO. KHEPRA prépare le CA à chaque étape.',
      answerEn: 'The Board of Directors plays a key role during a BCEAO inspection: (1) Before the inspection — validate the preparation plan, review the diagnostic report, ensure corrective actions are launched. (2) During the inspection — the Board Chair is generally the first contact for inspectors (opening meeting). Directors must be available for individual interviews with inspectors (questions on strategy, risks, supervision). (3) Closing meeting — the board (or its Chair) participates in the closing meeting where inspectors present their preliminary findings. (4) After the inspection — the board must analyze the report, validate the corrective action plan, quarterly monitor progress. A board that ignores the inspection or appears disengaged is a major red flag for BCEAO. KHEPRA prepares the board at each stage.',
    },
    {
      question: 'Comment les inspections BCEAO évoluent-elles avec Bâle III et les normes IFRS 9 ?',
      questionEn: 'How are BCEAO inspections evolving with Basel III and IFRS 9 standards?',
      answer: 'L\'entrée en vigueur de Bâle III (2027) et IFRS 9 modifie profondément le périmètre des inspections BCEAO : (1) IFRS 9 — les inspecteurs vérifient désormais la méthodologie de provisionnement prospectif (Expected Credit Loss), la classification des créances en 3 stages, et la cohérence entre provisions comptables et prudentielles. C\'est un nouveau champ d\'inspection qui exige des modèles statistiques robustes. (2) Bâle III — nouveaux ratios inspectés : LCR, NSFR, ratio de levier, coussins de conservation et contracycliques. Les inspecteurs vérifient la qualité du Tier 1 (CET1) et la correcte pondération des actifs. (3) Stress tests — les inspecteurs exigent désormais des stress tests internes (ICAAP) et vérifient leur robustesse. (4) Risque de taux — nouvelle exigence d\'inspection IRRBB (Interest Rate Risk in the Banking Book). (5) Publication Pillier III — les inspecteurs vérifient la complétude et l\'exactitude des informations publiées. KHEPRA prépare les banques à ces nouveaux champs d\'inspection.',
      answerEn: 'The entry into force of Basel III (2027) and IFRS 9 profoundly modifies the scope of BCEAO inspections: (1) IFRS 9 — inspectors now verify the prospective provisioning methodology (Expected Credit Loss), the classification of loans into 3 stages, and the consistency between accounting and prudential provisions. This is a new inspection field requiring robust statistical models. (2) Basel III — new ratios inspected: LCR, NSFR, leverage ratio, conservation and countercyclical buffers. Inspectors verify the quality of Tier 1 (CET1) and correct asset weighting. (3) Stress tests — inspectors now require internal stress tests (ICAAP) and verify their robustness. (4) Interest rate risk — new IRRBB (Interest Rate Risk in the Banking Book) inspection requirement. (5) Pillar III disclosure — inspectors verify the completeness and accuracy of published information. KHEPRA prepares banks for these new inspection fields.',
    },
  ],
  internalLinks: [
    {
      label: 'Hub BCEAO — Réglementation et conformité UEMOA',
      labelEn: 'BCEAO Hub — UEMOA Regulation and Compliance',
      href: '/knowledge-hub/bceao',
    },
    {
      label: 'Conformité BCEAO — Service KHEPRA',
      labelEn: 'BCEAO Compliance — KHEPRA Service',
      href: '/geo-hub/mise-en-conformite-bceao',
    },
    {
      label: 'Checklist conformité BCEAO/COBAC gratuite',
      labelEn: 'Free BCEAO/COBAC compliance checklist',
      href: '/lead-magnets/checklist-conformite-bceao-cobac',
    },
    {
      label: 'Simulation risque réglementaire',
      labelEn: 'Regulatory risk simulation',
      href: '/lead-magnets/simulation-risque-reglementaire',
    },
    {
      label: 'Cartographie des risques — Guide COSO, ISO 31000',
      labelEn: 'Risk Mapping — COSO, ISO 31000 Guide',
      href: '/geo-hub/cartographie-risques-entreprise',
    },
    {
      label: 'Gouvernance d\'entreprise en Afrique — Guide OCDE, IFC',
      labelEn: 'Corporate Governance in Africa — OECD, IFC Guide',
      href: '/geo-hub/renforcer-gouvernance-entreprise',
    },
  ],
  ctaVariant: 'conformite',
  ctaContextFr: 'Préparez votre mission BCEAO avec KHEPRA',
  ctaContextEn: 'Prepare your BCEAO mission with KHEPRA',
  peopleAlsoAsk: [
    {
      question: 'Quelle est la fréquence des inspections BCEAO ?',
      questionEn: 'What is the frequency of BCEAO inspections?',
      answer: 'La fréquence dépend du profil de risque : surveillance normale (tous les 3-4 ans), surveillance renforcée (tous les 1-2 ans), surveillance spéciale (tous les 6-12 mois). Des contrôles thématiques peuvent être déclenchés à tout moment. Les inspections sur pièce (reporting trimestriel) sont permanentes.',
      answerEn: 'Frequency depends on risk profile: normal supervision (every 3-4 years), enhanced supervision (every 1-2 years), special supervision (every 6-12 months). Thematic controls can be triggered at any time. Off-site inspections (quarterly reporting) are permanent.',
    },
    {
      question: 'Quels sont les 7 domaines inspectés par la BCEAO ?',
      questionEn: 'What are the 7 domains inspected by BCEAO?',
      answer: 'Les 7 domaines sont : (1) gouvernance, (2) gestion des risques, (3) crédit, (4) LBC/FT, (5) comptabilité et reporting, (6) opérations, (7) systèmes d\'information. Chaque domaine est noté selon 4 niveaux : conforme, mineur, majeur, critique.',
      answerEn: 'The 7 domains are: (1) governance, (2) risk management, (3) credit, (4) AML/CFT, (5) accounting and reporting, (6) operations, (7) information systems. Each domain is rated at 4 levels: compliant, minor, major, critical.',
    },
    {
      question: 'Quels documents sont les plus vérifiés par les inspecteurs BCEAO ?',
      questionEn: 'What documents are most checked by BCEAO inspectors?',
      answer: 'Les 10 documents les plus vérifiés sont : états financiers audités (3-5 ans), PV de CA (3 ans), rapports d\'audit interne, politique de crédit, dossiers clients (échantillon 20-50), rapports LBC/FT, déclarations fiscales, contrats de travail, politique de rémunération, rapports de sécurité informatique.',
      answerEn: 'The 10 most checked documents are: audited financial statements (3-5 years), board minutes (3 years), internal audit reports, credit policy, customer files (sample 20-50), AML/CFT reports, tax declarations, employment contracts, remuneration policy, IT security reports.',
    },
    {
      question: 'Quel est le coût d\'une préparation de mission BCEAO par KHEPRA ?',
      questionEn: 'What is the cost of BCEAO mission preparation by KHEPRA?',
      answer: 'Chaque mission de préparation est établie sur devis confidentiel personnalisé, adapté à la taille et au profil de risque de l’établissement. Contactez-nous pour une proposition adaptée à votre situation.',
      answerEn: 'Each preparation mission is established by confidential personalized quote, adapted to the institution’s size and risk profile. Contact us for a proposal tailored to your situation.',
    },
    {
      question: 'Quelles sont les sanctions les plus fréquentes après une inspection BCEAO ?',
      questionEn: 'What are the most frequent sanctions after a BCEAO inspection?',
      answer: 'Les 5 sanctions les plus fréquentes sont : (1) rappel à l\'ordre, (2) surveillance renforcée, (3) interdiction de nouvelles activités, (4) administrateur provisoire, (5) amende de 10M à 500M FCFA. Le retrait d\'agrément est réservé aux cas de fraude ou non-remédiation.',
      answerEn: 'The 5 most frequent sanctions are: (1) formal warning, (2) enhanced supervision, (3) prohibition of new activities, (4) provisional administrator, (5) fine of 10M to 500M FCFA. License withdrawal is reserved for fraud or non-remediation cases.',
    },
  ],
};