const common = {
  faq: { title: 'Preguntas Frecuentes', badge: 'FAQ', description: 'Encuentre respuestas a las preguntas más comunes sobre nuestros servicios.' },
  contact: { title: 'Contáctenos', subtitle: 'Hablemos de su proyecto estratégico', name: 'Nombre completo', email: 'Correo electrónico', phone: 'Teléfono', company: 'Organización', message: 'Mensaje', submit: 'Enviar', sending: 'Enviando…', success: '¡Mensaje enviado con éxito!', error: 'Ha ocurrido un error.', address: 'Dirección', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Su socio estratégico en consultoría, auditoría financiera, gobernanza y transformación digital', quickLinks: 'Enlaces Rápidos', services: 'Servicios', about: 'Acerca de', blog: 'Blog', contact: 'Contacto', legalLinks: 'Legal', privacy: 'Política de Privacidad', terms: 'Términos de Uso', followUs: 'Síguenos', rights: 'Todos los derechos reservados.' },
  common: { learnMore: 'Saber más' },
  cta: { diagnostic_free: 'Diagnóstico gratuito', diagnostic_subtitle: 'Respuesta en 2h · Sin compromiso' },
  leadMagnet: { whitepaper: { title: 'Descargue nuestro White Paper', description: 'Análisis profundo y recomendaciones prácticas.', button: 'Descargar White Paper' }, webinar: { title: 'Únase a nuestro Próximo Webinar', description: 'Intercambie en directo con nuestros expertos.', button: 'Inscribirse al Webinar' }, diagnostic: { title: 'Diagnóstico Estratégico Gratuito', description: '30 minutos con un experto para analizar su situación.', button: 'Iniciar Diagnóstico' }, newsletter: { title: 'Reciba nuestro Boletín Estratégico', description: 'Análisis exclusivos directamente en su correo.', button: 'Suscribirse al Boletín' } },
  monitoring: { title: 'Monitoreo Técnico', subtitle: 'Errores 404 y tiempos de respuesta', loading: 'Cargando datos…', retry: 'Reintentar', timeRange: { '24h': '24h', '7d': '7 días', '30d': '30 días' }, stats: { total404: 'Errores 404', total404Sub: 'Páginas no encontradas', totalErrors: 'Errores HTTP/JS', totalErrorsSub: 'Solicitudes y scripts', avgResponse: 'Tiempo API medio', avgResponseSub: 'ms', avgPageLoad: 'Carga de página', avgPageLoadSub: 'ms' }, notFound: { title: 'Principales URLs 404', subtitle: 'Páginas más frecuentemente no encontradas', url: 'URL', count: 'Ocurrencias', empty: 'Sin errores detectados' }, performance: { title: 'Tiempo de Respuesta API', subtitle: 'Media y máximo', tooltipAvg: 'Media', tooltipMax: 'Máx', tooltipCount: 'Solicitudes', empty: 'Sin datos' }, topErrors: { title: 'Principales errores', subtitle: 'Errores más frecuentes', empty: 'Sin errores' }, errorLog: { title: 'Registro de errores', subtitle: 'Errores recientes', type: 'Tipo', message: 'Mensaje', url: 'URL', date: 'Fecha', empty: 'Sin errores recientes' }, navigation: { title: 'Navegación', subtitle: 'Tiempos de carga', empty: 'Sin datos' } },
  dashboard: { login: { title: 'Panel de Control', subtitle: 'Acceso de administradores', passwordLabel: 'Contraseña', passwordPlaceholder: 'Ingrese la contraseña', loginButton: 'Iniciar sesión', incorrectPassword: 'Contraseña incorrecta' }, header: { title: 'Panel de Control', subtitle: 'Seguimiento de conversiones y rendimiento', timeRange: { '7d': '7 días', '30d': '30 días', '90d': '90 días', all: 'Todo' }, refreshButton: 'Actualizar' }, loading: 'Cargando datos…', kpis: { totalLeads: { title: 'Total Leads', subtitle: 'nuevos' } }, pipeline: { title: 'Pipeline de conversión' }, sources: { title: 'Fuentes de adquisición' }, formTypes: { title: 'Rendimiento por tipo de formulario', ofTotal: 'del total' }, recentLeads: { title: 'Leads recientes', table: { date: 'Fecha', contact: 'Contacto', organization: 'Organización', type: 'Tipo', score: 'Puntuación', status: 'Estado', source: 'Fuente' } }, status: { new: 'Nuevo', meeting_scheduled: 'Reunión programada', qualified: 'Calificado', converted: 'Convertido', lost: 'Perdido' }, formType: { contact: 'Contacto', diagnostic: 'Diagnóstico', expert: 'Experto', newsletter: 'Boletín' }, metrics: { toolCompletions: { title: 'Herramientas Completadas', subtitle: 'Diagnósticos' } }, diagnostics: { title: 'Diagnósticos Recientes', table: { date: 'Fecha', tool: 'Herramienta', score: 'Puntuación' } }, downloads: { title: 'Descargas Recientes', table: { date: 'Fecha', resource: 'Recurso', contact: 'Contacto', country: 'País' }, unknownResource: 'Recurso desconocido' }, noData: 'Sin datos', retry: 'Reintentar' },
};

export default common;