const common = {
  faq: {
    title: 'Myuedi ma tutedi jita', badge: 'FAQ',
    description: 'Bongwa mbadi ma myuedi ma tutedi jita ombusa besengedi ba mwemba, ekakato a m\'bongo, diwengedi da ba longo, njoandisedi a numelo na wuma yena la sengedi nde na Afrika.',
    q1: 'O nika nje na ba te̱ KHEPRA EXPERTS ka besengedi nde na Afrika e ?',
    a1: 'KHEPRA EXPERTS nde besengedi ba Afrika ńa bwambi, na mimbu buka 22 la bwambi ombusa bepolo ba Afrika a Wes\'ti na Afrika a Sese.',
    q2: 'Nje ebolo ba nika na mo̱ngwano ombusa mwemba e ?',
    a2: 'Di mombwea PME, milonga ma bebotedi, mambo ma m\'bongo ma ndandande, besengedi ba ndabo, mambo ma ekotedi, na besengedi ba wase nde na Afrika.',
  },
  contact: { title: 'Beledi biso̱', subtitle: 'Di kwala ombusa proje a mwemba, ekakato a m\'bongo to njoandisedi a diwengedi', name: 'Dina la bune̱', email: 'Email', phone: 'Telefon', company: 'Besengedi', message: 'Mulopo', submit: 'Loma', sending: 'Mulopo mu maloma…', success: 'Mulopo mu lomedi bwam ! Di me̱nde̱ timbise̱le̱ o ponda la son 24.', error: 'Ndut\'a bomane̱. Jombwea boso̱.', address: 'Adrès', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Munya mwemba mo̱ngo̱ ombusa besengedi, ekakato a m\'bongo, diwengedi na njoandisedi a numelo ońola diba la bwindea nde na Afrika', quickLinks: 'Ngea ni mpondi', services: 'Ebolo', about: 'Ombusa biso̱', blog: 'Blog', contact: 'Beledi', legalLinks: 'Mambenda', privacy: 'Mwe̱nde̱ ma tapa', terms: 'Mambenda ma bolane̱', followUs: 'Bupe̱ biso̱', rights: 'Bana ba mwe̱nde̱ be̱se̱ ba sengisabe̱.' },
  common: { learnMore: 'Bata bwambo' },
  cta: { diagnostic_free: 'Ekakato e nisabe̱', diagnostic_subtitle: 'Jombwea la muto o ponda la son 2 · E tilabe̱ nde na dikaki' },
  leadMagnet: { whitepaper: { title: 'Tanga kalati asu a Musomba', description: 'Ekakato a dibie̱ na beteledi ba be bolane̱.', button: 'Tanga Kalati a Musomba' }, webinar: { title: 'Ingede̱ o Webinaire asu ńa maya', description: 'Kwalea bwam na babienedi basu.', button: 'Tilise̱ ońola Webinaire' }, diagnostic: { title: 'Ekakato a Mwemba e nisabe̱', description: 'Minit 30 na mubienedi o jombwea bete̱medi bo̱ngo̱.', button: 'Botea ekakato' }, newsletter: { title: 'Kusa Kalati asu a Mwemba', description: 'Ekakato a jombwea, o email mo̱ngo̱.', button: 'Tilise̱ ońola Kalati a Mwemba' } },
  monitoring: { title: 'We̱ne̱ la Tékiniki', subtitle: 'Ndutu 404 na ponda la muto', loading: 'Mikanda mi malinga…', retry: 'Jombwea boso̱', timeRange: { '24h': 'Son 24', '7d': 'Buńa 7', '30d': 'Buńa 30' }, stats: { total404: 'Ndutu 404', total404Sub: 'Dipapa di si mabe̱ne̱', totalErrors: 'Ndutu HTTP/JS', totalErrorsSub: 'Ba m\u0027jombwea na ba script', avgResponse: 'Ponda API la sese', avgResponseSub: 'ms', avgPageLoad: 'Tangedi la dipapa', avgPageLoadSub: 'ms' }, notFound: { title: 'URL 404 a Mwe̱nde̱ Jita', subtitle: 'Dipapa di si mabe̱ne̱ buka me̱se̱', url: 'URL', count: 'Bedangwedi', empty: 'Ndutu 404 i si mabe̱ne̱ o ponda' }, performance: { title: 'Ponda la Muto API', subtitle: 'Mpom a ponda na mpom ma ngińa', tooltipAvg: 'Mpom', tooltipMax: 'Ngińa', tooltipCount: 'Ba m\u0027jombwea', empty: 'Mikanda mi titi' }, topErrors: { title: 'Ndutu a Mwe̱nde̱', subtitle: 'Ndutu i bukabe̱ buka me̱se̱', empty: 'Ndutu i titi' }, errorLog: { title: 'Kalati a ndutu', subtitle: 'Ndutu a maya', type: 'Dongo', message: 'Mulopo', url: 'URL', date: 'Buńa', empty: 'Ndutu a maya i titi' }, navigation: { title: 'Diwuta', subtitle: 'Ponda la tangedi la dipapa', empty: 'Mikanda mi titi' } },
  dashboard: { login: { title: 'Tapala la bediedi', subtitle: 'Jombwea la bala ba mitoa', passwordLabel: 'Ebongolo a ngińa', passwordPlaceholder: 'Tilise̱ ebongolo a ngińa', loginButton: 'Bengane̱', incorrectPassword: 'Ebongolo a ngińa e titi bwam' }, header: { title: 'Tapala la bediedi', subtitle: 'We̱ne̱ la njoandisedi na bolongi', timeRange: { '7d': 'Buńa 7 ba tombi', '30d': 'Buńa 30 ba tombi', '90d': 'Buńa 90 ba tombi', all: 'Ponda ye̱se̱' }, refreshButton: 'Timba peńa' }, loading: 'Mikanda mi malinga…', kpis: { totalLeads: { title: 'Leads ye̱se̱', subtitle: 'ba peńa' } }, pipeline: { title: 'Pipeline a njoandisedi' }, sources: { title: 'Mowudise̱le̱' }, formTypes: { title: 'Bolongi ba dongo la formulaire', ofTotal: 'la ye̱se̱' }, recentLeads: { title: 'Leads a maya', table: { date: 'Buńa', contact: 'Moto', organization: 'Besengedi', type: 'Dongo', score: 'Mako̱m', status: 'Bete̱medi', source: 'Mowudise̱le̱' } }, status: { new: 'Peńa', meeting_scheduled: 'Ndolam a te̱se̱be̱', qualified: 'Ye nika', converted: 'Ye njoandisedi', lost: 'Ye busise̱le̱' }, formType: { contact: 'Beledi', diagnostic: 'Ekakato', expert: 'Mubienedi', newsletter: 'Kalati a Mwemba' }, metrics: { toolCompletions: { title: 'Ebolo e mabangabe̱', subtitle: 'Ekakato e bolabe̱' } }, diagnostics: { title: 'Ekakato a Maya', table: { date: 'Buńa', tool: 'Ebolo', score: 'Mako̱m' } }, downloads: { title: 'Tangedi a Maya', table: { date: 'Buńa', resource: 'Ebolo', contact: 'Moto', country: 'Ekombo o njongo' }, unknownResource: 'Ebolo e si bowe̱' }, noData: 'Mikanda mi titi o ponda', retry: 'Jombwea boso̱' },
};
export default common;



