import type { KnowledgeRule } from '@/mocks/selfLearningEngine';

interface KnowledgeRulesPanelProps {
  rules: KnowledgeRule[];
}

const domainLabels: Record<string, string> = {
  exactitude: 'Exactitude réglementaire',
  tracabilite: 'Traçabilité des sources',
  gouvernance: 'Gouvernance',
  aml_cft: 'AML/CFT',
  clarte: 'Clarté documentaire',
  risque_juridique: 'Risque juridique',
};

const domainIcons: Record<string, string> = {
  exactitude: 'ri-check-double-line',
  tracabilite: 'ri-links-line',
  gouvernance: 'ri-building-4-line',
  aml_cft: 'ri-shield-flash-line',
  clarte: 'ri-file-text-line',
  risque_juridique: 'ri-scales-3-line',
};

const domainColors: Record<string, string> = {
  exactitude: 'bg-primary-100 text-primary-700 border-primary-200',
  tracabilite: 'bg-accent-100 text-accent-700 border-accent-200',
  gouvernance: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  aml_cft: 'bg-red-100 text-red-700 border-red-200',
  clarte: 'bg-secondary-100 text-secondary-700 border-secondary-200',
  risque_juridique: 'bg-amber-100 text-amber-700 border-amber-200',
};

export default function KnowledgeRulesPanel({ rules }: KnowledgeRulesPanelProps) {
  const sorted = [...rules].sort((a, b) => b.weight - a.weight);

  return (
    <div className="space-y-6">
      {/* Summary */}
      <div className="p-5 rounded-2xl bg-background-100 border border-background-200">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-amber-100 text-amber-700 flex items-center justify-center">
            <i className="ri-brain-line text-lg"></i>
          </div>
          <div>
            <h2 className="text-lg font-bold text-foreground-950 font-heading">Base de Connaissances Auto-Générée</h2>
            <p className="text-xs text-foreground-500">
              {rules.length} règles internes générées par autoapprentissage après {rules.filter(r => r.autoGenerated).length} cycles de correction.
              Ces règles alimentent le moteur de validation automatique des futurs contenus.
            </p>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          {Object.entries(domainLabels).map(([key, label]) => {
            const count = rules.filter(r => r.domain === key).length;
            const icon = domainIcons[key];
            const colors = domainColors[key];
            return (
              <span key={key} className={`text-[10px] px-3 py-1.5 rounded-full font-semibold border flex items-center gap-1.5 ${colors}`}>
                <i className={icon}></i>
                {label} ({count})
              </span>
            );
          })}
        </div>
      </div>

      {/* Rules list */}
      <div className="space-y-4">
        {sorted.map((rule, i) => {
          const icon = domainIcons[rule.domain];
          const colors = domainColors[rule.domain];
          return (
            <div key={rule.id} className="p-5 rounded-2xl bg-background-100 border border-background-200">
              <div className="flex items-start gap-4">
                <span className="text-xs font-bold text-foreground-400 w-6 text-right flex-shrink-0">{i + 1}</span>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-2 flex-wrap">
                    <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold border ${colors}`}>
                      <i className={`${icon} mr-1`}></i>
                      {domainLabels[rule.domain]}
                    </span>
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-background-200 text-foreground-600 font-semibold">
                      Poids : {rule.weight}/100
                    </span>
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 font-semibold">
                      Auto-générée
                    </span>
                    <span className="text-[10px] text-foreground-400">{rule.generationDate}</span>
                  </div>
                  <p className="text-sm font-semibold text-foreground-900 mb-3">{rule.rule}</p>
                  {rule.examples.length > 0 && (
                    <div className="space-y-1.5">
                      <p className="text-[10px] font-bold text-foreground-400 uppercase">Exemples d&apos;application :</p>
                      {rule.examples.map((ex, j) => (
                        <div key={j} className="flex items-start gap-2 text-xs">
                          <i className="ri-arrow-right-s-line text-foreground-300 flex-shrink-0 mt-0.5"></i>
                          <span className="text-foreground-600">{ex}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}





