const regions = {
  pillar: {
    digitalTransformation: { seo: { title: 'Transformation Digitale en Afrique : Guide Stratégique pour Institutions Financières | Khepra Experts', description: 'Guide complet sur les stratégies de transformation digitale pour les institutions financières africaines, banques et fintechs. Expertise en digitalisation, innovation et adoption technologique.', keywords: 'transformation digitale Afrique, digitalisation bancaire, innovation fintech, stratégie digitale Afrique, adoption technologique, banque digitale Afrique' } },
    financialInclusion: { seo: { title: 'Inclusion Financière en Afrique : Stratégies pour une Finance Inclusive | Khepra Experts', description: 'Guide complet sur les stratégies d\'inclusion financière, les services financiers digitaux et les politiques de finance inclusive en Afrique. Expertise mobile money, agent banking et accès financier.', keywords: 'inclusion financière Afrique, inclusion financière digitale, finance inclusive, mobile money, accès financier, agent banking, services financiers Afrique' } },
    fintechAdvisory: { seo: { title: 'Conseil Fintech en Afrique : Consulting Stratégique pour l\'Innovation Fintech | Khepra Experts', description: 'Guide expert sur la stratégie fintech, l\'innovation, le développement de l\'écosystème et la conformité réglementaire sur les marchés africains. Services complets de conseil fintech.', keywords: 'conseil fintech Afrique, stratégie fintech, innovation fintech, écosystème fintech, réglementation fintech, paiements digitaux, mobile money' } },
    microfinanceTransformation: { seo: { title: 'Transformation Microfinance en Afrique : Guide de Modernisation Digitale | Khepra Experts', description: 'Guide complet sur la transformation digitale des institutions de microfinance, stratégies de modernisation et innovation pour les IMF africaines. Expertise en digitalisation des IMF.', keywords: 'transformation digitale microfinance, modernisation microfinance, microfinance digitale, innovation IMF, technologie microfinance, digitalisation IMF' } },
    smeDevelopment: { seo: { title: 'Développement PME en Afrique : Conseil Stratégique pour la Croissance des Entreprises | Khepra Experts', description: 'Guide complet sur le développement des PME, stratégies de financement, conseil en croissance et transformation pour les petites et moyennes entreprises africaines. Services de conseil PME.', keywords: 'conseil développement PME Afrique, financement PME, stratégie croissance PME, petites entreprises Afrique, transformation PME, entrepreneuriat Afrique' } },
  },

  regions: {
    westAfrica: { seo: { title: 'Conseil Stratégique Afrique de l\'Ouest | UEMOA CEDEAO Fintech | Khepra Experts', description: 'Khepra Experts accompagne les institutions ouest-africaines dans leur transformation digitale et stratégique. Expertise UEMOA, écosystème fintech nigérian, systèmes de paiement régionaux. 16 pays, 411M habitants.', keywords: 'conseil Afrique de l\'Ouest, services financiers UEMOA, fintech Nigeria Ghana, mobile money Afrique Ouest, conformité BCEAO, transformation digitale CEDEAO' } },
    francophoneAfrica: { seo: { title: 'Conseil Afrique Francophone | Services Financiers UEMOA, CEMAC, Maghreb | Khepra Experts', description: 'Conseil stratégique pour institutions africaines francophones : conformité BCEAO/COBAC, transformation digitale, expansion régionale, stratégie fintech. 29 pays, 430M habitants, 950Mds$ PIB. Expertise UEMOA, CEMAC, Maghreb.', keywords: 'conseil Afrique francophone, services financiers UEMOA, banque CEMAC, conformité BCEAO, réglementation COBAC, transformation digitale Afrique francophone, microfinance UEMOA, fintech CEMAC' } },
    uemoaCemac: { seo: { title: 'Expertise Conformité UEMOA & CEMAC | Conseil Réglementaire BCEAO COBAC | Khepra Experts', description: 'Cabinet spécialisé en conformité réglementaire UEMOA et CEMAC. Expertise BCEAO, COBAC, mise en conformité institutions financières, microfinance, fintech. Accompagnement agrément et gouvernance. Gestion des risques Bâle II/III, reporting prudentiel, réglementation monnaie électronique.', keywords: 'conformité UEMOA, conformité CEMAC, conseil BCEAO, conseil COBAC, réglementation microfinance Afrique, agrément institution financière, normes prudentielles UEMOA, gouvernance bancaire CEMAC, réglementation monnaie électronique, conformité mobile money, Bâle II III Afrique, conformité IFRS, réglementation fintech Afrique' } },
    africa: { seo: { title: 'Conseil Stratégique Afrique | Inclusion Financière, Fintech & Transformation Digitale | Khepra Experts', description: 'Khepra Experts accompagne les institutions africaines : inclusion financière, développement écosystème fintech, transformation digitale, modernisation microfinance, développement PME. 54 pays, 1,4Md habitants, 3000Mds$ PIB.', keywords: 'conseil Afrique, conseil stratégique Afrique, inclusion financière Afrique, conseil fintech Afrique, transformation digitale Afrique, microfinance Afrique, développement PME Afrique, banque Afrique, mobile money Afrique' } },
    afrique: { seo: { title: 'Expertise Conseil Stratégique en Afrique | Présence 15+ Pays | Khepra Experts', description: 'Cabinet de conseil panafricain spécialisé en gouvernance, audit financier et transformation digitale. Présence active dans 15+ pays d\'Afrique de l\'Ouest et Centrale avec expertise locale approfondie. Conseil inclusion financière Afrique, fintech, microfinance.', keywords: 'conseil stratégique Afrique, cabinet conseil panafricain, expertise Afrique de l\'Ouest, conseil UEMOA, conseil CEMAC, transformation digitale Afrique, audit financier Afrique, gouvernance entreprise Afrique, inclusion financière Afrique, fintech Afrique, microfinance Afrique, conseil PME Afrique' } },
  },
};

export default regions;



