const common = {
  faq: {
    title: 'Mituna mingi kotunama', badge: 'FAQ',
    description: 'Zwana bayano na mituna mingi kotunama na tina na misala na biso ya toli ya mwango, bokuki ya mbongo, boyangeli ya bakompanyi, mbongwano ya numelo mpe esika na biso ya mosala na Afrika.',
    q1: 'Mpona nini opona KHEPRA EXPERTS lokola kompanyi ya toli na Afrika ?',
    a1: 'KHEPRA EXPERTS ezali kompanyi ya toli ya Afrika mobimba oyo ekembisami na boyebi ya mibu koleka 22 na Afrika ya Wɛsti mpe ya Kati.',
    q2: 'Bampaya nini bosungaka na toli ya mwango ?',
    a2: 'Tosungaka PME, startups, bibongiseli ya microfinance, bakompanyi minene, ONG, bibongiseli ya Leta mpe bibongiseli ya mokili mobimba na Afrika.',
  },
  contact: { title: 'Zwa biso', subtitle: 'Tosolo na tina ya projɛ na yo ya toli ya mwango, bokuki ya mbongo to mbongwano ya bokeli', name: 'Nkombo mobimba', email: 'Emele', phone: 'Telefone', company: 'Ebongiseli', message: 'Nsango', submit: 'Tinda', sending: 'Ezali kotinda…', success: 'Nsango etindami na elonga ! Tokozongela yo na kati ya ngonga 24.', error: 'Mabunga mazwami. Omeka lisusu.', address: 'Adresi', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Monano na yo ya mwango na toli, bokuki ya mbongo, boyangeli mpe mbongwano ya numelo mpo na bokoli ya libela na Afrika', quickLinks: 'Bakangi ya Nokinoki', services: 'Misala', about: 'Na tina na biso', blog: 'Blog', contact: 'Zwa biso', legalLinks: 'Mibeko', privacy: 'Mobeko ya Sekele', terms: 'Mibeko ya alela', followUs: 'Landa biso', rights: 'Makoki nyoso mabatelami.' },
  common: { learnMore: 'Yekola mingi' },
  cta: { diagnostic_free: 'Diagnostic ya ofele', diagnostic_subtitle: 'Eyano na kati ya ngonga 2 · Kozanga elako' },
  leadMagnet: { whitepaper: { title: 'Kita Lokasa na biso ya Pembe', description: 'Bososoli ya mozindo, ntalo mpe malako.', button: 'Kita Lokasa ya Pembe' }, webinar: { title: 'Kota na Webinaire na biso ya Kozala', description: 'Solola na bato ya mayele na biso.', button: 'Komipesa na Webinaire' }, diagnostic: { title: 'Diagnostic ya Mwango ya Ofele', description: 'Minute 30 na moto ya mayele mpo na osola likambo na yo.', button: 'Bandisa diagnostic' }, newsletter: { title: 'Zwaka Journal na biso ya Mwango', description: 'Bososoli ya sikisiki, na kati ya emele na yo.', button: 'Komipesa na Journal' } },
  monitoring: { title: 'Bolandeli ya Tekiniki', subtitle: 'Mabunga 404 mpe ntango ya kozongisa', loading: 'Ezali kokumba ba données…', retry: 'Meka lisusu', timeRange: { '24h': 'Ngonga 24', '7d': 'Mikolo 7', '30d': 'Mikolo 30' }, stats: { total404: 'Mabunga 404', total404Sub: 'Lokasa oyo ezali te', totalErrors: 'Mabunga HTTP/JS', totalErrorsSub: 'Ba demande mpe ba script', avgResponse: 'Ntango ya API ya katikati', avgResponseSub: 'ms', avgPageLoad: 'Bokumbi lokasa', avgPageLoadSub: 'ms' }, notFound: { title: 'Ba URL 404 ya Likolo', subtitle: 'Ba lokasa oyo ezangi mingimingi', url: 'URL', count: 'Bokutani', empty: 'Mabunga 404 te emonani' }, performance: { title: 'Ntango ya Kozongisa API', subtitle: 'Katikati mpe likolo', tooltipAvg: 'Kat', tooltipMax: 'Lik', tooltipCount: 'Ba demande', empty: 'Ba données te' }, topErrors: { title: 'Mabunga minene', subtitle: 'Mabunga ya mbala mingi', empty: 'Mabunga te' }, errorLog: { title: 'Mokanda ya mabunga', subtitle: 'Mabunga ya suka', type: 'Lolenge', message: 'Nsango', url: 'URL', date: 'Mokolo', empty: 'Mabunga ya suka te' }, navigation: { title: 'Botamboli', subtitle: 'Ntango ya kokumba lokasa', empty: 'Ba données te' } },
  dashboard: { login: { title: 'Tableau de bord', subtitle: 'Bokoti ya ba administrateur', passwordLabel: 'Mot de passe', passwordPlaceholder: 'Kotisa mot de passe', loginButton: 'Kota', incorrectPassword: 'Mot de passe mabe' }, header: { title: 'Tableau de bord', subtitle: 'Bolandeli ya mbongwano mpe mosala', timeRange: { '7d': 'Mikolo 7', '30d': 'Mikolo 30', '90d': 'Mikolo 90', all: 'Nionso' }, refreshButton: 'Zongisa sika' }, loading: 'Ezali kokumba ba données…', kpis: { totalLeads: { title: 'Ba Leads Nionso', subtitle: 'ya sika' } }, pipeline: { title: 'Pipeline ya mbongwano' }, sources: { title: 'Ba source ya bozwi' }, formTypes: { title: 'Mosala na lolenge ya formulaire', ofTotal: 'ya nionso' }, recentLeads: { title: 'Ba leads ya suka', table: { date: 'Mokolo', contact: 'Moto', organization: 'Ebongiseli', type: 'Lolenge', score: 'Motango', status: 'Ezali', source: 'Source' } }, status: { new: 'Sika', meeting_scheduled: 'Likita etiami', qualified: 'Ekoki', converted: 'Ebongolami', lost: 'Ebungi' }, formType: { contact: 'Kozwa', diagnostic: 'Diagnostic', expert: 'Moto ya mayele', newsletter: 'Journal' }, metrics: { toolCompletions: { title: 'Ba Bisaleli Bisili', subtitle: 'Ba diagnostic esalami' } }, diagnostics: { title: 'Ba Diagnostic ya Suka', table: { date: 'Mokolo', tool: 'Bisaleli', score: 'Motango' } }, downloads: { title: 'Ba Bokitisami ya Suka', table: { date: 'Mokolo', resource: 'Biloko', contact: 'Moto', country: 'Ekolo' }, unknownResource: 'Biloko eyebani te' }, noData: 'Ba données te', retry: 'Meka lisusu' },
};
export default common;



