import type { DiagnosticAxisConfig } from '';

export const SIM_FIN_AXES: DiagnosticAxisConfig[] = [
  { id: 'rentabilite', titleFr: 'Rentabilité', titleEn: 'Profitability', descriptionFr: 'Marges, point mort, EBITDA, résultat net, ROE/ROA', descriptionEn: 'Margins, break-even, EBITDA, net income, ROE/ROA', icon: 'ri-money-dollar-circle-line', color: '#059669', weight: 20, questions: [
    { id: 'sf-ren-1', questionFr: 'Votre marge brute est-elle suffisante pour couvrir vos charges de structure et dégager un résultat positif ?', questionEn: 'Is your gross margin sufficient to cover your overhead and generate a positive result?', options: [{ value: 100, labelFr: 'Marge brute > 40%, résultat net positif depuis 2+ ans, tendance en amélioration', labelEn: 'Gross margin > 40%, net profit positive for 2+ years, improving trend' }, { value: 60, labelFr: 'Marge brute 20-40%, résultat à l\'équilibre ou légèrement positif', labelEn: 'Gross margin 20-40%, break-even or slightly positive result' }, { value: 25, labelFr: 'Marge brute < 20%, résultat négatif, pas de visibilité sur le retour à la rentabilité', labelEn: 'Gross margin < 20%, negative result, no visibility on return to profitability' }, { value: 0, labelFr: 'Marge brute négative, pertes structurelles, situation critique', labelEn: 'Negative gross margin, structural losses, critical situation' }] },
    { id: 'sf-ren-2', questionFr: 'Connaissez-vous votre point mort et votre seuil de rentabilité par produit/service ?', questionEn: 'Do you know your break-even point and profitability threshold by product/service?', options: [{ value: 100, labelFr: 'Point mort calculé mensuellement, analyse par produit/client, scénarios de sensibilité', labelEn: 'Break-even calculated monthly, product/client analysis, sensitivity scenarios' }, { value: 60, labelFr: 'Point mort global calculé annuellement, pas d\'analyse par produit', labelEn: 'Global break-even calculated annually, no product analysis' }, { value: 25, labelFr: 'Point mort estimé approximativement, pas de calcul formalisé', labelEn: 'Break-even roughly estimated, no formal calculation' }, { value: 0, labelFr: 'Point mort inconnu, navigation financière à vue', labelEn: 'Unknown break-even, blind financial navigation' }] },
  ]},
  { id: 'tresorerie', titleFr: 'Trésorerie & Liquidité', titleEn: 'Cash & Liquidity', descriptionFr: 'BFRE, cash-flow, liquidité, endettement, capacité de remboursement', descriptionEn: 'Working capital, cash flow, liquidity, debt, repayment capacity', icon: 'ri-bank-line', color: '#0ea5e9', weight: 20, questions: [
    { id: 'sf-tre-1', questionFr: 'Votre trésorerie est-elle suffisante pour couvrir vos besoins à court terme sans tension ?', questionEn: 'Is your cash sufficient to cover your short-term needs without tension?', options: [{ value: 100, labelFr: 'Trésorerie > 3 mois de charges, prévisions de trésorerie glissantes sur 12 mois, lignes de crédit confirmées', labelEn: 'Cash > 3 months expenses, rolling 12-month cash forecasts, confirmed credit lines' }, { value: 60, labelFr: 'Trésorerie 1-3 mois, prévisions à 3-6 mois, quelques tensions ponctuelles', labelEn: 'Cash 1-3 months, 3-6 month forecasts, occasional tensions' }, { value: 25, labelFr: 'Trésorerie < 1 mois, pas de prévisions, tensions récurrentes', labelEn: 'Cash < 1 month, no forecasts, recurring tensions' }, { value: 0, labelFr: 'Trésorerie négative ou inexistante, risque de cessation de paiement', labelEn: 'Negative or non-existent cash, payment default risk' }] },
    { id: 'sf-tre-2', questionFr: 'Votre besoin en fonds de roulement (BFR) est-il maîtrisé et optimisé ?', questionEn: 'Is your working capital requirement (WCR) controlled and optimized?', options: [{ value: 100, labelFr: 'BFR < 30 jours de CA, DSO < 45j, DPO optimisé, rotation des stocks maîtrisée', labelEn: 'WCR < 30 days revenue, DSO < 45d, optimized DPO, controlled inventory turnover' }, { value: 60, labelFr: 'BFR 30-60 jours, délais de recouvrement modérés, stocks raisonnables', labelEn: 'WCR 30-60 days, moderate collection times, reasonable inventory' }, { value: 25, labelFr: 'BFR > 60 jours, retards de paiement clients chroniques, surstockage', labelEn: 'WCR > 60 days, chronic customer payment delays, overstocking' }, { value: 0, labelFr: 'BFR non calculé, délais de paiement non maîtrisés, trésorerie asphyxiée', labelEn: 'Uncalculated WCR, uncontrolled payment terms, suffocated cash' }] },
  ]},
  { id: 'structure-fin', titleFr: 'Structure Financière', titleEn: 'Financial Structure', descriptionFr: 'Fonds propres, endettement, levier, autonomie financière, capacité d\'investissement', descriptionEn: 'Equity, debt, leverage, financial autonomy, investment capacity', icon: 'ri-funds-box-line', color: '#7c3aed', weight: 20, questions: [
    { id: 'sf-str-1', questionFr: 'Votre structure financière est-elle équilibrée entre fonds propres et endettement ?', questionEn: 'Is your financial structure balanced between equity and debt?', options: [{ value: 100, labelFr: 'Ratio d\'autonomie financière > 50%, endettement maîtrisé (< 3x EBITDA), capacité de remboursement confortable', labelEn: 'Financial autonomy ratio > 50%, controlled debt (< 3x EBITDA), comfortable repayment capacity' }, { value: 60, labelFr: 'Ratio 30-50%, endettement modéré, capacité de remboursement acceptable', labelEn: 'Ratio 30-50%, moderate debt, acceptable repayment capacity' }, { value: 25, labelFr: 'Ratio < 30%, surendettement, capacité de remboursement tendue', labelEn: 'Ratio < 30%, over-indebtedness, tight repayment capacity' }, { value: 0, labelFr: 'Fonds propres négatifs, endettement excessif, risque de défaut', labelEn: 'Negative equity, excessive debt, default risk' }] },
  ]},
  { id: 'croissance', titleFr: 'Croissance & Investissement', titleEn: 'Growth & Investment', descriptionFr: 'Croissance CA, investissements, ROI, projets de développement', descriptionEn: 'Revenue growth, investments, ROI, development projects', icon: 'ri-rocket-line', color: '#d97706', weight: 20, questions: [
    { id: 'sf-cro-1', questionFr: 'Votre croissance est-elle soutenable et financée sans mettre en danger votre équilibre financier ?', questionEn: 'Is your growth sustainable and funded without endangering your financial balance?', options: [{ value: 100, labelFr: 'Croissance > 10%/an, autofinancée ou avec dette maîtrisée, plan d\'investissement 3 ans avec ROI documenté', labelEn: 'Growth > 10%/year, self-funded or with controlled debt, 3-year investment plan with documented ROI' }, { value: 60, labelFr: 'Croissance 5-10%, financement partiellement maîtrisé, quelques projets d\'investissement', labelEn: 'Growth 5-10%, partially controlled funding, some investment projects' }, { value: 25, labelFr: 'Croissance < 5%, investissements limités, pas de plan de développement', labelEn: 'Growth < 5%, limited investments, no development plan' }, { value: 0, labelFr: 'Décroissance ou stagnation, pas d\'investissement, déclin programmé', labelEn: 'Decline or stagnation, no investment, programmed decline' }] },
  ]},
  { id: 'pilotage', titleFr: 'Pilotage Financier', titleEn: 'Financial Steering', descriptionFr: 'Budget, contrôle de gestion, tableaux de bord, prévisions, reporting', descriptionEn: 'Budget, management control, dashboards, forecasts, reporting', icon: 'ri-dashboard-line', color: '#dc2626', weight: 20, questions: [
    { id: 'sf-pil-1', questionFr: 'Disposez-vous d\'un pilotage financier structuré avec budget, reporting et analyse des écarts ?', questionEn: 'Do you have structured financial steering with budget, reporting and variance analysis?', options: [{ value: 100, labelFr: 'Budget annuel détaillé, reporting mensuel avec analyse d\'écarts, prévisions glissantes, comité financier', labelEn: 'Detailed annual budget, monthly reporting with variance analysis, rolling forecasts, financial committee' }, { value: 60, labelFr: 'Budget annuel basique, reporting trimestriel, analyse d\'écarts partielle', labelEn: 'Basic annual budget, quarterly reporting, partial variance analysis' }, { value: 25, labelFr: 'Budget approximatif, pas de reporting formalisé, pas d\'analyse d\'écarts', labelEn: 'Approximate budget, no formalized reporting, no variance analysis' }, { value: 0, labelFr: 'Aucun pilotage financier, pas de budget, pas de reporting', labelEn: 'No financial steering, no budget, no reporting' }] },
  ]},
];

export function getSimFinScoreColor(s: number): string { if (s >= 80) return '#059669'; if (s >= 60) return '#0ea5e9'; if (s >= 40) return '#d97706'; return '#dc2626'; }
export function getSimFinScoreLabel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Excellence Financière':'Financial Excellence'; if (s>=60) return f?'Santé Financière Bonne':'Good Financial Health'; if (s>=40) return f?'Santé Financière Fragile':'Fragile Financial Health'; return f?'Situation Financière Critique':'Critical Financial Situation'; }
export function getSimFinLevel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Niveau 4 — Investment Grade':'Level 4 — Investment Grade'; if (s>=60) return f?'Niveau 3 — Performant':'Level 3 — Performer'; if (s>=40) return f?'Niveau 2 — Fragile':'Level 2 — Fragile'; return f?'Niveau 1 — Critique':'Level 1 — Critical'; }
export function getSimFinReadiness(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Votre situation financière est excellente. Continuez à optimiser votre structure financière et à piloter votre croissance.':'Your financial situation is excellent. Continue optimizing your financial structure and steering your growth.'; if (s>=60) return f?'Votre santé financière est bonne. Renforcez votre pilotage et votre structure financière pour atteindre l\'excellence.':'Your financial health is good. Strengthen your steering and financial structure to reach excellence.'; if (s>=40) return f?'Votre situation financière est fragile. Priorisez l\'amélioration de la trésorerie et la maîtrise du BFR.':'Your financial situation is fragile. Prioritize cash improvement and WCR control.'; return f?'Votre situation financière est critique. Une restructuration urgente est indispensable pour éviter la cessation de paiement.':'Your financial situation is critical. Urgent restructuring is essential to avoid payment default.'; }

export function getSimFinRisks(pa: Record<string,number>, gs: number, lang: string): string[] {
  const f=!lang.startsWith('en'); const r:string[]=[];
  if ((pa['rentabilite']??0)<50) r.push(f?'RISQUE CRITIQUE — Rentabilité insuffisante : pertes structurelles, pas de visibilité sur le retour à l\'équilibre — l\'entreprise consomme ses fonds propres':'CRITICAL RISK — Insufficient profitability: structural losses, no return-to-balance visibility — the company is consuming its equity');
  if ((pa['tresorerie']??0)<50) r.push(f?'RISQUE CRITIQUE — Trésorerie sous tension : risque de cessation de paiement à court terme, BFR non maîtrisé':'CRITICAL RISK — Cash under pressure: short-term payment default risk, uncontrolled WCR');
  if ((pa['structure-fin']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Structure financière déséquilibrée : surendettement, fonds propres insuffisants — vulnérabilité aux chocs':'HIGH RISK — Unbalanced financial structure: over-indebtedness, insufficient equity — vulnerability to shocks');
  if ((pa['croissance']??0)<50) r.push(f?'RISQUE MAJEUR — Croissance insuffisante : stagnation ou déclin, pas d\'investissement — perte de compétitivité':'MAJOR RISK — Insufficient growth: stagnation or decline, no investment — loss of competitiveness');
  if ((pa['pilotage']??0)<50) r.push(f?'RISQUE MAJEUR — Absence de pilotage : pas de budget, pas de reporting — décisions non éclairées, dérive financière':'MAJOR RISK — No steering: no budget, no reporting — uninformed decisions, financial drift');
  return r;
}

export function getSimFinRecommendations(pa: Record<string,number>, gs: number, lang: string): {title:string;axis?:string;items:string[]}[] {
  const f=!lang.startsWith('en'); const recs:{title:string;axis?:string;items:string[]}[]=[];
  if ((pa['rentabilite']??0)<60) recs.push({title:f?'Restaurer la Rentabilité':'Restore Profitability',axis:'rentabilite',items:f?['Analyser la rentabilité par produit/client pour identifier les pertes','Calculer et suivre le point mort mensuellement','Réduire les charges de structure non essentielles']:['Analyze profitability by product/client to identify losses','Calculate and track break-even monthly','Reduce non-essential overhead']});
  if ((pa['tresorerie']??0)<60) recs.push({title:f?'Sécuriser la Trésorerie':'Secure Cash',axis:'tresorerie',items:f?['Mettre en place des prévisions de trésorerie glissantes sur 12 mois','Optimiser le BFR : réduire les DSO, négocier les DPO','Négocier des lignes de crédit de précaution']:['Implement rolling 12-month cash forecasts','Optimize WCR: reduce DSO, negotiate DPO','Negotiate precautionary credit lines']});
  if ((pa['structure-fin']??0)<60) recs.push({title:f?'Rééquilibrer la Structure Financière':'Rebalance Financial Structure',axis:'structure-fin',items:f?['Renforcer les fonds propres (augmentation de capital, mise en réserve)','Restructurer la dette existante pour allonger les maturités','Maintenir un ratio d\'autonomie financière > 50%']:['Strengthen equity (capital increase, retained earnings)','Restructure existing debt to extend maturities','Maintain financial autonomy ratio > 50%']});
  if ((pa['croissance']??0)<60) recs.push({title:f?'Relancer la Croissance':'Relanch Growth',axis:'croissance',items:f?['Définir un plan d\'investissement 3 ans avec ROI par projet','Explorer de nouveaux marchés ou segments rentables','Financer la croissance par autofinancement prioritairement']:['Define a 3-year investment plan with ROI per project','Explore new profitable markets or segments','Finance growth primarily through self-funding']});
  if ((pa['pilotage']??0)<60) recs.push({title:f?'Structurer le Pilotage Financier':'Structure Financial Steering',axis:'pilotage',items:f?['Mettre en place un budget annuel détaillé avec reporting mensuel','Déployer un tableau de bord financier avec KPI clés','Instaurer un comité financier trimestriel']:['Implement a detailed annual budget with monthly reporting','Deploy a financial dashboard with key KPIs','Institute a quarterly financial committee']});
  if (recs.length===0) recs.push({title:f?'Maintenir l\'Excellence Financière':'Maintain Financial Excellence',items:f?['Optimiser la structure de capital (dette vs fonds propres)','Préparer une stratégie de financement de la croissance externe','Renforcer la gouvernance financière (comité d\'audit)']:['Optimize capital structure (debt vs equity)','Prepare a growth financing strategy for M&A','Strengthen financial governance (audit committee)']});
  return recs;
}


export const getSimFinScoreColor = { id: 1, label: "Stub data" }; // stub
export const getSimFinScoreLabel = { id: 1, label: "Stub data" }; // stub
export const getSimFinLevel = { id: 1, label: "Stub data" }; // stub
export const getSimFinReadiness = { id: 1, label: "Stub data" }; // stub
export const getSimFinRisks = { id: 1, label: "Stub data" }; // stub
export const getSimFinRecommendations = { id: 1, label: "Stub data" }; // stub



