import { Paragraph, TextRun, AlignmentType } from 'docx';
import { heading1, heading2, item } from './helpers';

export const title8Paragraphs: Paragraph[] = [
  heading1("TITRE VIII — CLAUSES JURIDIQUES DE PROTECTION (BOILERPLATE)"),
  heading2('Article 8.1 — Confidentialité'),
  item('8.1.1', "Les Parties s'engagent à maintenir une stricte confidentialité sur toutes les informations, données, documents, stratégies, modèles économiques, et méthodologies échangés dans le cadre du présent contrat. Cette obligation s'applique aux dirigeants, salariés, sous-traitants, et partenaires de chaque Partie ;", { after: 60, indent: 720 }),
  item('8.1.2', "La présente clause renforce l'NDA mutuel signé le 26 mai 2026. En cas de conflit entre les deux instruments, la clause la plus protectrice pour la Partie divulgatrice prévaut ;", { after: 60, indent: 720 }),
  item('8.1.3', "La durée de l'obligation de confidentialité est de la durée du présent contrat plus cinq (05) ans après sa résiliation ou son expiration. Les informations tombées dans le domaine public par voie autre qu'une faute de la Partie réceptrice sont exemptées de cette obligation ;", { after: 60, indent: 720 }),
  item('8.1.4', "Toute violation de cette clause de confidentialité expose la Partie fautive à des dommages et intérêts forfaitaires de cent millions (100 000 000) FCFA par incidence avérée, sans préjudice de la réparation du préjudice réel.", { after: 200, indent: 720 }),
  heading2('Article 8.2 — Propriété intellectuelle'),
  item('8.2.1', "Les manuels de procédures, les business plans, les statuts, les notes techniques, et l'ensemble des documents livrés dans le cadre du présent contrat sont et restent la propriété intellectuelle exclusive du Client. Le Prestataire cède au Client, dès leur livraison, l'intégralité des droits de propriété intellectuelle sur ces livrables, y compris les droits de reproduction, de modification, et d'exploitation commerciale ;", { after: 60, indent: 720 }),
  item('8.2.2', "Les méthodologies réglementaires, les outils d'analyse, les frameworks de scoring, les modèles financiers génériques, et les bases de données réglementaires développées par le Prestataire avant ou indépendamment du présent contrat restent la propriété intellectuelle exclusive du Prestataire. Le Client bénéficie d'une licence d'usage limitée à l'exploitation interne des livrables, sans droit de cession, de sous-licence, ou de reproduction à des tiers ;", { after: 60, indent: 720 }),
  item('8.2.3', "Le Prestataire s'engage à ne pas utiliser, pour le compte d'un concurrent direct du Client, les méthodologies spécifiques développées dans le cadre du présent contrat pendant une durée de trois (03) ans après l'expiration ou la résiliation du contrat.", { after: 200, indent: 720 }),
  heading2('Article 8.3 — Responsabilité et limitation'),
  item('8.3.1', "La responsabilité du Prestataire est strictement limitée aux fautes professionnelles avérées dans l'exécution de la mission. Le Prestataire est tenu à une obligation de moyens renforcée, et non à une obligation de résultat, l'octroi de l'agrément dépendant de la décision souveraine des autorités réglementaires ;", { after: 60, indent: 720 }),
  item('8.3.2', "Le montant total de la responsabilité du Prestataire, quelle que soit la nature du dommage, est plafonné au montant des honoraires fixes perçus par le Prestataire pour le pays concerné, à l'exclusion des success fees ;", { after: 60, indent: 720 }),
  item('8.3.3', "Sont expressément exclus de la responsabilité du Prestataire : les dommages indirects, le manque à gagner, la perte de chance, la perte de clientèle, la perte de réputation, et tout préjudice économique non directement lié à une faute professionnelle avérée du Prestataire ;", { after: 60, indent: 720 }),
  item('8.3.4', "Le Client reconnaît que les délais d'agrément sont variables et dépendent des calendriers internes des régulateurs, des évolutions législatives, et de la qualité des informations fournies par le Client. Le Prestataire ne saurait être tenu responsable des retards imputables à ces facteurs externes, ni à une faute du Client.", { after: 200, indent: 720 }),
  heading2('Article 8.4 — Force majeure'),
  item('8.4.1', "Constituent des cas de force majeure, outre les événements classiques reconnus par la jurisprudence (guerre, émeute, catastrophe naturelle, pandémie, grève générale), les événements spécifiques suivants : les moratoires bancaires décrétés par les autorités réglementaires, les modifications brutales et imprévisibles des réglementations bancaires ou microfinancières, les fermetures temporaires des Commissions Bancaires, et les décisions politiques affectant le secteur financier ;", { after: 60, indent: 720 }),
  item('8.4.2', "En cas de survenance d'un événement de force majeure, la Partie affectée en informe l'autre Partie par écrit dans les cinq (05) jours ouvrables. Les obligations sont suspendues pendant la durée de l'événement, sans pénalité ni indemnité. Si la force majeure perdure plus de quatre-vingt-dix (90) jours, chaque Partie peut résilier le contrat par lettre recommandée avec accusé de réception, sans indemnité. Les honoraires dus pour les jalons atteints avant la survenance de la force majeure restent exigibles.", { after: 300, indent: 720 }),
];