const common = {
  faq: {
    title: 'Mvō\'ō ndʉ\' ndʉk ndʉk', badge: 'FAQ',
    description: 'Ná\' ntʉmndā mvō\'ō ndʉ\' ndʉk ndʉk lénnê wōlò ntêh sì ntsʉ\'m\'ā, ntsʉ\' mfák ntêh lā\' sì, nkùmnjà\' lā\'ntô ntshʉ\', mbākncʉk ndā zǐ, má\' mfák nè zì ndʉā\' ntêtê nde nè Afríkà.',
    q1: 'Lá\' ywî ntshʉ\'á ntsʉ KHEPRA EXPERTS lā ndáp cwî\'ncʉk nde nè Afríkà ?',
    a1: 'KHEPRA EXPERTS ywî ndáp cwî\'ncʉk Afríkà fà\' ntô, fà\' ncwô ywî mbʉâ 22 nde nè Afríkà mfák ntêh ncʉk.',
    q2: 'Shwìì mncʉk ndʉ\' nsî ŋkwî\'h\'ā nde wōlò ntêh sì ?',
    a2: 'Pê nsî PME, ndáp mbʉ\'tê, ndáp ŋkóŋtê mfák ŋgàŋ-lād mbāk, ndáp ncwô, ONG, ndáp mfák là\' mfák ntô nde nè Afríkà.',
  },
  contact: { title: 'Kwǎ\' pê tê', subtitle: 'Pê ntʉ\'m ndʉ\' nè nshìŋkù\' ntêh sì, ntsʉ\' mfák ntêh lā\' sì yā\' mbākncʉk ndā ntô', name: 'Shwìì ncʉk', email: 'Email', phone: 'Ncém', company: 'Mō\'ntô', message: 'Ntsʉ\'m', submit: 'Tʉm', sending: 'Ŋkò ntʉm…', success: 'Ntsʉ\'m tʉmsí\' ndʉ\' ndé\' ! Pê sâ\' ntʉsí\' nde cā\'ntâ 24.', error: 'Ntshʉá lénsì\' ndè shwìì. Kwǎ\' ntō\'m.', address: 'Adrès', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Ŋkwî\'h\'ā mfák ntêh sì nde nè wōlò ntêh sì, ntsʉ\' mfák ntêh lā\' sì, nkùmnjà\' má\' mbākncʉk ndā zǐ lā mbâ\' ntsʉ\'tê nde nè Afríkà', quickLinks: 'Ncʉ\'ncʉk cwî\'h', services: 'Ntsʉ\'m', about: 'Nè kwî\' tsí\' pê', blog: 'Blog', contact: 'Kwǎ\' pê tê', legalLinks: 'Shwìì mfák', privacy: 'Ntsʉ\'m ncʉk', terms: 'Shwìì ŋkwî\'h\'ā', followUs: 'Ŋkwî\' pê', rights: 'Shwìì fà\' kù\'sí\'.' },
  common: { learnMore: 'Kwǎ\' ntʉ\'ō mnjâ' },
  cta: { diagnostic_free: 'Ntsʉ\' ncʉk ncwô', diagnostic_subtitle: 'Ntsʉsí\' nde cā\'ntâ 2 · Ŋkù\' mfák yā' },
  leadMagnet: { whitepaper: { title: 'Shwí\' ndû ηwá\'nè pê fà\'', description: 'Ntsʉ\' mnjâ lénnê tʉmndā.', button: 'Shwí\' ndû ηwá\'nè fà\'' }, webinar: { title: 'Nzhù\' nde Webinaire pê fà\'', description: 'Tʉ\'m ndʉ\' nè binì ncʉk pê.', button: 'Tí\' ywî Webinaire' }, diagnostic: { title: 'Ntsʉ\' Ncʉk Ntêh Sì Ncwô', description: 'Ntâmpòp 30 nè ncʉk ntsé\' nè ntsʉ\' nsî.', button: 'Cʉ\'tê ntsʉ\'' }, newsletter: { title: 'Kwǎ\' Ntsʉ\'m Pê Ntêh Sì', description: 'Ntsʉ\' tʉmndā, nde email ncʉk.', button: 'Tí\' ywî ntsʉ\'m' } },
  monitoring: { title: 'Ŋkwî\'h Nè Tékiniki', subtitle: 'Ntshʉá 404 nè cā\'ntâ ntsʉsí\'', loading: 'Ŋkò shwí\'…', retry: 'Kwǎ\' ntō\'m', timeRange: { '24h': 'Cā\'ntâ 24', '7d': 'Ŋkòsî 7', '30d': 'Ŋkòsî 30' }, stats: { total404: 'Ntshʉá 404', total404Sub: 'Tsô\' sì mbāk yā', totalErrors: 'Ntshʉá HTTP/JS', totalErrorsSub: 'Nkwî\' nè script', avgResponse: 'Cā\'ntâ API ncwô', avgResponseSub: 'ms', avgPageLoad: 'Cā\'ntâ tsô\'', avgPageLoadSub: 'ms' }, notFound: { title: 'URL 404 ndʉk', subtitle: 'Tsô\' sì mbāk yā ndʉk', url: 'URL', count: 'Mfák', empty: 'Ntshʉá 404 mbāk yā' }, performance: { title: 'Cā\'ntâ Ntsʉsí\' API', subtitle: 'Ncwô nè ndʉk', tooltipAvg: 'Ncwô', tooltipMax: 'Ndʉk', tooltipCount: 'Nkwî\'', empty: 'Tʉmndā mbāk yā' }, topErrors: { title: 'Ntshʉá ndʉk', subtitle: 'Ntshʉá ndʉk ndʉk', empty: 'Ntshʉá mbāk yā' }, errorLog: { title: 'Ŋwá\'nè ntshʉá', subtitle: 'Ntshʉá ndʉ\' gwā\'', type: 'Mfák', message: 'Ntsʉ\'m', url: 'URL', date: 'Ŋkòsî', empty: 'Ntshʉá gwā\' mbāk yā' }, navigation: { title: 'Ŋkwî\'h', subtitle: 'Cā\'ntâ tsô\'', empty: 'Tʉmndā mbāk yā' } },
  dashboard: { login: { title: 'Tableau de Bord', subtitle: 'Ŋkwî\' nè binì ntʉ\'m\'ā', passwordLabel: 'Ntsʉ\'m ncʉk', passwordPlaceholder: 'Tí\' ntsʉ\'m ncʉk', loginButton: 'Nzhù\'', incorrectPassword: 'Ntsʉ\'m ncʉk mbāk yā' }, header: { title: 'Tableau de Bord', subtitle: 'Ŋkwî\'h mbākncʉk nè ntsʉ\'m', timeRange: { '7d': 'Ŋkòsî 7', '30d': 'Ŋkòsî 30', '90d': 'Ŋkòsî 90', all: 'Póp fà\'' }, refreshButton: 'Ntsʉ\' ntō\'m' }, loading: 'Ŋkò shwí\' tʉmndā…', kpis: { totalLeads: { title: 'Leads fà\'', subtitle: 'fà\'' } }, pipeline: { title: 'Pipeline mbākncʉk' }, sources: { title: 'Mfák ndʉā\' nsî' }, formTypes: { title: 'Ntsʉ\'m nè mfák formulaire', ofTotal: 'fà\' póp' }, recentLeads: { title: 'Leads ndʉ\' gwā\'', table: { date: 'Ŋkòsî', contact: 'Ncʉk', organization: 'Mō\'ntô', type: 'Mfák', score: 'Mfák', status: 'Mfák', source: 'Mfák ndʉā\'' } }, status: { new: 'Fà\'', meeting_scheduled: 'Ndʉk nté\'sí\'', qualified: 'Sí\' ndé\'', converted: 'Mbākncʉk', lost: 'Ncʉ\'sí\'' }, formType: { contact: 'Kwǎ\' pê tê', diagnostic: 'Ntsʉ\' ncʉk', expert: 'Ncʉk', newsletter: 'Ntsʉ\'m' }, metrics: { toolCompletions: { title: 'Ntsʉ\'m Ncʉ\'sí\'', subtitle: 'Ntsʉ\' ncʉk bí\'sí\'' } }, diagnostics: { title: 'Ntsʉ\' Ncʉk Ndʉ\' Gwā\'', table: { date: 'Ŋkòsî', tool: 'Ntsʉ\'m', score: 'Mfák' } }, downloads: { title: 'Ŋwá\'nè Ndʉ\' Gwā\'', table: { date: 'Ŋkòsî', resource: 'Ntsʉ\'m', contact: 'Ncʉk', country: 'Ndá' }, unknownResource: 'Ntsʉ\'m mbāk jì yā' }, noData: 'Tʉmndā mbāk yā', retry: 'Kwǎ\' ntō\'m' },
};
export default common;