import type { DiagnosticAxisConfig } from '../components/types';

export const PERF_COM_AXES: DiagnosticAxisConfig[] = [
  { id: 'acquisition', titleFr: 'Acquisition Clients', titleEn: 'Customer Acquisition', descriptionFr: 'Stratégie commerciale, prospection, marketing, conversion, notoriété', descriptionEn: 'Sales strategy, prospecting, marketing, conversion, awareness', icon: 'ri-user-add-line', color: '#059669', weight: 25, questions: [
    { id: 'pc-acq-1', questionFr: 'Disposez-vous d\'un processus commercial structuré avec un pipeline de prospection actif et qualifié ?', questionEn: 'Do you have a structured sales process with an active and qualified prospecting pipeline?', options: [{ value: 100, labelFr: 'CRM déployé, pipeline documenté par étape, KPIs commerciaux suivis (taux de conversion par étape), prospection outbound structurée', labelEn: 'CRM deployed, documented pipeline by stage, tracked sales KPIs (stage conversion rate), structured outbound prospecting' }, { value: 60, labelFr: 'Processus commercial défini mais non outillé, pipeline suivi dans Excel', labelEn: 'Sales process defined but not tooled, Excel-tracked pipeline' }, { value: 25, labelFr: 'Démarche commerciale réactive, pas de processus structuré, dépendance aux recommandations', labelEn: 'Reactive sales approach, no structured process, referral dependence' }, { value: 0, labelFr: 'Aucune stratégie commerciale, clients acquis de manière aléatoire', labelEn: 'No sales strategy, clients acquired randomly' }] },
    { id: 'pc-acq-2', questionFr: 'Votre force de vente est-elle dimensionnée, formée et outillée pour atteindre vos objectifs de croissance ?', questionEn: 'Is your sales force sized, trained and equipped to achieve your growth objectives?', options: [{ value: 100, labelFr: 'Équipe commerciale expérimentée, plan de formation continu, outils CRM/BI, rémunération incentivante alignée objectifs', labelEn: 'Experienced sales team, continuous training plan, CRM/BI tools, incentive compensation aligned with objectives' }, { value: 60, labelFr: 'Équipe compétente mais formation insuffisante, outils basiques', labelEn: 'Competent team but insufficient training, basic tools' }, { value: 25, labelFr: 'Équipe sous-dimensionnée, pas de formation structurée, pas d\'outils', labelEn: 'Undersized team, no structured training, no tools' }, { value: 0, labelFr: 'Pas de force de vente dédiée, le dirigeant fait tout', labelEn: 'No dedicated sales force, the leader does everything' }] },
  ]},
  { id: 'fidelisation', titleFr: 'Fidélisation & Expansion', titleEn: 'Retention & Expansion', descriptionFr: 'Satisfaction client, rétention, cross-sell, upsell, NPS, SAV', descriptionEn: 'Customer satisfaction, retention, cross-sell, upsell, NPS, support', icon: 'ri-heart-line', color: '#d97706', weight: 25, questions: [
    { id: 'pc-fid-1', questionFr: 'Mesurez-vous et pilotez-vous activement la satisfaction et la fidélité de vos clients ?', questionEn: 'Do you actively measure and manage customer satisfaction and loyalty?', options: [{ value: 100, labelFr: 'NPS mesuré trimestriellement, plan d\'action post-enquête, taux de rétention > 90%, programme de fidélité', labelEn: 'NPS measured quarterly, post-survey action plan, retention rate > 90%, loyalty program' }, { value: 60, labelFr: 'Enquête satisfaction annuelle, suivi basique des réclamations', labelEn: 'Annual satisfaction survey, basic complaint tracking' }, { value: 25, labelFr: 'Satisfaction non mesurée formellement, feedback anecdotique', labelEn: 'Satisfaction not formally measured, anecdotal feedback' }, { value: 0, labelFr: 'Aucune gestion de la satisfaction client, attrition ignorée', labelEn: 'No customer satisfaction management, attrition ignored' }] },
    { id: 'pc-fid-2', questionFr: 'Avez-vous une stratégie de cross-sell et d\'upsell pour développer le revenu par client existant ?', questionEn: 'Do you have a cross-sell and upsell strategy to grow revenue per existing customer?', options: [{ value: 100, labelFr: 'Stratégie cross-sell documentée par segment, offres packagées, account management dédié, wallet share mesuré', labelEn: 'Documented cross-sell strategy by segment, packaged offers, dedicated account management, measured wallet share' }, { value: 60, labelFr: 'Quelques initiatives cross-sell, pas de stratégie formalisée', labelEn: 'Some cross-sell initiatives, no formalized strategy' }, { value: 25, labelFr: 'Focus exclusif acquisition, pas de développement des comptes existants', labelEn: 'Exclusive acquisition focus, no existing account development' }, { value: 0, labelFr: 'Aucune stratégie de croissance sur la base installée', labelEn: 'No growth strategy on installed base' }] },
  ]},
  { id: 'performance-com', titleFr: 'Performance Commerciale', titleEn: 'Sales Performance', descriptionFr: 'KPIs, reporting, pilotage, prévisions, rentabilité commerciale', descriptionEn: 'KPIs, reporting, steering, forecasts, sales profitability', icon: 'ri-bar-chart-line', color: '#0ea5e9', weight: 25, questions: [
    { id: 'pc-pc-1', questionFr: 'Pilotez-vous votre performance commerciale avec des KPIs clairs et un reporting régulier ?', questionEn: 'Do you steer your sales performance with clear KPIs and regular reporting?', options: [{ value: 100, labelFr: 'Tableau de bord commercial temps réel, KPIs par commercial/produit/région, revue hebdomadaire, prévisions mensuelles', labelEn: 'Real-time sales dashboard, KPIs by salesperson/product/region, weekly review, monthly forecasts' }, { value: 60, labelFr: 'Reporting mensuel basique, quelques KPIs suivis, revue irrégulière', labelEn: 'Basic monthly reporting, some KPIs tracked, irregular review' }, { value: 25, labelFr: 'Suivi minimal (CA global), pas de KPIs détaillés', labelEn: 'Minimal tracking (total revenue), no detailed KPIs' }, { value: 0, labelFr: 'Aucun pilotage de la performance commerciale', labelEn: 'No sales performance steering' }] },
  ]},
  { id: 'marche-concurrence', titleFr: 'Marché & Concurrence', titleEn: 'Market & Competition', descriptionFr: 'Connaissance marché, positionnement, pricing, différenciation, parts de marché', descriptionEn: 'Market knowledge, positioning, pricing, differentiation, market share', icon: 'ri-pie-chart-2-line', color: '#7c3aed', weight: 25, questions: [
    { id: 'pc-mc-1', questionFr: 'Connaissez-vous précisément votre marché, vos concurrents et votre positionnement concurrentiel ?', questionEn: 'Do you precisely know your market, your competitors and your competitive positioning?', options: [{ value: 100, labelFr: 'Étude de marché récente, analyse concurrentielle documentée, veille active, pricing optimisé par segment', labelEn: 'Recent market study, documented competitive analysis, active monitoring, segment-optimized pricing' }, { value: 60, labelFr: 'Connaissance informelle du marché, quelques données concurrentielles', labelEn: 'Informal market knowledge, some competitive data' }, { value: 25, labelFr: 'Connaissance approximative du marché, pas de données structurées', labelEn: 'Approximate market knowledge, no structured data' }, { value: 0, labelFr: 'Aucune connaissance formalisée du marché, navigation à vue', labelEn: 'No formalized market knowledge, ad hoc navigation' }] },
  ]},
];

export function getPerfComScoreColor(s: number): string { if (s >= 80) return '#059669'; if (s >= 60) return '#0ea5e9'; if (s >= 40) return '#d97706'; return '#dc2626'; }
export function getPerfComScoreLabel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Excellence Commerciale':'Sales Excellence'; if (s>=60) return f?'Performance Structurée':'Structured Performance'; if (s>=40) return f?'Performance Émergente':'Emerging Performance'; return f?'Performance Insuffisante':'Insufficient Performance'; }
export function getPerfComLevel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Niveau 4 — Commercial Excellence':'Level 4 — Commercial Excellence'; if (s>=60) return f?'Niveau 3 — Commercial Performer':'Level 3 — Commercial Performer'; if (s>=40) return f?'Niveau 2 — Commercial Builder':'Level 2 — Commercial Builder'; return f?'Niveau 1 — Commercial Starter':'Level 1 — Commercial Starter'; }
export function getPerfComReadiness(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Votre organisation commerciale est une machine bien huilée. Continuez à optimiser et à innover dans vos approches commerciales.':'Your sales organization is a well-oiled machine. Continue optimizing and innovating in your sales approaches.'; if (s>=60) return f?'Votre performance commerciale est structurée. Renforcez le pilotage par les données et la fidélisation pour atteindre l\'excellence.':'Your sales performance is structured. Strengthen data-driven steering and retention to reach excellence.'; if (s>=40) return f?'Votre performance commerciale est émergente. Structurez votre processus de vente et outillez votre force commerciale.':'Your sales performance is emerging. Structure your sales process and equip your sales force.'; return f?'Votre performance commerciale est insuffisante. Formalisez une stratégie commerciale, structurez votre équipe et mettez en place des KPIs.':'Your sales performance is insufficient. Formalize a sales strategy, structure your team and implement KPIs.'; }

export function getPerfComRisks(pa: Record<string,number>, gs: number, lang: string): string[] {
  const f=!lang.startsWith('en'); const r:string[]=[];
  if ((pa['acquisition']??0)<50) r.push(f?'RISQUE CRITIQUE — Acquisition clients défaillante : pas de processus, pas de pipeline — la croissance est menacée':'CRITICAL RISK — Failing customer acquisition: no process, no pipeline — growth is threatened');
  if ((pa['fidelisation']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Fidélisation inexistante : attrition non mesurée, pas de stratégie de rétention — les clients partent sans qu\'on sache pourquoi':'HIGH RISK — Non-existent retention: unmeasured attrition, no retention strategy — clients leave without knowing why');
  if ((pa['performance-com']??0)<50) r.push(f?'RISQUE MAJEUR — Absence de pilotage : pas de KPIs, pas de prévisions — navigation à vue, décisions non éclairées':'MAJOR RISK — No steering: no KPIs, no forecasts — blind navigation, uninformed decisions');
  if ((pa['marche-concurrence']??0)<50) r.push(f?'RISQUE MAJEUR — Méconnaissance du marché : pas d\'analyse concurrentielle, pricing non optimisé — perte de compétitivité':'MAJOR RISK — Market ignorance: no competitive analysis, non-optimized pricing — loss of competitiveness');
  return r;
}

export function getPerfComRecommendations(pa: Record<string,number>, gs: number, lang: string): {title:string;axis?:string;items:string[]}[] {
  const f=!lang.startsWith('en'); const recs:{title:string;axis?:string;items:string[]}[]=[];
  if ((pa['acquisition']??0)<60) recs.push({title:f?'Structurer l\'Acquisition':'Structure Acquisition',axis:'acquisition',items:f?['Déployer un CRM et structurer le pipeline commercial par étapes','Définir des objectifs par commercial et mettre en place un plan de prospection','Former et outiller la force de vente avec des arguments et des supports']:['Deploy a CRM and structure the sales pipeline by stages','Define objectives per salesperson and implement a prospecting plan','Train and equip the sales force with arguments and materials']});
  if ((pa['fidelisation']??0)<60) recs.push({title:f?'Développer la Fidélisation':'Develop Retention',axis:'fidelisation',items:f?['Mettre en place une mesure NPS trimestrielle avec plan d\'action','Définir une stratégie de cross-sell et d\'upsell par segment client','Structurer un programme de fidélité et de compte rendu régulier']:['Implement quarterly NPS measurement with action plan','Define a cross-sell and upsell strategy by customer segment','Structure a loyalty program and regular account review']});
  if ((pa['performance-com']??0)<60) recs.push({title:f?'Piloter la Performance':'Steer Performance',axis:'performance-com',items:f?['Construire un tableau de bord commercial avec KPIs clés','Mettre en place des revues commerciales hebdomadaires','Établir des prévisions mensuelles glissantes']:['Build a sales dashboard with key KPIs','Implement weekly sales reviews','Establish rolling monthly forecasts']});
  if ((pa['marche-concurrence']??0)<60) recs.push({title:f?'Analyser le Marché':'Analyze the Market',axis:'marche-concurrence',items:f?['Réaliser une étude de marché et une analyse concurrentielle formelle','Optimiser le pricing par segment sur base de données concurrentielles','Mettre en place une veille concurrentielle systématique']:['Conduct a formal market study and competitive analysis','Optimize pricing by segment based on competitive data','Implement systematic competitive monitoring']});
  if (recs.length===0) recs.push({title:f?'Maintenir l\'Excellence Commerciale':'Maintain Sales Excellence',items:f?['Explorer de nouveaux canaux de distribution','Investir dans l\'intelligence artificielle pour le scoring et le ciblage','Développer une culture de la performance commerciale']:['Explore new distribution channels','Invest in AI for scoring and targeting','Develop a sales performance culture']});
  return recs;
}