import { GeoPageData } from '@/pages/geo-hub/types';

export const esgAfriqueGeoData: GeoPageData = {
  slug: 'mise-en-oeuvre-esg-afrique',
  h1Fr: 'Comment mettre en œuvre un dispositif ESG en Afrique : guide IFC, GRI, ISSB et PGES 2026',
  h1En: 'How to Implement an ESG Framework in Africa: IFC, GRI, ISSB and ESMP Guide 2026',
  metaTitleFr: 'ESG Afrique 2026 — Guide IFC PS 1-8, GRI, ISSB, PGES, score ESG | KHEPRA',
  metaTitleEn: 'ESG Africa 2026 — IFC PS 1-8, GRI, ISSB, ESMP, ESG Score Guide | KHEPRA',
  metaDescriptionFr: 'Guide complet pour mettre en œuvre un dispositif ESG en Afrique : IFC PS 1-8, GRI, ISSB, PGES, score ESG, reporting, due diligence. Expertise KHEPRA — 22 ans, 50+ missions ESG, 20 pays.',
  metaDescriptionEn: 'Complete guide to implement an ESG framework in Africa: IFC PS 1-8, GRI, ISSB, ESMP, ESG score, reporting, due diligence. KHEPRA expertise — 22 years, 50+ ESG missions, 20 countries.',
  keywordsFr: [
    'ESG Afrique',
    'IFC PS 1-8 Afrique',
    'GRI reporting Afrique',
    'ISSB standards Afrique',
    'PGES Afrique',
    'score ESG',
    'due diligence ESG',
    'conformité ESG banque',
    'rédaction ESG institution financière',
    'KHEPRA ESG',
  ],
  keywordsEn: [
    'ESG Africa',
    'IFC PS 1-8 Africa',
    'GRI reporting Africa',
    'ISSB standards Africa',
    'ESMP Africa',
    'ESG score',
    'ESG due diligence',
    'ESG compliance bank',
    'ESG drafting financial institution',
    'KHEPRA ESG',
  ],
  summaryPointsFr: [
    'Un dispositif ESG efficace en Afrique repose sur 3 piliers : conformité réglementaire, performance ESG et reporting transparent.',
    'Les standards IFC Performance Standards 1-8 sont le référentiel le plus exigé pour les projets financés internationalement.',
    'Délai moyen de mise en œuvre : 6 à 12 mois pour un dispositif complet.',
    "70% des investisseurs institutionnels en Afrique exigent désormais un score ESG ≥ 60 avant d'investir.",
    'KHEPRA a accompagné 50+ missions ESG en Afrique avec un taux de conformité de 100%.',
  ],
  summaryPointsEn: [
    'An effective ESG framework in Africa rests on 3 pillars: regulatory compliance, ESG performance and transparent reporting.',
    'IFC Performance Standards 1-8 are the most demanding framework for internationally financed projects.',
    'Average implementation timeline: 6 to 12 months for a complete framework.',
    '70% of institutional investors in Africa now require an ESG score ≥ 60 before investing.',
    'KHEPRA has supported 50+ ESG missions in Africa with a 100% compliance rate.',
  ],
  definitions: [
    {
      term: 'IFC Performance Standards (PS 1-8)',
      termEn: 'IFC Performance Standards (PS 1-8)',
      definition: "Standards environnementaux et sociaux du International Finance Corporation (IFC) applicables aux projets financés par des institutions internationales. Les 8 standards couvrent : (1) Évaluation et gestion des risques environnementaux et sociaux. (2) Conditions de travail et sécurité. (3) Prévention et réduction de la pollution. (4) Santé et sécurité communautaire. (5) Acquisition et déplacement involontaire. (6) Biodiversité et services écosystémiques. (7) Populations autochtones. (8) Patrimoine culturel. En Afrique, les PS sont imposés par la plupart des bailleurs de fonds (IFC, BAD, AFD, FMO).",
      definitionEn: "Environmental and social standards of the International Finance Corporation (IFC) applicable to projects financed by international institutions. The 8 standards cover: (1) Assessment and management of environmental and social risks. (2) Labor and working conditions. (3) Pollution prevention and abatement. (4) Community health and safety. (5) Land acquisition and involuntary resettlement. (6) Biodiversity and ecosystem services. (7) Indigenous peoples. (8) Cultural heritage. In Africa, the PS are imposed by most donors (IFC, AfDB, AFD, FMO).",
    },
    {
      term: 'PGES — Plan de Gestion Environnementale et Sociale',
      termEn: 'ESMP — Environmental and Social Management Plan',
      definition: "Document stratégique qui synthétise les impacts environnementaux et sociaux d'un projet, les mesures d'atténuation, les responsabilités, le budget, le calendrier et les indicateurs de suivi. Le PGES est exigé par les standards IFC PS 1 et doit être validé par le Conseil d'Administration. Il est public et soumis à consultation des parties prenantes.",
      definitionEn: "Strategic document that synthesizes the environmental and social impacts of a project, mitigation measures, responsibilities, budget, timeline and monitoring indicators. The ESMP is required by IFC PS 1 and must be validated by the Board of Directors. It is public and subject to stakeholder consultation.",
    },
    {
      term: 'Score ESG',
      termEn: 'ESG score',
      definition: "Notation synthétique de la performance environnementale, sociale et de gouvernance d'une entreprise. Le score ESG standard est sur 100. Les investisseurs institutionnels en Afrique fixent généralement un seuil minimum de 60/100 pour investir. Le score est évalué selon 3 dimensions : Environnementale (bilan carbone, gestion des déchets, biodiversité), Sociale (droits des travailleurs, communautés, inclusion), Gouvernance (transparence, anti-corruption, conformité).",
      definitionEn: "Synthetic rating of the environmental, social and governance performance of a company. The standard ESG score is out of 100. Institutional investors in Africa generally set a minimum threshold of 60/100 to invest. The score is evaluated across 3 dimensions: Environmental (carbon footprint, waste management, biodiversity), Social (workers' rights, communities, inclusion), Governance (transparency, anti-corruption, compliance).",
    },
  ],
  steps: [
    {
      title: 'Diagnostic ESG initial et maturité',
      titleEn: 'Initial ESG diagnostic and maturity',
      description: "Évaluation de la maturité ESG selon 5 niveaux : 1 (informel) à 5 (leadership). Analyse des 3 dimensions : environnementale, sociale, gouvernance. Identification des écarts par rapport aux standards IFC, GRI, ISSB. Benchmark sectoriel. Livrable : rapport de maturité avec score ESG initial, heatmap des écarts et plan de fermeture.",
      descriptionEn: "ESG maturity assessment across 5 levels: 1 (informal) to 5 (leadership). Analysis of 3 dimensions: environmental, social, governance. Identification of gaps against IFC, GRI, ISSB standards. Sector benchmarking. Deliverable: maturity report with initial ESG score, gap heatmap and closing plan.",
      icon: 'ri-search-eye-line',
    },
    {
      title: 'Analyse des impacts et matrice matérialité',
      titleEn: 'Impact analysis and materiality matrix',
      description: "Identification des impacts environnementaux et sociaux du projet/entreprise : empreinte carbone, consommation d'eau, déchets, emploi local, communautés, biodiversité. Matrice de matérialité : importance pour les parties prenantes (clients, employés, communautés, régulateurs, investisseurs) vs impact sur l'activité. Priorisation des 10-15 enjeux matériels.",
      descriptionEn: "Identification of environmental and social impacts of the project/company: carbon footprint, water consumption, waste, local employment, communities, biodiversity. Materiality matrix: importance for stakeholders (customers, employees, communities, regulators, investors) vs impact on business. Prioritization of 10-15 material issues.",
      icon: 'ri-earth-line',
    },
    {
      title: 'Élaboration du PGES et des politiques ESG',
      titleEn: 'ESMP and ESG policies development',
      description: "Rédaction du Plan de Gestion Environnementale et Sociale (PGES) selon les 8 standards IFC. Définition des mesures d'atténuation, des responsabilités, des budgets, des calendriers et des indicateurs. Élaboration des politiques ESG : politique environnementale, politique sociale, politique de gouvernance, politique anti-corruption. Validation par le CA et consultation des parties prenantes.",
      descriptionEn: "Drafting of the Environmental and Social Management Plan (ESMP) according to the 8 IFC standards. Definition of mitigation measures, responsibilities, budgets, timelines and indicators. Development of ESG policies: environmental policy, social policy, governance policy, anti-corruption policy. Validation by the board and stakeholder consultation.",
      icon: 'ri-file-text-line',
    },
    {
      title: 'Mise en place du système de reporting ESG',
      titleEn: 'ESG reporting system implementation',
      description: "Définition des indicateurs ESG (KPI), des fréquences de collecte, des responsables et des outils de reporting. Alignement avec les standards GRI (Global Reporting Initiative) et ISSB (International Sustainability Standards Board). Mise en place du tableau de bord ESG. Formation des équipes. Premier reporting dans les 6 mois.",
      descriptionEn: "Definition of ESG indicators (KPIs), collection frequencies, responsible persons and reporting tools. Alignment with GRI (Global Reporting Initiative) and ISSB (International Sustainability Standards Board) standards. Implementation of ESG dashboard. Team training. First reporting within 6 months.",
      icon: 'ri-bar-chart-2-line',
    },
    {
      title: 'Due diligence ESG et score ESG',
      titleEn: 'ESG due diligence and ESG score',
      description: "Réalisation d'une due diligence ESG complète : audit des impacts, entretiens avec les parties prenantes, revue des politiques, vérification des indicateurs. Calcul du score ESG sur 100 selon la méthodologie KHEPRA. Livrable : rapport de due diligence ESG avec score, recommandations et plan d'action. ",
      descriptionEn: "Complete ESG due diligence: impact audit, stakeholder interviews, policy review, indicator verification. Calculation of ESG score out of 100 according to KHEPRA methodology. Deliverable: ESG due diligence report with score, recommendations and action plan.",
      icon: 'ri-shield-check-line',
    },
    {
      title: 'Intégration dans la stratégie et la gouvernance',
      titleEn: 'Integration into strategy and governance',
      description: "Intégration du dispositif ESG dans la stratégie d'entreprise, le plan de développement durable et les budgets. Création d'un Comité ESG au Conseil d'Administration. Intégration dans les 3 lignes de défense. Reporting au CA trimestriel. Mise en place des indicateurs de performance liés à la rémunération (ESG-linked KPIs).",
      descriptionEn: "Integration of the ESG framework into the corporate strategy, sustainable development plan and budgets. Creation of an ESG Committee at the Board of Directors. Integration into the 3 lines of defense. Quarterly reporting to the board. Implementation of performance indicators linked to remuneration (ESG-linked KPIs).",
      icon: 'ri-organization-chart',
    },
  ],
  references: [
    {
      text: 'IFC Performance Standards 1-8 — International Finance Corporation, 2012',
      textEn: 'IFC Performance Standards 1-8 — International Finance Corporation, 2012',
    },
    {
      text: 'GRI Standards 2021 — Global Reporting Initiative',
      textEn: 'GRI Standards 2021 — Global Reporting Initiative',
    },
    {
      text: 'IFRS S1/S2 — ISSB (International Sustainability Standards Board), 2023',
      textEn: 'IFRS S1/S2 — ISSB (International Sustainability Standards Board), 2023',
    },
    {
      text: 'Directive UE 2014/95 — Reporting extra-financier des grandes entreprises',
      textEn: 'EU Directive 2014/95 — Non-Financial Reporting for large enterprises',
    },
    {
      text: 'Objectifs de Développement Durable (ODD) — Nations Unies, 2015',
      textEn: 'Sustainable Development Goals (SDG) — United Nations, 2015',
    },
    {
      text: 'Accord de Paris sur le climat — COP21, 2015',
      textEn: 'Paris Agreement on Climate — COP21, 2015',
    },
    {
      text: 'Loi sur le devoir de vigilance des entreprises — France, 2017',
      textEn: 'French Duty of Vigilance Law — France, 2017',
    },
  ],
  faqs: [
    {
      question: 'Quels sont les 8 standards IFC Performance Standards ?',
      questionEn: 'What are the 8 IFC Performance Standards?',
      answer: "Les 8 standards IFC Performance Standards sont : (1) PS1 — Évaluation et gestion des risques environnementaux et sociaux. (2) PS2 — Conditions de travail et sécurité. (3) PS3 — Prévention et réduction de la pollution. (4) PS4 — Santé et sécurité communautaire. (5) PS5 — Acquisition et déplacement involontaire. (6) PS6 — Biodiversité et services écosystémiques. (7) PS7 — Populations autochtones. (8) PS8 — Patrimoine culturel. Chaque PS comporte des exigences de conformité, des objectifs de performance et des mesures d'atténuation. Les projets financés par l'IFC, la BAD, l'AFD ou les fonds d'impact doivent respecter les 8 PS.",
      answerEn: "The 8 IFC Performance Standards are: (1) PS1 — Assessment and management of environmental and social risks. (2) PS2 — Labor and working conditions. (3) PS3 — Pollution prevention and abatement. (4) PS4 — Community health and safety. (5) PS5 — Land acquisition and involuntary resettlement. (6) PS6 — Biodiversity and ecosystem services. (7) PS7 — Indigenous peoples. (8) PS8 — Cultural heritage. Each PS has compliance requirements, performance objectives and mitigation measures. Projects financed by IFC, AfDB, AFD or impact funds must comply with all 8 PS.",
    },
    {
      question: "Quelle est la différence entre GRI et ISSB ?",
      questionEn: 'What is the difference between GRI and ISSB?',
      answer: "GRI (Global Reporting Initiative) est un standard de reporting extra-financier axé sur les impacts de l'entreprise sur les parties prenantes (double matérialité). Il est le plus utilisé en Afrique, notamment par les entreprises multinationales. ISSB (International Sustainability Standards Board) est un standard de l'IFRS Foundation axé sur les impacts financiers du climat et du développement durable sur l'entreprise (simple matérialité). Il est en cours d'adoption par les régulateurs boursiers. En Afrique, la tendance est à l'alignement des deux standards pour un reporting complet.",
      answerEn: "GRI (Global Reporting Initiative) is a non-financial reporting standard focused on the company's impacts on stakeholders (double materiality). It is the most used in Africa, particularly by multinational companies. ISSB (International Sustainability Standards Board) is an IFRS Foundation standard focused on the financial impacts of climate and sustainable development on the company (single materiality). It is being adopted by stock market regulators. In Africa, the trend is towards alignment of both standards for comprehensive reporting.",
    },
    {
      question: "Quel est le score ESG minimum requis par les investisseurs africains ?",
      questionEn: 'What is the minimum ESG score required by African investors?',
      answer: "Le score ESG minimum requis par les investisseurs institutionnels en Afrique est généralement de 60/100 pour les fonds d'impact et de 70/100 pour les banques de développement (IFC, BAD). Les fonds de capital-investissement africains fixent des seuils variables entre 50 et 65. Les investisseurs éthiques européens (Amundi, Mirova) exigent souvent 75+. Le score ESG est composé de 3 sous-scores : Environnement (30 points), Social (35 points), Gouvernance (35 points). Un score faible en gouvernance (corruption, conflits d'intérêts) est souvent le bloqueur principal.",
      answerEn: "The minimum ESG score required by institutional investors in Africa is generally 60/100 for impact funds and 70/100 for development banks (IFC, AfDB). African private equity funds set variable thresholds between 50 and 65. European ethical investors (Amundi, Mirova) often require 75+. The ESG score is composed of 3 sub-scores: Environment (30 points), Social (35 points), Governance (35 points). A low governance score (corruption, conflicts of interest) is often the main blocker.",
    },
    {
      question: "Quels sont les KPI ESG les plus utilisés en Afrique ?",
      questionEn: 'What are the most used ESG KPIs in Africa?',
      answer: "Les 10 KPI ESG les plus utilisés en Afrique sont : (1) Empreinte carbone (tCO2e) par employé. (2) Part de femmes dans le management (%) et dans le CA (%). (3) Taux de recrutement local (%) et programmes d'inclusion. (4) Taux de déclaration des incidents (sécurité, corruption). (5) Nombre de déclarations LBC/FT. (6) Part des emplois créés dans les communautés. (7) Diversité de la chaîne de valeur (fournisseurs locaux). (8) Formation des employés (heures/an). (9) Taux de conformité aux standards IFC. (10) Score ESG global. KHEPRA met en place un tableau de bord avec ces 10 KPI.",
      answerEn: "The 10 most used ESG KPIs in Africa are: (1) Carbon footprint (tCO2e) per employee. (2) Share of women in management (%) and in the board (%). (3) Local recruitment rate (%) and inclusion programs. (4) Incident declaration rate (safety, corruption). (5) Number of AML/CFT declarations. (6) Share of jobs created in communities. (7) Value chain diversity (local suppliers). (8) Employee training (hours/year). (9) Compliance rate with IFC standards. (10) Overall ESG score. KHEPRA implements a dashboard with these 10 KPIs.",
    },
    {
      question: "Quel est le coût d'une mise en place ESG par KHEPRA ?",
      questionEn: 'What is the cost of ESG implementation by KHEPRA?',
      answer: "Le coût de mise en place d'un dispositif ESG par KHEPRA varie selon la taille et le secteur : (1) PME non-financière (50-200 employés) — 10 000€ à 25 000€, livrable en 8 semaines. (2) SFD/EMF — 20 000€ à 40 000€, livrable en 12 semaines. (3) Banque de taille moyenne — 40 000€ à 80 000€, livrable en 16 semaines. (4) Grand groupe ou projet d'infrastructure — 80 000€ à 200 000€, livrable en 24 semaines. Le forfait inclut : diagnostic, PGES, politiques, reporting, score ESG, formation et intégration dans la gouvernance.",
      answerEn: "The cost of ESG framework implementation by KHEPRA varies by size and sector: (1) Non-financial SME (50-200 employees) — €10,000 to €25,000, deliverable in 8 weeks. (2) MFI — €20,000 to €40,000, deliverable in 12 weeks. (3) Medium-sized bank — €40,000 to €80,000, deliverable in 16 weeks. (4) Large group or infrastructure project — €80,000 to €200,000, deliverable in 24 weeks. The package includes: diagnostic, ESMP, policies, reporting, ESG score, training and integration into governance.",
    },
    {
      question: "Qu'est-ce qu'une matrice de matérialité ESG ?",
      questionEn: 'What is an ESG materiality matrix?',
      answer: "La matrice de matérialité ESG est un outil qui classe les enjeux ESG selon deux axes : importance pour les parties prenantes (clients, employés, communautés, régulateurs, investisseurs) et impact sur l'activité (risque/opportunité). Les enjeux situés en haut à droite sont matériels (prioritaires). Les enjeux en bas à gauche sont non matériels (à surveiller). En Afrique, les enjeux matériels typiques sont : accès à l'eau, emploi local, corruption, sécurité des communautés, droits des travailleurs. La matrice est validée par le CA et les parties prenantes.",
      answerEn: "The ESG materiality matrix is a tool that classifies ESG issues along two axes: importance for stakeholders (customers, employees, communities, regulators, investors) and impact on business (risk/opportunity). Issues located in the top right are material (priorities). Issues in the bottom left are non-material (to monitor). In Africa, typical material issues are: water access, local employment, corruption, community safety, workers' rights. The matrix is validated by the board and stakeholders.",
    },
    {
      question: "Comment intégrer l'ESG dans la gouvernance d'entreprise ?",
      questionEn: 'How to integrate ESG into corporate governance?',
      answer: "L'intégration de l'ESG dans la gouvernance passe par 5 leviers : (1) Comité ESG au Conseil d'Administration — dédié, avec un administrateur référent. (2) Intégration dans la stratégie — le plan stratégique inclut des objectifs ESG chiffrés. (3) Intégration dans les budgets — lignes budgétaires ESG dédiées. (4) ESG-linked KPIs — indicateurs de performance liés à la rémunération des dirigeants. (5) Reporting au CA — trimestriel, avec des indicateurs de matérialité et des alertes. Les Circulaires BCEAO 01-2017 et 03-2017 créent un cadre favorable à cette intégration.",
      answerEn: "ESG integration into governance goes through 5 levers: (1) ESG Committee at the Board of Directors — dedicated, with a lead director. (2) Integration into strategy — the strategic plan includes quantified ESG objectives. (3) Integration into budgets — dedicated ESG budget lines. (4) ESG-linked KPIs — performance indicators linked to executive remuneration. (5) Reporting to the board — quarterly, with materiality indicators and alerts. BCEAO Circulars 01-2017 and 03-2017 create a favorable framework for this integration.",
    },
    {
      question: "Quels sont les enjeux ESG spécifiques à l'Afrique ?",
      questionEn: 'What are ESG issues specific to Africa?',
      answer: "Les 5 enjeux ESG spécifiques à l'Afrique sont : (1) Accès à l'eau et à l'énergie — les projets industriels doivent gérer l'impact sur les ressources hydriques. (2) Conflits fonciers et déplacements — l'acquisition de terres pour les projets agricoles ou miniers crée des tensions. (3) Inclusion financière — les institutions financières doivent démontrer leur impact sur l'inclusion. (4) Corruption — les investisseurs internationaux exigent des politiques anti-corruption renforcées. (5) Biodiversité — les zones de forêt tropicale et de savane sont des hotspots à protéger. KHEPRA intègre ces 5 enjeux dans chaque dispositif ESG.",
      answerEn: "The 5 ESG issues specific to Africa are: (1) Access to water and energy — industrial projects must manage impact on water resources. (2) Land conflicts and displacement — land acquisition for agricultural or mining projects creates tensions. (3) Financial inclusion — financial institutions must demonstrate their impact on inclusion. (4) Corruption — international investors require strengthened anti-corruption policies. (5) Biodiversity — tropical forest and savanna zones are hotspots to protect. KHEPRA integrates these 5 issues into every ESG framework.",
    },
    {
      question: "Quelle est la différence entre reporting ESG et due diligence ESG ?",
      questionEn: 'What is the difference between ESG reporting and ESG due diligence?',
      answer: "Le reporting ESG est la publication régulière (annuelle ou trimestrielle) des indicateurs ESG de l'entreprise, destinée aux parties prenantes et aux investisseurs. C'est un processus continu et transparent. La due diligence ESG est une investigation approfondie réalisée par un investisseur ou un acquéreur avant une transaction, visant à évaluer les risques ESG de la cible. Elle est ponctuelle, confidentielle et souvent plus stricte. Le reporting ESG répond aux normes GRI/ISSB ; la due diligence ESG répond aux standards IFC. Les deux sont complémentaires.",
      answerEn: "ESG reporting is the regular publication (annual or quarterly) of the company's ESG indicators, intended for stakeholders and investors. It is a continuous and transparent process. ESG due diligence is a thorough investigation conducted by an investor or acquirer before a transaction, aiming to evaluate the target's ESG risks. It is ad-hoc, confidential and often stricter. ESG reporting complies with GRI/ISSB standards; ESG due diligence complies with IFC standards. Both are complementary.",
    },
    {
      question: 'Comment mesurer l\'empreinte carbone d\'une entreprise africaine ? Méthodologie et outils.',
      questionEn: 'How to measure the carbon footprint of an African company? Methodology and tools.',
      answer: 'La mesure de l\'empreinte carbone d\'une entreprise africaine suit le protocole GHG (Greenhouse Gas Protocol) en 3 scopes : (1) Scope 1 — émissions directes (carburant, gaz, fluides frigorigènes). (2) Scope 2 — émissions indirectes liées à l\'énergie (électricité, chaleur achetée). En Afrique, le mix énergétique inclut souvent des générateurs diesel, ce qui augmente significativement le Scope 2. (3) Scope 3 — autres émissions indirectes (transport, déchets, achats, déplacements des employés, utilisation des produits vendus). Le Scope 3 représente 70-90% de l\'empreinte totale pour les institutions financières. Méthodologie : collecte des données physiques (litres de carburant, kWh, km parcourus, tonnes de déchets) × facteurs d\'émission (ADEME, IPCC, DEFRA). Outils : Bilan Carbone (ABC), GHG Protocol Tool, Carbon Trust, SimaPro. KHEPRA réalise des bilans carbone complets avec un plan de réduction sur 3-5 ans.',
      answerEn: 'Measuring the carbon footprint of an African company follows the GHG Protocol in 3 scopes: (1) Scope 1 — direct emissions (fuel, gas, refrigerant fluids). (2) Scope 2 — indirect energy-related emissions (purchased electricity, heat). In Africa, the energy mix often includes diesel generators, which significantly increases Scope 2. (3) Scope 3 — other indirect emissions (transport, waste, purchases, employee travel, use of sold products). Scope 3 represents 70-90% of the total footprint for financial institutions. Methodology: collection of physical data (liters of fuel, kWh, km traveled, tons of waste) × emission factors (ADEME, IPCC, DEFRA). Tools: Bilan Carbone (ABC), GHG Protocol Tool, Carbon Trust, SimaPro. KHEPRA conducts complete carbon footprints with a 3-5 year reduction plan.',
    },
    {
      question: 'Comment impliquer les communautés locales dans un projet avec impact ESG en Afrique ?',
      questionEn: 'How to involve local communities in a project with ESG impact in Africa?',
      answer: 'L\'implication des communautés locales est un pilier central de l\'ESG en Afrique, exigée par IFC PS1 et PS4. La méthodologie KHEPRA comprend 6 étapes : (1) Cartographie des parties prenantes — identification de tous les groupes affectés (villages, chefferies, associations, femmes, jeunes). (2) Consultation préalable (Free, Prior and Informed Consent — FPIC) — réunions publiques, entretiens individuels, enquêtes de perception, dans la langue locale. (3) Évaluation des impacts — identification des impacts positifs (emploi, infrastructures) et négatifs (bruit, poussière, eau, déplacement). (4) Plan de Gestion des Impacts Sociaux (PGIS) — mesures d\'atténuation, mécanisme de gestion des plaintes, comités de suivi locaux. (5) Contenu local — emploi prioritaire des locaux, sous-traitance locale, formation professionnelle. (6) Suivi participatif — réunions trimestrielles, enquêtes de satisfaction, indicateurs co-construits. Un projet sans acceptabilité sociale est voué à l\'échec. KHEPRA a géré 50+ consultations communautaires.',
      answerEn: 'Involving local communities is a central pillar of ESG in Africa, required by IFC PS1 and PS4. The KHEPRA methodology includes 6 steps: (1) Stakeholder mapping — identification of all affected groups (villages, chieftaincies, associations, women, youth). (2) Prior consultation (Free, Prior and Informed Consent — FPIC) — public meetings, individual interviews, perception surveys, in the local language. (3) Impact assessment — identification of positive impacts (employment, infrastructure) and negative impacts (noise, dust, water, displacement). (4) Social Impact Management Plan — mitigation measures, grievance mechanism, local monitoring committees. (5) Local content — priority employment of locals, local subcontracting, vocational training. (6) Participatory monitoring — quarterly meetings, satisfaction surveys, co-constructed indicators. A project without social acceptability is doomed to fail. KHEPRA has managed 50+ community consultations.',
    },
    {
      question: 'Qu\'est-ce que la taxonomie verte et comment s\'applique-t-elle en Afrique ?',
      questionEn: 'What is the green taxonomy and how does it apply in Africa?',
      answer: 'La taxonomie verte est un système de classification des activités économiques durables, développé initialement par l\'UE (Taxonomie Européenne 2020) et en cours d\'adaptation en Afrique. Elle définit 6 objectifs : (1) atténuation du changement climatique, (2) adaptation au changement climatique, (3) utilisation durable de l\'eau, (4) économie circulaire, (5) prévention de la pollution, (6) biodiversité. En Afrique, plusieurs initiatives émergent : (1) Taxonomie Verte Africaine — portée par la BAD et l\'IFC, adaptée aux spécificités africaines (agriculture durable, accès à l\'énergie, inclusion financière). (2) Taxonomie nationale — le Nigeria, l\'Afrique du Sud, le Kenya et le Maroc développent leurs propres taxonomies. (3) Taxonomie UEMOA/CEMAC — en discussion pour harmoniser les standards régionaux. Pour les banques africaines, la taxonomie verte impacte la classification du portefeuille de crédit (green assets vs brown assets) et le reporting ESG. KHEPRA prépare les institutions financières à la transition vers la taxonomie verte.',
      answerEn: 'The green taxonomy is a classification system for sustainable economic activities, initially developed by the EU (European Taxonomy 2020) and being adapted in Africa. It defines 6 objectives: (1) climate change mitigation, (2) climate change adaptation, (3) sustainable water use, (4) circular economy, (5) pollution prevention, (6) biodiversity. In Africa, several initiatives are emerging: (1) African Green Taxonomy — led by AfDB and IFC, adapted to African specificities (sustainable agriculture, energy access, financial inclusion). (2) National taxonomy — Nigeria, South Africa, Kenya and Morocco are developing their own taxonomies. (3) WAEMU/CEMAC taxonomy — under discussion to harmonize regional standards. For African banks, the green taxonomy impacts credit portfolio classification (green assets vs brown assets) and ESG reporting. KHEPRA prepares financial institutions for the transition to the green taxonomy.',
    },
    {
      question: 'Comment l\'ESG impacte-t-il la valorisation des entreprises africaines ?',
      questionEn: 'How does ESG impact the valuation of African companies?',
      answer: 'L\'ESG impacte la valorisation des entreprises africaines via 5 canaux : (1) Prime de valorisation — les entreprises avec un score ESG > 70 bénéficient d\'une prime de 10-20% sur les multiples de valorisation (EV/EBITDA, P/E) par rapport aux pairs non-ESG. (2) Coût du capital — un score ESG élevé réduit le coût de la dette de 50-150 points de base (les banques de développement offrent des taux préférentiels). (3) Accès aux investisseurs — 70% des fonds internationaux excluent les entreprises sans reporting ESG. (4) Risques — une mauvaise gestion ESG expose à des risques de réputation, de litige, de sanctions réglementaires, de boycott. (5) Résilience — les entreprises ESG-matures résistent mieux aux crises (études IFC 2020-2024). Pour une PME africaine, un investissement ESG de 50 000€ peut générer une augmentation de valorisation de 500 000€ à 2M€. KHEPRA intègre l\'ESG dans ses valorisations DCF via un ajustement du taux d\'actualisation.',
      answerEn: 'ESG impacts the valuation of African companies through 5 channels: (1) Valuation premium — companies with an ESG score > 70 benefit from a 10-20% premium on valuation multiples (EV/EBITDA, P/E) compared to non-ESG peers. (2) Cost of capital — a high ESG score reduces the cost of debt by 50-150 basis points (development banks offer preferential rates). (3) Investor access — 70% of international funds exclude companies without ESG reporting. (4) Risks — poor ESG management exposes to reputational, litigation, regulatory sanction, boycott risks. (5) Resilience — ESG-mature companies withstand crises better (IFC studies 2020-2024). For an African SME, an ESG investment of €50,000 can generate a valuation increase of €500,000 to €2M. KHEPRA integrates ESG into its DCF valuations through a discount rate adjustment.',
    },
    {
      question: 'Quels sont les financements disponibles pour les projets ESG en Afrique ?',
      questionEn: 'What financing is available for ESG projects in Africa?',
      answer: 'Les financements ESG en Afrique sont abondants mais sous-utilisés. 7 sources principales : (1) Green Climate Fund (GCF) — fonds ONU pour projets climatiques, tickets 10-250M$. (2) Global Environment Facility (GEF) — biodiversité, dégradation des sols, tickets 1-10M$. (3) Fonds Vert pour le Climat — guichet africain géré par la BAD. (4) Green Bonds — obligations vertes émises par les banques et États africains (marché de 10Md$ en 2025, en croissance de 30%/an). (5) Sustainability-Linked Loans — prêts bancaires dont le taux est indexé sur la performance ESG (ex : réduction de 50bp si le score ESG progresse de 5 points). (6) Carbon Credits — vente de crédits carbone sur les marchés volontaires (10-50$/tonne CO2). (7) Subventions bilatérales — AFD, GIZ, USAID, DFID financent des projets ESG à fonds perdus. KHEPRA identifie et mobilise ces financements pour ses clients.',
      answerEn: 'ESG financing in Africa is abundant but under-utilized. 7 main sources: (1) Green Climate Fund (GCF) — UN fund for climate projects, tickets $10-250M. (2) Global Environment Facility (GEF) — biodiversity, land degradation, tickets $1-10M. (3) Green Climate Fund — African window managed by AfDB. (4) Green Bonds — green bonds issued by African banks and states (market of $10Bn in 2025, growing 30%/year). (5) Sustainability-Linked Loans — bank loans whose rate is indexed to ESG performance (e.g., 50bp reduction if ESG score improves by 5 points). (6) Carbon Credits — sale of carbon credits on voluntary markets ($10-50/tonne CO2). (7) Bilateral grants — AFD, GIZ, USAID, DFID finance ESG projects on a grant basis. KHEPRA identifies and mobilizes these financings for its clients.',
    },
    {
      question: 'Comment préparer un rapport ESG conforme aux exigences des bailleurs internationaux (IFC, BAD, AFD) ?',
      questionEn: 'How to prepare an ESG report compliant with international donor requirements (IFC, AfDB, AFD)?',
      answer: 'Un rapport ESG conforme aux exigences des bailleurs internationaux doit inclure 10 sections : (1) Résumé exécutif — score ESG, performance clé, recommandations. (2) Périmètre et méthodologie — période, entités couvertes, standards utilisés (IFC, GRI, ISSB). (3) Gouvernance ESG — comité ESG, politique, intégration dans la stratégie. (4) Performance environnementale — empreinte carbone, eau, déchets, biodiversité. (5) Performance sociale — emploi, diversité, formation, santé-sécurité, communautés. (6) Performance gouvernance — anti-corruption, conformité, éthique, whistleblowing. (7) PGES — mesures d\'atténuation, budget, calendrier. (8) Indicateurs GRI/ISSB — tableau de bord avec 20-30 KPI. (9) Plan d\'amélioration continue — objectifs à 1 an, 3 ans, 5 ans. (10) Annexes — données brutes, méthodologie de calcul, lettres de vérification. Le rapport doit être vérifié par un auditeur externe pour les projets > 50M$. KHEPRA rédige des rapports ESG bailleur-ready.',
      answerEn: 'An ESG report compliant with international donor requirements must include 10 sections: (1) Executive summary — ESG score, key performance, recommendations. (2) Scope and methodology — period, covered entities, used standards (IFC, GRI, ISSB). (3) ESG governance — ESG committee, policy, strategic integration. (4) Environmental performance — carbon footprint, water, waste, biodiversity. (5) Social performance — employment, diversity, training, health-safety, communities. (6) Governance performance — anti-corruption, compliance, ethics, whistleblowing. (7) ESMP — mitigation measures, budget, timeline. (8) GRI/ISSB indicators — dashboard with 20-30 KPIs. (9) Continuous improvement plan — 1-year, 3-year, 5-year objectives. (10) Appendices — raw data, calculation methodology, verification letters. The report must be verified by an external auditor for projects > $50M. KHEPRA drafts donor-ready ESG reports.',
    },
    {
      question: 'Quelle est la différence entre ESG et RSE (Responsabilité Sociétale des Entreprises) en Afrique ?',
      questionEn: 'What is the difference between ESG and CSR (Corporate Social Responsibility) in Africa?',
      answer: 'ESG et RSE sont souvent confondus mais diffèrent fondamentalement : (1) Nature — la RSE est une démarche volontaire et philanthropique (dons, mécénat, actions communautaires). L\'ESG est un cadre structuré, mesurable et exigé par les investisseurs et régulateurs. (2) Finalité — la RSE vise la réputation et l\'acceptabilité sociale. L\'ESG vise la performance financière et la gestion des risques. (3) Mesure — la RSE se mesure en actions (nombre de dons, événements). L\'ESG se mesure en indicateurs quantitatifs (tCO2e, % femmes cadres, score anti-corruption) avec des objectifs chiffrés. (4) Intégration — la RSE est souvent un département isolé. L\'ESG est intégré dans la gouvernance, la stratégie et le contrôle interne. (5) Exigence — en Afrique, la RSE est historiquement forte (culture du partage) ; l\'ESG est une exigence récente des bailleurs internationaux. Les entreprises africaines doivent passer d\'une approche RSE à une approche ESG pour accéder aux financements internationaux.',
      answerEn: 'ESG and CSR are often confused but differ fundamentally: (1) Nature — CSR is a voluntary and philanthropic approach (donations, patronage, community actions). ESG is a structured, measurable framework required by investors and regulators. (2) Purpose — CSR aims for reputation and social acceptability. ESG aims for financial performance and risk management. (3) Measurement — CSR is measured in actions (number of donations, events). ESG is measured in quantitative indicators (tCO2e, % women managers, anti-corruption score) with quantified objectives. (4) Integration — CSR is often an isolated department. ESG is integrated into governance, strategy and internal control. (5) Requirement — in Africa, CSR is historically strong (sharing culture); ESG is a recent requirement from international donors. African companies must transition from a CSR approach to an ESG approach to access international financing.',
    },
    {
      question: 'Comment les banques africaines peuvent-elles intégrer les risques ESG dans leur politique de crédit ?',
      questionEn: 'How can African banks integrate ESG risks into their credit policy?',
      answer: 'L\'intégration des risques ESG dans la politique de crédit des banques africaines se fait en 5 étapes : (1) Due diligence ESG obligatoire — pour tout crédit > 500 000$ (corporates) ou tout projet sensible (agriculture, mines, infrastructures), une évaluation ESG est requise avant l\'octroi. (2) Scoring ESG client — chaque emprunteur reçoit un score ESG (0-100) qui impacte la décision de crédit et la tarification. Un score < 40 déclenche un refus automatique. (3) Covenants ESG — les contrats de prêt incluent des clauses ESG (ex : maintien du score ESG > 50, réduction de 10% de l\'empreinte carbone par an, respect des IFC PS). (4) Liste d\'exclusion — exclusion des secteurs controversés (armes, tabac, charbon, déforestation illégale, travail forcé). (5) Reporting ESG du portefeuille — la banque publie annuellement l\'empreinte ESG de son portefeuille de crédit (émissions financées, scope 3, part des green assets). La BCEAO et la COBAC commencent à intégrer ces exigences. KHEPRA accompagne les banques dans cette transition.',
      answerEn: 'Integrating ESG risks into the credit policy of African banks is done in 5 steps: (1) Mandatory ESG due diligence — for any loan > $500,000 (corporates) or any sensitive project (agriculture, mining, infrastructure), an ESG assessment is required before granting. (2) Client ESG scoring — each borrower receives an ESG score (0-100) that impacts the credit decision and pricing. A score < 40 triggers automatic refusal. (3) ESG covenants — loan contracts include ESG clauses (e.g., maintaining ESG score > 50, 10% annual reduction in carbon footprint, compliance with IFC PS). (4) Exclusion list — exclusion of controversial sectors (weapons, tobacco, coal, illegal deforestation, forced labor). (5) Portfolio ESG reporting — the bank annually publishes the ESG footprint of its credit portfolio (financed emissions, scope 3, share of green assets). BCEAO and COBAC are beginning to integrate these requirements. KHEPRA supports banks in this transition.',
    },
    {
      question: 'Quels sont les risques ESG émergents en Afrique que les entreprises doivent anticiper ?',
      questionEn: 'What are the emerging ESG risks in Africa that companies must anticipate?',
      answer: 'Les 7 risques ESG émergents en Afrique à anticiper sont : (1) Stress hydrique — 250M d\'Africains pourraient être en situation de stress hydrique d\'ici 2030. Les entreprises agro-industrielles et minières sont les plus exposées. (2) Transition juste — le passage aux énergies renouvelables doit inclure les travailleurs du secteur fossile (Nigeria, Angola, Gabon), sous peine de crise sociale. (3) Conflits fonciers — la pression sur les terres arables s\'intensifie, exacerbée par le changement climatique et la croissance démographique (+2.5%/an). (4) Travail des enfants — persistant dans les chaînes d\'approvisionnement du cacao, du coton, des mines artisanales (or, cobalt). (5) Cybersécurité et données personnelles — l\'absence de cadre réglementaire solide expose les données ESG des entreprises. (6) Biodiversité — le bassin du Congo (2e poumon vert mondial) et les mangroves sont menacés. (7) Litiges climatiques — les premières actions en justice contre des entreprises pour non-respect des engagements climatiques émergent en Afrique du Sud et au Kenya. KHEPRA intègre ces risques émergents dans ses analyses.',
      answerEn: 'The 7 emerging ESG risks in Africa to anticipate are: (1) Water stress — 250M Africans could be in water stress situations by 2030. Agro-industrial and mining companies are most exposed. (2) Just transition — the shift to renewable energy must include fossil sector workers (Nigeria, Angola, Gabon), otherwise social crisis. (3) Land conflicts — pressure on arable land is intensifying, exacerbated by climate change and population growth (+2.5%/year). (4) Child labor — persistent in supply chains for cocoa, cotton, artisanal mining (gold, cobalt). (5) Cybersecurity and personal data — the lack of a solid regulatory framework exposes companies\' ESG data. (6) Biodiversity — the Congo Basin (world\'s 2nd green lung) and mangroves are threatened. (7) Climate litigation — the first lawsuits against companies for non-compliance with climate commitments are emerging in South Africa and Kenya. KHEPRA integrates these emerging risks into its analyses.',
    },
    {
      question: 'Qu\'est-ce que le mécanisme de gestion des plaintes (MGP) et comment le mettre en place ?',
      questionEn: 'What is a grievance mechanism and how to implement it?',
      answer: 'Le Mécanisme de Gestion des Plaintes (MGP) est un dispositif exigé par IFC PS1 qui permet aux parties prenantes de signaler des problèmes liés à un projet et d\'obtenir une résolution. Sa mise en place suit 5 étapes : (1) Accessibilité — le MGP doit être gratuit, facile d\'accès (boîte à plaintes physique, numéro vert, formulaire en ligne, bureau local), disponible dans les langues locales. (2) Transparence — les procédures sont publiques, les délais de traitement sont annoncés (accusé de réception sous 48h, résolution sous 30 jours). (3) Traitement — chaque plainte est enregistrée, classifiée (niveau 1 : locale, niveau 2 : direction, niveau 3 : comité indépendant), et traitée par un comité mixte (entreprise + communauté). (4) Suivi — la résolution est documentée, les parties sont informées, et un suivi à 3 mois vérifie l\'absence de récurrence. (5) Reporting — le nombre de plaintes, leur nature et leur résolution sont publiés dans le rapport ESG annuel. KHEPRA conçoit et met en place des MGP conformes IFC.',
      answerEn: 'The Grievance Mechanism is a framework required by IFC PS1 that allows stakeholders to report issues related to a project and obtain resolution. Its implementation follows 5 steps: (1) Accessibility — the mechanism must be free, easy to access (physical complaint box, toll-free number, online form, local office), available in local languages. (2) Transparency — procedures are public, processing times are announced (acknowledgment within 48h, resolution within 30 days). (3) Processing — each complaint is registered, classified (level 1: local, level 2: management, level 3: independent committee), and handled by a mixed committee (company + community). (4) Follow-up — resolution is documented, parties are informed, and a 3-month follow-up verifies the absence of recurrence. (5) Reporting — the number of complaints, their nature and resolution are published in the annual ESG report. KHEPRA designs and implements IFC-compliant grievance mechanisms.',
    },
  ],
  internalLinks: [
    {
      label: 'Hub ESG — Ressources et conformité',
      labelEn: 'ESG Hub — Resources and Compliance',
      href: '/knowledge-hub/esg',
    },
    {
      label: 'Guide ESG Afrique — Score et reporting',
      labelEn: 'Africa ESG Guide — Score and Reporting',
      href: '/guide-esg-afrique',
    },
    {
      label: 'Diagnostic ESG — Outil en ligne gratuit',
      labelEn: 'ESG Diagnostic — Free online tool',
      href: '/tools/diagnostic-esg-impact',
    },
    {
      label: 'Due Diligence ESG — Service KHEPRA',
      labelEn: 'ESG Due Diligence — KHEPRA Service',
      href: '/services/due-diligence-acquisition',
    },
    {
      label: 'Réussir une due diligence en Afrique — Guide complet',
      labelEn: 'How to Succeed in Due Diligence in Africa — Complete Guide',
      href: '/geo-hub/reussir-due-diligence-afrique',
    },
    {
      label: 'Gouvernance d\'entreprise en Afrique — Comité ESG, CA',
      labelEn: 'Corporate Governance in Africa — ESG Committee, Board',
      href: '/geo-hub/renforcer-gouvernance-entreprise',
    },
  ],
  ctaVariant: 'diagnostic',
  ctaContextFr: 'Évaluez votre maturité ESG avec KHEPRA',
  ctaContextEn: 'Evaluate your ESG maturity with KHEPRA',
  peopleAlsoAsk: [
    {
      question: 'Quels sont les 8 standards IFC Performance Standards ?',
      questionEn: 'What are the 8 IFC Performance Standards?',
      answer: 'Les 8 standards IFC sont : PS1 (évaluation et gestion des risques E&S), PS2 (conditions de travail), PS3 (prévention pollution), PS4 (santé communautaire), PS5 (déplacement involontaire), PS6 (biodiversité), PS7 (populations autochtones), PS8 (patrimoine culturel). Les projets financés par IFC, BAD, AFD doivent respecter les 8 PS.',
      answerEn: 'The 8 IFC standards are: PS1 (E&S risk assessment), PS2 (working conditions), PS3 (pollution prevention), PS4 (community health), PS5 (involuntary resettlement), PS6 (biodiversity), PS7 (indigenous peoples), PS8 (cultural heritage). Projects financed by IFC, AfDB, AFD must comply with all 8 PS.',
    },
    {
      question: 'Quelle est la différence entre GRI et ISSB ?',
      questionEn: 'What is the difference between GRI and ISSB?',
      answer: 'GRI est un standard de reporting extra-financier axé sur les impacts de l\'entreprise sur les parties prenantes (double matérialité). ISSB est un standard IFRS axé sur les impacts financiers du climat sur l\'entreprise (simple matérialité). En Afrique, la tendance est à l\'alignement des deux pour un reporting complet.',
      answerEn: 'GRI is a non-financial reporting standard focused on company impacts on stakeholders (double materiality). ISSB is an IFRS standard focused on financial impacts of climate on the company (single materiality). In Africa, the trend is toward alignment of both for comprehensive reporting.',
    },
    {
      question: 'Quel est le score ESG minimum requis par les investisseurs en Afrique ?',
      questionEn: 'What is the minimum ESG score required by investors in Africa?',
      answer: 'Les fonds d\'impact exigent généralement 60/100, les banques de développement (IFC, BAD) 70/100, les fonds PE africains 50-65, et les investisseurs éthiques européens 75+. Le score se compose de Environnement (30 pts), Social (35 pts), Gouvernance (35 pts).',
      answerEn: 'Impact funds generally require 60/100, development banks (IFC, AfDB) 70/100, African PE funds 50-65, and European ethical investors 75+. The score is composed of Environment (30 pts), Social (35 pts), Governance (35 pts).',
    },
    {
      question: 'Quels sont les KPI ESG les plus utilisés en Afrique ?',
      questionEn: 'What are the most used ESG KPIs in Africa?',
      answer: 'Les 10 KPI les plus utilisés sont : empreinte carbone par employé, part de femmes dans le management, taux de recrutement local, taux de déclaration d\'incidents, déclarations LBC/FT, emplois créés dans les communautés, diversité fournisseurs locaux, formation des employés, conformité IFC, score ESG global.',
      answerEn: 'The 10 most used KPIs are: carbon footprint per employee, share of women in management, local recruitment rate, incident declaration rate, AML/CFT declarations, jobs created in communities, local supplier diversity, employee training, IFC compliance, overall ESG score.',
    },
    {
      question: 'Quel est le coût d\'une mise en place ESG par KHEPRA ?',
      questionEn: 'What is the cost of ESG implementation by KHEPRA?',
      answer: 'Le coût varie : PME (50-200 employés) 10 000€-25 000€, SFD/EMF 20 000€-40 000€, banque moyenne 40 000€-80 000€, grand groupe 80 000€-200 000€. Le forfait inclut diagnostic, PGES, politiques, reporting, score ESG, formation et intégration dans la gouvernance.',
      answerEn: 'Cost varies: SME (50-200 employees) €10,000-€25,000, MFI €20,000-€40,000, medium bank €40,000-€80,000, large group €80,000-€200,000. The package includes diagnostic, ESMP, policies, reporting, ESG score, training and integration into governance.',
    },
  ],
};