import { useState, useEffect } from 'react';

export interface ThinkingSpace {
  id: string;
  spaceType: string;
  name: string;
  client: string;
  sector: string;
  jurisdiction: string;
  pastAnalyses: string[];
  decisions: string[];
  hypothesesRetained: string[];
  hypothesesRejected: string[];
  sources: string[];
  arbitrages: string[];
  documents: string[];
  experts: string[];
  reconstitutionDate: string;
  confidenceScore: number;
}

export interface ReasoningMemoryItem {
  id: string;
  title: string;
  decisionDate: string;
  decisionMaker: string;
  context: string;
  options: { name: string; pros: string; cons: string }[];
  decisiveFactors: string[];
  risksAccepted: string[];
  confidenceAtDecision: number;
  outcome: string;
}

export interface ContinuityDossier {
  id: string;
  dossierRef: string;
  title: string;
  client: string;
  status: string;
  history: { date: string; action: string; version: string; pages: number }[];
  decisions: string[];
  knowledgeGenerated: string[];
  validators: string[];
  lastModified: string;
  confidenceScore: number;
}

export interface VirtualKnowledgeGraph {
  nodes: number;
  embeddings: number;
  categories: number;
  relations: { from: string; to: string; type: string; strength: number; description: string }[];
  topNodes: { name: string; connections: number; category: string }[];
}

export interface AutoSeedingData {
  newlyDetected: { concept: string; domain: string; sources: number; confidence: number }[];
  newlyLinkedAssets: { source: string; target: string; type: string }[];
  trendAcceleration: { trend: string; growth: string; period: string }[];
}

export interface CrossCapitalizationData {
  similarMissions: { missionA: string; missionB: string; similarity: number; sharedDomains: string[]; reusableAssets: string[]; gainEstimate: string }[];
  similarRisks: { risk: string; count: number; missions: string[] }[];
  similarOffers: { offer: string; count: number; pipelineValue: string }[];
}

export interface SelfImprovementData {
  evaluationCycles: number;
  lastCycle: {
    date: string;
    scores: Record<string, number>;
    improvements: string[];
    blindSpots: string[];
    optimizations: string[];
  };
  improvementsDeployed: number;
  autoFixesApplied: number;
}

export interface ThinkTankData {
  autoGenerated: { source: string; production: string; status: string; targetDate: string; citations: number }[];
  researchAxes: string[];
  reformProposals: string[];
}

export interface ObservatoryData {
  detectedChanges: { type: string; description: string; impact: string; affectedMissions: string[] }[];
  connectedDomains: string[];
}

export interface ExpertiseEvolutionData {
  enrichedArtefacts: { artefact: string; newEntries?: number; total?: number; newSection?: string; pages?: number; update?: string; newDimension?: string; lastMission: string }[];
  guidesCount: number;
  totalPages: number;
  templates: number;
  specializedTemplates: number;
}

export interface OrganizationalLearningData {
  cycles: { phase: string; description: string; date: string; outcomes: string }[];
  metrics: {
    cycleDuration: string;
    roiCapitalization: string;
    timeReduction: string;
    qualityIncrease: string;
    knowledgeReuseRate: string;
  };
}

export interface GenoraGlobalKPIs {
  thinkingSpaces: number;
  reconstructedContexts: number;
  reasoningMemories: number;
  decisionTraces: number;
  knowledgeGraphNodes: number;
  knowledgeGraphRelations: number;
  virtualLinks: number;
  capitalizationEntries: number;
  autoSeededConcepts: number;
  crossCapitalizationMatches: number;
  selfImprovementCycles: number;
  improvementsDeployed: number;
  thinkTankProductions: number;
  observatoryAlerts: number;
  enrichedArtefacts: number;
  learningCycles: number;
  totalConfidenceAvg: number;
  productionLatencyMs: number;
  queryOptimizationPct: number;
  costFCFA: number;
  readiness: string;
}

export function useKOSGenoraCapitalization() {
  const [thinkingSpaces, setThinkingSpaces] = useState<ThinkingSpace[]>([]);
  const [reasoningMemory, setReasoningMemory] = useState<ReasoningMemoryItem[]>([]);
  const [intellectualContinuity, setIntellectualContinuity] = useState<ContinuityDossier[]>([]);
  const [virtualKnowledgeGraph, setVirtualKnowledgeGraph] = useState<VirtualKnowledgeGraph | null>(null);
  const [autoSeeding, setAutoSeeding] = useState<AutoSeedingData | null>(null);
  const [crossCapitalization, setCrossCapitalization] = useState<CrossCapitalizationData | null>(null);
  const [selfImprovement, setSelfImprovement] = useState<SelfImprovementData | null>(null);
  const [thinkTank, setThinkTank] = useState<ThinkTankData | null>(null);
  const [intelligentObservatory, setIntelligentObservatory] = useState<ObservatoryData | null>(null);
  const [expertiseEvolution, setExpertiseEvolution] = useState<ExpertiseEvolutionData | null>(null);
  const [organizationalLearning, setOrganizationalLearning] = useState<OrganizationalLearningData | null>(null);
  const [globalKPIs, setGlobalKPIs] = useState<GenoraGlobalKPIs | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [dataSource, setDataSource] = useState<'mock' | 'supabase'>('mock');

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        // Try to fetch from Supabase strategic_memory for live data
        const supabaseUrl = (import.meta as Record<string, unknown>).env ? (import.meta as Record<string, Record<string, string>>).env.VITE_PUBLIC_SUPABASE_URL : undefined;
        if (supabaseUrl) {
          try {
            const supabaseKey = (import.meta as Record<string, Record<string, string>>).env.VITE_PUBLIC_SUPABASE_ANON_KEY;
            const resp = await fetch(`${supabaseUrl}/rest/v1/strategic_memory?select=*&memory_type=in.(thinking_space,reasoning,continuity,capitalization,auto_seed,long_term,self_improvement,cross_cap,decision,think_tank,observatory,expertise,learning,production,knowledge_graph)&order=created_at.desc&limit=50`, {
              headers: { apikey: supabaseKey || '', Authorization: `Bearer ${supabaseKey || ''}` },
            });
            if (resp.ok) {
              const data = await resp.json();
              if (!cancelled && data && data.length > 0) {
                setDataSource('supabase');
                // Map Supabase data to thinking spaces
                const spaces = data.filter((m: Record<string, unknown>) => m.memory_type === 'thinking_space').map((m: Record<string, unknown>) => ({
                  id: String(m.id),
                  spaceType: 'Mission',
                  name: String(m.title || ''),
                  client: '',
                  sector: '',
                  jurisdiction: '',
                  pastAnalyses: [],
                  decisions: [],
                  hypothesesRetained: [],
                  hypothesesRejected: [],
                  sources: [],
                  arbitrages: [],
                  documents: [],
                  experts: [],
                  reconstitutionDate: String(m.created_at || ''),
                  confidenceScore: 90,
                }));
                if (spaces.length > 0) setThinkingSpaces(spaces);
              }
            }
          } catch {
            // Supabase unavailable, fallback to mock
          }
        }
      } catch {
        // ignore
      }
      if (!cancelled) setLoading(false);
    }
    load();
    return () => { cancelled = true; };
  }, []);

  // Fallback to mock data
  useEffect(() => {
    if (!loading && thinkingSpaces.length === 0) {
      import('@/mocks/kosGenoraCapitalization').then((m) => {
        setThinkingSpaces(m.thinkingSpaces);
        setReasoningMemory(m.reasoningMemory);
        setIntellectualContinuity(m.intellectualContinuity);
        setVirtualKnowledgeGraph(m.virtualKnowledgeGraph);
        setAutoSeeding(m.autoSeeding);
        setCrossCapitalization(m.crossCapitalization);
        setSelfImprovement(m.selfImprovement);
        setThinkTank(m.thinkTank);
        setIntelligentObservatory(m.intelligentObservatory);
        setExpertiseEvolution(m.expertiseEvolution);
        setOrganizationalLearning(m.organizationalLearning);
        setGlobalKPIs(m.globalKPIs);
        setDataSource('mock');
      });
    }
  }, [loading, thinkingSpaces.length]);

  const refresh = () => {
    setLoading(true);
    setError(null);
    setTimeout(() => setLoading(false), 500);
  };

  return {
    thinkingSpaces,
    reasoningMemory,
    intellectualContinuity,
    virtualKnowledgeGraph,
    autoSeeding,
    crossCapitalization,
    selfImprovement,
    thinkTank,
    intelligentObservatory,
    expertiseEvolution,
    organizationalLearning,
    globalKPIs,
    loading,
    error,
    dataSource,
    refresh,
  };
}