const common = {
  faq: { title: 'Maswali Yanayoulizwa Mara kwa Mara', badge: 'FAQ', description: 'Pata majibu kwa maswali ya kawaida kuhusu huduma zetu.' },
  contact: { title: 'Wasiliana Nasi', subtitle: 'Jadili mradi wako wa kimkakati nasi', name: 'Jina kamili', email: 'Barua pepe', phone: 'Simu', company: 'Shirika', message: 'Ujumbe', submit: 'Tuma', sending: 'Inatumwa…', success: 'Ujumbe umetumwa kwa mafanikio!', error: 'Hitilafu imetokea.', address: 'Anwani', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Mshirika wako wa kimkakati katika ushauri, ukaguzi wa kifedha, utawala na mageuzi ya kidijitali', quickLinks: 'Viungo vya Haraka', services: 'Huduma', about: 'Kuhusu', blog: 'Blogu', contact: 'Wasiliana', legalLinks: 'Kisheria', privacy: 'Sera ya Faragha', terms: 'Masharti ya Matumizi', followUs: 'Tufuate', rights: 'Haki zote zimehifadhiwa.' },
  common: { learnMore: 'Jifunze zaidi' },
  cta: { diagnostic_free: 'Uchunguzi bila malipo', diagnostic_subtitle: 'Jibu ndani ya saa 2 · Hakuna ahadi' },
  leadMagnet: { whitepaper: { title: 'Pakua Karatasi yetu Nyeupe', description: 'Uchambuzi wa kina na mapendekezo.', button: 'Pakua Karatasi Nyeupe' }, webinar: { title: 'Jiunge na Mada yetu Inayokuja', description: 'Badilishana moja kwa moja na wataalam wetu.', button: 'Jiandikishe kwa Mada' }, diagnostic: { title: 'Uchunguzi wa Kimkakati Bila Malipo', description: 'Dakika 30 na mtaalam kuchambua hali yako.', button: 'Anza Uchunguzi' }, newsletter: { title: 'Jarida letu la Kimkakati', description: 'Uchambuzi wa kipekee moja kwa moja kwenye barua pepe yako.', button: 'Jiandikishe kwa Jarida' } },
  monitoring: { title: 'Ufuatiliaji wa Kiufundi', subtitle: 'Hitilafu 404 na nyakati za majibu', loading: 'Inapakia data…', retry: 'Jaribu tena', timeRange: { '24h': 'Saa 24', '7d': 'Siku 7', '30d': 'Siku 30' }, stats: { total404: 'Hitilafu 404', total404Sub: 'Kurasa ambazo hazipo', totalErrors: 'Hitilafu HTTP/JS', totalErrorsSub: 'Maombi na skripti', avgResponse: 'Wastani wa muda API', avgResponseSub: 'ms', avgPageLoad: 'Upakiaji wa ukurasa', avgPageLoadSub: 'ms' }, notFound: { title: 'URL 404 Kuu', subtitle: 'Kurasa zinazokosekana mara nyingi', url: 'URL', count: 'Matukio', empty: 'Hakuna hitilafu zilizotambuliwa' }, performance: { title: 'Muda wa Majibu API', subtitle: 'Wastani na upeo', tooltipAvg: 'Wastani', tooltipMax: 'Upeo', tooltipCount: 'Maombi', empty: 'Hakuna data' }, topErrors: { title: 'Hitilafu kuu', subtitle: 'Hitilafu za mara kwa mara', empty: 'Hakuna hitilafu' }, errorLog: { title: 'Kumbukumbu ya hitilafu', subtitle: 'Hitilafu za hivi karibuni', type: 'Aina', message: 'Ujumbe', url: 'URL', date: 'Tarehe', empty: 'Hakuna hitilafu za hivi karibuni' }, navigation: { title: 'Urambazaji', subtitle: 'Nyakati za upakiaji wa kurasa', empty: 'Hakuna data' } },
  dashboard: { login: { title: 'Dashibodi', subtitle: 'Ufikiaji wa wasimamizi', passwordLabel: 'Nenosiri', passwordPlaceholder: 'Ingiza nenosiri', loginButton: 'Ingia', incorrectPassword: 'Nenosiri si sahihi' }, header: { title: 'Dashibodi', subtitle: 'Ufuatiliaji wa ubadilishaji na utendaji', timeRange: { '7d': 'Siku 7', '30d': 'Siku 30', '90d': 'Siku 90', all: 'Zote' }, refreshButton: 'Onyesha upya' }, loading: 'Inapakia data…', kpis: { totalLeads: { title: 'Jumla ya Viongozi', subtitle: 'wapya' } }, pipeline: { title: 'Bomba la ubadilishaji' }, sources: { title: 'Vyanzo vya upatikanaji' }, formTypes: { title: 'Utendaji kwa aina ya fomu', ofTotal: 'ya jumla' }, recentLeads: { title: 'Viongozi wa hivi karibuni', table: { date: 'Tarehe', contact: 'Mwasiliani', organization: 'Shirika', type: 'Aina', score: 'Alama', status: 'Hali', source: 'Chanzo' } }, status: { new: 'Mpya', meeting_scheduled: 'Mkutano umepangwa', qualified: 'Aliyehitimu', converted: 'Amebadilishwa', lost: 'Amepotea' }, formType: { contact: 'Mawasiliano', diagnostic: 'Uchunguzi', expert: 'Mtaalam', newsletter: 'Jarida' }, metrics: { toolCompletions: { title: 'Zana Zilizokamilishwa', subtitle: 'Uchunguzi' } }, diagnostics: { title: 'Uchunguzi wa Hivi Karibuni', table: { date: 'Tarehe', tool: 'Zana', score: 'Alama' } }, downloads: { title: 'Upakuaji wa Hivi Karibuni', table: { date: 'Tarehe', resource: 'Rasilimali', contact: 'Mwasiliani', country: 'Nchi' }, unknownResource: 'Rasilimali isiyojulikana' }, noData: 'Hakuna data', retry: 'Jaribu tena' },
};

export default common;