// KOS Self-Learning Engine — Base de connaissances réglementaire auto-apprenante
// Patterns de formulation, règles internes générées, historique des corrections

export interface RegulatoryPattern {
  id: string;
  category: 'formulation' | 'source' | 'governance' | 'aml_cft' | 'prudential' | 'legal';
  severity: 'critique' | 'élevé' | 'moyen';
  pattern: string;
  description: string;
  correction: string;
  rule: string;
  occurrencesFound: number;
  dateAdded: string;
  sourceArticles: string[];
}

export interface CorrectionRecord {
  id: string;
  articleSlug: string;
  articleTitle: string;
  patternId: string;
  before: string;
  after: string;
  motif: string;
  scoreBefore: number;
  scoreAfter: number;
  timestamp: string;
  validatedBy: string;
}

export interface KnowledgeRule {
  id: string;
  domain: 'exactitude' | 'tracabilite' | 'gouvernance' | 'aml_cft' | 'clarte' | 'risque_juridique';
  weight: number;
  rule: string;
  examples: string[];
  autoGenerated: boolean;
  generationDate: string;
  parentPatternId: string;
}

export interface LearningStats {
  totalArticlesScanned: number;
  totalCorrectionsApplied: number;
  totalPatternsDetected: number;
  totalRulesGenerated: number;
  averageScoreBefore: number;
  averageScoreAfter: number;
  mostCommonPattern: string;
  lastLearningCycle: string;
  nextScheduledScan: string;
  autoFixEnabled: boolean;
}

// ═══ REGULATORY PATTERNS — Détectés et corrigés automatiquement ═══

export const REGULATORY_PATTERNS: RegulatoryPattern[] = [
  {
    id: 'PAT-001',
    category: 'formulation',
    severity: 'critique',
    pattern: 'conforme (à|au|aux)',
    description: 'Affirmation de conformité sans validation officielle par le régulateur',
    correction: 'Aligné sur les exigences de',
    rule: 'Ne jamais affirmer "conforme à [texte]" sans validation officielle. Remplacer par "aligné sur les exigences de [texte]".',
    occurrencesFound: 47,
    dateAdded: '2026-07-01',
    sourceArticles: ['reforme-ratio-solvabilite-uemoa-2026', 'gouvernance-sfd-piliers-bceao-investisseurs-2026', 'digitalisation-sfd-bceao-2026'],
  },
  {
    id: 'PAT-002',
    category: 'formulation',
    severity: 'critique',
    pattern: 'agréé (par|BCEAO|COBAC|régulateur)',
    description: 'Utilisation abusive du terme "agréé" pour une institution privée',
    correction: 'Accompagnement réglementaire / Expertise',
    rule: 'Seul le Ministère des Finances / le régulateur délivre un agrément. Une institution privée ne peut se qualifier d\'"agréée".',
    occurrencesFound: 23,
    dateAdded: '2026-07-01',
    sourceArticles: ['microfinance-ratios-prudentiels-sfd-emf-bceao-cobac', 'textes-officiels-sfd-uemoa-catalogue-22-instructions-bceao'],
  },
  {
    id: 'PAT-003',
    category: 'formulation',
    severity: 'critique',
    pattern: 'certifi(é|e|er) (BCEAO|COBAC|GAFI|GIABA)',
    description: 'Pseudo-certification par une autorité qui ne certifie pas les produits/services tiers',
    correction: 'Expertise alignée sur les standards de',
    rule: 'Aucune autorité réglementaire (BCEAO, COBAC, GAFI) ne certifie les produits ou services de consultants tiers.',
    occurrencesFound: 18,
    dateAdded: '2026-07-01',
    sourceArticles: ['audit-credit-scoring-2026', 'lbcft-gafi-2026'],
  },
  {
    id: 'PAT-004',
    category: 'formulation',
    severity: 'élevé',
    pattern: 'garanti(t|r) (la conformité|conformité|conforme)',
    description: 'Garantie de conformité — juridiquement impossible pour un tiers',
    correction: 'Renforcement du dispositif de conformité',
    rule: 'La conformité est un processus continu, non un état garanti. Aucun tiers ne peut garantir la conformité d\'une institution.',
    occurrencesFound: 31,
    dateAdded: '2026-07-01',
    sourceArticles: ['gouvernance-sfd-piliers-bceao-investisseurs-2026', 'conseil-administration-cobac-2026'],
  },
  {
    id: 'PAT-005',
    category: 'formulation',
    severity: 'élevé',
    pattern: 'approuvé (par|BCEAO|COBAC)',
    description: 'Affirmation d\'approbation réglementaire inexistante',
    correction: 'Aligné sur les exigences de',
    rule: 'Les régulateurs n\'approuvent pas les services ou publications de tiers. Remplacer par "aligné sur les exigences de".',
    occurrencesFound: 14,
    dateAdded: '2026-07-01',
    sourceArticles: ['microfinance-ratios-prudentiels-sfd-emf-bceao-cobac'],
  },
  {
    id: 'PAT-006',
    category: 'source',
    severity: 'critique',
    pattern: 'ratio (de )?(solvabilité|liquidité|couverture|division)',
    description: 'Ratio prudentiel cité sans référence à l\'article du texte source',
    correction: 'Ajout de la référence exacte : Instruction/Article/Date',
    rule: 'Ne jamais affirmer un ratio prudentiel sans citer l\'article exact du texte BCEAO/COBAC correspondant.',
    occurrencesFound: 56,
    dateAdded: '2026-07-01',
    sourceArticles: ['microfinance-ratios-prudentiels-sfd-emf-bceao-cobac', 'reforme-ratio-solvabilite-uemoa-2026', 'finance-islamique-sfd-dispositions-generales-instruction-bceao-003-2018'],
  },
  {
    id: 'PAT-007',
    category: 'legal',
    severity: 'élevé',
    pattern: 'obligation (réglementaire|légale)',
    description: 'Affirmation d\'obligation sans référence juridique précise',
    correction: 'Exigence issue de [référence exacte]',
    rule: 'Toute "obligation" doit être sourcée sur un article identifiable. Remplacer "obligation réglementaire" par "exigence issue de [texte]".',
    occurrencesFound: 42,
    dateAdded: '2026-07-01',
    sourceArticles: ['lbcft-gafi-2026', 'protection-donnees-personnelles-secteur-financier-uemoa-rgpd-bceao-2026'],
  },
  {
    id: 'PAT-008',
    category: 'governance',
    severity: 'moyen',
    pattern: 'conseil d\'administration (doit|devrait)',
    description: 'Prescription non sourcée sur les devoirs du CA',
    correction: 'Il est recommandé au Conseil d\'Administration, conformément à [référence], de',
    rule: 'Les prescriptions sur les devoirs du CA doivent toujours être rattachées à un texte OHADA/COBAC/BCEAO.',
    occurrencesFound: 35,
    dateAdded: '2026-07-02',
    sourceArticles: ['conseil-administration-cobac-2026', 'independance-administrateurs-circulaire-01-2017'],
  },
  {
    id: 'PAT-009',
    category: 'aml_cft',
    severity: 'élevé',
    pattern: '(KYC|bénéficiaire effectif|PPE|déclaration de soupçon)',
    description: 'Terme AML/CFT sans référence au cadre juridique applicable',
    correction: 'Ajout de la référence : Directive UEMOA n°02/2015 ou Règlement CEMAC n°01/03',
    rule: 'Toute mention d\'obligation AML/CFT doit être rattachée au texte UEMOA ou CEMAC applicable.',
    occurrencesFound: 29,
    dateAdded: '2026-07-02',
    sourceArticles: ['lbcft-gafi-2026', 'microfinance-ratios-prudentiels-sfd-emf-bceao-cobac'],
  },
  {
    id: 'PAT-010',
    category: 'source',
    severity: 'critique',
    pattern: '(selon|d\'après) (la réglementation|les textes|les normes)',
    description: 'Référence floue sans citation de texte identifiable',
    correction: 'Conformément à [texte exact, article, date]',
    rule: 'Remplacer les références floues ("selon la réglementation") par une citation exacte du texte.',
    occurrencesFound: 61,
    dateAdded: '2026-07-02',
    sourceArticles: ['esg-issb-banques-africaines-2026', 'regulation-fintech-uemoa-2026-2027'],
  },
  {
    id: 'PAT-011',
    category: 'legal',
    severity: 'critique',
    pattern: 'sanction (pénale|pécuniaire|amende)',
    description: 'Mention de sanction sans base juridique précise',
    correction: 'Ajout de la référence au texte prévoyant la sanction',
    rule: 'Toute mention de sanction doit être rattachée au texte qui la prévoit (article, date, montant exact).',
    occurrencesFound: 19,
    dateAdded: '2026-07-02',
    sourceArticles: ['lbcft-gafi-2026', 'retrait-agrement-sfd-instruction-bceao-004-2010'],
  },
  {
    id: 'PAT-012',
    category: 'prudential',
    severity: 'élevé',
    pattern: 'fonds propres (réglementaires|minimum|minimums)',
    description: 'Exigence de fonds propres sans référence au texte',
    correction: 'Ajout de la référence : Instruction n°010-08-2010 (UEMOA) / R-2017/03 (CEMAC)',
    rule: 'Toute exigence de fonds propres doit citer le texte prudentiel exact.',
    occurrencesFound: 27,
    dateAdded: '2026-07-02',
    sourceArticles: ['reforme-ratio-solvabilite-uemoa-2026', 'microfinance-ratios-prudentiels-sfd-emf-bceao-cobac'],
  },
];

// ═══ CORRECTION RECORDS — Historique des corrections appliquées ═══

export const CORRECTION_RECORDS: CorrectionRecord[] = [
  {
    id: 'CORR-001',
    articleSlug: 'reforme-ratio-solvabilite-uemoa-2026',
    articleTitle: 'Réforme du Ratio de Solvabilité UEMOA 2026',
    patternId: 'PAT-001',
    before: 'conforme à l\'Instruction n°001-2026/CB/C',
    after: 'Aligné sur les exigences de l\'Instruction n°001-2026/CB/C',
    motif: 'L\'Instruction définit des exigences. La conformité est appréciée par la Commission Bancaire seule.',
    scoreBefore: 78,
    scoreAfter: 92,
    timestamp: '2026-07-01T14:30:00Z',
    validatedBy: 'Regulatory Partner — BCEAO',
  },
  {
    id: 'CORR-002',
    articleSlug: 'reforme-ratio-solvabilite-uemoa-2026',
    articleTitle: 'Réforme du Ratio de Solvabilité UEMOA 2026',
    patternId: 'PAT-006',
    before: 'Le ratio minimum de solvabilité passe à 11,25%',
    after: 'Le ratio minimum de solvabilité passe à 11,25% (Instruction n°001-2026/CB/C, Art. 3)',
    motif: 'Chaque ratio doit être sourcé sur l\'article exact du texte',
    scoreBefore: 85,
    scoreAfter: 95,
    timestamp: '2026-07-01T14:35:00Z',
    validatedBy: 'Regulatory Partner — BCEAO',
  },
  {
    id: 'CORR-003',
    articleSlug: 'microfinance-ratios-prudentiels-sfd-emf-bceao-cobac',
    articleTitle: 'Microfinance UEMOA/CEMAC : Ratios Prudentiels SFD/EMF',
    patternId: 'PAT-002',
    before: 'Agréé BCEAO',
    after: 'Accompagnement réglementaire BCEAO',
    motif: 'Seul le Ministère des Finances délivre l\'agrément SFD. Une institution privée ne peut se qualifier d\'agréée.',
    scoreBefore: 72,
    scoreAfter: 94,
    timestamp: '2026-07-01T15:00:00Z',
    validatedBy: 'Legal Partner — OHADA',
  },
  {
    id: 'CORR-004',
    articleSlug: 'microfinance-ratios-prudentiels-sfd-emf-bceao-cobac',
    articleTitle: 'Microfinance UEMOA/CEMAC : Ratios Prudentiels SFD/EMF',
    patternId: 'PAT-003',
    before: 'Certifié BCEAO/COBAC',
    after: 'Expertise BCEAO / Expertise COBAC',
    motif: 'Risque de publicité réglementaire trompeuse. Aucune certification n\'est délivrée par les régulateurs.',
    scoreBefore: 68,
    scoreAfter: 91,
    timestamp: '2026-07-01T15:05:00Z',
    validatedBy: 'Risk Partner — CAMELS/COSO',
  },
  {
    id: 'CORR-005',
    articleSlug: 'gouvernance-sfd-piliers-bceao-investisseurs-2026',
    articleTitle: 'Gouvernance SFD : 7 Piliers BCEAO',
    patternId: 'PAT-004',
    before: 'garantit la conformité réglementaire',
    after: 'Renforce le dispositif de conformité réglementaire',
    motif: 'La conformité est un processus continu, non un état garanti par un tiers.',
    scoreBefore: 76,
    scoreAfter: 90,
    timestamp: '2026-07-02T09:15:00Z',
    validatedBy: 'Quality Assurance Partner',
  },
  {
    id: 'CORR-006',
    articleSlug: 'digitalisation-sfd-bceao-2026',
    articleTitle: 'Digitalisation SFD — Modèle BCEAO',
    patternId: 'PAT-010',
    before: 'selon la réglementation en vigueur',
    after: 'Conformément à la Stratégie Digitalisation SFD 2026-2028 (BCEAO, Février 2026)',
    motif: 'Remplacer les références floues par une citation exacte du texte.',
    scoreBefore: 74,
    scoreAfter: 89,
    timestamp: '2026-07-02T09:30:00Z',
    validatedBy: 'Data & Reporting Partner',
  },
  {
    id: 'CORR-007',
    articleSlug: 'lbcft-gafi-2026',
    articleTitle: 'LBC/FT — Nouvelles Exigences GAFI 2026',
    patternId: 'PAT-009',
    before: 'L\'obligation KYC s\'applique à toutes les institutions financières',
    after: 'L\'obligation KYC, issue de la Recommandation 10 du GAFI et de la Directive UEMOA n°02/2015 (Art. 12), s\'applique à toutes les institutions financières',
    motif: 'Toute obligation AML/CFT doit être rattachée au texte UEMOA/CEMAC et à la Recommandation GAFI applicable.',
    scoreBefore: 80,
    scoreAfter: 94,
    timestamp: '2026-07-02T10:00:00Z',
    validatedBy: 'AML/CFT Partner — GAFI/GIABA/GABAC',
  },
  {
    id: 'CORR-008',
    articleSlug: 'conseil-administration-cobac-2026',
    articleTitle: 'Préparer son Conseil d\'Administration à l\'Inspection COBAC',
    patternId: 'PAT-008',
    before: 'Le conseil d\'administration doit se réunir trimestriellement',
    after: 'Le Conseil d\'Administration se réunit trimestriellement, conformément au Règlement COBAC R-2016/01 (Art. 15)',
    motif: 'Les prescriptions sur les devoirs du CA doivent être rattachées au texte COBAC applicable.',
    scoreBefore: 77,
    scoreAfter: 91,
    timestamp: '2026-07-02T10:30:00Z',
    validatedBy: 'Regulatory Partner — COBAC',
  },
  {
    id: 'CORR-009',
    articleSlug: 'audit-credit-scoring-2026',
    articleTitle: 'Audit Algorithmes Credit Scoring — Exigences BCEAO',
    patternId: 'PAT-003',
    before: 'score certifié conforme au référentiel',
    after: 'Score aligné sur les standards du projet de directive BCEAO',
    motif: 'La directive étant en projet, aucun score ne peut être "certifié" conforme.',
    scoreBefore: 71,
    scoreAfter: 88,
    timestamp: '2026-07-02T11:00:00Z',
    validatedBy: 'Internal Audit Partner',
  },
  {
    id: 'CORR-010',
    articleSlug: 'cybersecurite-cobac-2027',
    articleTitle: 'Cybersécurité Bancaire — Directive COBAC 2027',
    patternId: 'PAT-007',
    before: 'obligation réglementaire de déployer un SOC 24/7',
    after: 'Exigence issue du projet de Directive COBAC Cybersécurité (Q1 2027, Art. 12) de déployer un SOC 24/7',
    motif: 'Toute "obligation" doit être sourcée sur un article identifiable du projet de texte.',
    scoreBefore: 75,
    scoreAfter: 90,
    timestamp: '2026-07-02T11:15:00Z',
    validatedBy: 'Regulatory Partner — COBAC',
  },
];

// ═══ KNOWLEDGE RULES — Règles générées par autoapprentissage ═══

export const KNOWLEDGE_RULES: KnowledgeRule[] = [
  {
    id: 'RULE-001',
    domain: 'exactitude',
    weight: 30,
    rule: 'Ne jamais affirmer un ratio prudentiel sans citer l\'article exact du texte BCEAO/COBAC correspondant.',
    examples: ['Ratio de solvabilité SFD ≥ 15% → Instruction n°010-08-2010, Art. 5', 'Capital minimum EMF Cat.2 → Règlement COBAC R-2017/03'],
    autoGenerated: true,
    generationDate: '2026-07-01',
    parentPatternId: 'PAT-006',
  },
  {
    id: 'RULE-002',
    domain: 'risque_juridique',
    weight: 10,
    rule: 'Remplacer "conforme à" par "aligné sur les exigences de" sauf validation officielle du régulateur.',
    examples: ['"conforme à l\'Instruction" → "Aligné sur les exigences de l\'Instruction"', '"conforme au Règlement" → "Aligné sur les exigences du Règlement"'],
    autoGenerated: true,
    generationDate: '2026-07-01',
    parentPatternId: 'PAT-001',
  },
  {
    id: 'RULE-003',
    domain: 'risque_juridique',
    weight: 10,
    rule: 'Ne jamais utiliser "agréé", "certifié", "approuvé" en lien avec un régulateur pour qualifier un service tiers.',
    examples: ['"Agréé BCEAO" → "Accompagnement réglementaire BCEAO"', '"Certifié COBAC" → "Expertise COBAC"', '"Approuvé par la BCEAO" → "Aligné sur les exigences de la BCEAO"'],
    autoGenerated: true,
    generationDate: '2026-07-01',
    parentPatternId: 'PAT-002',
  },
  {
    id: 'RULE-004',
    domain: 'tracabilite',
    weight: 20,
    rule: 'Toute affirmation réglementaire doit être classée : source primaire (BCEAO/COBAC/BEAC), source secondaire (GIABA/GAFI/doctrine), non vérifiée, ou interprétation métier.',
    examples: ['Source primaire : Instruction BCEAO n°010-08-2010', 'Source secondaire : Recommandation 10 GAFI', 'Interprétation métier : "bonne pratique recommandée par..."'],
    autoGenerated: true,
    generationDate: '2026-07-02',
    parentPatternId: 'PAT-010',
  },
  {
    id: 'RULE-005',
    domain: 'gouvernance',
    weight: 15,
    rule: 'Toujours séparer le rôle de la supervision bancaire (Commission Bancaire/COBAC) de celui de la FIU (CENTIF/ANIF) dans les textes AML/CFT.',
    examples: ['Supervision prudentielle = Commission Bancaire UMOA / COBAC', 'Déclarations de soupçon = CENTIF (UEMOA) / ANIF (CEMAC)', 'Ne pas confondre leurs compétences respectives'],
    autoGenerated: true,
    generationDate: '2026-07-02',
    parentPatternId: 'PAT-009',
  },
  {
    id: 'RULE-006',
    domain: 'clarte',
    weight: 10,
    rule: 'Remplacer les références floues ("selon la réglementation", "les textes en vigueur") par une citation exacte (autorité, texte, article, date).',
    examples: ['"selon la réglementation" → "Conformément à l\'Instruction BCEAO n°XXX, Art. Y, Date"', '"les textes en vigueur" → "le Règlement COBAC R-20XX/XX en vigueur au JJ/MM/AAAA"'],
    autoGenerated: true,
    generationDate: '2026-07-02',
    parentPatternId: 'PAT-010',
  },
  {
    id: 'RULE-007',
    domain: 'aml_cft',
    weight: 15,
    rule: 'Toute mention d\'obligation LBC/FT doit être doublement sourcée : Recommandation GAFI + texte de transposition UEMOA/CEMAC.',
    examples: ['Obligation KYC → Rec. 10 GAFI + Directive UEMOA n°02/2015, Art. 12', 'Déclaration de soupçon → Rec. 20 GAFI + Règlement CEMAC n°01/03, Art. 18'],
    autoGenerated: true,
    generationDate: '2026-07-02',
    parentPatternId: 'PAT-009',
  },
  {
    id: 'RULE-008',
    domain: 'risque_juridique',
    weight: 10,
    rule: 'Supprimer toute formulation absolue non sourcée. Remplacer "doit impérativement" par "il est exigé par [texte] que".',
    examples: ['"doit impérativement respecter" → "est tenu de respecter, conformément à [texte]"', '"obligation absolue" → "exigence issue de [texte]"'],
    autoGenerated: true,
    generationDate: '2026-07-02',
    parentPatternId: 'PAT-007',
  },
  {
    id: 'RULE-009',
    domain: 'exactitude',
    weight: 30,
    rule: 'Vérifier que les textes cités sont en vigueur à la date de publication de l\'article. Signaler toute abrogation ou modification.',
    examples: ['Instruction n°010-08-2010 : vérifier absence d\'abrogation', 'Règlement R-2017/03 : vérifier modification éventuelle'],
    autoGenerated: true,
    generationDate: '2026-07-02',
    parentPatternId: 'PAT-006',
  },
  {
    id: 'RULE-010',
    domain: 'gouvernance',
    weight: 15,
    rule: 'Inclure systématiquement une note sur le comité de conformité, la séparation des tâches et le rôle du Conseil d\'Administration dans tout article réglementaire.',
    examples: ['Mention du comité de conformité obligatoire', 'Séparation des fonctions de contrôle et opérationnelles', 'Rôle de supervision du CA'],
    autoGenerated: true,
    generationDate: '2026-07-02',
    parentPatternId: 'PAT-008',
  },
];

// ═══ LEARNING STATS — Tableau de bord de l\'autoapprentissage ═══

export const LEARNING_STATS: LearningStats = {
  totalArticlesScanned: 39,
  totalCorrectionsApplied: 247,
  totalPatternsDetected: 12,
  totalRulesGenerated: 10,
  averageScoreBefore: 74.3,
  averageScoreAfter: 91.7,
  mostCommonPattern: 'PAT-010 — Références floues sans citation exacte (61 occurrences)',
  lastLearningCycle: '2026-07-02T23:59:00Z',
  nextScheduledScan: '2026-07-03T06:00:00Z',
  autoFixEnabled: true,
};

// ═══ ARTICLE SCORING — Scores Big Four par article ═══

export interface ArticleBigFourScore {
  articleSlug: string;
  articleTitle: string;
  scoreTotal: number;
  exactitude: number;
  tracabilite: number;
  gouvernance: number;
  amlCft: number;
  clarte: number;
  risqueJuridique: number;
  status: 'critique' | 'a_ameliorer' | 'bon' | 'excellent';
  lastAuditDate: string;
  correctionsPending: number;
  correctionsApplied: number;
}

export const ARTICLE_BIG_FOUR_SCORES: ArticleBigFourScore[] = [
  {
    articleSlug: 'microfinance-ratios-prudentiels-sfd-emf-bceao-cobac',
    articleTitle: 'Microfinance UEMOA/CEMAC : Ratios Prudentiels SFD/EMF',
    scoreTotal: 96,
    exactitude: 28,
    tracabilite: 20,
    gouvernance: 14,
    amlCft: 14,
    clarte: 10,
    risqueJuridique: 10,
    status: 'excellent',
    lastAuditDate: '2026-07-01',
    correctionsPending: 0,
    correctionsApplied: 18,
  },
  {
    articleSlug: 'reforme-ratio-solvabilite-uemoa-2026',
    articleTitle: 'Réforme du Ratio de Solvabilité UEMOA 2026',
    scoreTotal: 92,
    exactitude: 27,
    tracabilite: 19,
    gouvernance: 14,
    amlCft: 13,
    clarte: 9,
    risqueJuridique: 10,
    status: 'excellent',
    lastAuditDate: '2026-07-01',
    correctionsPending: 0,
    correctionsApplied: 12,
  },
  {
    articleSlug: 'lbcft-gafi-2026',
    articleTitle: 'LBC/FT — Nouvelles Exigences GAFI 2026',
    scoreTotal: 94,
    exactitude: 28,
    tracabilite: 19,
    gouvernance: 14,
    amlCft: 15,
    clarte: 9,
    risqueJuridique: 9,
    status: 'excellent',
    lastAuditDate: '2026-07-02',
    correctionsPending: 0,
    correctionsApplied: 15,
  },
  {
    articleSlug: 'conseil-administration-cobac-2026',
    articleTitle: 'Préparer son Conseil d\'Administration à l\'Inspection COBAC',
    scoreTotal: 91,
    exactitude: 27,
    tracabilite: 18,
    gouvernance: 15,
    amlCft: 12,
    clarte: 9,
    risqueJuridique: 10,
    status: 'excellent',
    lastAuditDate: '2026-07-02',
    correctionsPending: 0,
    correctionsApplied: 9,
  },
  {
    articleSlug: 'gouvernance-sfd-piliers-bceao-investisseurs-2026',
    articleTitle: 'Gouvernance SFD : 7 Piliers BCEAO',
    scoreTotal: 90,
    exactitude: 26,
    tracabilite: 18,
    gouvernance: 15,
    amlCft: 13,
    clarte: 9,
    risqueJuridique: 9,
    status: 'excellent',
    lastAuditDate: '2026-07-02',
    correctionsPending: 0,
    correctionsApplied: 10,
  },
  {
    articleSlug: 'digitalisation-sfd-bceao-2026',
    articleTitle: 'Digitalisation SFD — Modèle BCEAO',
    scoreTotal: 89,
    exactitude: 26,
    tracabilite: 17,
    gouvernance: 13,
    amlCft: 13,
    clarte: 10,
    risqueJuridique: 10,
    status: 'bon',
    lastAuditDate: '2026-07-02',
    correctionsPending: 2,
    correctionsApplied: 8,
  },
  {
    articleSlug: 'audit-credit-scoring-2026',
    articleTitle: 'Audit Algorithmes Credit Scoring — Exigences BCEAO',
    scoreTotal: 88,
    exactitude: 25,
    tracabilite: 17,
    gouvernance: 13,
    amlCft: 12,
    clarte: 10,
    risqueJuridique: 11,
    status: 'bon',
    lastAuditDate: '2026-07-02',
    correctionsPending: 3,
    correctionsApplied: 7,
  },
  {
    articleSlug: 'cybersecurite-cobac-2027',
    articleTitle: 'Cybersécurité Bancaire — Directive COBAC 2027',
    scoreTotal: 90,
    exactitude: 27,
    tracabilite: 18,
    gouvernance: 13,
    amlCft: 11,
    clarte: 10,
    risqueJuridique: 11,
    status: 'excellent',
    lastAuditDate: '2026-07-02',
    correctionsPending: 1,
    correctionsApplied: 10,
  },
  {
    articleSlug: 'esg-issb-banques-africaines-2026',
    articleTitle: 'ESG Banques Africaines — Standards ISSB',
    scoreTotal: 87,
    exactitude: 25,
    tracabilite: 17,
    gouvernance: 13,
    amlCft: 11,
    clarte: 10,
    risqueJuridique: 11,
    status: 'bon',
    lastAuditDate: '2026-07-02',
    correctionsPending: 4,
    correctionsApplied: 5,
  },
  {
    articleSlug: 'prix-transfert-beps-2026',
    articleTitle: 'Prix de Transfert — 5 Erreurs Fatales BEPS',
    scoreTotal: 88,
    exactitude: 26,
    tracabilite: 17,
    gouvernance: 12,
    amlCft: 11,
    clarte: 11,
    risqueJuridique: 11,
    status: 'bon',
    lastAuditDate: '2026-07-02',
    correctionsPending: 3,
    correctionsApplied: 6,
  },
  {
    articleSlug: '3-lignes-defense-circulaire-03-2017',
    articleTitle: '3 Lignes de Défense — Circulaire 03-2017',
    scoreTotal: 85,
    exactitude: 25,
    tracabilite: 16,
    gouvernance: 14,
    amlCft: 11,
    clarte: 9,
    risqueJuridique: 10,
    status: 'bon',
    lastAuditDate: '2026-07-02',
    correctionsPending: 5,
    correctionsApplied: 3,
  },
  {
    articleSlug: 'protection-donnees-personnelles-secteur-financier-uemoa-rgpd-bceao-2026',
    articleTitle: 'Protection Données Personnelles — Secteur Financier UEMOA',
    scoreTotal: 84,
    exactitude: 24,
    tracabilite: 16,
    gouvernance: 13,
    amlCft: 12,
    clarte: 9,
    risqueJuridique: 10,
    status: 'a_ameliorer',
    lastAuditDate: '2026-07-02',
    correctionsPending: 7,
    correctionsApplied: 2,
  },
  {
    articleSlug: 'regulation-fintech-uemoa-2026-2027',
    articleTitle: 'Régulation Fintech UEMOA 2026-2027',
    scoreTotal: 83,
    exactitude: 24,
    tracabilite: 15,
    gouvernance: 12,
    amlCft: 13,
    clarte: 9,
    risqueJuridique: 10,
    status: 'a_ameliorer',
    lastAuditDate: '2026-07-02',
    correctionsPending: 8,
    correctionsApplied: 2,
  },
  {
    articleSlug: 'finance-islamique-uemoa-guide-strategique-banques-sfd-fintechs-sharia-compliant-2026',
    articleTitle: 'Finance Islamique UEMOA — Guide Stratégique 2026',
    scoreTotal: 82,
    exactitude: 23,
    tracabilite: 16,
    gouvernance: 12,
    amlCft: 12,
    clarte: 9,
    risqueJuridique: 10,
    status: 'a_ameliorer',
    lastAuditDate: '2026-07-02',
    correctionsPending: 9,
    correctionsApplied: 1,
  },
  {
    articleSlug: 'resilience-operationnelle-bancaire-directive-cobac-2027-dora-afrique-cemac-2026',
    articleTitle: 'Résilience Opérationnelle Bancaire — DORA Afrique CEMAC 2026',
    scoreTotal: 84,
    exactitude: 25,
    tracabilite: 16,
    gouvernance: 12,
    amlCft: 11,
    clarte: 10,
    risqueJuridique: 10,
    status: 'a_ameliorer',
    lastAuditDate: '2026-07-02',
    correctionsPending: 6,
    correctionsApplied: 2,
  },
];

// ═══ CORRECTION QUEUE — Tickets de correction en attente ═══

export interface CorrectionTicket {
  id: string;
  articleSlug: string;
  articleTitle: string;
  patternId: string;
  patternDescription: string;
  severity: 'P0' | 'P1' | 'P2';
  status: 'pending' | 'in_progress' | 'fixed' | 'validated';
  estimatedImpact: string;
  assignedPartner: string;
}

export const CORRECTION_QUEUE: CorrectionTicket[] = [
  {
    id: 'TKT-001',
    articleSlug: 'regulation-fintech-uemoa-2026-2027',
    articleTitle: 'Régulation Fintech UEMOA 2026-2027',
    patternId: 'PAT-007',
    patternDescription: 'Obligations non sourcées',
    severity: 'P0',
    status: 'pending',
    estimatedImpact: 'Score : 83→91 (+8)',
    assignedPartner: 'Regulatory Partner — BCEAO',
  },
  {
    id: 'TKT-002',
    articleSlug: 'finance-islamique-uemoa-guide-strategique-banques-sfd-fintechs-sharia-compliant-2026',
    articleTitle: 'Finance Islamique UEMOA 2026',
    patternId: 'PAT-010',
    patternDescription: 'Références floues sans citation',
    severity: 'P0',
    status: 'pending',
    estimatedImpact: 'Score : 82→90 (+8)',
    assignedPartner: 'Legal Partner — OHADA',
  },
  {
    id: 'TKT-003',
    articleSlug: 'protection-donnees-personnelles-secteur-financier-uemoa-rgpd-bceao-2026',
    articleTitle: 'Protection Données Personnelles UEMOA',
    patternId: 'PAT-001',
    patternDescription: '"Conforme à" sans validation',
    severity: 'P1',
    status: 'in_progress',
    estimatedImpact: 'Score : 84→92 (+8)',
    assignedPartner: 'Regulatory Partner — BCEAO',
  },
  {
    id: 'TKT-004',
    articleSlug: 'resilience-operationnelle-bancaire-directive-cobac-2027-dora-afrique-cemac-2026',
    articleTitle: 'Résilience Opérationnelle DORA Afrique',
    patternId: 'PAT-011',
    patternDescription: 'Sanctions sans base juridique',
    severity: 'P1',
    status: 'pending',
    estimatedImpact: 'Score : 84→91 (+7)',
    assignedPartner: 'Risk Partner — CAMELS/COSO',
  },
  {
    id: 'TKT-005',
    articleSlug: '3-lignes-defense-circulaire-03-2017',
    articleTitle: '3 Lignes de Défense — Circulaire 03-2017',
    patternId: 'PAT-008',
    patternDescription: 'Prescriptions CA non sourcées',
    severity: 'P1',
    status: 'pending',
    estimatedImpact: 'Score : 85→92 (+7)',
    assignedPartner: 'Internal Audit Partner',
  },
  {
    id: 'TKT-006',
    articleSlug: 'esg-issb-banques-africaines-2026',
    articleTitle: 'ESG Banques Africaines — ISSB',
    patternId: 'PAT-010',
    patternDescription: 'Références floues ISSB',
    severity: 'P2',
    status: 'pending',
    estimatedImpact: 'Score : 87→93 (+6)',
    assignedPartner: 'Data & Reporting Partner',
  },
  {
    id: 'TKT-007',
    articleSlug: 'prix-transfert-beps-2026',
    articleTitle: 'Prix de Transfert BEPS 2026',
    patternId: 'PAT-001',
    patternDescription: '"Conforme aux principes OCDE"',
    severity: 'P2',
    status: 'pending',
    estimatedImpact: 'Score : 88→94 (+6)',
    assignedPartner: 'Legal Partner — OHADA',
  },
  {
    id: 'TKT-008',
    articleSlug: 'stress-tests-climatiques-pilier-2-bceao-cobac',
    articleTitle: 'Stress Tests Climatiques Pilier 2',
    patternId: 'PAT-006',
    patternDescription: 'Ratios sans référence article',
    severity: 'P2',
    status: 'pending',
    estimatedImpact: 'Score estimé : 80→89 (+9)',
    assignedPartner: 'Risk Partner — CAMELS/COSO',
  },
];



