import type { DiagnosticAxisConfig } from '';

const PRIMARY = '#7c3aed';

export const DIAG_ORG_AXES: DiagnosticAxisConfig[] = [
  {
    id: 'gouvernance', titleFr: 'Gouvernance', titleEn: 'Governance',
    descriptionFr: 'Structure de gouvernance, Conseil, comités, séparation des pouvoirs, transparence',
    descriptionEn: 'Governance structure, Board, committees, separation of powers, transparency',
    icon: 'ri-building-2-line', color: '#7c3aed', weight: 25,
    questions: [
      { id: 'do-g-1', questionFr: "L'organisation dispose-t-elle d'un Conseil d'Administration fonctionnel avec des administrateurs indépendants ?", questionEn: 'Does the organization have a functional Board of Directors with independent directors?', options: [{ value: 100, labelFr: 'CA constitué avec majorité d\'administrateurs indépendants, comités spécialisés, réunions trimestrielles documentées', labelEn: 'Board with majority independent directors, specialized committees, documented quarterly meetings' }, { value: 60, labelFr: 'CA constitué mais sans administrateurs indépendants, comités partiels', labelEn: 'Board constituted but without independent directors, partial committees' }, { value: 25, labelFr: 'CA formel mais non opérationnel, réunions irrégulières', labelEn: 'Formal but non-operational Board, irregular meetings' }, { value: 0, labelFr: 'Pas de Conseil d\'Administration structuré', labelEn: 'No structured Board of Directors' }] },
      { id: 'do-g-2', questionFr: 'Les rôles et responsabilités des dirigeants sont-ils clairement définis avec une séparation effective des pouvoirs ?', questionEn: 'Are executive roles and responsibilities clearly defined with effective separation of powers?', options: [{ value: 100, labelFr: 'Séparation CEO/Chairman effective, délégations de pouvoir documentées, fiches de poste à jour pour tous les dirigeants', labelEn: 'Effective CEO/Chairman separation, documented power delegations, updated job descriptions for all executives' }, { value: 60, labelFr: 'Rôles définis mais cumul de fonctions, délégations partielles', labelEn: 'Roles defined but function accumulation, partial delegations' }, { value: 25, labelFr: 'Définition floue des responsabilités, concentration excessive des pouvoirs', labelEn: 'Unclear responsibility definition, excessive power concentration' }, { value: 0, labelFr: 'Aucune définition des rôles, confusion totale des responsabilités', labelEn: 'No role definition, total responsibility confusion' }] },
      { id: 'do-g-3', questionFr: 'Un processus de planification stratégique formalisé avec objectifs pluriannuels est-il en place ?', questionEn: 'Is a formalized strategic planning process with multi-year objectives in place?', options: [{ value: 100, labelFr: 'Plan stratégique 3-5 ans documenté, revu annuellement, décliné en plans opérationnels, KPI suivis', labelEn: '3-5 year documented strategic plan, reviewed annually, cascaded to operational plans, KPIs tracked' }, { value: 60, labelFr: 'Plan stratégique défini mais non décliné opérationnellement, revue irrégulière', labelEn: 'Strategic plan defined but not operationally cascaded, irregular review' }, { value: 25, labelFr: 'Vision stratégique informelle, pas de document formalisé', labelEn: 'Informal strategic vision, no formalized document' }, { value: 0, labelFr: 'Pas de planification stratégique, navigation à vue', labelEn: 'No strategic planning, ad hoc navigation' }] },
      { id: 'do-g-4', questionFr: "Les processus de prise de décision sont-ils documentés avec des seuils d'approbation clairs ?", questionEn: 'Are decision-making processes documented with clear approval thresholds?', options: [{ value: 100, labelFr: 'Matrice des délégations complète, circuit de validation documenté, système de gestion électronique des approbations', labelEn: 'Complete delegation matrix, documented validation circuit, electronic approval management system' }, { value: 60, labelFr: 'Processus définis mais application inconstante, quelques seuils documentés', labelEn: 'Processes defined but inconsistent application, some documented thresholds' }, { value: 25, labelFr: 'Décisions informelles, pas de seuils formalisés', labelEn: 'Informal decisions, no formalized thresholds' }, { value: 0, labelFr: 'Aucun processus décisionnel documenté, décisions arbitraires', labelEn: 'No documented decision process, arbitrary decisions' }] },
    ],
  },
  {
    id: 'structure-rh', titleFr: 'Structure & RH', titleEn: 'Structure & HR',
    descriptionFr: 'Organigramme, gestion des talents, rémunération, formation, culture',
    descriptionEn: 'Organization chart, talent management, compensation, training, culture',
    icon: 'ri-team-line', color: '#0ea5e9', weight: 25,
    questions: [
      { id: 'do-sr-1', questionFr: "L'organigramme est-il documenté, à jour et reflète-t-il la réalité opérationnelle de l'organisation ?", questionEn: 'Is the organization chart documented, up-to-date and reflecting the operational reality?', options: [{ value: 100, labelFr: 'Organigramme complet avec rattachements, comités, et instances de coordination, mis à jour semestriellement', labelEn: 'Complete org chart with reporting lines, committees, coordination bodies, updated semi-annually' }, { value: 60, labelFr: 'Organigramme existant mais obsolète ou ne reflétant pas les relations informelles', labelEn: 'Org chart exists but outdated or not reflecting informal relationships' }, { value: 25, labelFr: 'Organigramme partiel ou non communiqué aux équipes', labelEn: 'Partial org chart or not communicated to teams' }, { value: 0, labelFr: "Pas d'organigramme, structure organisationnelle floue", labelEn: 'No org chart, unclear organizational structure' }] },
      { id: 'do-sr-2', questionFr: "Disposez-vous d'un système de gestion des talents (recrutement, évaluation, développement, rétention) structuré ?", questionEn: 'Do you have a structured talent management system (recruitment, evaluation, development, retention)?', options: [{ value: 100, labelFr: 'Processus RH complets : recrutement standardisé, entretiens annuels, plans de développement, plans de succession, politique de rétention', labelEn: 'Complete HR processes: standardized recruitment, annual reviews, development plans, succession plans, retention policy' }, { value: 60, labelFr: 'Processus RH existants mais non formalisés, évaluation annuelle basique', labelEn: 'HR processes exist but not formalized, basic annual evaluation' }, { value: 25, labelFr: 'Gestion RH minimaliste, pas d\'évaluation structurée, recrutement ad hoc', labelEn: 'Minimalist HR management, no structured evaluation, ad hoc recruitment' }, { value: 0, labelFr: 'Aucune gestion des ressources humaines formalisée', labelEn: 'No formalized human resources management' }] },
      { id: 'do-sr-3', questionFr: 'La politique de rémunération est-elle compétitive, équitable et alignée sur le marché ?', questionEn: 'Is the compensation policy competitive, equitable and market-aligned?', options: [{ value: 100, labelFr: 'Politique de rémunération documentée, benchmarkée secteur, incluant part variable, avantages, et intéressement', labelEn: 'Documented compensation policy, sector-benchmarked, including variable, benefits, and profit-sharing' }, { value: 60, labelFr: 'Rémunération compétitive mais sans politique formalisée ni benchmarking régulier', labelEn: 'Competitive compensation but no formalized policy or regular benchmarking' }, { value: 25, labelFr: 'Rémunération en dessous du marché, pas de politique d\'augmentation structurée', labelEn: 'Below-market compensation, no structured increase policy' }, { value: 0, labelFr: 'Rémunération arbitraire, inéquitable, non compétitive — turnover élevé', labelEn: 'Arbitrary, inequitable, non-competitive compensation — high turnover' }] },
    ],
  },
  {
    id: 'processus', titleFr: 'Processus & Qualité', titleEn: 'Processes & Quality',
    descriptionFr: 'Cartographie processus, procédures, gestion de la qualité, amélioration continue',
    descriptionEn: 'Process mapping, procedures, quality management, continuous improvement',
    icon: 'ri-flow-chart', color: '#059669', weight: 25,
    questions: [
      { id: 'do-pq-1', questionFr: "Les processus clés de l'organisation sont-ils cartographiés, documentés et optimisés régulièrement ?", questionEn: 'Are the organization\'s key processes mapped, documented and regularly optimized?', options: [{ value: 100, labelFr: 'Cartographie complète des processus, procédures documentées, revue annuelle, indicateurs de performance, amélioration continue Lean/Six Sigma', labelEn: 'Complete process mapping, documented procedures, annual review, performance indicators, Lean/Six Sigma continuous improvement' }, { value: 60, labelFr: 'Processus principaux documentés mais cartographie incomplète, optimisation ponctuelle', labelEn: 'Main processes documented but incomplete mapping, ad hoc optimization' }, { value: 25, labelFr: 'Quelques procédures écrites, pas de cartographie globale', labelEn: 'Some written procedures, no global mapping' }, { value: 0, labelFr: 'Aucune documentation des processus, fonctionnement artisanal', labelEn: 'No process documentation, artisanal operation' }] },
      { id: 'do-pq-2', questionFr: 'Un système de gestion de la qualité est-il en place avec des indicateurs de performance suivis ?', questionEn: 'Is a quality management system in place with tracked performance indicators?', options: [{ value: 100, labelFr: 'Système qualité certifié (ISO 9001), tableau de bord qualité, audits internes réguliers, actions correctives systématiques', labelEn: 'Certified quality system (ISO 9001), quality dashboard, regular internal audits, systematic corrective actions' }, { value: 60, labelFr: 'Démarche qualité formalisée mais non certifiée, quelques KPI qualité suivis', labelEn: 'Formalized quality approach but not certified, some quality KPIs tracked' }, { value: 25, labelFr: 'Contrôle qualité informel, pas d\'indicateurs structurés', labelEn: 'Informal quality control, no structured indicators' }, { value: 0, labelFr: 'Aucune gestion de la qualité, pas de mesure de la performance', labelEn: 'No quality management, no performance measurement' }] },
      { id: 'do-pq-3', questionFr: "Les systèmes d'information supportent-ils efficacement les processus opérationnels et la prise de décision ?", questionEn: 'Do information systems effectively support operational processes and decision-making?', options: [{ value: 100, labelFr: 'ERP intégré, BI et reporting automatisés, données centralisées et fiables, accessibles en temps réel pour la décision', labelEn: 'Integrated ERP, automated BI and reporting, centralized and reliable data, accessible in real-time for decision-making' }, { value: 60, labelFr: 'ERP en place mais modules partiels, reporting semi-automatisé, quelques silos de données', labelEn: 'ERP in place but partial modules, semi-automated reporting, some data silos' }, { value: 25, labelFr: 'Systèmes disparates, pas d\'ERP intégré, reporting manuel sous Excel', labelEn: 'Disparate systems, no integrated ERP, manual Excel reporting' }, { value: 0, labelFr: 'Pas de système d\'information structuré, données éparpillées et non fiables', labelEn: 'No structured information system, scattered and unreliable data' }] },
    ],
  },
  {
    id: 'culture-performance', titleFr: 'Culture & Performance', titleEn: 'Culture & Performance',
    descriptionFr: 'Culture d\'entreprise, gestion de la performance, communication interne, conduite du changement',
    descriptionEn: 'Corporate culture, performance management, internal communication, change management',
    icon: 'ri-lightbulb-flash-line', color: '#d97706', weight: 25,
    questions: [
      { id: 'do-cp-1', questionFr: "La culture d'entreprise est-elle définie (mission, vision, valeurs) et incarnée au quotidien ?", questionEn: 'Is the corporate culture defined (mission, vision, values) and embodied daily?', options: [{ value: 100, labelFr: 'Mission/Vision/Valeurs formalisées, communiquées à tous, incarnées par le leadership, évaluées dans les entretiens annuels', labelEn: 'Mission/Vision/Values formalized, communicated to all, embodied by leadership, evaluated in annual reviews' }, { value: 60, labelFr: 'Éléments de culture définis mais communication limitée, incarnation partielle par le management', labelEn: 'Culture elements defined but limited communication, partial management embodiment' }, { value: 25, labelFr: 'Culture implicite, pas de formalisation, valeurs non communiquées', labelEn: 'Implicit culture, no formalization, non-communicated values' }, { value: 0, labelFr: 'Pas de culture d\'entreprise identifiable, environnement toxique ou désengagé', labelEn: 'No identifiable corporate culture, toxic or disengaged environment' }] },
      { id: 'do-cp-2', questionFr: "Un système de gestion de la performance individuelle et collective est-il déployé avec des objectifs mesurables ?", questionEn: 'Is an individual and collective performance management system deployed with measurable objectives?', options: [{ value: 100, labelFr: 'Système de gestion de la performance complet : objectifs SMART, évaluations 360°, feedback continu, plans de développement liés aux résultats', labelEn: 'Complete performance management system: SMART objectives, 360° evaluations, continuous feedback, results-linked development plans' }, { value: 60, labelFr: 'Entretiens annuels en place mais objectifs non systématiquement mesurables, pas de 360°', labelEn: 'Annual reviews in place but objectives not systematically measurable, no 360°' }, { value: 25, labelFr: 'Évaluation informelle, pas d\'objectifs formalisés, feedback irrégulier', labelEn: 'Informal evaluation, no formalized objectives, irregular feedback' }, { value: 0, labelFr: 'Aucune gestion de la performance, ni individuelle ni collective', labelEn: 'No performance management, individual or collective' }] },
    ],
  },
];

export function getDiagOrgScoreColor(s: number): string { if (s >= 80) return '#059669'; if (s >= 60) return '#0ea5e9'; if (s >= 40) return '#d97706'; return '#dc2626'; }
export function getDiagOrgScoreLabel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Organisation d\'Excellence':'Excellent Organization'; if (s>=60) return f?'Organisation Performante':'Performing Organization'; if (s>=40) return f?'Organisation en Structuration':'Structuring Organization'; return f?'Organisation Fragile':'Fragile Organization'; }
export function getDiagOrgLevel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Niveau 4 — Excellence':'Level 4 — Excellence'; if (s>=60) return f?'Niveau 3 — Performance':'Level 3 — Performance'; if (s>=40) return f?'Niveau 2 — Structure':'Level 2 — Structure'; return f?'Niveau 1 — Fondation':'Level 1 — Foundation'; }
export function getDiagOrgReadiness(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Votre organisation affiche un niveau de maturité excellent. Continuez à innover dans vos pratiques organisationnelles pour maintenir cette avance.':'Your organization displays excellent maturity. Continue innovating in organizational practices to maintain this lead.'; if (s>=60) return f?'Votre organisation est bien structurée avec des fondamentaux solides. Quelques axes d\'amélioration ciblés vous mèneront à l\'excellence organisationnelle.':'Your organization is well structured with solid fundamentals. A few targeted improvements will lead you to organizational excellence.'; if (s>=40) return f?'Votre organisation est en phase de structuration. Des efforts sont nécessaires pour formaliser la gouvernance, les processus et la gestion RH.':'Your organization is in structuring phase. Efforts are needed to formalize governance, processes and HR management.'; return f?'Votre organisation nécessite une refonte structurelle profonde. Les fondamentaux — gouvernance, processus, RH — doivent être construits ou reconstruits.':'Your organization requires deep structural overhaul. The fundamentals — governance, processes, HR — must be built or rebuilt.'; }

export function getDiagOrgRisks(perAxis: Record<string,number>, gs: number, lang: string): string[] {
  const f=!lang.startsWith('en'); const r:string[]=[];
  if ((perAxis['gouvernance']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Gouvernance défaillante : pas de CA structuré, concentration des pouvoirs, absence de planification stratégique — risque de décisions non contrôlées':'HIGH RISK — Failing governance: no structured Board, power concentration, no strategic planning — uncontrolled decision risk');
  if ((perAxis['structure-rh']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Structure RH défaillante : organigramme flou, absence de gestion des talents, rémunération non compétitive — risque de perte des talents clés':'HIGH RISK — Failing HR structure: unclear org chart, no talent management, non-competitive compensation — key talent loss risk');
  if ((perAxis['processus']??0)<50) r.push(f?'RISQUE MAJEUR — Processus non maîtrisés : pas de cartographie, pas de système qualité, SI défaillants — inefficience opérationnelle et risques de non-conformité':'MAJOR RISK — Uncontrolled processes: no mapping, no quality system, failing IS — operational inefficiency and non-compliance risks');
  if ((perAxis['culture-performance']??0)<50) r.push(f?'RISQUE MAJEUR — Absence de culture de performance : pas de valeurs formalisées, pas d\'évaluation — désengagement des équipes et contre-performance':'MAJOR RISK — No performance culture: no formalized values, no evaluation — team disengagement and underperformance');
  return r;
}

export function getDiagOrgRecommendations(perAxis: Record<string,number>, gs: number, lang: string): {title:string;axis?:string;items:string[]}[] {
  const f=!lang.startsWith('en'); const recs:{title:string;axis?:string;items:string[]}[]=[];
  if ((perAxis['gouvernance']??0)<60) recs.push({title:f?'Renforcer la Gouvernance':'Strengthen Governance',axis:'gouvernance',items:f?['Constituer un CA avec administrateurs indépendants et comités spécialisés','Formaliser un plan stratégique 3-5 ans décliné en plans opérationnels','Mettre en place une matrice des délégations avec seuils d\'approbation']:['Constitute a Board with independent directors and specialized committees','Formalize a 3-5 year strategic plan cascaded to operational plans','Implement a delegation matrix with approval thresholds']});
  if ((perAxis['structure-rh']??0)<60) recs.push({title:f?'Structurer les RH':'Structure HR',axis:'structure-rh',items:f?['Documenter un organigramme complet et le communiquer à toute l\'organisation','Déployer un système de gestion des talents : recrutement, évaluation, développement','Benchmarker la politique de rémunération et l\'aligner sur le marché']:['Document a complete org chart and communicate it organization-wide','Deploy a talent management system: recruitment, evaluation, development','Benchmark compensation policy and align it with the market']});
  if ((perAxis['processus']??0)<60) recs.push({title:f?'Optimiser les Processus':'Optimize Processes',axis:'processus',items:f?['Cartographier les processus clés et rédiger les procédures associées','Engager une démarche de certification qualité (ISO 9001)','Évaluer et moderniser les systèmes d\'information pour un ERP intégré']:['Map key processes and write associated procedures','Engage a quality certification approach (ISO 9001)','Evaluate and modernize information systems for an integrated ERP']});
  if ((perAxis['culture-performance']??0)<60) recs.push({title:f?'Développer la Culture de Performance':'Develop Performance Culture',axis:'culture-performance',items:f?['Formaliser et communiquer la mission, la vision et les valeurs','Déployer un système d\'évaluation de la performance avec objectifs SMART','Mettre en place un programme de reconnaissance et de feedback continu']:['Formalize and communicate mission, vision and values','Deploy a performance evaluation system with SMART objectives','Implement a recognition and continuous feedback program']});
  if (recs.length===0) recs.push({title:f?'Maintenir l\'Excellence Organisationnelle':'Maintain Organizational Excellence',items:f?['Continuer à innover dans les pratiques de gouvernance','Renforcer la culture d\'amélioration continue','Partager les bonnes pratiques organisationnelles']:['Continue innovating governance practices','Strengthen continuous improvement culture','Share organizational best practices']});
  return recs;
}


export const getDiagOrgScoreColor = { id: 1, label: "Stub data" }; // stub
export const getDiagOrgScoreLabel = { id: 1, label: "Stub data" }; // stub
export const getDiagOrgLevel = { id: 1, label: "Stub data" }; // stub
export const getDiagOrgReadiness = { id: 1, label: "Stub data" }; // stub
export const getDiagOrgRisks = { id: 1, label: "Stub data" }; // stub
export const getDiagOrgRecommendations = { id: 1, label: "Stub data" }; // stub



