import { Paragraph, Table } from 'docx';
import {
  sp, h1, h2, h3, h4, body, bullet, tbl, pb, infoBox, successBox, alertBox,
} from '@/utils/businessPlanCGI/helpers';

export function porterAnalysis(): (Paragraph | Table)[] {
  return [
    h1('SECTION VIII — ANALYSE PORTER ET DIAGNOSTIC STRATEGIQUE'),
    sp(),

    h2('VIII.1 Introduction — Cadre analytique Porter applique au secteur des granulats'),
    body('L\'analyse des cinq forces concurrentielles de Michael Porter (Competitive Strategy, 1980), adaptee au contexte de l\'industrie extractive en Afrique de l\'Ouest, permet d\'evaluer l\'intensite concurrentielle du marche des granulats et d\'identifier les leviers de differenciation de CGI SA. Les deux forces complementaires (impact de la reglementation et impact ESG) sont integrees compte tenu de leur importance dans le contexte institutionnel africain.'),
    sp(),

    h2('VIII.2 Force 1 — Intensite concurrentielle (Rivalite entre acteurs existants)'),
    sp(),
    body('L\'intensite concurrentielle dans le marche des granulats au Togo est moderee (echelle 1-5 : 3/5), avec des caracteristiques specifiques :'),
    sp(),
    bullet('Concentration du marche : Le marche est domine par Granutogo (55-60 % de parts) avec trois sites dans le sud. Les 40-60 carrieres artisanales se partagent 25-30 % du marche. Le reste (15-20 %) est absorbe par les importations ponctuelles et les petits producteurs semi-industriels.'),
    sp(),
    bullet('Croissance du marche : A +4,0 %/an, la croissance du marche togolais est superieure a la croissance de la capacite installee (+2,5 %/an), ce qui reduit la rivalite directe pour les volumes. Le deficit structurel de 700 000 T/an limite la guerre des prix.'),
    sp(),
    bullet('Differentiation produit : Faible sur le segment standard (0/31,5), mais croissante sur les segments certifies et haute resistance. Granutogo ne dispose pas de certification LNBTP complete ni de granulats > 120 MPa, creant une niche de differentiation pour CGI SA.'),
    sp(),
    bullet('Couts de sortie : Eleves. Les investissements en equipements de concassage (CAPEX 2 000-5 000 M FCFA) et les permis miniers sont des actifs specifiques dont la cession est difficile. Les acteurs existants sont donc incites a rester sur le marche plutot que de sortir.'),
    sp(),
    bullet('Surcapacite : Non. La demande (3,2 M T/an) excede l\'offre nationale (2,5 M T/an). Aucune surcapacite structurelle n\'existe au Togo.'),
    sp(),
    infoBox('Evaluation Porter — Intensite concurrentielle : MODEREE (3/5). La domination de Granutogo et le deficit structurel limitent la rivalite aggressive. Cependant, l\'entree de CGI SA pourrait declencher une reaction defensive (guerre des prix sur le segment 0/31,5 — probabilite 25 %).'),

    h2('VIII.3 Force 2 — Pouvoir de negociation des fournisseurs'),
    sp(),
    body('Le pouvoir de negociation des fournisseurs est faible a modere (2/5), en raison de la diversification des sources d\'approvisionnement :'),
    sp(),
    bullet('Fournisseurs d\'equipements : METSO (Finlande) est le fournisseur principal de concasseurs et cribles. Bien que METSO soit un leader mondial, CGI SA a deja negocie et acquit ses equipements (Nordberg C120 + HP300). Les pieces de rechange sont disponibles via des distributeurs regionaux (Cote d\'Ivoire, Ghana). Le pouvoir de METSO est limite apres la livraison initiale.'),
    sp(),
    bullet('Fournisseurs d\'energie : La CEET (Compagnie Energie Electrique du Togo) est le fournisseur monopolistique d\'electricite. Cependant, CGI SA a prevu une centrale solaire 3-4 MWc (reduction de 35 % de la dependance au reseau) et un groupe electrogene de secours. La diversification energetique reduit le pouvoir de la CEET.'),
    sp(),
    bullet('Fournisseurs de carburant : Le marche des hydrocarbures au Togo est liberalise avec plusieurs distributeurs (Total, Shell, Oryx). CGI SA peut arbitrer entre fournisseurs. Le prix du gasoil est indexe sur le cours international mais les volumes sont negociables.'),
    sp(),
    bullet('Fournisseurs de services (maintenance, expertise) : La maintenance METSO est assuree par des techniciens formes localement, avec un soutien a distance depuis la Cote d\'Ivoire. Les bureaux d\'etudes (BECE, SETSTO) sont nombreux et en concurrence.'),
    sp(),
    infoBox('Evaluation Porter — Pouvoir fournisseurs : FAIBLE a MODERE (2/5). La diversification des sources et la concurrence entre fournisseurs limitent leur pouvoir de negociation. Le principal risque reside dans la dependance a la CEET, attenuee par la centrale solaire.'),

    h2('VIII.4 Force 3 — Pouvoir de negociation des clients'),
    sp(),
    body('Le pouvoir de negociation des clients est modere (3/5), avec des variations significatives selon les segments :'),
    sp(),
    bullet('Grands comptes BTP (CIMCO, EBOMAF, grands promoteurs) : Pouvoir eleve (4/5). Ces clients achetent en volume (> 50 000 T/an), disposent de plusieurs fournisseurs potentiels, et negocient des contrats cadres avec des prix fixes sur 12-24 mois. Cependant, leur dependance a la qualite LNBTP et a la regularite des livraisons limite leur pouvoir de substitution.'),
    sp(),
    bullet('Marches publics (ARMP) : Pouvoir modere (3/5). Les marches publics sont attribues par appel d\'offres, avec des criteres de selection ponderes (prix 60 %, qualite 25 %, delais 15 %). La certification LNBTP est un critere d\'eligibilite. CGI SA, une fois certifiee, est en position competitive.'),
    sp(),
    bullet('Promoteurs immobiliers et PME BTP : Pouvoir faible (2/5). Fragmentation elevee, volumes faibles par client (< 5 000 T/an), faible capacite de negociation. Ces clients sont sensibles au prix mais dependent de la disponibilite et de la qualite.'),
    sp(),
    bullet('Export (Benin, Ghana) : Pouvoir modere (3/5). Les clients beninois ont un deficit structurel et peu d\'alternatives locales. Cependant, ils peuvent importer depuis le Ghana ou le Nigeria. L\'avantage logistique de CGI SA (176 km de Cotonou) limite le pouvoir de substitution.'),
    sp(),
    infoBox('Evaluation Porter — Pouvoir clients : MODERE (3/5). La fragmentation du marche et la dependance a la qualite certifiee limitent le pouvoir global des clients. Les grands comptes detiennent un pouvoir localise sur les volumes mais sont contraints par la certification LNBTP.'),

    h2('VIII.5 Force 4 — Menace des nouveaux entrants'),
    sp(),
    body('La menace des nouveaux entrants est faible a moderee (2/5), en raison des barrieres a l\'entree significatives :'),
    sp(),
    bullet('Barriere financiere : Le CAPEX d\'une unite industrielle de 200-250 TPH est estime a 3 200-5 000 M FCFA (equipements, infrastructure, laboratoire). Ce montant, associe au BFR de demarrage (800-1 200 M FCFA), constitue une barriere elevee pour les investisseurs locaux.'),
    sp(),
    bullet('Barriere reglementaire : L\'obtention d\'un permis d\'exploitation DGMG prend 18-24 mois et coute 45-85 M FCFA. La certification LNBTP exige un investissement de 85 M FCFA en equipements de laboratoire. Ces delais et couts decouragent les entrants opportunistes.'),
    sp(),
    bullet('Barriere technologique : La technologie METSO (fiabilite 95 %) necessite une expertise technique et une formation des operateurs. Les equipements chinois generiques, bien que moins chers, offrent une fiabilite de 75-80 % et une qualite inferieure, ce qui limite leur competitivite sur le marche institutionnel.'),
    sp(),
    bullet('Barriere logistique : La position geographique de Siyime (nord du Togo) est strategique mais exige un investissement en infrastructure routiere interne (25 M FCFA) et des contrats de transport.'),
    sp(),
    bullet('Barriere relationnelle : Les relations avec les bureaux d\'etudes, les maitres d\'ouvrage publics (ARMP), et les grands comptes BTP necessitent du temps et de la credibilite. CGI SA, avec son contrat CIMCO et ses relations DGMG/LNBTP, a deja franchi cette etape.'),
    sp(),
    infoBox('Evaluation Porter — Menace entrants : FAIBLE a MODERE (2/5). Les barrieres financieres, reglementaires, technologiques et relationnelles protegent CGI SA contre une entree massive de nouveaux concurrents. Une entree limitee de petites carrieres artisanales reste possible mais non menacante sur le segment industriel.'),

    h2('VIII.6 Force 5 — Menace des produits de substitution'),
    sp(),
    body('La menace des produits de substitution est faible (1,5/5), en raison de l\'absence de materiaux de construction viables pour remplacer les granulats dans les infrastructures lourdes :'),
    sp(),
    bullet('Substituts potentiels : Les granulats concasses n\'ont pas de substitut direct pour les couches de base routiere, le beton structurel, et les ouvrages d\'art. Le sable de riviere (substitut partiel pour les mortiers) est en voie d\'epuisement au Togo et interdit dans plusieurs pays pour des raisons environnementales.'),
    sp(),
    bullet('Materiaux alternatifs : Le verre recycle, les dechets de construction, et les scories metallurgiques peuvent etre utilises comme adjuvants mais ne remplacent pas les granulats pour les structures porteuses. Leur part de marche est negligeable (< 1 %) en Afrique de l\'Ouest.'),
    sp(),
    bullet('Beton recycle : Le beton de demolition recycle est utilise pour le remblaiement bas de gamme mais ne satisfait pas aux normes NF EN 12620 pour le beton structurel. Source : LNBTP — « Guide des materiaux alternatifs au Togo, 2022 ».'),
    sp(),
    infoBox('Evaluation Porter — Menace substitution : FAIBLE (1,5/5). Les granulats concasses sont irremplacables pour les applications structurelles BTP. L\'absence de substituts viables a grande echelle protege le marche contre une erosion par substitution.'),

    h2('VIII.7 Forces complementaires — Impact de la reglementation et de l\'ESG'),
    sp(),
    body('Dans le contexte africain, deux forces supplementaires doivent etre integrees a l\'analyse Porter :'),
    sp(),
    bullet('Impact de la reglementation (Force 6) : MODERE a ELEVE (3,5/5). La certification LNBTP, les permis DGMG, la fiscalite miniere, et les normes environnementales creent des barrieres a l\'entree mais augmentent les couts de conformite. Les acteurs non conformes (carrieres artisanales) sont progressivement exclus du marche institutionnel. CGI SA, entierement conforme, tire un avantage competitif de cette force.'),
    sp(),
    bullet('Impact ESG (Force 7) : MODERE (3/5). Les bailleurs internationaux, les grands comptes BTP, et les marches publics integrent de plus en plus des criteres ESG. Les acteurs non certifies ESG perdent l\'acces aux financements et aux contrats internationaux. CGI SA, avec son PGES IFC et sa centrale solaire, est positionne favorablement.'),
    sp(),

    tbl(
      ['Force Porter', 'Intensite (1-5)', 'Impact sur CGI SA', 'Strategie recommandee'],
      [
        ['1. Rivalite acteurs', '3/5 — Moderee', 'Menace guerre des prix (25%)', 'Differenciation specialite > 120 MPa'],
        ['2. Pouvoir fournisseurs', '2/5 — Faible/Modere', 'Dependance CEET attenuee', 'Centrale solaire + groupes secours'],
        ['3. Pouvoir clients', '3/5 — Modere', 'Pression prix grands comptes', 'Contrats cadres long terme + certification'],
        ['4. Menace entrants', '2/5 — Faible/Modere', 'Fenetre 2-3 ans avant reaction', 'Acceleration Programme 1 et 2'],
        ['5. Menace substitution', '1,5/5 — Faible', 'Aucun substitut viable', 'Maintien positionnement granulats premium'],
        ['6. Impact reglementation', '3,5/5 — Modere/Eleve', 'Opportunite pour conformes', 'Certification complete + lobbying'],
        ['7. Impact ESG', '3/5 — Modere', 'Opportunite differenciation', 'Certification ESG + green bond'],
      ],
      [25, 18, 30, 27]
    ),
    sp(),

    h2('VIII.8 Diagnostic SWOT de CGI SA'),
    sp(),
    body('Le diagnostic SWOT (Strengths, Weaknesses, Opportunities, Threats) synthetise la position strategique de CGI SA dans son environnement concurrentiel et institutionnel :'),
    sp(),

    h3('VIII.8.1 Forces (Strengths) — Avantages internes'),
    sp(),
    bullet('S1 — Gisement exceptionnel : 201 ha global / 50M+ tonnes de reserves, Phase 1 = 24 ha viabilises, masse volumique 2,63 g/cm³, securite d\'approvisionnement > 100 ans. Permis DGMG deja acquis.'),
    sp(),
    bullet('S2 — Technologie de classe mondiale : Equipements METSO Nordberg C120 + HP300, fiabilite 95 %, conformite NF EN 12620, capacite 200-250 TPH, flexibilite granulometrique (7 classes).'),
    sp(),
    bullet('S3 — Certification LNBTP complete : 7 classes granulométriques certifiees + granulats haute resistance > 120 MPa. Acces aux marches publics ARMP et aux grands chantiers internationaux.'),
    sp(),
    bullet('S4 — Avantage logistique nord : 150 km de Lome, 176 km de Cotonou, couts de transport 20-40 % inferieurs aux carrieres du sud, absence de congestion portuaire.'),
    sp(),
    bullet('S5 — Contrat cadre CIMCO : Base installee de 150 000 T/an (19 % du SOM), revenu previsible des la premiere annee, validation commerciale du projet.'),
    sp(),
    bullet('S6 — Equipe de management experimente : PDG avec 15 ans d\'experience dans le BTP et les mines, DG avec expertise METSO, equipe commerciale former en negociation B2B.'),
    sp(),

    h3('VIII.8.2 Faiblesses (Weaknesses) — handicaps internes'),
    sp(),
    bullet('W1 — Notoriete limitee : CGI SA est un nouvel entrant sans historique de livraison public. La notoriete doit etre construite via des projets pilotes, des references clients, et une presence marketing.'),
    sp(),
    bullet('W2 — Dependance au demarrage : La Phase 1 (Ligne 1) genere 450 000 T/an uniquement. L\'atteinte du SOM cible (795 000 T/an) necessite les Lignes 2 et 3 (CAPEX additionnel 4 100 M FCFA).'),
    sp(),
    bullet('W3 — Cout de conformite eleve : 1 571 M FCFA sur 3 ans (fiscalite, OHADA, certification, environnement, social). Ces couts pesent sur la rentabilite des premieres annees.'),
    sp(),
    bullet('W4 — Fragilite financiere de demarrage : Le ratio endettement/capitaux propres est eleve (11 440 M FCFA de dette BIDC vs 2 500 M FCFA de capital). La sensibilite aux retards de production et aux sous-performances commerciales est elevee.'),
    sp(),
    bullet('W5 — Manque de presence commerciale au Benin : Aucun bureau, aucun commercial, aucun contrat signe au Benin a ce jour. L\'export necessite un investissement commercial de 45 M FCFA (bureau Cotonou, recrutement, prospection).'),
    sp(),

    h3('VIII.8.3 Opportunites (Opportunities) — facteurs externes favorables'),
    sp(),
    bullet('O1 — Deficit structurel togolais : 700 000 T/an de deficit offre/demande, comble par des importations couteuses. CGI SA peut capter une part significative de ce deficit.'),
    sp(),
    bullet('O2 — Programmes publics massifs : PND 2025-2029 (10,85 M T de granulats), grands chantiers (Port Lomé, corridor Abidjan-Lagos, aeroport), urbanisation Lomé (+3,2 %/an).'),
    sp(),
    bullet('O3 — Export Benin structurel : Deficit beninois de 700 000 T/an, prix superieurs de 8-12 %, reconnaissance mutuelle LNBTP-LCBC, proximite Cotonou (176 km).'),
    sp(),
    bullet('O4 — Fenetre de marche 2026-2028 : Aucun nouveau producteur industriel annonce avant 2028. CGI SA a 2-3 ans pour consolider sa position.'),
    sp(),
    bullet('O5 — Tendance ESG et financement vert : Les prets verts offrent des taux inferieurs de 0,5-1,0 point. La certification ESG ouvre les marches internationaux et les contrats a prime.'),
    sp(),
    bullet('O6 — Specialite haute resistance : Segment premium sous-alimente dans la CEDEAO (3 producteurs seulement). Marges de 48-55 % vs 30-38 % pour les standards.'),
    sp(),

    h3('VIII.8.4 Menaces (Threats) — facteurs externes defavorables'),
    sp(),
    bullet('T1 — Guerre des prix (Granutogo) : Probabilite 25 %. Granutogo pourrait reduire ses prix de 10-15 % sur le segment 0/31,5 pour proteger ses parts de marche. Impact : compression marge 5-8 points.'),
    sp(),
    bullet('T2 — Retard des grands chantiers publics : Probabilite 20 %. Les projets publics (PND, corridor) pourraient etre retardes par des contraintes budgetaires ou politiques. Impact : baisse volume 10-15 %.'),
    sp(),
    bullet('T3 — Hausse des couts energetiques : Probabilite 40 %. La CEET a augmente ses tarifs de 12 % en 2024 et pourrait continuer. Impact : baisse marge 3-5 points.'),
    sp(),
    bullet('T4 — Instabilite politique ou reglementaire : Probabilite 10 %. Changement de gouvernement, reforme du Code Minier, ou instabilite sociale. Impact : retard projets, nouvelles taxes.'),
    sp(),
    bullet('T5 — Entree d\'un nouveau producteur industriel : Probabilite 15 %. Un groupe etranger (chinois, turc) pourrait investir dans une carriere industrielle au Togo. Impact : concurrence accrue, guerre des prix.'),
    sp(),
    bullet('T6 — Volatilite du change et inflation : Probabilite 35 %. Le Togo est membre de l\'UEMOA (FCFA indexe sur l\'euro), mais l\'inflation importee (carburant, equipements) peut eroder les marges. Impact : 2-4 points de marge.'),
    sp(),

    h2('VIII.9 Facteurs cles de succes (FCS) du secteur'),
    sp(),
    body('Les facteurs cles de succes (Key Success Factors — KSF) du marche des granulats industriels en Afrique de l\'Ouest sont les suivants :'),
    sp(),

    tbl(
      ['Facteur cle de succes', 'Poids (%)', 'Performance CGI SA', 'Performance Granutogo', 'Ecart CGI vs Granutogo'],
      [
        ['Qualite certifiee (LNBTP/NF EN)', '25%', 'Excellente (7 classes + haute resistance)', 'Bonne (2 classes seulement)', '+++'],
        ['Fiabilite production (taux disponibilite)', '20%', 'Excellente (95% — METSO)', 'Bonne (75-80% — equipt. chinois)', '++'],
        ['Cout logistique vers marches cles', '15%', 'Excellent (150 km Lome, 176 km Cotonou)', 'Moyen (30-80 km mais congestion)', '++'],
        ['Capacite industrielle (TPH)', '15%', 'Tres bon (200-250 TPH)', 'Bon (450 TPH — 3 sites)', '='],
        ['Certification ESG / Finance verte', '10%', 'Tres bon (PGES IFC, centrale solaire)', 'Faible (pas de certification)', '+++'],
        ['Relations institutionnelles (ARMP, DGMG)', '10%', 'Bon (permis acquis, agrement en cours)', 'Tres bon (15 ans de relations)', '-'],
        ['Flexibilite granulometrique', '5%', 'Excellente (7 classes, traçabilite QR)', 'Moyenne (5 classes, pas QR)', '++'],
      ],
      [30, 12, 22, 22, 14]
    ),
    sp(),
    body('CGI SA surpasse Granutogo sur 5 des 7 facteurs cles de succes, avec un avantage particulier sur la qualite certifiee (+25 % du poids), la fiabilite production (+20 %), et la certification ESG (+10 %). Les deux facteurs ou Granutogo conserve un avantage (capacite totale et relations institutionnelles) sont attenues par la position geographique de CGI SA et par la fenetre de marche 2026-2028.'),
    sp(),

    successBox('Conclusion Section VIII : L\'analyse Porter revele un marche a intensite concurrentielle moderee (3/5), protege par des barrieres a l\'entree elevees et l\'absence de substituts viables. CGI SA dispose de 6 forces internes significatives, compensees par 5 faiblesses gerables. Les 6 opportunites externes (deficit structurel, programmes publics, export Benin, fenetre de marche, ESG, specialite) l\'emportent sur les 6 menaces, dont la probabilite cumulee reste moderee. Les facteurs cles de succes confirment le positionnement competitif de CGI SA sur la qualite, la fiabilite, la logistique, et l\'ESG.'),
    pb(),
  ];
}



