import { Paragraph, Table } from 'docx';
import {
  sp, h1, h2, h3, h4, body, bullet, tbl, pb, infoBox, alertBox, successBox,
} from '@/utils/businessPlanCGI/helpers';

export function regulatoryFramework(): (Paragraph | Table)[] {
  return [
    h1('SECTION VI — CADRE REGLEMENTAIRE ET INSTITUTIONNEL'),
    sp(),

    h2('VI.1 Introduction — Architecture normative applicable'),
    body('L\'exploitation industrielle d\'une carriere de granulats au Togo et la commercialisation regionale en Afrique de l\'Ouest sont soumises a un cadre reglementaire multilayer, impliquant le droit national togolais, le droit communautaire de la CEDEAO/UEMOA, l\'Acte Uniforme OHADA, les normes techniques internationales, et les exigences des bailleurs de fonds internationaux (IFC, BAD, BIDC). Ce chapitre analyse de maniere systematique chaque couche reglementaire, evalue son impact sur la rentabilite, et identifie les risques de conformite.'),
    sp(),

    h2('VI.2 Droit minier togolais — Code Minier Loi 2014-010'),
    sp(),
    body('Le Code Minier de la Republique togolaise, adopte par la Loi n° 2014-010 du 24 juin 2014 et ses decrets d\'application, constitue le pilier reglementaire de l\'exploitation des ressources minerales au Togo. Les dispositions applicables aux granulats industriels sont les suivantes :'),
    sp(),

    h3('VI.2.1 Permis d\'exploitation (Article 42 a 55)'),
    body('L\'exploitation de granulats a titre industriel requiert un permis d\'exploitation delivre par la Direction Generale des Mines et de la Geologie (DGMG), apres etude du dossier technique par le Conseil National des Mines. Les conditions sont :'),
    sp(),
    bullet('Duree : 5 ans renouvelable une fois (10 ans total), conformement a l\'Article 48 du Code Minier.'),
    sp(),
    bullet('Superficie : La superficie du permis d\'exploitation est limitee a 200 hectares pour les carrieres de granulats (Article 46). CGI SA detient un permis pour la Phase 1 (24 ha viabilises), dans la limite des 200 ha autorises.'),
    sp(),
    bullet('Cession des droits : Toute cession, fusion ou apport des droits miniers requiert l\'autorisation prealable du Ministre des Mines (Article 52). Cette disposition protege CGI SA contre une appropriation hostile mais limite la flexibilite strategique en cas de sortie.'),
    sp(),
    bullet('Droits et obligations : Le titulaire du permis dispose du droit d\'acces au terrain, d\'extraction, et de commercialisation. En contrepartie, il doit soumettre un Plan d\'Exploitation et de Rehabilitation (PER), maintenir une caution environnementale, et payer les redevances et redevances minieres.'),
    sp(),

    tbl(
      ['Element reglementaire', 'Disposition applicable', 'Cout / Delai', 'Statut CGI SA'],
      [
        ['Permis d\'exploitation', 'Art. 42-55 Code Minier 2014-010', '18-24 mois / 45-85 M FCFA', '✔ Acquis — Phase 1 (24 ha)'],
        ['Renouvellement', 'Art. 48 — renouvelable 1 fois (5+5 ans)', '6 mois avant expiration', '✔ A planifier 2029'],
        ['Caution environnementale', 'Art. 67 — garantie rehabilitation', '2% du CAPEX estimé', '✔ Versee — 178 M FCFA'],
        ['PER (Plan Exploitation Rehabilitation)', 'Art. 56 — approuve par DGE', '45 M FCFA / 6-9 mois', '✔ Soumis — mars 2025'],
        ['Redevance miniere', 'Art. 70 — 3% de la valeur production', '~192 M FCFA/an (2028)', '✔ Budgetee'],
        ['Redevance superficiaire', 'Art. 71 — 50 000 FCFA/ha/an', '1,2 M FCFA/an (24 ha)', '✔ Budgetee'],
      ],
      [25, 30, 22, 23]
    ),
    sp(),

    h3('VI.2.2 Fiscalite miniere (Articles 70 a 75)'),
    body('La fiscalite applicable aux operations minieres au Togo comprend plusieurs prelevements dont l\'impact sur la rentabilite doit etre integre dans le modele financier :'),
    sp(),
    bullet('Redevance miniere : 3 % de la valeur de la production (Article 70). Pour CGI SA, avec une production de 795 000 T/an a 8 000 FCFA/T, la redevance s\'eleve a 190,8 M FCFA par an.'),
    sp(),
    bullet('Redevance superficiaire : 50 000 FCFA par hectare et par an (Article 71). Pour 24 ha, le montant est de 1,2 M FCFA par an, negligeable au regard du chiffre d\'affaires.'),
    sp(),
    bullet('Taxe professionnelle : 2,5 % du chiffre d\'affaires (Code des Impots, Article 234). Montant estime : 159 M FCFA par an (2028).'),
    sp(),
    bullet('TVA : 18 % sur les ventes de granulats (Code des Impots, Article 267). CGI SA est assujetti a la TVA et doit s\'acquitter des obligations de facturation et de declaration mensuelle. La TVA collectee est recuperable sur les achats de biens et services (equipements, carburant, electricite).'),
    sp(),
    bullet('Impots sur les societes (IS) : Taux progressif de 25 % a 35 % selon le benefice (Code des Impots, Article 198). Pour CGI SA, le taux applicable sera de 27 % (tranche 500 M a 1 Mds FCFA de benefice) a 30 % (au-dela).'),
    sp(),
    infoBox('Source : Code Minier de la Republique togolaise — Loi n° 2014-010 du 24 juin 2014 | Decret n° 2015-007 du 15 janvier 2015 portant application du Code Minier | Code General des Impots du Togo — Loi de finances 2024 | DGMG Togo — « Guide du demandeur de permis minier, edition 2023 ».'),

    h2('VI.3 Droit des societes — Acte Uniforme OHADA (AUSC)'),
    sp(),
    body('CORNERSTONE GROUP INTERNATIONAL (CGI) SA est constituee sous la forme d\'une Societe Anonyme (SA), soumise a l\'Acte Uniforme relatif au Droit des Societes Commerciales et du GIE (AUSCGIE) de l\'OHADA, revise par l\'Acte Uniforme du 15 decembre 2020. Les obligations suivantes s\'appliquent :'),
    sp(),

    h3('VI.3.1 Gouvernance societaire (AUSCGIE, Articles 387 a 558)'),
    body('Les SA de l\'OHADA doivent respecter un minimum de gouvernance corporate, renforce par les exigences des bailleurs internationaux :'),
    sp(),
    bullet('Conseil d\'Administration : Minimum 3 membres (Article 423). CGI SA a structure un CA de 5 membres (2 executifs — PDG et DG, 3 non-executifs independants). Les administrateurs non-executifs sont remuneres par des jetons de presence plafonnes a 8 % du resultat net (Article 546).'),
    sp(),
    bullet('Commissaire aux Comptes : Obligatoire pour les SA depassant certains seuils (Article 523). CGI SA, avec un CA previsionnel de 6,4 Mds FCFA, depasse largement les seuils et doit designer un commissaire aux comptes externe (Cac) des la premiere annee d\'exercice. Cout estime : 25 M FCFA par an.'),
    sp(),
    bullet('Publication des comptes : Les SA doivent deposer leurs comptes annuels au Greffe du Tribunal de Commerce (Article 37 du AUSCGIE). Cette obligation de transparence, bien que contraignante, renforce la credibilite de CGI SA aupres des bailleurs et des partenaires commerciaux.'),
    sp(),
    bullet('Assemblee Generale Ordinaire (AGO) : Convoquee dans les 6 mois suivant la cloture de l\'exercice (Article 438). L\'AGO approuve les comptes, affecte le resultat, et autorise les conventions reglementees.'),
    sp(),

    tbl(
      ['Obligation OHADA', 'Article AUSCGIE', 'Cout annuel (M FCFA)', 'Impact strategique'],
      [
        ['Conseil d\'Administration (5 membres)', 'Art. 423-446', '45', 'Gouvernance « investment grade »'],
        ['Commissaire aux Comptes externe', 'Art. 523-538', '25', 'Credibilite bailleurs'],
        ['Publication comptes au Greffe', 'Art. 37', '5', 'Transparence, reputation'],
        ['AGO annuelle', 'Art. 438-445', '3', 'Gouvernance actionnaires'],
        ['Contrats reglementes (conventions)', 'Art. 510-520', '2', 'Prevention conflits d\'interets'],
        ['TOTAL conformite OHADA', '—', '80', '2,1% du CA 2028'],
      ],
      [30, 25, 25, 20]
    ),
    sp(),

    h3('VI.3.2 Droit comptable SYSCOHADA (AUDCIF)'),
    body('Les etats financiers de CGI SA doivent etre etablis conformement au Systeme Comptable Ouest-Africain et de Developpement (SYSCOHADA), revise par l\'Acte Uniforme relatif au Droit Comptable et a la Information Financiere (AUDCIF) du 15 decembre 2020. Les particularites suivantes s\'appliquent :'),
    sp(),
    bullet('Plan de comptes : Utilisation du plan de comptes SYSCOHADA standard (classes 1 a 8) avec possibilite d\'adaptation pour les societes minieres.'),
    sp(),
    bullet('Amortissements : Les immobilisations industrielles (concasseurs, cribles, centrale electrique) sont amorties sur leur duree d\'utilite. Concasseur METSO : 15 ans (taux 6,67 %/an). Crible : 12 ans (taux 8,33 %/an). Centrale solaire : 20 ans (taux 5 %/an). Vehicules : 5 ans (taux 20 %/an).'),
    sp(),
    bullet('Stock : Evaluation des stocks de granulats en production (biens en cours) et en magasin (produits finis) au cout de production complet (matieres premieres, main-d\'oeuvre directe, charges indirectes de production).'),
    sp(),
    bullet('Provisions : Constitution de provisions pour depreciation des stocks, risques litiges, et charges a repartir. Les provisions pour rehabilitation environnementale sont comptabilisees en fonds de dotation (compte 198).'),
    sp(),
    infoBox('Source : Acte Uniforme OHADA relatif au Droit des Societes Commerciales et du GIE (AUSCGIE) — 15 decembre 2020 | Acte Uniforme OHADA relatif au Droit Comptable et a la Information Financiere (AUDCIF) — 15 decembre 2020 | SYSCOHADA — Plan de comptes, 4eme edition 2023.'),

    h2('VI.4 Normes techniques et certification'),
    sp(),
    body('La conformite aux normes techniques est determinante pour l\'acces aux marches publics et aux grands comptes BTP. Les normes applicables sont :'),
    sp(),

    h3('VI.4.1 Normes NF EN (Normes Francaises / Europeennes)'),
    body('Les normes NF EN sont systematiquement referencees dans les cahiers des charges des marches publics togolais et beninois, conformement aux recommandations de la LNBTP et du LCBC :'),
    sp(),
    bullet('NF EN 12620 :2013 — Granulats pour beton. Cette norme definit les specifications techniques des granulats destines a la fabrication de betons, incluant la granulometrie, la forme, la resistance a l\'usure (Los Angeles), la resistance a l\'abrasion (Micro-Deval), l\'absorption d\'eau, et la teneur en chlorures.'),
    sp(),
    bullet('NF EN 13043 :2013 — Granulats pour enrobes bitumineux et couches de roulement. Applicable aux granulats utilises dans les enrobes bitumineux et les couches de roulement routieres.'),
    sp(),
    bullet('NF EN 13242 :2002+A1:2007 — Granulats pour materiaux traites aux liants hydrauliques et pour remblaiement. Applicable aux graves non traitees et aux materiaux de remblaiement.'),
    sp(),
    bullet('NF EN 13383-1 :2002 — Enrochements. Applicable aux blocs de roche utilises pour la protection des ouvrages hydrauliques (brise-lames, digues).'),
    sp(),

    h3('VI.4.2 Certification LNBTP (Togo) et LCBC (Benin)'),
    body('Le Laboratoire National du Batiment et des Travaux Publics du Togo (LNBTP) est l\'organisme certificateur officiel pour les materiaux de construction. La certification LNBTP comprend :'),
    sp(),
    bullet('Essais de caracterisation : Analyse granulometrique, Los Angeles (NF EN 1097-2), Micro-Deval (NF EN 1097-1), absorption d\'eau (NF EN 1097-6), masse volumique (NF EN 1097-6), coefficient de friabilite (NF EN 1097-2).'),
    sp(),
    bullet('Inspection de l\'etablissement : Visite annuelle du site de production par les inspecteurs LNBTP pour verifier les equipements, les procedes, et la tracabilite.'),
    sp(),
    bullet('Delivrance du certificat : Le certificat LNBTP est valable 1 an et doit etre renouvele annuellement. Cout : 12 M FCFA par an (renouvellement) + 85 M FCFA (investissement initial en laboratoire et equipements de controle).'),
    sp(),
    bullet('Reconnaissance mutuelle : L\'accord LNBTP-LCBC permet aux granulats certifies LNBTP d\'etre reconnus au Benin sans essai complementaire, reduisant les delais et couts d\'acces au marche beninois.'),
    sp(),

    tbl(
      ['Norme / Certification', 'Objet', 'Cout initial (M FCFA)', 'Cout recurrent (M FCFA/an)', 'Impact marche'],
      [
        ['NF EN 12620 :2013', 'Granulats pour beton', '— (inclus METSO)', '—', 'Obligatoire marches publics'],
        ['NF EN 13043 :2013', 'Granulats pour enrobes', '— (inclus METSO)', '—', 'Obligatoire routes ARMP'],
        ['NF EN 13242 :2002', 'Graves et remblaiement', '— (inclus METSO)', '—', 'Obligatoire terrassement'],
        ['Certification LNBTP', 'Qualification site + produit', '85', '12', 'Obligatoire ARMP > 50 M'],
        ['Accord LNBTP-LCBC', 'Reconnaissance Benin', '5', '2', 'Facilite export Benin'],
        ['TOTAL', '—', '90', '14', 'Acces marches publics + export'],
      ],
      [25, 25, 17, 17, 16]
    ),
    sp(),

    h2('VI.5 Reglementation environnementale et sociale'),
    sp(),
    body('L\'exploitation de la carriere de Siyime est soumise aux dispositions de la Loi-cadre sur l\'Environnement au Togo (Loi n° 2008-005 du 14 mai 2008) et aux decrets d\'application, ainsi qu\'aux Performance Standards de la IFC (PS 1 a 8).'),
    sp(),

    h3('VI.5.1 Etude d\'Impact Environnemental (EIE) et Plan de Gestion Environnementale et Sociale (PGES)'),
    body('Conformement au Decret n° 2014-015 du 22 avril 2014 portant procedure d\'evaluation environnementale au Togo, tout projet d\'exploitation miniere a titre industriel necessite :'),
    sp(),
    bullet('Etude d\'Impact Environnemental (EIE) : Analyse des impacts potentiels sur l\'air, l\'eau, les sols, la faune, la flore, et les populations. Realisee par un bureau d\'etudes agree (CETAF, Togo). Cout : 65 M FCFA. Duree : 4-6 mois. CGI SA : EIE realisee en 2024, rapport approuve par la DGE en fevrier 2025.'),
    sp(),
    bullet('Plan de Gestion Environnementale et Sociale (PGES) : Mesures d\'attenuation, de surveillance, et de rehabilitation. Le PGES de CGI SA est conforme aux Performance Standards IFC PS 1 (Evaluation et gestion des risques et impacts environnementaux et sociaux) et PS 4 (Sante, securite et environnement communautaire). Cout : 45 M FCFA. Duree : 3-4 mois. CGI SA : PGES soumis en mars 2025.'),
    sp(),
    bullet('Plan d\'Action de Reinstallation (PAR) : Si le projet implique le deplacement involontaire de populations, un PAR est requis conformement a la Loi 2008-005 et a la Norme IFC PS 5. CGI SA : Le site de Siyime est situe en zone rurale avec une densite de population faible. Aucun deplacement involontaire n\'est requis pour la Phase 1 (24 ha). Un PAR de precaution a neanmoins ete etabli (cout : 15 M FCFA).'),
    sp(),
    bullet('Audits environnementaux periodiques : La DGE realise des inspections annuelles. Cout : 8 M FCFA par an. CGI SA : Budgete dans le plan de conformite ESG.'),
    sp(),

    tbl(
      ['Obligation environnementale', 'Texte applicable', 'Cout (M FCFA)', 'Statut CGI SA'],
      [
        ['EIE (Etude d\'Impact Environnemental)', 'Decret 2014-015', '65', '✔ Approuvee — fev. 2025'],
        ['PGES (Plan Gestion Env. & Sociale)', 'Decret 2014-015 + IFC PS 1-4', '45', '✔ Soumis — mars 2025'],
        ['PAR (Plan Action Reinstallation)', 'Loi 2008-005 + IFC PS 5', '15', '✔ Soumis — precautionnel'],
        ['Caution environnementale', 'Code Minier Art. 67', '178', '✔ Versee'],
        ['Audits environnementaux annuels', 'Decret 2014-015', '8/an', '✔ Budgete'],
        ['Rehabilitation post-exploitation', 'PER — Code Minier Art. 56', '120 (sur 10 ans)', '✔ Budgete'],
      ],
      [30, 30, 20, 20]
    ),
    sp(),

    h3('VI.5.2 Performance Standards IFC (PS 1 a 8)'),
    body('Les bailleurs internationaux (BIDC, BAD, IFC) conditionnent leurs financements au respect des 8 Performance Standards du IFC. Pour CGI SA, les standards les plus pertinents sont :'),
    sp(),
    bullet('PS 1 — Evaluation et gestion des risques et impacts environnementaux et sociaux : Etablissement d\'un systeme de gestion environnementale et sociale (SGES). CGI SA a designe un responsable ESG et un consultant externe (CETAF) pour la mise en oeuvre.'),
    sp(),
    bullet('PS 2 — Conditions de travail et relations de travail : Respect du Code du Travail togolais et des conventions OIT (n° 87, 98, 100, 111). Politique de recrutement local, formation, securite, et egalite de remuneration.'),
    sp(),
    bullet('PS 3 — Efficacite des ressources et prevention de la pollution : Reduction de la consommation d\'eau et d\'energie, gestion des dechets, controle des poussieres. CGI SA a prevu une centrale solaire 3-4 MWc et un systeme de suppression des poussieres.'),
    sp(),
    bullet('PS 4 — Sante, securite et environnement communautaire : Mesures de securite pour les communautes riveraines, gestion du trafic de camions, et plan d\'urgence.'),
    sp(),
    bullet('PS 5 — Acquisition de terres et relocalisation involontaire : Aucune relocalisation requise pour la Phase 1, mais un PAR de precaution a ete etabli.'),
    sp(),
    bullet('PS 6 — Conservation de la biodiversite et gestion durable des ressources naturelles : Le site de Siyime est en zone de savane arbustive (non foret primaire). Aucun habitat critique identifie. Un plan de reboisement de 5 ha est prevu.'),
    sp(),
    bullet('PS 7 — Populations autochtones : Non applicable — aucune population autochtone au sens de la PS 7 n\'est presente dans la zone.'),
    sp(),
    bullet('PS 8 — Patrimoine culturel : Aucun site archeologique ou patrimonial identifie dans la zone de permis. Un protocole d\'arret de travaux en cas de decouverte fortuite est integre au PER.'),
    sp(),
    infoBox('Source : IFC — « Performance Standards on Environmental and Social Sustainability, 2012 » | Loi-cadre sur l\'Environnement au Togo — Loi n° 2008-005 du 14 mai 2008 | Decret n° 2014-015 du 22 avril 2014 portant procedure d\'evaluation environnementale | DGE Togo — « Guide de l\'evaluateur environmental, edition 2023 ».'),

    h2('VI.6 Reglementation du travail et normes sociales'),
    sp(),
    body('CGI SA, en tant qu\'employeur au Togo, est soumise au Code du Travail togolais (Loi n° 2006-010 du 26 juin 2006, modifiee) et aux conventions de l\'Organisation Internationale du Travail (OIT) ratifiees par le Togo :'),
    sp(),
    bullet('Duree du travail : 40 heures par semaine (Code du Travail, Article 120). Heures supplementaires remunerees a 125 % (50 %) ou 150 % (100 %). CGI SA : Horaires de production en 2x8 (6h-14h / 14h-22h), total 48h/semaine avec recuperation.'),
    sp(),
    bullet('Salaire minimum interprofessionnel garanti (SMIG) : 52 500 FCFA/mois (2024). CGI SA s\'engage a remunerer tous les employes au-dessus du SMIG, avec un salaire median de 95 000 FCFA/mois.'),
    sp(),
    bullet('Securite sociale : Affiliation a la Caisse Nationale de Securite Sociale (CNSS) obligatoire. Cotisations : employeur 17,5 %, salarie 4 % (Code du Travail, Article 245). CGI SA : Budget CNSS estime a 85 M FCFA/an.'),
    sp(),
    bullet('Conventions collectives : Le secteur des mines et carrieres n\'est pas couvert par une convention collective specifique au Togo. CGI SA applique les dispositions du Code du Travail et les standards IFC PS 2.'),
    sp(),
    bullet('Egalite de remuneration : Conventions OIT n° 100 (egalite de remuneration) et n° 111 (discrimination — emploi et profession). CGI SA : Politique de non-discrimination et d\'egalite de remuneration entre hommes et femmes pour des fonctions equivalentes. Ratio femmes/hommes cible : 30 % dans l\'effectif total.'),
    sp(),

    tbl(
      ['Obligation sociale', 'Texte applicable', 'Cout annuel (M FCFA)', 'Statut CGI SA'],
      [
        ['Cotisations CNSS (employeur)', 'Code Travail Art. 245 — 17,5%', '85', '✔ Budgete'],
        ['Prevention risques professionnels', 'Code Travail Art. 180-200', '22', '✔ Budgete'],
        ['Formation professionnelle continue', 'Code Travail Art. 210-220', '35', '✔ Budgete'],
        ['EPI (Equipements de Protection Individuelle)', 'Code Travail Art. 185', '18', '✔ Budgete'],
        ['Actions sociales et communautaires', 'IFC PS 2 + PDC', '45', '✔ Budgete'],
        ['TOTAL social', '—', '205', '2,6% du CA 2028'],
      ],
      [30, 30, 20, 20]
    ),
    sp(),

    h2('VI.7 Reglementation douaniere et commerce regional'),
    sp(),
    body('L\'export de granulats depuis le Togo vers le Benin et le Ghana est regi par le Traite de la CEDEAO (libre circulation des biens) et les reglementations douanieres nationales :'),
    sp(),
    bullet('Libre circulation CEDEAO : Les granulats, en tant que biens produits dans un Etat membre de la CEDEAO, beneficient de la libre circulation sans droits de douane (Traite CEDEAO, Article 35). Ce principe est operationalise par le Certificat de Circulation des Marchandises (CCM).'),
    sp(),
    bullet('TVA a l\'importation : Au Benin, la TVA a l\'importation est de 18 %. CGI SA peut optimiser cette charge en creant un etablissement commercial au Benin (filiale ou representant), permettant la recuperation de la TVA et la facturation locale.'),
    sp(),
    bullet('Reglementation sanitaire et phytosanitaire : Les granulats ne sont pas soumis a des restrictions sanitaires ou phytosanitaires. Cependant, les camions doivent disposer d\'un permis de transport de materiaux en vrac et respecter les normes de securite routiere.'),
    sp(),
    bullet('Normes techniques transfrontalieres : L\'accord de reconnaissance mutuelle LNBTP-LCBC facilite l\'export vers le Benin. Pour le Ghana, les granulats doivent satisfaire aux normes du Ghana Standards Authority (GSA), qui sont generalement alignees sur les normes NF EN.'),
    sp(),

    h2('VI.8 Impact reglementaire sur la rentabilite'),
    sp(),
    body('L\'ensemble des contraintes reglementaires et institutionnelles represente un cout total de conformite de 487 M FCFA sur 2026-2028, reparti comme suit :'),
    sp(),

    tbl(
      ['Categorie de conformite', 'Cout 2026-2028 (M FCFA)', '% du CAPEX', '% du CA 2028'],
      [
        ['Fiscalite miniere et generale', '351', '3,9%', '5,5%'],
        ['Gouvernance OHADA', '240', '2,7%', '3,8%'],
        ['Certification et normes techniques', '104', '1,2%', '1,6%'],
        ['Environnement et ESG', '431', '4,8%', '6,7%'],
        ['Social et ressources humaines', '410', '4,6%', '6,4%'],
        ['Douane et commerce regional', '35', '0,4%', '0,5%'],
        ['TOTAL CONFORMITE', '1 571', '17,6%', '24,5%'],
      ],
      [35, 20, 15, 15, 15]
    ),
    sp(),
    body('Le cout de conformite reglementaire, bien que significatif (17,6 % du CAPEX sur 3 ans), est amplement compense par les benefices suivants : (i) acces aux marches publics ARMP (35 % du volume cible), (ii) acces aux financements concessionnels (BIDC taux 5,5 %, 12 ans), (iii) prime ESG sur les contrats internationaux (5-8 % de premium), (iv) reduction des risques de sanctions et de contentieux, et (v) renforcement de la reputation et de la perennite de CGI SA.'),
    sp(),
    alertBox('Risque reglementaire majeur identifie : Toute modification du Code Minier togolais augmentant la redevance miniere (actuellement 3 %) ou instaurant de nouvelles taxes environnementales pourrait impacter la rentabilite. La probabilite d\'un tel changement est evaluee a 15 % d\'ici 2030, avec un impact potentiel de -3 a -5 points de marge nette. La mitigation repose sur le lobbying institutionnel (Chambre des Mines du Togo) et la diversification geographique (export Benin).'),
    sp(),

    successBox('Conclusion Section VI : Le cadre reglementaire et institutionnel applicable a CGI SA est dense mais maitrisable. Les permis sont acquis, les normes sont satisfaites, et le budget de conformite (1 571 M FCFA sur 3 ans) est integre dans le plan de financement sans degradation des indicateurs de rentabilite. Le risque reglementaire principal reside dans une eventuelle reforme fiscale miniere, mais ce risque est limite (15 %) et attenue par la diversification geographique et le lobbying institutionnel.'),
    pb(),
  ];
}



