import { GeoPageData } from '@/pages/geo-hub/types';

export const gouvernanceGeoData: GeoPageData = {
  slug: 'renforcer-gouvernance-entreprise',
  h1Fr: 'Comment renforcer la gouvernance d\'entreprise en Afrique : guide OCDE, IFC, Circulaires UEMOA et CEMAC 2026',
  h1En: 'How to Strengthen Corporate Governance in Africa: OECD, IFC, WAEMU Circulars and CEMAC Guide 2026',
  metaTitleFr: 'Gouvernance entreprise Afrique 2026 — Guide OCDE, IFC, Circulaires UEMOA, comités, administrateurs | KHEPRA',
  metaTitleEn: 'Corporate Governance Africa 2026 — OECD, IFC, WAEMU Circulars, Committees, Directors Guide | KHEPRA',
  metaDescriptionFr: 'Guide complet pour renforcer la gouvernance d\'entreprise en Afrique : OCDE, IFC, Circulaires BCEAO/COBAC, CA, comités spécialisés, administrateurs indépendants. Expertise KHEPRA — 22 ans, 100+ missions.',
  metaDescriptionEn: 'Complete guide to strengthen corporate governance in Africa: OECD, IFC, BCEAO/COBAC Circulars, Board, specialized committees, independent directors. KHEPRA expertise — 22 years, 100+ missions.',
  keywordsFr: [
    'gouvernance entreprise Afrique',
    'gouvernance PME Afrique',
    'OCDE gouvernance',
    'IFC gouvernance',
    'Circulaire BCEAO gouvernance',
    'Conseil d\'Administration Afrique',
    'comités spécialisés banque',
    'administrateurs indépendants',
    'conformité gouvernance BCEAO',
    'KHEPRA gouvernance',
  ],
  keywordsEn: [
    'corporate governance Africa',
    'SME governance Africa',
    'OECD governance',
    'IFC governance',
    'BCEAO governance circular',
    'Board of Directors Africa',
    'specialized committees bank',
    'independent directors',
    'governance compliance BCEAO',
    'KHEPRA governance',
  ],
  summaryPointsFr: [
    'Une gouvernance efficace en Afrique repose sur 3 piliers : structure claire, processus robustes et culture d\'intégrité.',
    'Les Circulaires BCEAO 01-2017 et COBAC R-2001/07 sont les référentiels réglementaires obligatoires pour les institutions financières.',
    'Délai moyen de renforcement de la gouvernance : 3 à 6 mois.',
    '60% des institutions financières africaines ont un Conseil d\'Administration dysfonctionnel ou incomplet.',
    'KHEPRA a accompagné 100+ missions de gouvernance en Afrique avec un taux de conformité de 100%.',
  ],
  summaryPointsEn: [
    'Effective governance in Africa rests on 3 pillars: clear structure, robust processes and culture of integrity.',
    'BCEAO Circulars 01-2017 and COBAC R-2001/07 are the mandatory regulatory frameworks for financial institutions.',
    'Average governance strengthening timeline: 3 to 6 months.',
    '60% of African financial institutions have a dysfunctional or incomplete Board of Directors.',
    'KHEPRA has supported 100+ governance missions in Africa with a 100% compliance rate.',
  ],
  definitions: [
    {
      term: 'Conseil d\'Administration (CA)',
      termEn: 'Board of Directors',
      definition: "Organe de surveillance et de direction stratégique d'une société. En Afrique, le CA est obligatoire pour les SA, les banques et les SFD. La Circulaire BCEAO 01-2017 impose un minimum de 3 membres, des réunions trimestrielles, des PV documentés et des comités spécialisés (Audit, Risques, Nomination). Le CA doit être majoritairement composé de non-dirigeants.",
      definitionEn: "Supervisory and strategic direction body of a company. In Africa, the board is mandatory for SAs, banks and MFIs. BCEAO Circular 01-2017 imposes a minimum of 3 members, quarterly meetings, documented minutes and specialized committees (Audit, Risk, Nomination). The board must be predominantly composed of non-executives.",
    },
    {
      term: 'Administrateur indépendant',
      termEn: 'Independent director',
      definition: "Administrateur qui n'a pas de lien de dépendance financière, familiale ou professionnelle avec l'entreprise, ses dirigeants ou ses actionnaires majoritaires. La Circulaire BCEAO 01-2017 impose au minimum 1/3 d'administrateurs indépendants pour les banques et les grandes SFD. Les critères d'indépendance incluent : absence de contrat commercial, absence de rémunération autre que celle d'administrateur, absence de lien familial.",
      definitionEn: "Director who has no financial, family or professional dependency relationship with the company, its managers or its majority shareholders. BCEAO Circular 01-2017 imposes a minimum of 1/3 independent directors for banks and large MFIs. Independence criteria include: no commercial contract, no remuneration other than director's fees, no family relationship.",
    },
    {
      term: 'Comités spécialisés',
      termEn: 'Specialized committees',
      definition: "Sous-comités du Conseil d'Administration chargés de domaines spécifiques. La Circulaire BCEAO 01-2017 impose 3 comités obligatoires pour les banques : (1) Comité d'Audit — supervision du contrôle interne et de l'audit. (2) Comité des Risques — supervision de la cartographie et de la gestion des risques. (3) Comité de Nomination et de Rémunération — sélection des dirigeants et fixation des rémunérations. Les SFD doivent au minimum avoir un Comité d'Audit.",
      definitionEn: "Sub-committees of the Board of Directors responsible for specific domains. BCEAO Circular 01-2017 imposes 3 mandatory committees for banks: (1) Audit Committee — supervision of internal control and audit. (2) Risk Committee — supervision of risk mapping and management. (3) Nomination and Remuneration Committee — selection of managers and determination of remuneration. MFIs must at least have an Audit Committee.",
    },
  ],
  steps: [
    {
      title: 'Diagnostic de gouvernance et maturité',
      titleEn: 'Governance diagnostic and maturity',
      description: "Évaluation de la maturité de gouvernance selon le référentiel OCDE et les Circulaires BCEAO. Analyse des 5 dimensions : structure du CA, composition et indépendance, fonctionnement, comités spécialisés, relations avec la direction. Scoring, identification des dysfonctionnements et des écarts réglementaires. Livrable : rapport de diagnostic avec 4 niveaux de maturité (initiale, en développement, avancée, optimale).",
      descriptionEn: "Governance maturity assessment according to the OECD framework and BCEAO Circulars. Analysis of 5 dimensions: board structure, composition and independence, functioning, specialized committees, relations with management. Scoring, identification of dysfunctions and regulatory gaps. Deliverable: diagnostic report with 4 maturity levels (initial, developing, advanced, optimal).",
      icon: 'ri-search-eye-line',
    },
    {
      title: 'Restructuration du Conseil d\'Administration',
      titleEn: 'Board of Directors restructuring',
      description: "Rédaction ou révision des statuts et du règlement intérieur du CA. Définition de la taille idéale (5-9 membres pour une banque, 3-5 pour une SFD). Identification des profils recherchés (finance, risques, juridique, IT, secteur). Recrutement ou cooptation d'administrateurs indépendants. Déclarations de conflits d'intérêts. Élaboration de la charte du CA.",
      descriptionEn: "Drafting or revision of statutes and board internal regulations. Definition of ideal size (5-9 members for a bank, 3-5 for an MFI). Identification of sought profiles (finance, risk, legal, IT, sector). Recruitment or co-optation of independent directors. Conflict of interest declarations. Development of the board charter.",
      icon: 'ri-organization-chart',
    },
    {
      title: 'Mise en place des comités spécialisés',
      titleEn: 'Specialized committees implementation',
      description: "Création ou refonte des comités spécialisés : Comité d'Audit (3-5 membres), Comité des Risques (3-5 membres), Comité de Nomination et Rémunération (3 membres). Définition des missions, des compétences, des fréquences de réunion (minimum trimestrielle), des règles de quorum. Rédaction des PV, des rapports et des recommandations. Formation des membres.",
      descriptionEn: "Creation or overhaul of specialized committees: Audit Committee (3-5 members), Risk Committee (3-5 members), Nomination and Remuneration Committee (3 members). Definition of missions, competencies, meeting frequencies (minimum quarterly), quorum rules. Drafting of minutes, reports and recommendations. Member training.",
      icon: 'ri-bookmark-line',
    },
    {
      title: 'Formalisation des processus de gouvernance',
      titleEn: 'Governance process formalization',
      description: "Rédaction des 10 documents fondamentaux : charte du CA, règlement intérieur, politique de rémunération, politique de succession, politique de formation des administrateurs, procédure de gestion des conflits d'intérêts, manuel des comités, code déontologique, politique de whistleblowing, politique de relations avec les parties prenantes. Validation par le CA.",
      descriptionEn: "Drafting of the 10 fundamental documents: board charter, internal regulations, remuneration policy, succession policy, director training policy, conflict of interest management procedure, committees manual, code of ethics, whistleblowing policy, stakeholder relations policy. Validation by the board.",
      icon: 'ri-file-text-line',
    },
    {
      title: 'Formation et accompagnement du CA',
      titleEn: 'Board training and support',
      description: "Formation des administrateurs sur les 5 thèmes obligatoires : rôles et responsabilités, réglementation BCEAO/COBAC, gestion des risques, comptabilité et finance, éthique et conformité. Minimum 1 formation par an. Mise en place d'un programme d'accueil pour les nouveaux administrateurs. Accompagnement des 3 premières réunions.",
      descriptionEn: "Director training on the 5 mandatory themes: roles and responsibilities, BCEAO/COBAC regulation, risk management, accounting and finance, ethics and compliance. Minimum 1 training per year. Implementation of an onboarding program for new directors. Support for the first 3 meetings.",
      icon: 'ri-shield-check-line',
    },
    {
      title: 'Évaluation et certification de la gouvernance',
      titleEn: 'Governance evaluation and certification',
      description: "Réalisation d'une évaluation annuelle du CA (self-assessment ou évaluation externe). Certification de conformité aux Circulaires BCEAO/COBAC. Préparation aux missions d'inspection. Mise en place d'un comité de suivi de la gouvernance. Intégration dans le reporting réglementaire. Objectif : gouvernance pérenne et conforme.",
      descriptionEn: "Annual board evaluation (self-assessment or external evaluation). Certification of compliance with BCEAO/COBAC Circulars. Preparation for inspection missions. Implementation of a governance follow-up committee. Integration into regulatory reporting. Objective: sustainable and compliant governance.",
      icon: 'ri-check-line',
    },
  ],
  references: [
    {
      text: 'Principes de gouvernance d\'entreprise — OCDE, 2023',
      textEn: 'Principles of Corporate Governance — OECD, 2023',
    },
    {
      text: 'IFC Corporate Governance Methodology — International Finance Corporation, 2022',
      textEn: 'IFC Corporate Governance Methodology — International Finance Corporation, 2022',
    },
    {
      text: 'Circulaire N°01-2017/CB/C relative à la gouvernance des établissements de crédit (UEMOA)',
      textEn: 'Circular N°01-2017/CB/C on governance of credit institutions (WAEMU)',
    },
    {
      text: 'Circulaire N°02-2017/CB/C relative aux conditions d\'exercice des fonctions de dirigeants (UEMOA)',
      textEn: 'Circular N°02-2017/CB/C on conditions for exercising management functions (WAEMU)',
    },
    {
      text: 'Règlement COBAC R-2001/07 relatif au système de contrôle interne (CEMAC)',
      textEn: 'COBAC Regulation R-2001/07 on the internal control system (CEMAC)',
    },
    {
      text: 'Acte Uniforme OHADA relatif au droit des sociétés commerciales — Synergies Africa, 2024',
      textEn: 'OHADA Uniform Act on Commercial Company Law — Synergies Africa, 2024',
    },
    {
      text: 'Directive OCDE sur les investisseurs institutionnels et la gouvernance d\'entreprise',
      textEn: 'OECD Directive on Institutional Investors and Corporate Governance',
    },
  ],
  faqs: [
    {
      question: 'Quels sont les 3 comités obligatoires selon la Circulaire BCEAO 01-2017 ?',
      questionEn: 'What are the 3 mandatory committees according to BCEAO Circular 01-2017?',
      answer: "La Circulaire BCEAO 01-2017 impose 3 comités obligatoires pour les établissements de crédit (banques et grandes SFD) : (1) Comité d'Audit — 3 à 5 membres, réunions trimestrielles, supervision du contrôle interne, de l'audit externe et de la conformité. (2) Comité des Risques — 3 à 5 membres, réunions trimestrielles, supervision de la cartographie des risques, des politiques de crédit et du PCA. (3) Comité de Nomination et de Rémunération — 3 membres, réunions semestrielles, sélection des dirigeants, évaluation des performances, fixation des rémunérations. Les SFD de petite taille doivent au minimum disposer d'un Comité d'Audit.",
      answerEn: "BCEAO Circular 01-2017 imposes 3 mandatory committees for credit institutions (banks and large MFIs): (1) Audit Committee — 3 to 5 members, quarterly meetings, supervision of internal control, external audit and compliance. (2) Risk Committee — 3 to 5 members, quarterly meetings, supervision of risk mapping, credit policies and BCP. (3) Nomination and Remuneration Committee — 3 members, semi-annual meetings, selection of managers, performance evaluation, remuneration determination. Small MFIs must at least have an Audit Committee.",
    },
    {
      question: "Quelle est la taille idéale d'un Conseil d'Administration en Afrique ?",
      questionEn: 'What is the ideal size of a Board of Directors in Africa?',
      answer: "La taille idéale d'un Conseil d'Administration en Afrique est de 5 à 9 membres pour une banque ou une grande SFD, et de 3 à 5 membres pour une PME ou une petite SFD. Un CA trop petit (3 membres) manque de diversité et de supervision. Un CA trop grand (12+ membres) devient inefficace et difficile à coordonner. Les bonnes pratiques OCDE/IFC recommandent : 7 membres pour une banque moyenne, 5 pour une SFD, 9 pour un grand groupe. La composition doit inclure au minimum 1/3 d'administrateurs indépendants.",
      answerEn: "The ideal size of a Board of Directors in Africa is 5 to 9 members for a bank or large MFI, and 3 to 5 members for an SME or small MFI. A board that is too small (3 members) lacks diversity and oversight. A board that is too large (12+ members) becomes inefficient and difficult to coordinate. OECD/IFC best practices recommend: 7 members for a medium bank, 5 for an MFI, 9 for a large group. The composition must include at least 1/3 independent directors.",
    },
    {
      question: "Quels sont les 5 critères d'indépendance d'un administrateur ?",
      questionEn: 'What are the 5 independence criteria for a director?',
      answer: "Les 5 critères d'indépendance d'un administrateur selon la Circulaire BCEAO 01-2017 sont : (1) Absence de lien familial direct avec un dirigeant ou un actionnaire majoritaire. (2) Absence de contrat commercial avec l'entreprise (fournisseur, client, consultant) au cours des 2 dernières années. (3) Absence de rémunération autre que celle d'administrateur (pas de salaire, pas de bonus). (4) Absence de mandat dans une entreprise concurrente ou liée. (5) Détention d'actions inférieure à 5% du capital (pour éviter l'alignement excessif avec les actionnaires). Un administrateur doit satisfaire aux 5 critères pour être qualifié d'indépendant.",
      answerEn: "The 5 independence criteria for a director according to BCEAO Circular 01-2017 are: (1) No direct family relationship with a manager or majority shareholder. (2) No commercial contract with the company (supplier, customer, consultant) in the past 2 years. (3) No remuneration other than director's fees (no salary, no bonus). (4) No mandate in a competing or related company. (5) Shareholding below 5% of capital (to avoid excessive alignment with shareholders). A director must satisfy all 5 criteria to be qualified as independent.",
    },
    {
      question: "Quelle est la fréquence des réunions de Conseil d'Administration ?",
      questionEn: 'What is the frequency of Board of Directors meetings?',
      answer: "La Circulaire BCEAO 01-2017 impose un minimum de 3 réunions par an pour le Conseil d'Administration. Les bonnes pratiques internationales (OCDE, IFC) recommandent 4 à 6 réunions par an. Les banques sous surveillance renforcée peuvent tenir des réunions mensuelles. Les comités spécialisés doivent se réunir au minimum trimestriellement. Chaque réunion doit faire l'objet d'un PV détaillé, signé par tous les membres présents, et conservé pendant 10 ans. Les réunions peuvent être mixtes (présentiel + visioconférence).",
      answerEn: "BCEAO Circular 01-2017 imposes a minimum of 3 meetings per year for the Board of Directors. International best practices (OECD, IFC) recommend 4 to 6 meetings per year. Banks under enhanced supervision may hold monthly meetings. Specialized committees must meet at least quarterly. Each meeting must be the subject of detailed minutes, signed by all present members, and kept for 10 years. Meetings can be hybrid (in-person + video conference).",
    },
    {
      question: "Qu'est-ce que la politique de succession des dirigeants ?",
      questionEn: 'What is the management succession policy?',
      answer: "La politique de succession des dirigeants est un document stratégique qui définit les critères de remplacement du Directeur Général et des membres de la direction en cas de départ, de décès, d'incapacité ou de sanction. Elle comprend : (1) Identification des candidats potentiels (internes et externes). (2) Plan de développement des talents. (3) Processus de sélection et de nomination. (4) Période de transition et d'accompagnement. (5) Communication interne et externe. La Circulaire BCEAO 01-2017 impose l'élaboration de cette politique. Son absence est un red flag majeur pour les inspections.",
      answerEn: "The management succession policy is a strategic document that defines the criteria for replacing the CEO and management members in case of departure, death, incapacity or sanction. It includes: (1) Identification of potential candidates (internal and external). (2) Talent development plan. (3) Selection and nomination process. (4) Transition and support period. (5) Internal and external communication. BCEAO Circular 01-2017 mandates the development of this policy. Its absence is a major red flag for inspections.",
    },
    {
      question: "Quels sont les 10 documents fondamentaux de la gouvernance ?",
      questionEn: 'What are the 10 fundamental governance documents?',
      answer: "Les 10 documents fondamentaux de la gouvernance sont : (1) Statuts de la société. (2) Règlement intérieur du Conseil d'Administration. (3) Charte du Conseil d'Administration. (4) Politique de rémunération. (5) Politique de succession des dirigeants. (6) Politique de formation des administrateurs. (7) Procédure de gestion des conflits d'intérêts. (8) Manuel des comités spécialisés. (9) Code déontologique. (10) Politique de whistleblowing (lanceurs d'alerte). Ces documents sont exigés par les Circulaires BCEAO 01-2017 et 03-2017. Leur absence est un motif de sanction majeur.",
      answerEn: "The 10 fundamental governance documents are: (1) Company statutes. (2) Board of Directors internal regulations. (3) Board charter. (4) Remuneration policy. (5) Management succession policy. (6) Director training policy. (7) Conflict of interest management procedure. (8) Specialized committees manual. (9) Code of ethics. (10) Whistleblowing policy. These documents are required by BCEAO Circulars 01-2017 and 03-2017. Their absence is a major reason for sanction.",
    },
    {
      question: "Quel est le coût d'un renforcement de gouvernance par KHEPRA ?",
      questionEn: 'What is the cost of governance strengthening by KHEPRA?',
      answer: "Le coût d'un renforcement de gouvernance par KHEPRA varie selon la taille et la complexité : (1) PME non-financière (3-5 membres de CA) — 5 000€ à 12 000€, livrable en 4 semaines. (2) SFD/EMF (5-7 membres de CA, 1-2 comités) — 12 000€ à 25 000€, livrable en 6 semaines. (3) Banque de taille moyenne (7-9 membres, 3 comités) — 25 000€ à 50 000€, livrable en 8 semaines. (4) Grand groupe (9+ membres, comités internationaux) — 50 000€ à 100 000€, livrable en 12 semaines. Le forfait inclut : diagnostic, rédaction des documents, formation, recrutement d'administrateurs, accompagnement.",
      answerEn: "The cost of governance strengthening by KHEPRA varies by size and complexity: (1) Non-financial SME (3-5 board members) — €5,000 to €12,000, deliverable in 4 weeks. (2) MFI (5-7 board members, 1-2 committees) — €12,000 to €25,000, deliverable in 6 weeks. (3) Medium-sized bank (7-9 members, 3 committees) — €25,000 to €50,000, deliverable in 8 weeks. (4) Large group (9+ members, international committees) — €50,000 to €100,000, deliverable in 12 weeks. The package includes: diagnostic, document drafting, training, director recruitment, support.",
    },
    {
      question: "Qu'est-ce que l'évaluation du Conseil d'Administration ?",
      questionEn: 'What is the Board of Directors evaluation?',
      answer: "L'évaluation du Conseil d'Administration est un processus annuel (obligatoire selon la Circulaire BCEAO 01-2017) qui mesure l'efficacité du CA sur 5 dimensions : (1) Composition et diversité. (2) Fonctionnement et organisation. (3) Rôle et responsabilités. (4) Relations avec la direction. (5) Performance et résultats. L'évaluation peut être : (a) Self-assessment — questionnaire rempli par les administrateurs eux-mêmes. (b) Évaluation externe — menée par un consultant indépendant (KHEPRA). L'évaluation externe est recommandée tous les 3 ans. Les résultats sont portés au CA et servent à améliorer la gouvernance.",
      answerEn: "The Board of Directors evaluation is an annual process (mandatory according to BCEAO Circular 01-2017) that measures the effectiveness of the board across 5 dimensions: (1) Composition and diversity. (2) Functioning and organization. (3) Role and responsibilities. (4) Relations with management. (5) Performance and results. The evaluation can be: (a) Self-assessment — questionnaire completed by the directors themselves. (b) External evaluation — conducted by an independent consultant (KHEPRA). External evaluation is recommended every 3 years. Results are brought to the board and serve to improve governance.",
    },
    {
      question: "Comment gérer les conflits d'intérêts en Afrique ?",
      questionEn: 'How to manage conflicts of interest in Africa?',
      answer: "La gestion des conflits d'intérêts en Afrique repose sur 5 mécanismes : (1) Déclaration annuelle — chaque administrateur et dirigeant déclare ses intérêts au début de chaque exercice. (2) Registre des conflits — document centralisé tenu par le secrétaire du CA. (3) Abstention — l'administrateur concerné s'abstient de voter sur les sujets où il a un conflit. (4) Recusation — exclusion de la réunion pour les sujets sensibles. (5) Suivi — revue annuelle par le Comité d'Audit. La culture des réseaux familiaux et des conflits d'intérêts est forte en Afrique : un dispositif rigoureux est indispensable.",
      answerEn: "Conflict of interest management in Africa relies on 5 mechanisms: (1) Annual declaration — each director and manager declares their interests at the beginning of each fiscal year. (2) Conflict registry — centralized document maintained by the board secretary. (3) Abstention — the concerned director abstains from voting on subjects where they have a conflict. (4) Recusal — exclusion from the meeting for sensitive subjects. (5) Monitoring — annual review by the Audit Committee. The culture of family networks and conflicts of interest is strong in Africa: a rigorous framework is essential.",
    },
  ],
  internalLinks: [
    {
      label: 'Série Gouvernance Bancaire UEMOA — 5 articles',
      labelEn: 'UEMOA Banking Governance Series — 5 articles',
      href: '/blog/serie-gouvernance-bancaire-uemoa',
    },
    {
      label: 'Guide Gouvernance IMF — 120 points checklist',
      labelEn: 'MFI Governance Guide — 120-point checklist',
      href: '/guide-gouvernance-imf',
    },
    {
      label: 'Template Audit Gouvernance gratuit',
      labelEn: 'Free Governance Audit Template',
      href: '/lead-magnets/template-audit-gouvernance',
    },
    {
      label: 'Service Gouvernance d\'Entreprise — KHEPRA',
      labelEn: 'Corporate Governance Service — KHEPRA',
      href: '/services',
    },
    {
      label: 'Conformité BCEAO — Guide complet de mise en conformité',
      labelEn: 'BCEAO Compliance — Complete Compliance Guide',
      href: '/geo-hub/mise-en-conformite-bceao',
    },
    {
      label: 'Préparer une mission d\'inspection BCEAO — Checklist et simulation',
      labelEn: 'How to Prepare for a BCEAO Inspection Mission — Checklist and Simulation',
      href: '/geo-hub/preparer-mission-bceao',
    },
  ],
  ctaVariant: 'audit',
  ctaContextFr: 'Auditez votre gouvernance avec KHEPRA',
  ctaContextEn: 'Audit your governance with KHEPRA',
  peopleAlsoAsk: [
    {
      question: 'Quels sont les 3 comités obligatoires selon la Circulaire BCEAO 01-2017 ?',
      questionEn: 'What are the 3 mandatory committees according to BCEAO Circular 01-2017?',
      answer: 'Les 3 comités obligatoires pour les banques sont : (1) Comité d\'Audit (3-5 membres, supervision contrôle interne), (2) Comité des Risques (3-5 membres, supervision cartographie et crédit), (3) Comité de Nomination et Rémunération (3 membres, sélection dirigeants). Les SFD de petite taille doivent au minimum avoir un Comité d\'Audit.',
      answerEn: 'The 3 mandatory committees for banks are: (1) Audit Committee (3-5 members, internal control supervision), (2) Risk Committee (3-5 members, risk mapping and credit supervision), (3) Nomination and Remuneration Committee (3 members, manager selection). Small MFIs must at least have an Audit Committee.',
    },
    {
      question: "Quelle est la taille idéale d'un Conseil d'Administration en Afrique ?",
      questionEn: 'What is the ideal size of a Board of Directors in Africa?',
      answer: '5 à 9 membres pour une banque ou grande SFD, 3 à 5 pour une PME ou petite SFD. Un CA trop petit manque de diversité, un CA trop grand devient inefficace. Les bonnes pratiques OCDE/IFC recommandent 7 membres pour une banque moyenne, avec au minimum 1/3 d\'administrateurs indépendants.',
      answerEn: '5 to 9 members for a bank or large MFI, 3 to 5 for an SME or small MFI. A board too small lacks diversity, one too large becomes inefficient. OECD/IFC best practices recommend 7 members for a medium bank, with at least 1/3 independent directors.',
    },
    {
      question: "Quels sont les 5 critères d'indépendance d'un administrateur ?",
      questionEn: 'What are the 5 independence criteria for a director?',
      answer: 'Les 5 critères sont : (1) absence de lien familial direct avec un dirigeant, (2) absence de contrat commercial avec l\'entreprise sur les 2 dernières années, (3) absence de rémunération autre que celle d\'administrateur, (4) absence de mandat dans une entreprise concurrente, (5) détention d\'actions inférieure à 5% du capital.',
      answerEn: 'The 5 criteria are: (1) no direct family relationship with a manager, (2) no commercial contract with the company in the past 2 years, (3) no remuneration other than director fees, (4) no mandate in a competing company, (5) shareholding below 5% of capital.',
    },
    {
      question: 'Quels sont les 10 documents fondamentaux de la gouvernance ?',
      questionEn: 'What are the 10 fundamental governance documents?',
      answer: 'Les 10 documents sont : statuts, règlement intérieur du CA, charte du CA, politique de rémunération, politique de succession, politique de formation des administrateurs, procédure de gestion des conflits d\'intérêts, manuel des comités, code déontologique, politique de whistleblowing. Leur absence est un motif de sanction majeur.',
      answerEn: 'The 10 documents are: statutes, board internal regulations, board charter, remuneration policy, succession policy, director training policy, conflict of interest procedure, committees manual, code of ethics, whistleblowing policy. Their absence is a major reason for sanction.',
    },
    {
      question: 'Quel est le coût d\'un renforcement de gouvernance par KHEPRA ?',
      questionEn: 'What is the cost of governance strengthening by KHEPRA?',
      answer: 'Le coût varie : PME (3-5 membres) 5 000€-12 000€, SFD/EMF (5-7 membres) 12 000€-25 000€, banque moyenne (7-9 membres) 25 000€-50 000€, grand groupe (9+ membres) 50 000€-100 000€. Le forfait inclut diagnostic, rédaction des documents, formation, recrutement d\'administrateurs et accompagnement.',
      answerEn: 'Cost varies: SME (3-5 members) €5,000-€12,000, MFI (5-7 members) €12,000-€25,000, medium bank (7-9 members) €25,000-€50,000, large group (9+ members) €50,000-€100,000. The package includes diagnostic, document drafting, training, director recruitment and support.',
    },
    {
      question: 'Comment mettre en place un dispositif de whistleblowing (lanceurs d\'alerte) conforme aux exigences BCEAO/COBAC ?',
      questionEn: 'How to implement a whistleblowing mechanism compliant with BCEAO/COBAC requirements?',
      answer: 'Le dispositif de whistleblowing est obligatoire selon la Circulaire BCEAO 01-2017 et le Règlement COBAC R-2001/07. Il doit comprendre 7 éléments : (1) Canal de signalement sécurisé — ligne téléphonique dédiée, adresse email cryptée, plateforme web sécurisée, accessible 24/7 et anonyme si souhaité. (2) Politique de protection — garantie de non-représailles (licenciement, harcèlement, discrimination), confidentialité stricte de l\'identité. (3) Procédure de traitement — accusé de réception sous 48h, évaluation préliminaire sous 7 jours, enquête sous 30 jours, décision sous 45 jours. (4) Comité d\'éthique indépendant — composé de 3 membres (un administrateur indépendant, un responsable conformité, un expert externe). (5) Formation — sensibilisation annuelle de tous les employés, formation spécifique des managers. (6) Reporting — rapport annuel au CA et à la BCEAO/COBAC sur le nombre de signalements, la nature et les suites. (7) Sanctions — procédure disciplinaire en cas de fausse accusation malveillante. KHEPRA déploie des dispositifs clés en main.',
      answerEn: 'The whistleblowing mechanism is mandatory according to BCEAO Circular 01-2017 and COBAC Regulation R-2001/07. It must include 7 elements: (1) Secure reporting channel — dedicated phone line, encrypted email address, secure web platform, accessible 24/7 and anonymous if desired. (2) Protection policy — guarantee of non-retaliation (dismissal, harassment, discrimination), strict confidentiality of identity. (3) Processing procedure — acknowledgment within 48h, preliminary assessment within 7 days, investigation within 30 days, decision within 45 days. (4) Independent ethics committee — composed of 3 members (an independent director, a compliance officer, an external expert). (5) Training — annual awareness of all employees, specific manager training. (6) Reporting — annual report to the board and BCEAO/COBAC on the number of reports, nature and follow-up. (7) Sanctions — disciplinary procedure in case of malicious false accusation. KHEPRA deploys turnkey mechanisms.',
    },
    {
      question: 'Qu\'est-ce que la séparation des pouvoirs entre DG et PCA et comment l\'appliquer en Afrique ?',
      questionEn: 'What is the separation of powers between CEO and Board Chair and how to apply it in Africa?',
      answer: 'La séparation des pouvoirs entre Directeur Général (DG) et Président du Conseil d\'Administration (PCA) est un principe fondamental de gouvernance exigé par la Circulaire BCEAO 01-2017. Le cumul est interdit pour les banques et grandes SFD. Rôles : (1) DG — responsable de la gestion opérationnelle, exécute la stratégie validée par le CA, représente l\'institution auprès des tiers, nomme les cadres dirigeants. (2) PCA — préside le CA, organise les réunions, fixe l\'ordre du jour, veille au bon fonctionnement des comités, supervise la performance du DG, organise l\'évaluation annuelle du DG. En Afrique, la séparation est souvent difficile dans les entreprises familiales où le fondateur cumule les deux rôles. Solutions : nomination d\'un PCA non-exécutif (administrateur indépendant), ou nomination d\'un DG délégué aux côtés du PCA-DG. KHEPRA accompagne les transitions de gouvernance avec un plan de séparation sur 12 mois.',
      answerEn: 'The separation of powers between CEO and Board Chair is a fundamental governance principle required by BCEAO Circular 01-2017. Cumulation is prohibited for banks and large MFIs. Roles: (1) CEO — responsible for operational management, executes the strategy validated by the board, represents the institution to third parties, appoints senior managers. (2) Board Chair — chairs the board, organizes meetings, sets the agenda, ensures proper functioning of committees, supervises the CEO\'s performance, organizes the annual CEO evaluation. In Africa, separation is often difficult in family businesses where the founder cumulates both roles. Solutions: appointment of a non-executive Board Chair (independent director), or appointment of a Deputy CEO alongside the CEO-Board Chair. KHEPRA supports governance transitions with a 12-month separation plan.',
    },
    {
      question: 'Comment les entreprises familiales africaines peuvent-elles professionnaliser leur gouvernance ?',
      questionEn: 'How can African family businesses professionalize their governance?',
      answer: 'La professionnalisation de la gouvernance des entreprises familiales africaines passe par 6 leviers : (1) Conseil de famille — instance parallèle au CA pour gérer les relations familiales, la transmission, et séparer le patrimoine familial de l\'entreprise. (2) Charte familiale — document formalisant les valeurs, la vision, les règles de recrutement des membres de la famille, la politique de dividendes. (3) Administrateurs indépendants — recrutement de 1 à 3 administrateurs non familiaux pour apporter une expertise externe et objectiver les décisions. (4) Comité stratégique — ouvert à des experts externes (banquiers, consultants, partenaires) pour challenger la stratégie. (5) Plan de succession — écrit, approuvé par le conseil de famille, avec un calendrier de transition. (6) Audit externe — certification des comptes par un cabinet international pour rassurer les banques et partenaires. KHEPRA a accompagné 30+ entreprises familiales dans leur professionnalisation.',
      answerEn: 'Professionalizing the governance of African family businesses goes through 6 levers: (1) Family council — parallel body to the board to manage family relations, transmission, and separate family wealth from the company. (2) Family charter — document formalizing values, vision, rules for recruiting family members, dividend policy. (3) Independent directors — recruitment of 1 to 3 non-family directors to bring external expertise and objectify decisions. (4) Strategic committee — open to external experts (bankers, consultants, partners) to challenge strategy. (5) Succession plan — written, approved by the family council, with a transition timeline. (6) External audit — certification of accounts by an international firm to reassure banks and partners. KHEPRA has supported 30+ family businesses in their professionalization.',
    },
    {
      question: 'Quels sont les indicateurs de performance du Conseil d\'Administration (Board KPIs) ?',
      questionEn: 'What are the Board of Directors performance indicators (Board KPIs)?',
      answer: 'Les 10 KPI d\'un Conseil d\'Administration performant sont : (1) Taux de présence aux réunions — minimum 80% par administrateur. (2) Nombre de réunions par an — 4 à 6, avec un taux de tenue > 90%. (3) Délai de diffusion des PV — maximum 15 jours après la réunion. (4) Nombre de décisions stratégiques prises par an — mesures et suivi. (5) Diversité du CA — % de femmes (objectif 30%), % d\'indépendants (33%), diversité sectorielle et géographique. (6) Nombre de formations suivies par administrateur — minimum 1 par an. (7) Nombre de conflits d\'intérêts déclarés et traités. (8) Taux de rotation des administrateurs — idéalement 10-20% par an (renouvellement sans instabilité). (9) Score d\'évaluation du CA — sur 100, objectif > 75. (10) Taux de conformité aux circulaires BCEAO — 100%. KHEPRA met en place un tableau de bord de gouvernance avec ces 10 KPI.',
      answerEn: 'The 10 KPIs of a high-performing Board of Directors are: (1) Meeting attendance rate — minimum 80% per director. (2) Number of meetings per year — 4 to 6, with a holding rate > 90%. (3) Minutes distribution delay — maximum 15 days after the meeting. (4) Number of strategic decisions taken per year — measured and monitored. (5) Board diversity — % women (target 30%), % independents (33%), sector and geographic diversity. (6) Number of trainings attended per director — minimum 1 per year. (7) Number of declared and handled conflicts of interest. (8) Director turnover rate — ideally 10-20% per year (renewal without instability). (9) Board evaluation score — out of 100, target > 75. (10) BCEAO circular compliance rate — 100%. KHEPRA implements a governance dashboard with these 10 KPIs.',
    },
    {
      question: 'Comment la gouvernance ESG s\'intègre-t-elle dans le CA ? Le rôle du Comité ESG.',
      questionEn: 'How does ESG governance integrate into the board? The role of the ESG Committee.',
      answer: 'L\'intégration de la gouvernance ESG au CA se fait via la création d\'un Comité ESG (ou extension du Comité des Risques). Son rôle comprend 6 missions : (1) Définir la stratégie ESG — objectifs carbone, inclusion financière, diversité, alignés sur les standards IFC/GRI/ISSB. (2) Superviser le score ESG — suivi trimestriel, identification des zones de faiblesse. (3) Valider le rapport ESG annuel — avant publication, vérification des données. (4) Veille réglementaire — anticipation des nouvelles normes (taxonomie verte, CSRD européenne applicable aux filiales africaines de groupes européens). (5) Dialogue avec les parties prenantes — investisseurs, régulateurs, communautés. (6) Intégration dans la rémunération — définition des KPI ESG liés aux bonus des dirigeants. Le Comité ESG doit inclure au moins un administrateur expert en durabilité. KHEPRA forme les administrateurs aux enjeux ESG et structure le Comité ESG.',
      answerEn: 'ESG governance integration into the board is done through the creation of an ESG Committee (or extension of the Risk Committee). Its role includes 6 missions: (1) Define ESG strategy — carbon targets, financial inclusion, diversity, aligned with IFC/GRI/ISSB standards. (2) Supervise the ESG score — quarterly monitoring, identification of weakness areas. (3) Validate the annual ESG report — before publication, data verification. (4) Regulatory watch — anticipation of new standards (green taxonomy, European CSRD applicable to African subsidiaries of European groups). (5) Stakeholder dialogue — investors, regulators, communities. (6) Integration into remuneration — definition of ESG KPIs linked to executive bonuses. The ESG Committee must include at least one director with sustainability expertise. KHEPRA trains directors on ESG issues and structures the ESG Committee.',
    },
    {
      question: 'Qu\'est-ce que la gouvernance des données (Data Governance) et pourquoi est-elle critique pour les banques africaines ?',
      questionEn: 'What is Data Governance and why is it critical for African banks?',
      answer: 'La gouvernance des données est le cadre qui régit la collecte, le stockage, la qualité, la sécurité et l\'utilisation des données dans une organisation. Pour les banques africaines, elle est devenue critique pour 5 raisons : (1) Conformité BCEAO — les reportings SURFI et les inspections exigent des données fiables et traçables. (2) IFRS 9 — le provisionnement prospectif (ECL) nécessite des modèles statistiques alimentés par des données de qualité sur 5-7 ans. (3) Bâle III — les calculs d\'actifs pondérés (RWA) exigent une granularité fine des données de crédit. (4) LBC/FT — le KYC et la surveillance des transactions reposent sur des données clients à jour. (5) Cybersécurité — la protection des données clients est une exigence réglementaire (lois nationales, RGPD pour les données européennes). Un Chief Data Officer (CDO) doit être nommé, rattaché à la direction générale ou au CA. KHEPRA audite la maturité Data Governance et propose un plan de convergence.',
      answerEn: 'Data governance is the framework governing the collection, storage, quality, security and use of data in an organization. For African banks, it has become critical for 5 reasons: (1) BCEAO compliance — SURFI reporting and inspections require reliable and traceable data. (2) IFRS 9 — prospective provisioning (ECL) requires statistical models fed by quality data over 5-7 years. (3) Basel III — risk-weighted asset calculations require fine granularity of credit data. (4) AML/CFT — KYC and transaction monitoring rely on up-to-date customer data. (5) Cybersecurity — customer data protection is a regulatory requirement (national laws, GDPR for European data). A Chief Data Officer (CDO) must be appointed, reporting to general management or the board. KHEPRA audits Data Governance maturity and proposes a convergence plan.',
    },
    {
      question: 'Comment organiser une Assemblée Générale conforme aux exigences OHADA et BCEAO ?',
      questionEn: 'How to organize a General Assembly compliant with OHADA and BCEAO requirements?',
      answer: 'L\'organisation d\'une Assemblée Générale (AG) conforme OHADA et BCEAO suit 7 étapes : (1) Convocation — 30 jours avant l\'AG (SA) ou 15 jours (SARL), par lettre recommandée ou insertion dans un journal d\'annonces légales. (2) Ordre du jour — fixé par le CA, doit inclure l\'approbation des comptes, l\'affectation du résultat, le renouvellement des mandats, les conventions réglementées. (3) Documents mis à disposition — états financiers, rapport de gestion, rapport du commissaire aux comptes, rapport ESG, texte des résolutions. (4) Quorum — pour les SA, 25% du capital pour la première convocation, aucun quorum pour la seconde. (5) Vote — les résolutions sont adoptées à la majorité simple (SA) ou selon les statuts (SARL). (6) PV — rédigé dans les 15 jours, signé par le Président et le scrutateur, conservé 10 ans. (7) Publication — les résolutions sociales doivent être déposées au registre de commerce et publiées dans un journal d\'annonces légales. Pour les banques, le rapport de l\'AG est transmis à la BCEAO. KHEPRA assiste les CA dans la préparation des AG.',
      answerEn: 'Organizing a General Assembly compliant with OHADA and BCEAO follows 7 steps: (1) Convocation — 30 days before the GA (SA) or 15 days (SARL), by registered letter or insertion in a legal announcements journal. (2) Agenda — set by the board, must include approval of accounts, allocation of results, renewal of mandates, regulated agreements. (3) Documents made available — financial statements, management report, auditor\'s report, ESG report, text of resolutions. (4) Quorum — for SAs, 25% of capital for the first convocation, no quorum for the second. (5) Vote — resolutions are adopted by simple majority (SA) or according to statutes (SARL). (6) Minutes — drafted within 15 days, signed by the Chair and scrutinizer, kept for 10 years. (7) Publication — corporate resolutions must be filed with the trade register and published in a legal announcements journal. For banks, the GA report is transmitted to BCEAO. KHEPRA assists boards in preparing GAs.',
    },
    {
      question: 'Qu\'est-ce que le dispositif de contrôle interne selon le COSO et comment l\'appliquer en Afrique ?',
      questionEn: 'What is the COSO internal control framework and how to apply it in Africa?',
      answer: 'Le COSO (Committee of Sponsoring Organizations) définit le contrôle interne en 5 composantes interconnectées : (1) Environnement de contrôle — culture éthique, intégrité, compétence, philosophie de gestion, structure organisationnelle. (2) Évaluation des risques — identification, analyse et gestion des risques liés aux objectifs. (3) Activités de contrôle — procédures et politiques pour atténuer les risques (approbations, autorisations, vérifications, rapprochements, séparation des tâches). (4) Information et communication — circulation de l\'information pertinente, ascendante et descendante, interne et externe. (5) Pilotage — évaluation continue du dispositif, audits internes, remontée des défaillances. En Afrique, le COSO est le référentiel exigé par la BCEAO (Circulaire 03-2017) et la COBAC. Son application doit être adaptée : les PME africaines peuvent simplifier (COSO Light), les banques doivent appliquer le COSO intégral. KHEPRA déploie des dispositifs COSO conformes avec des matrices de contrôle et des plans de remédiation.',
      answerEn: 'COSO (Committee of Sponsoring Organizations) defines internal control in 5 interconnected components: (1) Control environment — ethical culture, integrity, competence, management philosophy, organizational structure. (2) Risk assessment — identification, analysis and management of risks related to objectives. (3) Control activities — procedures and policies to mitigate risks (approvals, authorizations, verifications, reconciliations, segregation of duties). (4) Information and communication — circulation of relevant information, upward and downward, internal and external. (5) Monitoring — continuous evaluation of the framework, internal audits, escalation of failures. In Africa, COSO is the framework required by BCEAO (Circular 03-2017) and COBAC. Its application must be adapted: African SMEs can simplify (COSO Light), banks must apply full COSO. KHEPRA deploys compliant COSO frameworks with control matrices and remediation plans.',
    },
    {
      question: 'Comment recruter des administrateurs indépendants de qualité en Afrique ?',
      questionEn: 'How to recruit quality independent directors in Africa?',
      answer: 'Le recrutement d\'administrateurs indépendants en Afrique suit une méthodologie rigoureuse en 6 étapes : (1) Définition du profil — compétences recherchées (finance, risques, IT, secteur, international), critères d\'indépendance (5 critères BCEAO), temps disponible (20-30 jours/an). (2) Sourcing — bases de données (IFC Board Database, Institut Français des Administrateurs, African Corporate Governance Network), chasseurs de têtes, réseaux professionnels, recommandations de partenaires. (3) Due diligence — vérification du casier judiciaire, des mandats existants (pas plus de 3 mandats simultanés), de la réputation, des conflits d\'intérêts potentiels. (4) Entretiens — avec le Comité de Nomination, le PCA, le DG, et les autres administrateurs. (5) Intégration — programme d\'onboarding de 3 mois : immersion dans l\'entreprise, formation à la réglementation BCEAO/OHADA, rencontre des équipes. (6) Évaluation — après 1 an, évaluation de la contribution de l\'administrateur. KHEPRA dispose d\'un vivier de 200+ administrateurs certifiés en Afrique.',
      answerEn: 'Recruiting independent directors in Africa follows a rigorous methodology in 6 steps: (1) Profile definition — sought skills (finance, risk, IT, sector, international), independence criteria (5 BCEAO criteria), available time (20-30 days/year). (2) Sourcing — databases (IFC Board Database, French Institute of Directors, African Corporate Governance Network), headhunters, professional networks, partner recommendations. (3) Due diligence — criminal record verification, existing mandates (no more than 3 simultaneous mandates), reputation, potential conflicts of interest. (4) Interviews — with the Nomination Committee, Board Chair, CEO, and other directors. (5) Integration — 3-month onboarding program: immersion in the company, training in BCEAO/OHADA regulation, meeting teams. (6) Evaluation — after 1 year, evaluation of the director\'s contribution. KHEPRA has a pool of 200+ certified directors in Africa.',
    },
    {
      question: 'Quelle est la responsabilité juridique des administrateurs en cas de faillite d\'une banque en zone UEMOA ?',
      questionEn: 'What is the legal liability of directors in case of bank failure in the WAEMU zone?',
      answer: 'La responsabilité des administrateurs en cas de faillite bancaire en zone UEMOA est régie par l\'Acte Uniforme OHADA et les Circulaires BCEAO : (1) Responsabilité civile — les administrateurs peuvent être poursuivis pour faute de gestion (négligence, décision imprudente, absence de surveillance) ayant contribué à la faillite. Ils peuvent être condamnés à combler le passif sur leurs biens personnels. (2) Responsabilité pénale — en cas de fraude (faux bilans, distribution de dividendes fictifs, abus de biens sociaux, corruption), les administrateurs encourent des peines d\'emprisonnement (1 à 5 ans) et des amendes. (3) Sanctions administratives BCEAO — interdiction d\'exercer des fonctions de direction ou d\'administration dans toute institution financière UEMOA, amende jusqu\'à 500M FCFA. (4) Assurance — les banques doivent souscrire une assurance responsabilité civile des administrateurs (D&O Insurance). (5) Business Judgment Rule — les décisions prises de bonne foi, sur la base d\'informations adéquates, et dans l\'intérêt de l\'entreprise, sont protégées. KHEPRA sensibilise les administrateurs à leurs responsabilités.',
      answerEn: 'The liability of directors in case of bank failure in the WAEMU zone is governed by the OHADA Uniform Act and BCEAO Circulars: (1) Civil liability — directors can be sued for mismanagement (negligence, imprudent decision, lack of oversight) contributing to the failure. They can be ordered to cover the deficit from their personal assets. (2) Criminal liability — in case of fraud (false balance sheets, distribution of fictitious dividends, misuse of corporate assets, corruption), directors face prison sentences (1 to 5 years) and fines. (3) BCEAO administrative sanctions — prohibition from exercising management or administration functions in any WAEMU financial institution, fine up to 500M FCFA. (4) Insurance — banks must take out Directors & Officers (D&O) liability insurance. (5) Business Judgment Rule — decisions taken in good faith, on the basis of adequate information, and in the company\'s interest are protected. KHEPRA raises awareness among directors about their responsibilities.',
    },
  ],
};