import type { DiagnosticToolConfig } from '../components/types';
import { ROADMAP_AXES, getRoadmapScoreColor, getRoadmapScoreLabel, getRoadmapLevel, getRoadmapReadiness, getRoadmapRisks, getRoadmapRecommendations } from './data';
const FORM_URL='https://readdy.ai/api/form/d8pg2pnij7vns5otj9kg'; const PRIMARY='#7c3aed';
export const roadmapConfig: DiagnosticToolConfig = {
  toolId:'generateur-roadmap-innovation',toolNameFr:'Générateur Roadmap Innovation KHEPRA™',toolNameEn:'Innovation Roadmap Generator KHEPRA™',
  toolSubtitleFr:'Évaluez votre capacité d\'innovation sur 4 phases : idéation, expérimentation, incubation et industrialisation.',toolSubtitleEn:'Assess your innovation capability across 4 phases: ideation, experimentation, incubation and industrialization.',
  seoTitleFr:'Générateur Roadmap Innovation | KHEPRA EXPERTS',seoTitleEn:'Innovation Roadmap Generator | KHEPRA EXPERTS',
  seoDescriptionFr:'Évaluez votre capacité d\'innovation et générez une roadmap personnalisée : idéation, expérimentation, incubation, industrialisation.',seoDescriptionEn:'Assess your innovation capability and generate a personalized roadmap: ideation, experimentation, incubation, industrialization.',
  seoKeywordsFr:'roadmap innovation, gestion innovation, culture innovation, R&D, transformation, Afrique',seoKeywordsEn:'innovation roadmap, innovation management, innovation culture, R&D, transformation, Africa',
  canonicalPath:'/tools/generateur-roadmap-innovation',axes:ROADMAP_AXES,
  howToNameFr:'Générateur Roadmap Innovation KHEPRA™',howToNameEn:'Innovation Roadmap Generator KHEPRA™',
  howToDescriptionFr:'Évaluez votre capacité d\'innovation sur 4 phases : idéation et exploration, expérimentation et prototypage, incubation et développement, industrialisation et scaling.',howToDescriptionEn:'Assess your innovation capability across 4 phases: ideation & exploration, experimentation & prototyping, incubation & development, industrialization & scaling.',
  howToTotalTime:'6M',howToSteps:ROADMAP_AXES.map(a=>({name:a.titleFr,text:a.descriptionFr})),
  getScoreColor:getRoadmapScoreColor,getScoreLabel:getRoadmapScoreLabel,getMaturityLevel:getRoadmapLevel,getReadinessIndicator:getRoadmapReadiness,
  getRisks:(pa,gs,l)=>getRoadmapRisks(pa,gs,l),getRecommendations:(pa,gs,l)=>getRoadmapRecommendations(pa,gs,l),
  getOptionStyle:(v,s)=>{if(v===100)return s?'border-emerald-500 bg-emerald-50':'border-secondary-200 hover:border-emerald-300';if(v===60)return s?'border-sky-500 bg-sky-50':'border-secondary-200 hover:border-sky-300';if(v===25)return s?'border-accent-500 bg-accent-50':'border-secondary-200 hover:border-accent-300';return s?'border-red-500 bg-red-50':'border-secondary-200 hover:border-red-300';},
  getOptionIcon:(v)=>{if(v===100)return'ri-check-double-line';if(v===60)return'ri-check-line';if(v===25)return'ri-subtract-line';return'ri-close-line';},
  getOptionColor:(v)=>{if(v===100)return'text-emerald-600';if(v===60)return'text-sky-600';if(v===25)return'text-accent-600';return'text-red-600';},
  showLeadForm:true,formUrl:FORM_URL,hashtags:['Innovation','Roadmap','R&D','Strategie'],
  showRadarChart:true,renderRadarChart:(s,pa,ax,fr)=>{const c=s/2,rad=100,ac=ax.length,as=(2*Math.PI)/ac,sa=-Math.PI/2,gp=(i:number,v:number)=>{const a=sa+i*as,r=(v/100)*rad;return{x:c+r*Math.cos(a),y:c+r*Math.sin(a)};};return(<svg width={s} height={s} viewBox={`0 0 ${s} ${s}`} className="mx-auto">{[20,40,60,80,100].map(lv=>{const ps=ax.map((_,i)=>{const p=gp(i,lv);return`${p.x},${p.y}`}).join(' ');return<polygon key={lv} points={ps} fill="none" stroke="#e5e7eb" strokeWidth="1"/>})}{ax.map((_,i)=>{const e=gp(i,100);return<line key={i} x1={c} y1={c} x2={e.x} y2={e.y} stroke="#e5e7eb" strokeWidth="1"/>})}{(()=>{const dp=ax.map((a,i)=>gp(i,pa[a.id]??0)),ps=dp.map(p=>`${p.x},${p.y}`).join(' ');return(<><polygon points={ps} fill="rgba(124,58,237,0.15)" stroke={PRIMARY} strokeWidth="2"/>{dp.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="5" fill={PRIMARY} stroke="white" strokeWidth="2"/>)}</>)})()}{ax.map((a,i)=>{const lp=gp(i,125),w=(fr?a.titleFr:a.titleEn).split(' '),lb=w.length>2?w.slice(0,2).join(' '):w.join(' ');return<text key={i} x={lp.x} y={lp.y} textAnchor="middle" dominantBaseline="middle" fontSize="9" fontWeight="600" fill="#374151">{lb}</text>})}</svg>)},
  badgeIcon:'ri-road-map-line',badgeTextFr:'4 phases · 6 questions · 6 min',badgeTextEn:'4 phases · 6 questions · 6 min',
  expertCTA:{titleFr:'Besoin d\'accélérer votre pipeline d\'innovation ?',titleEn:'Need to accelerate your innovation pipeline?',descriptionFr:'Nos experts vous aident à structurer votre démarche d\'innovation et à industrialiser vos projets.',descriptionEn:'Our experts help you structure your innovation approach and industrialize your projects.',ctaFr:'Planifier un rendez-vous',ctaEn:'Schedule a meeting',ctaLink:'/contact'},
};