import type { DiagnosticAxisConfig } from '../components/types';

export const ROADMAP_AXES: DiagnosticAxisConfig[] = [
  { id: 'ideation', titleFr: 'Idéation & Exploration', titleEn: 'Ideation & Exploration', descriptionFr: 'Génération d\'idées, veille, prospective, culture innovation', descriptionEn: 'Idea generation, monitoring, foresight, innovation culture', icon: 'ri-lightbulb-flash-line', color: '#7c3aed', weight: 25, questions: [
    { id: 'rm-ie-1', questionFr: 'Disposez-vous d\'un processus structuré de génération et de capture d\'idées innovantes (collaborateurs, clients, partenaires) ?', questionEn: 'Do you have a structured process for generating and capturing innovative ideas (employees, clients, partners)?', options: [{ value: 100, labelFr: 'Plateforme d\'innovation ouverte, hackathons, boîte à idées digitale, processus de sélection documenté', labelEn: 'Open innovation platform, hackathons, digital idea box, documented selection process' }, { value: 60, labelFr: 'Processus informel de collecte d\'idées, quelques initiatives ponctuelles', labelEn: 'Informal idea collection process, some ad hoc initiatives' }, { value: 25, labelFr: 'Idées capturées de manière anecdotique, pas de processus', labelEn: 'Ideas captured anecdotally, no process' }, { value: 0, labelFr: 'Aucune démarche de capture d\'idées, innovation inexistante', labelEn: 'No idea capture approach, non-existent innovation' }] },
    { id: 'rm-ie-2', questionFr: 'Réalisez-vous une veille technologique et concurrentielle systématique pour identifier les opportunités d\'innovation ?', questionEn: 'Do you conduct systematic technology and competitive monitoring to identify innovation opportunities?', options: [{ value: 100, labelFr: 'Veille structurée multi-sources, analyses trimestrielles, diffusion aux décideurs, influence sur la roadmap', labelEn: 'Structured multi-source monitoring, quarterly analyses, distributed to decision-makers, roadmap influence' }, { value: 60, labelFr: 'Veille partielle, certaines sources suivies, diffusion limitée', labelEn: 'Partial monitoring, some sources tracked, limited distribution' }, { value: 25, labelFr: 'Veille passive, pas de processus formalisé', labelEn: 'Passive monitoring, no formalized process' }, { value: 0, labelFr: 'Aucune veille, l\'organisation ignore les tendances de son secteur', labelEn: 'No monitoring, the organization ignores sector trends' }] },
  ]},
  { id: 'experimentation', titleFr: 'Expérimentation & Prototypage', titleEn: 'Experimentation & Prototyping', descriptionFr: 'POC, MVP, tests utilisateurs, itération rapide, gestion de l\'échec', descriptionEn: 'POC, MVP, user testing, rapid iteration, failure management', icon: 'ri-test-tube-line', color: '#0ea5e9', weight: 25, questions: [
    { id: 'rm-ep-1', questionFr: 'Avez-vous une capacité à prototyper rapidement (POC, MVP) et à tester vos idées auprès des utilisateurs ?', questionEn: 'Do you have the ability to rapidly prototype (POC, MVP) and test your ideas with users?', options: [{ value: 100, labelFr: 'Lab d\'innovation équipé, équipe dédiée, cycles de prototypage < 4 semaines, tests utilisateurs systématiques avec métriques', labelEn: 'Equipped innovation lab, dedicated team, prototyping cycles < 4 weeks, systematic user testing with metrics' }, { value: 60, labelFr: 'Capacité de prototypage existante mais non structurée, tests utilisateurs ponctuels', labelEn: 'Prototyping capability exists but unstructured, occasional user testing' }, { value: 25, labelFr: 'Prototypage lent et bureaucratique, pas de tests utilisateurs', labelEn: 'Slow and bureaucratic prototyping, no user testing' }, { value: 0, labelFr: 'Aucune capacité de prototypage, les idées restent théoriques', labelEn: 'No prototyping capability, ideas remain theoretical' }] },
  ]},
  { id: 'incubation', titleFr: 'Incubation & Développement', titleEn: 'Incubation & Development', descriptionFr: 'Allocation ressources, équipe, budget, gouvernance innovation, KPI', descriptionEn: 'Resource allocation, team, budget, innovation governance, KPIs', icon: 'ri-seedling-line', color: '#059669', weight: 25, questions: [
    { id: 'rm-id-1', questionFr: 'Allouez-vous des ressources dédiées (budget, équipe, temps) aux projets d\'innovation ?', questionEn: 'Do you allocate dedicated resources (budget, team, time) to innovation projects?', options: [{ value: 100, labelFr: 'Budget innovation > 3% du CA, équipe dédiée, temps protégé (20% rule), portefeuille de projets suivi', labelEn: 'Innovation budget > 3% revenue, dedicated team, protected time (20% rule), tracked project portfolio' }, { value: 60, labelFr: 'Budget < 3% du CA, équipe partiellement dédiée, projets prioritaires mais pas de portefeuille structuré', labelEn: 'Budget < 3% revenue, partially dedicated team, priority projects but no structured portfolio' }, { value: 25, labelFr: 'Pas de budget dédié, innovation faite "sur le temps restant"', labelEn: 'No dedicated budget, innovation done "on leftover time"' }, { value: 0, labelFr: 'Aucune ressource allouée, l\'innovation n\'est pas une priorité', labelEn: 'No resources allocated, innovation is not a priority' }] },
    { id: 'rm-id-2', questionFr: 'Disposez-vous d\'un processus de stage-gate ou d\'un cadre de gouvernance de l\'innovation ?', questionEn: 'Do you have a stage-gate process or innovation governance framework?', options: [{ value: 100, labelFr: 'Processus stage-gate documenté, comité d\'innovation trimestriel, critères go/no-go clairs, KPI innovation suivis', labelEn: 'Documented stage-gate process, quarterly innovation committee, clear go/no-go criteria, tracked innovation KPIs' }, { value: 60, labelFr: 'Processus défini mais informel, comité ponctuel, critères de décision subjectifs', labelEn: 'Process defined but informal, ad hoc committee, subjective decision criteria' }, { value: 25, labelFr: 'Pas de processus formalisé, décisions ad hoc', labelEn: 'No formalized process, ad hoc decisions' }, { value: 0, labelFr: 'Aucune gouvernance de l\'innovation, projets lancés et arrêtés sans cadre', labelEn: 'No innovation governance, projects started and stopped without framework' }] },
  ]},
  { id: 'industrialisation', titleFr: 'Industrialisation & Scaling', titleEn: 'Industrialization & Scaling', descriptionFr: 'Mise à l\'échelle, intégration, ROI, partenariats, écosystème', descriptionEn: 'Scaling, integration, ROI, partnerships, ecosystem', icon: 'ri-rocket-2-line', color: '#d97706', weight: 25, questions: [
    { id: 'rm-is-1', questionFr: 'Avez-vous déjà industrialisé avec succès une innovation (passage du POC à la production à l\'échelle) ?', questionEn: 'Have you successfully industrialized an innovation (POC to production at scale)?', options: [{ value: 100, labelFr: 'Plusieurs innovations industrialisées avec ROI mesuré, processus de scaling documenté, équipe de déploiement', labelEn: 'Several innovations industrialized with measured ROI, documented scaling process, deployment team' }, { value: 60, labelFr: 'Une innovation industrialisée, ROI partiellement mesuré, processus de scaling en cours de formalisation', labelEn: 'One innovation industrialized, partially measured ROI, scaling process being formalized' }, { value: 25, labelFr: 'POC réalisés mais aucune industrialisation réussie', labelEn: 'POCs completed but no successful industrialization' }, { value: 0, labelFr: 'Aucune innovation n\'a dépassé le stade de l\'idée', labelEn: 'No innovation has passed the idea stage' }] },
  ]},
];

export function getRoadmapScoreColor(s: number): string { if (s >= 80) return '#059669'; if (s >= 60) return '#0ea5e9'; if (s >= 40) return '#d97706'; return '#dc2626'; }
export function getRoadmapScoreLabel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Innovation Systematique':'Systematic Innovation'; if (s>=60) return f?'Innovation Structurée':'Structured Innovation'; if (s>=40) return f?'Innovation Émergente':'Emerging Innovation'; return f?'Innovation Absente':'Absent Innovation'; }
export function getRoadmapLevel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Niveau 4 — Innovation Factory':'Level 4 — Innovation Factory'; if (s>=60) return f?'Niveau 3 — Innovation Builder':'Level 3 — Innovation Builder'; if (s>=40) return f?'Niveau 2 — Innovation Explorer':'Level 2 — Innovation Explorer'; return f?'Niveau 1 — Innovation Starter':'Level 1 — Innovation Starter'; }
export function getRoadmapReadiness(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Votre organisation a construit une véritable usine à innovation. Continuez à alimenter le pipeline et à industrialiser les projets les plus prometteurs.':'Your organization has built a true innovation factory. Continue feeding the pipeline and industrializing the most promising projects.'; if (s>=60) return f?'Votre démarche d\'innovation est structurée. Renforcez l\'industrialisation et la mesure du ROI pour passer au niveau supérieur.':'Your innovation approach is structured. Strengthen industrialization and ROI measurement to reach the next level.'; if (s>=40) return f?'Votre innovation est émergente. Formalisez vos processus, allouez des ressources dédiées et créez une culture d\'expérimentation.':'Your innovation is emerging. Formalize your processes, allocate dedicated resources and create an experimentation culture.'; return f?'L\'innovation n\'est pas une priorité dans votre organisation. Commencez par mettre en place une veille et un processus simple de capture d\'idées.':'Innovation is not a priority in your organization. Start by setting up monitoring and a simple idea capture process.'; }

export function getRoadmapRisks(pa: Record<string,number>, gs: number, lang: string): string[] {
  const f=!lang.startsWith('en'); const r:string[]=[];
  if ((pa['ideation']??0)<50) r.push(f?'RISQUE MAJEUR — Absence de culture d\'innovation : pas de processus de capture d\'idées, pas de veille — l\'organisation stagne':'MAJOR RISK — No innovation culture: no idea capture process, no monitoring — the organization stagnates');
  if ((pa['experimentation']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Incapacité à prototyper : les idées restent théoriques, pas de tests utilisateurs — retard face aux concurrents qui innovent':'HIGH RISK — Inability to prototype: ideas remain theoretical, no user testing — lag behind innovating competitors');
  if ((pa['incubation']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Sous-investissement en innovation : pas de budget, pas d\'équipe — l\'innovation est étouffée avant de naître':'HIGH RISK — Under-investment in innovation: no budget, no team — innovation is stifled before birth');
  if ((pa['industrialisation']??0)<50) r.push(f?'RISQUE MAJEUR — Incapacité à scaler : les POC ne deviennent jamais des produits — ROI nul sur l\'innovation':'MAJOR RISK — Inability to scale: POCs never become products — zero ROI on innovation');
  return r;
}

export function getRoadmapRecommendations(pa: Record<string,number>, gs: number, lang: string): {title:string;axis?:string;items:string[]}[] {
  const f=!lang.startsWith('en'); const recs:{title:string;axis?:string;items:string[]}[]=[];
  if ((pa['ideation']??0)<60) recs.push({title:f?'Stimuler l\'Idéation':'Stimulate Ideation',axis:'ideation',items:f?['Mettre en place une plateforme de capture d\'idées ouverte à tous les collaborateurs','Organiser des hackathons ou challenges d\'innovation trimestriels','Structurer une veille technologique et concurrentielle systématique']:['Set up an idea capture platform open to all employees','Organize quarterly hackathons or innovation challenges','Structure systematic technology and competitive monitoring']});
  if ((pa['experimentation']??0)<60) recs.push({title:f?'Accélérer l\'Expérimentation':'Accelerate Experimentation',axis:'experimentation',items:f?['Créer un lab d\'innovation avec des cycles de prototypage rapide (< 4 semaines)','Systématiser les tests utilisateurs avec des métriques de succès','Instaurer un droit à l\'erreur et célébrer les apprentissages']:['Create an innovation lab with rapid prototyping cycles (< 4 weeks)','Systematize user testing with success metrics','Institute a right to fail and celebrate learnings']});
  if ((pa['incubation']??0)<60) recs.push({title:f?'Investir dans l\'Incubation':'Invest in Incubation',axis:'incubation',items:f?['Allouer un budget dédié (>3% du CA) et constituer une équipe innovation','Mettre en place un processus stage-gate avec comité d\'innovation','Définir des KPI innovation (nombre de POC, taux de conversion, ROI)']:['Allocate dedicated budget (>3% revenue) and build an innovation team','Implement a stage-gate process with innovation committee','Define innovation KPIs (POC count, conversion rate, ROI)']});
  if ((pa['industrialisation']??0)<60) recs.push({title:f?'Industrialiser les Innovations':'Industrialize Innovations',axis:'industrialisation',items:f?['Documenter le processus de passage du POC à la production','Créer une équipe de déploiement dédiée au scaling','Mesurer et communiquer le ROI des innovations industrialisées']:['Document the POC-to-production process','Create a dedicated deployment team for scaling','Measure and communicate ROI of industrialized innovations']});
  if (recs.length===0) recs.push({title:f?'Maintenir la Culture d\'Innovation':'Maintain Innovation Culture',items:f?['Explorer l\'innovation ouverte avec des partenaires externes','Créer un fonds d\'investissement pour les spin-offs','Devenir une référence sectorielle en innovation']:['Explore open innovation with external partners','Create an investment fund for spin-offs','Become a sector reference in innovation']});
  return recs;
}