import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { RagDocument } from '@/pages/rag-synthese/types';
import RAGSynthesePDFExport from './RAGSynthesePDFExport';

interface RAGSyntheseResultsProps {
  query: string;
  results: RagDocument[];
  summary: string | null;
  summaryLoading: boolean;
  summaryKeywords: string[];
  totalDocs: number;
  searchMethod: string;
  topDocCount: number;
  onTopDocCountChange: (n: number) => void;
  isPinned: boolean;
  onPin: () => void;
  onUnpin: () => void;
  lang: 'fr' | 'en';
  isEn: boolean;
  t: (fr: string, en?: string) => string;
  translateText: (text: string) => Promise<string>;
  translateBatch: (texts: string[]) => Promise<string[]>;
  translating: boolean;
  translatedSummary: string | null;
  translatedKw: string[];
  translatedItems: Record<string, { titre?: string; description?: string }>;
  onTranslateItem: (docId: string, titre: string, description?: string) => void;
}

export default function RAGSyntheseResults({
  query,
  results,
  summary,
  summaryLoading,
  summaryKeywords,
  totalDocs,
  searchMethod,
  topDocCount,
  onTopDocCountChange,
  isPinned,
  onPin,
  onUnpin,
  lang,
  isEn,
  t,
  translateText,
  translateBatch,
  translating,
  translatedSummary,
  translatedKw,
  translatedItems,
  onTranslateItem,
}: RAGSyntheseResultsProps) {
  const navigate = useNavigate();
  const [selectedDomaine, setSelectedDomaine] = useState<string>('');
  const [showAll, setShowAll] = useState(false);
  const [copied, setCopied] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const [shared, setShared] = useState(false);
  const [pdfExporting, setPdfExporting] = useState(false);
  const [translatingIndex, setTranslatingIndex] = useState<string | null>(null);

  const domaines = Array.from(new Set(results.map((r) => r.domaine).filter(Boolean))).sort();
  const filteredResults = selectedDomaine
    ? results.filter((r) => r.domaine === selectedDomaine)
    : results;
  const displayedResults = showAll ? filteredResults : filteredResults.slice(0, 8);

  const handleCopy = async () => {
    const text = isEn && translatedSummary ? translatedSummary : summary;
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // silent
    }
  };

  const handleDownload = () => {
    const text = isEn && translatedSummary ? translatedSummary : summary;
    if (!text) return;
    const sanitized = query.replace(/[^a-z0-9\u00e0-\u00fc\s-]/gi, '').replace(/\s+/g, '-').slice(0, 40);
    const langSuffix = isEn ? '-en' : '';
    const filename = `synthese-rag-${sanitized}${langSuffix}.txt`;
    const content = `${t('Synthèse RAG', 'RAG Synthesis')} — "${query}"\n${t('Généré par KOS Automaton (extractif, TF-IDF + Cosine Similarity)', 'Generated by KOS Automaton (extractive, TF-IDF + Cosine Similarity)')}\n${'─'.repeat(50)}\n\n${text}\n\n${(isEn && translatedKw.length > 0 ? translatedKw : summaryKeywords).length > 0 ? `${t('Mots-clés', 'Keywords')} : ${(isEn && translatedKw.length > 0 ? translatedKw : summaryKeywords).join(', ')}\n\n` : ''}${t('Avertissement : Résumé extractif généré automatiquement à partir des ', 'Disclaimer: Extractive summary generated automatically from the ')}${topDocCount} ${t('documents réglementaires les plus pertinents.', 'most relevant regulatory documents.')}`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2000);
  };

  const handleShare = async () => {
    const text = isEn && translatedSummary ? translatedSummary : summary;
    if (!text) return;
    const shareUrl = `${window.location.origin}/rag-synthese?rag=${encodeURIComponent(query)}`;
    const shareText = `${t('Synthèse RAG', 'RAG Synthesis')} — "${query}"\n\n${text.slice(0, 200)}${text.length > 200 ? '...' : ''}\n\n${shareUrl}`;
    try {
      if (navigator.share) {
        await navigator.share({
          title: `${t('Synthèse RAG', 'RAG Synthesis')} — ${query}`,
          text: shareText,
          url: shareUrl,
        });
      } else {
        await navigator.clipboard.writeText(shareText);
      }
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    } catch {
      // silent
    }
  };

  const handleDocTranslate = async (doc: RagDocument) => {
    const docId = doc.id || doc.titre;
    const existing = translatedItems[docId];
    if (existing?.titre && existing?.description) return;
    setTranslatingIndex(docId);
    await onTranslateItem(docId, doc.titre, doc.description || undefined);
    setTranslatingIndex(null);
  };

  const getStatutBadge = (statut: string) => {
    switch (statut) {
      case 'En vigueur':
        return 'bg-emerald-100 text-emerald-700';
      case 'Révisé':
        return 'bg-amber-100 text-amber-700';
      case 'Abrogé':
        return 'bg-red-100 text-red-700';
      default:
        return 'bg-background-200 text-foreground-600';
    }
  };

  const getDomaineIcon = (domaine: string) => {
    const d = domaine.toLowerCase();
    if (d.includes('régulation') || d.includes('bceao')) return 'ri-bank-line';
    if (d.includes('lbc') || d.includes('conformité') || d.includes('gafi')) return 'ri-shield-check-line';
    if (d.includes('prix de transfert') || d.includes('beps')) return 'ri-exchange-dollar-line';
    if (d.includes('gouvernance')) return 'ri-organization-chart';
    if (d.includes('protection') || d.includes('rgpd')) return 'ri-lock-line';
    if (d.includes('ia') || d.includes('intelligence')) return 'ri-robot-line';
    if (d.includes('cyber')) return 'ri-shield-flash-line';
    if (d.includes('méthodolog')) return 'ri-tools-line';
    if (d.includes('contrôle interne')) return 'ri-check-double-line';
    if (d.includes('fintech')) return 'ri-smartphone-line';
    if (d.includes('audit')) return 'ri-search-eye-line';
    if (d.includes('droit') || d.includes('ohada')) return 'ri-scales-3-line';
    if (d.includes('esg') || d.includes('durabil')) return 'ri-leaf-line';
    if (d.includes('cobac')) return 'ri-building-2-line';
    if (d.includes('microfinance') || d.includes('sfd')) return 'ri-money-dollar-circle-line';
    if (d.includes('cima') || d.includes('assurance')) return 'ri-umbrella-line';
    return 'ri-file-text-line';
  };

  const getSimilarityColor = (sim: number) => {
    if (sim >= 0.7) return 'text-emerald-600';
    if (sim >= 0.4) return 'text-amber-600';
    return 'text-foreground-400';
  };

  const getSimilarityWidth = (sim: number) => `${Math.round(sim * 100)}%`;

  return (
    <div className="w-full space-y-6">
      {/* Stats bar */}
      <div className="flex flex-wrap items-center gap-3">
        <span className="text-sm font-medium text-foreground-500">
          {results.length} {t('document', 'document')}{results.length > 1 ? 's' : ''} {t('trouvé', 'found')}{results.length > 1 ? 's' : ''}
        </span>
        {totalDocs > 0 && (
          <span className="text-sm text-foreground-400">
            {t('sur', 'out of')} {totalDocs} {t('références', 'references')}
          </span>
        )}
        {searchMethod && (
          <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-accent-100 text-accent-700 rounded-full text-xs font-medium">
            <i className="ri-brain-line text-xs"></i>
            {t('Recherche sémantique', 'Semantic search')}
          </span>
        )}
        <button
          onClick={() => navigate('/')}
          className="ml-auto text-sm text-accent-600 hover:text-accent-700 font-medium cursor-pointer"
        >
          <i className="ri-arrow-left-line mr-1"></i>
          {t('Nouvelle recherche', 'New search')}
        </button>
      </div>

      {/* Domaine filters */}
      {domaines.length > 1 && (
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => setSelectedDomaine('')}
            className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors whitespace-nowrap cursor-pointer ${
              selectedDomaine === ''
                ? 'bg-accent-500 text-white'
                : 'bg-background-100 text-foreground-600 hover:bg-background-200'
            }`}
          >
            {t('Tous', 'All')}
          </button>
          {domaines.map((domaine) => (
            <button
              key={domaine}
              onClick={() => setSelectedDomaine(domaine)}
              className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors whitespace-nowrap cursor-pointer ${
                selectedDomaine === domaine
                  ? 'bg-accent-500 text-white'
                  : 'bg-background-100 text-foreground-600 hover:bg-background-200'
              }`}
            >
              {domaine}
            </button>
          ))}
        </div>
      )}

      {/* Synthèse panel */}
      {(summary || summaryLoading) && (
        <div className="bg-gradient-to-r from-accent-50/60 to-background-50 border border-background-200 rounded-xl p-6">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 flex-shrink-0 flex items-center justify-center rounded-xl bg-accent-500 text-white mt-0.5">
              <i className="ri-magic-line text-xl"></i>
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-3 flex-wrap">
                <h2 className="font-semibold text-base text-foreground-950">
                  {t('Synthèse RAG', 'RAG Synthesis')}
                </h2>
                <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-accent-100 text-accent-700 rounded-full text-xs font-medium">
                  <i className="ri-sparkling-line text-xs"></i>
                  KOS Automaton
                </span>
                <div className="flex items-center gap-1 ml-1">
                  <span className="text-xs text-foreground-400">{t('Doc.', 'Docs')}</span>
                  {[3, 5, 10].map((n) => (
                    <button
                      key={n}
                      onClick={() => onTopDocCountChange(n)}
                      className={`px-2 py-0.5 rounded text-xs font-medium transition-colors whitespace-nowrap cursor-pointer ${
                        topDocCount === n
                          ? 'bg-accent-500 text-white'
                          : 'bg-background-100 text-foreground-600 hover:bg-background-200'
                      }`}
                    >
                      Top {n}
                    </button>
                  ))}
                </div>
              </div>

              {summaryLoading && !summary ? (
                <div className="space-y-2">
                  <div className="h-3 bg-background-200 rounded animate-pulse w-full"></div>
                  <div className="h-3 bg-background-200 rounded animate-pulse w-11/12"></div>
                  <div className="h-3 bg-background-200 rounded animate-pulse w-4/5"></div>
                </div>
              ) : summary ? (
                <>
                  <p className="text-sm text-foreground-700 leading-relaxed whitespace-pre-wrap">
                    {isEn && translatedSummary ? translatedSummary : summary}
                  </p>
                  {(isEn && translatedKw.length > 0 ? translatedKw : summaryKeywords).length > 0 && (
                    <div className="flex flex-wrap gap-1.5 mt-4">
                      {(isEn && translatedKw.length > 0 ? translatedKw : summaryKeywords).slice(0, 8).map((kw) => (
                        <span
                          key={kw}
                          className="px-2.5 py-1 bg-accent-100/70 text-accent-800 rounded-md text-xs font-medium whitespace-nowrap"
                        >
                          {kw}
                        </span>
                      ))}
                    </div>
                  )}
                </>
              ) : null}

              {/* Action buttons */}
              {summary && !summaryLoading && (
                <div className="flex flex-wrap gap-2 mt-5">
                  <button
                    onClick={handleCopy}
                    className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-full text-xs font-medium transition-all whitespace-nowrap cursor-pointer border border-background-300 hover:bg-background-100 hover:border-accent-300"
                  >
                    {copied ? (
                      <>
                        <i className="ri-check-line text-emerald-600"></i>
                        <span className="text-emerald-600">{t('Copié !', 'Copied!')}</span>
                      </>
                    ) : (
                      <>
                        <i className="ri-file-copy-line text-foreground-500"></i>
                        <span className="text-foreground-600">{t('Copier', 'Copy')}</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={handleDownload}
                    className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-full text-xs font-medium transition-all whitespace-nowrap cursor-pointer border border-background-300 hover:bg-background-100 hover:border-accent-300"
                  >
                    {downloaded ? (
                      <>
                        <i className="ri-check-line text-emerald-600"></i>
                        <span className="text-emerald-600">{t('Téléchargé !', 'Downloaded!')}</span>
                      </>
                    ) : (
                      <>
                        <i className="ri-download-line text-foreground-500"></i>
                        <span className="text-foreground-600">.txt</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={handleShare}
                    className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-full text-xs font-medium transition-all whitespace-nowrap cursor-pointer border border-background-300 hover:bg-background-100 hover:border-accent-300"
                  >
                    {shared ? (
                      <>
                        <i className="ri-check-line text-emerald-600"></i>
                        <span className="text-emerald-600">{t('Partagé !', 'Shared!')}</span>
                      </>
                    ) : (
                      <>
                        <i className="ri-share-line text-foreground-500"></i>
                        <span className="text-foreground-600">{t('Partager', 'Share')}</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={isPinned ? onUnpin : onPin}
                    className={`inline-flex items-center gap-1 px-2.5 py-1.5 rounded-full text-xs font-medium transition-all whitespace-nowrap cursor-pointer border ${
                      isPinned
                        ? 'border-accent-300 bg-accent-50 text-accent-700'
                        : 'border-background-300 hover:bg-background-100 hover:border-accent-300'
                    }`}
                  >
                    <i className={`${isPinned ? 'ri-pushpin-fill' : 'ri-pushpin-line'} ${isPinned ? 'text-accent-600' : 'text-foreground-500'}`}></i>
                    <span className={isPinned ? 'text-accent-700' : 'text-foreground-600'}>
                      {isPinned ? t('Épinglé', 'Pinned') : t('Épingler', 'Pin')}
                    </span>
                  </button>
                  <RAGSynthesePDFExport
                    query={query}
                    summary={isEn && translatedSummary ? translatedSummary : (summary || '')}
                    keywords={isEn && translatedKw.length > 0 ? translatedKw : summaryKeywords}
                    results={results.slice(0, topDocCount).map((r) => {
                      const docId = r.id || r.titre;
                      const trans = translatedItems[docId];
                      return {
                        titre: isEn && trans?.titre ? trans.titre : r.titre,
                        domaine: r.domaine,
                        organisation: r.organisation,
                        pays: r.pays,
                        statut: r.statut,
                        description: isEn && trans?.description ? trans.description : r.description,
                      };
                    })}
                    docCount={topDocCount}
                    onExportStart={() => setPdfExporting(true)}
                    onExportEnd={() => setPdfExporting(false)}
                  />
                  {pdfExporting && (
                    <span className="inline-flex items-center gap-1 text-xs text-foreground-400">
                      <div className="w-3 h-3 border-2 border-accent-500 border-t-transparent rounded-full animate-spin"></div>
                      PDF...
                    </span>
                  )}
                </div>
              )}

              {summary && (
                <p className="text-xs text-foreground-400 mt-3 flex items-center gap-1">
                  <i className="ri-information-line"></i>
                  {t(
                    `Résumé extractif généré à partir des ${topDocCount} documents les plus pertinents`,
                    `Extractive summary generated from the ${topDocCount} most relevant documents`
                  )}
                </p>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Results list */}
      <div className="bg-background-50 border border-background-200 rounded-xl overflow-hidden">
        <div className="max-h-[600px] overflow-y-auto divide-y divide-background-200">
          {displayedResults.map((doc, idx) => {
            const docId = doc.id || doc.titre;
            const trans = translatedItems[docId];
            const displayTitre = isEn && trans?.titre ? trans.titre : doc.titre;
            const displayDesc = isEn && trans?.description ? trans.description : doc.description;
            const isTranslated = !!(trans?.titre);
            const isTranslatingItem = translatingIndex === docId;

            return (
              <div
                key={doc.id || idx}
                className="p-5 hover:bg-background-100 transition-colors"
              >
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 flex items-center justify-center bg-accent-100 rounded-lg flex-shrink-0 mt-0.5">
                    <i className={`${getDomaineIcon(doc.domaine)} text-accent-600 text-lg`}></i>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <h4 className="font-semibold text-sm text-foreground-950 leading-snug">
                        {displayTitre}
                      </h4>
                      <span className={`px-2 py-0.5 rounded text-xs font-medium whitespace-nowrap ${getStatutBadge(doc.statut)}`}>
                        {doc.statut}
                      </span>
                    </div>
                    <p className="text-xs text-foreground-500 mb-2 line-clamp-2">
                      {displayDesc}
                    </p>
                    <div className="flex flex-wrap items-center gap-2 text-xs text-foreground-400 mb-2">
                      <span className="flex items-center gap-1">
                        <i className="ri-building-line"></i>
                        {doc.organisation}
                      </span>
                      <span className="flex items-center gap-1">
                        <i className="ri-earth-line"></i>
                        {doc.pays}
                      </span>
                      <span className="flex items-center gap-1">
                        <i className="ri-file-text-line"></i>
                        {doc.type_document}
                      </span>
                      {/* Translate button per document */}
                      {isEn && (
                        <button
                          onClick={(e) => { e.stopPropagation(); handleDocTranslate(doc); }}
                          disabled={isTranslatingItem || isTranslated}
                          className={`inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[10px] font-medium transition-all cursor-pointer ${
                            isTranslated
                              ? 'bg-emerald-50 text-emerald-600 border border-emerald-200'
                              : isTranslatingItem
                                ? 'bg-background-100 text-foreground-400'
                                : 'bg-background-100 text-foreground-500 hover:text-foreground-700 hover:bg-background-200 border border-background-200'
                          }`}
                        >
                          {isTranslatingItem ? (
                            <div className="w-2.5 h-2.5 border border-foreground-400 border-t-transparent rounded-full animate-spin"></div>
                          ) : isTranslated ? (
                            <>
                              <i className="ri-check-line text-[9px]"></i>
                              EN
                            </>
                          ) : (
                            'EN'
                          )}
                        </button>
                      )}
                    </div>
                    {doc.similarity > 0 && (
                      <div className="flex items-center gap-2">
                        <div className="flex-1 h-1.5 bg-background-200 rounded-full overflow-hidden">
                          <div
                            className={`h-full rounded-full transition-all duration-500 ${
                              doc.similarity >= 0.7
                                ? 'bg-emerald-500'
                                : doc.similarity >= 0.4
                                  ? 'bg-amber-500'
                                  : 'bg-foreground-300'
                            }`}
                            style={{ width: getSimilarityWidth(doc.similarity) }}
                          ></div>
                        </div>
                        <span className={`text-xs font-semibold whitespace-nowrap ${getSimilarityColor(doc.similarity)}`}>
                          {Math.round(doc.similarity * 100)}%
                        </span>
                      </div>
                    )}
                    {doc.mots_cles && doc.mots_cles.length > 0 && (
                      <div className="flex flex-wrap gap-1 mt-2">
                        {doc.mots_cles.slice(0, 5).map((kw) => (
                          <span
                            key={kw}
                            className="px-2 py-0.5 bg-background-100 text-foreground-500 rounded text-xs whitespace-nowrap"
                          >
                            {kw}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {filteredResults.length > 8 && (
          <div className="p-3 border-t border-background-200 bg-background-50">
            <button
              onClick={() => setShowAll(!showAll)}
              className="w-full py-2 text-sm text-accent-600 hover:text-accent-700 font-medium text-center transition-colors cursor-pointer"
            >
              {showAll
                ? t('Afficher moins', 'Show less')
                : `${t('Voir les', 'See all')} ${filteredResults.length} ${t('résultats', 'results')}`}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}