import type { DiagnosticAxisConfig } from '../components/types';

export const ROI_MKT_AXES: DiagnosticAxisConfig[] = [
  { id: 'strategie-mkt', titleFr: 'Stratégie Marketing', titleEn: 'Marketing Strategy', descriptionFr: 'Plan marketing, positionnement, ciblage, budget, objectifs', descriptionEn: 'Marketing plan, positioning, targeting, budget, objectives', icon: 'ri-megaphone-line', color: '#7c3aed', weight: 25, questions: [
    { id: 'rm-st-1', questionFr: 'Disposez-vous d\'un plan marketing formalisé avec des objectifs mesurables et un budget dédié ?', questionEn: 'Do you have a formalized marketing plan with measurable objectives and a dedicated budget?', options: [{ value: 100, labelFr: 'Plan marketing annuel documenté, budget dédié > 5% du CA, objectifs SMART, KPIs suivis mensuellement', labelEn: 'Documented annual marketing plan, dedicated budget > 5% revenue, SMART objectives, monthly KPI tracking' }, { value: 60, labelFr: 'Plan marketing défini mais non formalisé, budget < 5% du CA, suivi irrégulier', labelEn: 'Marketing plan defined but not formalized, budget < 5% revenue, irregular tracking' }, { value: 25, labelFr: 'Actions marketing ponctuelles sans stratégie globale, pas de budget dédié', labelEn: 'Ad hoc marketing actions without global strategy, no dedicated budget' }, { value: 0, labelFr: 'Aucune stratégie marketing, actions aléatoires sans mesure', labelEn: 'No marketing strategy, random unmeasured actions' }] },
    { id: 'rm-st-2', questionFr: 'Suivez-vous le ROI de vos actions marketing (coût par lead, coût d\'acquisition client, taux de conversion) ?', questionEn: 'Do you track the ROI of your marketing actions (cost per lead, customer acquisition cost, conversion rate)?', options: [{ value: 100, labelFr: 'ROI mesuré par canal/campagne, attribution modélisée, CAC optimisé en continu, dashboard marketing temps réel', labelEn: 'ROI measured by channel/campaign, modeled attribution, continuously optimized CAC, real-time marketing dashboard' }, { value: 60, labelFr: 'ROI mesuré globalement, attribution partielle, optimisation ponctuelle', labelEn: 'ROI measured globally, partial attribution, occasional optimization' }, { value: 25, labelFr: 'ROI estimé approximativement, pas d\'attribution, pas d\'optimisation', labelEn: 'ROI roughly estimated, no attribution, no optimization' }, { value: 0, labelFr: 'ROI inconnu, dépenses marketing sans aucune mesure de retour', labelEn: 'Unknown ROI, marketing spend without any return measurement' }] },
  ]},
  { id: 'canaux', titleFr: 'Canaux & Performance', titleEn: 'Channels & Performance', descriptionFr: 'Mix canaux, digital vs traditionnel, SEO/SEA, réseaux sociaux, emailing', descriptionEn: 'Channel mix, digital vs traditional, SEO/SEA, social media, email', icon: 'ri-share-line', color: '#0ea5e9', weight: 25, questions: [
    { id: 'rm-ca-1', questionFr: 'Votre mix de canaux marketing est-il diversifié et optimisé en fonction des performances ?', questionEn: 'Is your marketing channel mix diversified and optimized based on performance?', options: [{ value: 100, labelFr: 'Mix multicanal équilibré, budget alloué par performance, tests A/B systématiques, nouveaux canaux testés régulièrement', labelEn: 'Balanced multi-channel mix, performance-based budget allocation, systematic A/B testing, new channels tested regularly' }, { value: 60, labelFr: '2-3 canaux utilisés, allocation basée sur l\'intuition, peu de tests', labelEn: '2-3 channels used, intuition-based allocation, little testing' }, { value: 25, labelFr: 'Un seul canal dominant, dépendance excessive, pas de diversification', labelEn: 'Single dominant channel, excessive dependence, no diversification' }, { value: 0, labelFr: 'Pas de stratégie canal, présence marketing quasi-inexistante', labelEn: 'No channel strategy, nearly non-existent marketing presence' }] },
  ]},
  { id: 'contenu', titleFr: 'Contenu & Marque', titleEn: 'Content & Brand', descriptionFr: 'Stratégie de contenu, brand content, inbound marketing, SEO éditorial', descriptionEn: 'Content strategy, brand content, inbound marketing, editorial SEO', icon: 'ri-file-text-line', color: '#059669', weight: 25, questions: [
    { id: 'rm-co-1', questionFr: 'Produisez-vous du contenu à valeur ajoutée (articles, livres blancs, études de cas) pour attirer et convertir ?', questionEn: 'Do you produce value-added content (articles, white papers, case studies) to attract and convert?', options: [{ value: 100, labelFr: 'Stratégie de contenu documentée, calendrier éditorial, production régulière, contenu optimisé SEO, lead magnets performants', labelEn: 'Documented content strategy, editorial calendar, regular production, SEO-optimized content, performing lead magnets' }, { value: 60, labelFr: 'Contenu produit ponctuellement, pas de calendrier, SEO basique', labelEn: 'Content produced occasionally, no calendar, basic SEO' }, { value: 25, labelFr: 'Très peu de contenu, pas de stratégie éditoriale', labelEn: 'Very little content, no editorial strategy' }, { value: 0, labelFr: 'Aucune production de contenu, marque invisible', labelEn: 'No content production, invisible brand' }] },
  ]},
  { id: 'conversion', titleFr: 'Conversion & Nurturing', titleEn: 'Conversion & Nurturing', descriptionFr: 'Tunnel de conversion, lead nurturing, marketing automation, CRM', descriptionEn: 'Conversion funnel, lead nurturing, marketing automation, CRM', icon: 'ri-user-heart-line', color: '#d97706', weight: 25, questions: [
    { id: 'rm-cv-1', questionFr: 'Avez-vous un tunnel de conversion documenté avec lead nurturing et marketing automation ?', questionEn: 'Do you have a documented conversion funnel with lead nurturing and marketing automation?', options: [{ value: 100, labelFr: 'Tunnel documenté par étape, scoring leads, séquences nurturing automatisées, CRM intégré, taux de conversion optimisé', labelEn: 'Documented funnel by stage, lead scoring, automated nurturing sequences, integrated CRM, optimized conversion rate' }, { value: 60, labelFr: 'Tunnel défini mais non outillé, nurturing manuel, CRM basique', labelEn: 'Funnel defined but not tooled, manual nurturing, basic CRM' }, { value: 25, labelFr: 'Pas de tunnel formalisé, pas de nurturing, leads perdus après le premier contact', labelEn: 'No formalized funnel, no nurturing, leads lost after first contact' }, { value: 0, labelFr: 'Aucune gestion des leads, pas de processus de conversion', labelEn: 'No lead management, no conversion process' }] },
  ]},
];

export function getRoiMktScoreColor(s: number): string { if (s >= 80) return '#059669'; if (s >= 60) return '#0ea5e9'; if (s >= 40) return '#d97706'; return '#dc2626'; }
export function getRoiMktScoreLabel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Marketing Excellence':'Marketing Excellence'; if (s>=60) return f?'Marketing Performant':'Performing Marketing'; if (s>=40) return f?'Marketing Émergent':'Emerging Marketing'; return f?'Marketing Inexistant':'Non-existent Marketing'; }
export function getRoiMktLevel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Niveau 4 — ROI Marketing Optimisé':'Level 4 — Optimized Marketing ROI'; if (s>=60) return f?'Niveau 3 — ROI Marketing Mesuré':'Level 3 — Measured Marketing ROI'; if (s>=40) return f?'Niveau 2 — ROI Marketing Estimé':'Level 2 — Estimated Marketing ROI'; return f?'Niveau 1 — ROI Marketing Inconnu':'Level 1 — Unknown Marketing ROI'; }
export function getRoiMktReadiness(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Votre marketing est une machine à générer du ROI. Continuez à tester de nouveaux canaux et à optimiser vos conversions.':'Your marketing is an ROI-generating machine. Continue testing new channels and optimizing your conversions.'; if (s>=60) return f?'Votre marketing est performant. Renforcez la mesure du ROI et l\'automatisation pour passer au niveau supérieur.':'Your marketing is performing. Strengthen ROI measurement and automation to reach the next level.'; if (s>=40) return f?'Votre marketing est émergent. Formalisez votre stratégie, diversifiez vos canaux et commencez à mesurer le ROI.':'Your marketing is emerging. Formalize your strategy, diversify your channels and start measuring ROI.'; return f?'Votre marketing est quasi-inexistant. Commencez par définir une stratégie, un budget et des objectifs mesurables.':'Your marketing is nearly non-existent. Start by defining a strategy, a budget and measurable objectives.'; }
export function getRoiMktRisks(pa: Record<string,number>, gs: number, lang: string): string[] {
  const f=!lang.startsWith('en'); const r:string[]=[];
  if ((pa['strategie-mkt']??0)<50) r.push(f?'RISQUE MAJEUR — Absence de stratégie marketing : pas de plan, pas d\'objectifs, pas de budget — croissance commerciale non pilotée':'MAJOR RISK — No marketing strategy: no plan, no objectives, no budget — unsteered sales growth');
  if ((pa['canaux']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Canaux non optimisés : dépendance à un seul canal, pas de tests — vulnérabilité aux changements d\'algorithme ou de coût':'HIGH RISK — Non-optimized channels: single channel dependence, no testing — vulnerability to algorithm or cost changes');
  if ((pa['contenu']??0)<50) r.push(f?'RISQUE MAJEUR — Absence de contenu : pas d\'inbound marketing, pas de SEO — dépendance totale à la publicité payante':'MAJOR RISK — No content: no inbound marketing, no SEO — total dependence on paid advertising');
  if ((pa['conversion']??0)<50) r.push(f?'RISQUE CRITIQUE — Tunnel de conversion inexistant : leads non convertis, pas de nurturing — le marketing génère des contacts mais pas de clients':'CRITICAL RISK — Non-existent conversion funnel: unconverted leads, no nurturing — marketing generates contacts but not clients');
  return r;
}
export function getRoiMktRecommendations(pa: Record<string,number>, gs: number, lang: string): {title:string;axis?:string;items:string[]}[] {
  const f=!lang.startsWith('en'); const recs:{title:string;axis?:string;items:string[]}[]=[];
  if ((pa['strategie-mkt']??0)<60) recs.push({title:f?'Formaliser la Stratégie Marketing':'Formalize Marketing Strategy',axis:'strategie-mkt',items:f?['Définir un plan marketing annuel avec objectifs SMART et budget dédié','Mettre en place un dashboard de suivi des KPIs marketing','Mesurer le ROI par action/canal et optimiser en continu']:['Define annual marketing plan with SMART objectives and dedicated budget','Implement marketing KPI tracking dashboard','Measure ROI per action/channel and optimize continuously']});
  if ((pa['canaux']??0)<60) recs.push({title:f?'Diversifier les Canaux':'Diversify Channels',axis:'canaux',items:f?['Tester de nouveaux canaux (SEO, SEA, social media, emailing)','Allouer le budget en fonction des performances mesurées','Mettre en place des tests A/B systématiques']:['Test new channels (SEO, SEA, social media, email)','Allocate budget based on measured performance','Implement systematic A/B testing']});
  if ((pa['contenu']??0)<60) recs.push({title:f?'Produire du Contenu':'Produce Content',axis:'contenu',items:f?['Définir une stratégie de contenu et un calendrier éditorial','Produire des lead magnets (livres blancs, études de cas, guides)','Optimiser le contenu pour le SEO et les moteurs IA (GEO/AEO)']:['Define content strategy and editorial calendar','Produce lead magnets (white papers, case studies, guides)','Optimize content for SEO and AI engines (GEO/AEO)']});
  if ((pa['conversion']??0)<60) recs.push({title:f?'Optimiser la Conversion':'Optimize Conversion',axis:'conversion',items:f?['Cartographier le tunnel de conversion par étape','Mettre en place un scoring leads et des séquences nurturing','Déployer un CRM et automatiser le suivi des leads']:['Map the conversion funnel by stage','Implement lead scoring and nurturing sequences','Deploy a CRM and automate lead follow-up']});
  if (recs.length===0) recs.push({title:f?'Maintenir l\'Excellence Marketing':'Maintain Marketing Excellence',items:f?['Explorer l\'IA pour la personnalisation et l\'optimisation','Tester de nouveaux formats (vidéo, podcast, webinaires)','Benchmarker vos performances contre les leaders du secteur']:['Explore AI for personalization and optimization','Test new formats (video, podcast, webinars)','Benchmark your performance against sector leaders']});
  return recs;
}