import type { DiagnosticToolConfig } from '../components/types';
import { MATURITE_DIGITALE_AXES, getMaturiteDigitaleScoreColor, getMaturiteDigitaleScoreLabel, getMaturiteDigitaleLevel, getMaturiteDigitaleReadiness, getMaturiteDigitaleRisks, getMaturiteDigitaleRecommendations } from './data';
const FORM_URL='https://readdy.ai/api/form/d8pg2pnij7vns5otj9l0'; const PRIMARY='#0ea5e9';
export const maturiteDigitaleConfig: DiagnosticToolConfig = {
  toolId:'maturite-digitale',toolNameFr:'Maturité Digitale KHEPRA™',toolNameEn:'Digital Maturity Assessment KHEPRA™',
  toolSubtitleFr:'Évaluez la maturité de votre système d\'information sur 4 axes : infrastructure, applications, usages et pilotage.',toolSubtitleEn:'Assess your information system maturity across 4 axes: infrastructure, applications, usage and steering.',
  seoTitleFr:'Évaluation Maturité Digitale | KHEPRA EXPERTS',seoTitleEn:'Digital Maturity Assessment | KHEPRA EXPERTS',
  seoDescriptionFr:'Évaluez la maturité de votre système d\'information : infrastructure, applications, usages et pilotage. Rapport avec feuille de route de modernisation.',seoDescriptionEn:'Assess your information system maturity: infrastructure, applications, usage and steering. Report with modernization roadmap.',
  seoKeywordsFr:'maturité digitale, audit SI, infrastructure IT, cloud, cybersécurité, Afrique',seoKeywordsEn:'digital maturity, IT audit, IT infrastructure, cloud, cybersecurity, Africa',
  canonicalPath:'/tools/maturite-digitale',axes:MATURITE_DIGITALE_AXES,
  howToNameFr:'Maturité Digitale KHEPRA™',howToNameEn:'Digital Maturity Assessment KHEPRA™',
  howToDescriptionFr:'Évaluez la maturité de votre SI sur 4 axes : infrastructure IT, applications et logiciels, usages et adoption, pilotage et stratégie SI.',howToDescriptionEn:'Assess your IS maturity across 4 axes: IT infrastructure, applications & software, usage & adoption, IT steering & strategy.',
  howToTotalTime:'6M',howToSteps:MATURITE_DIGITALE_AXES.map(a=>({name:a.titleFr,text:a.descriptionFr})),
  getScoreColor:getMaturiteDigitaleScoreColor,getScoreLabel:getMaturiteDigitaleScoreLabel,getMaturityLevel:getMaturiteDigitaleLevel,getReadinessIndicator:getMaturiteDigitaleReadiness,
  getRisks:(pa,gs,l)=>getMaturiteDigitaleRisks(pa,gs,l),getRecommendations:(pa,gs,l)=>getMaturiteDigitaleRecommendations(pa,gs,l),
  getOptionStyle:(v,s)=>{if(v===100)return s?'border-emerald-500 bg-emerald-50':'border-secondary-200 hover:border-emerald-300';if(v===60)return s?'border-sky-500 bg-sky-50':'border-secondary-200 hover:border-sky-300';if(v===25)return s?'border-accent-500 bg-accent-50':'border-secondary-200 hover:border-accent-300';return s?'border-red-500 bg-red-50':'border-secondary-200 hover:border-red-300';},
  getOptionIcon:(v)=>{if(v===100)return'ri-check-double-line';if(v===60)return'ri-check-line';if(v===25)return'ri-subtract-line';return'ri-close-line';},
  getOptionColor:(v)=>{if(v===100)return'text-emerald-600';if(v===60)return'text-sky-600';if(v===25)return'text-accent-600';return'text-red-600';},
  showLeadForm:true,formUrl:FORM_URL,hashtags:['MaturiteDigitale','AuditSI','TransformationDigitale'],
  showRadarChart:true,renderRadarChart:(s,pa,ax,fr)=>{const c=s/2,rad=100,ac=ax.length,as=(2*Math.PI)/ac,sa=-Math.PI/2,gp=(i:number,v:number)=>{const a=sa+i*as,r=(v/100)*rad;return{x:c+r*Math.cos(a),y:c+r*Math.sin(a)};};return(<svg width={s} height={s} viewBox={`0 0 ${s} ${s}`} className="mx-auto">{[20,40,60,80,100].map(lv=>{const ps=ax.map((_,i)=>{const p=gp(i,lv);return`${p.x},${p.y}`}).join(' ');return<polygon key={lv} points={ps} fill="none" stroke="#e5e7eb" strokeWidth="1"/>})}{ax.map((_,i)=>{const e=gp(i,100);return<line key={i} x1={c} y1={c} x2={e.x} y2={e.y} stroke="#e5e7eb" strokeWidth="1"/>})}{(()=>{const dp=ax.map((a,i)=>gp(i,pa[a.id]??0)),ps=dp.map(p=>`${p.x},${p.y}`).join(' ');return(<><polygon points={ps} fill="rgba(14,165,233,0.15)" stroke={PRIMARY} strokeWidth="2"/>{dp.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="5" fill={PRIMARY} stroke="white" strokeWidth="2"/>)}</>)})()}{ax.map((a,i)=>{const lp=gp(i,125),w=(fr?a.titleFr:a.titleEn).split(' '),lb=w.length>2?w.slice(0,2).join(' '):w.join(' ');return<text key={i} x={lp.x} y={lp.y} textAnchor="middle" dominantBaseline="middle" fontSize="9" fontWeight="600" fill="#374151">{lb}</text>})}</svg>)},
  badgeIcon:'ri-computer-line',badgeTextFr:'4 axes · 6 questions · 6 min',badgeTextEn:'4 axes · 6 questions · 6 min',
  expertCTA:{titleFr:'Besoin d\'un audit SI complet ?',titleEn:'Need a complete IS audit?',descriptionFr:'Nos experts en systèmes d\'information vous accompagnent dans la modernisation de votre infrastructure et de vos applications.',descriptionEn:'Our IS experts support you in modernizing your infrastructure and applications.',ctaFr:'Planifier un rendez-vous',ctaEn:'Schedule a meeting',ctaLink:'/contact'},
};