import type { DiagnosticAxisConfig } from '../components/types';

export const MATURITE_DIGITALE_AXES: DiagnosticAxisConfig[] = [
  { id: 'infrastructure', titleFr: 'Infrastructure IT', titleEn: 'IT Infrastructure', descriptionFr: 'Cloud, réseau, postes de travail, sécurité, résilience', descriptionEn: 'Cloud, network, workstations, security, resilience', icon: 'ri-server-line', color: '#0ea5e9', weight: 25, questions: [
    { id: 'md-inf-1', questionFr: 'Votre infrastructure est-elle modernisée (cloud, virtualisation) avec une haute disponibilité ?', questionEn: 'Is your infrastructure modernized (cloud, virtualization) with high availability?', options: [{ value: 100, labelFr: 'Cloud hybride, 99.9%+ uptime, disaster recovery testé, infrastructure as code', labelEn: 'Hybrid cloud, 99.9%+ uptime, tested disaster recovery, infrastructure as code' }, { value: 60, labelFr: 'Virtualisation partielle, cloud en cours, uptime 99-99.9%', labelEn: 'Partial virtualization, cloud ongoing, 99-99.9% uptime' }, { value: 25, labelFr: 'Serveurs physiques majoritaires, pas de cloud, pannes fréquentes', labelEn: 'Mostly physical servers, no cloud, frequent outages' }, { value: 0, labelFr: 'Infrastructure obsolète, pas de redondance, risque de panne permanent', labelEn: 'Obsolete infrastructure, no redundancy, permanent outage risk' }] },
    { id: 'md-inf-2', questionFr: 'La cybersécurité est-elle prise en compte avec des mesures proportionnées aux risques ?', questionEn: 'Is cybersecurity addressed with measures proportionate to risks?', options: [{ value: 100, labelFr: 'SOC 24/7 ou MSSP, EDR, SIEM, tests d\'intrusion, politique de sécurité documentée, sensibilisation continue', labelEn: 'SOC 24/7 or MSSP, EDR, SIEM, penetration tests, documented security policy, continuous awareness' }, { value: 60, labelFr: 'Antivirus, pare-feu, quelques audits, politique de sécurité basique', labelEn: 'Antivirus, firewall, some audits, basic security policy' }, { value: 25, labelFr: 'Protection minimale, pas de politique formalisée, mises à jour irrégulières', labelEn: 'Minimal protection, no formalized policy, irregular updates' }, { value: 0, labelFr: 'Aucune cybersécurité, vulnérabilités critiques exposées', labelEn: 'No cybersecurity, exposed critical vulnerabilities' }] },
  ]},
  { id: 'applications', titleFr: 'Applications & Logiciels', titleEn: 'Applications & Software', descriptionFr: 'ERP, CRM, outils métier, couverture fonctionnelle, intégration', descriptionEn: 'ERP, CRM, business tools, functional coverage, integration', icon: 'ri-window-line', color: '#7c3aed', weight: 25, questions: [
    { id: 'md-app-1', questionFr: 'Vos applications couvrent-elles l\'ensemble de vos processus métier de manière intégrée ?', questionEn: 'Do your applications cover all your business processes in an integrated manner?', options: [{ value: 100, labelFr: 'ERP intégré couvrant >90% des processus, CRM, HRIS, BI — données unifiées', labelEn: 'Integrated ERP covering >90% processes, CRM, HRIS, BI — unified data' }, { value: 60, labelFr: 'ERP partiel + applications satellites, quelques intégrations', labelEn: 'Partial ERP + satellite applications, some integrations' }, { value: 25, labelFr: 'Applications disparates, pas d\'ERP, nombreuses saisies manuelles', labelEn: 'Disparate applications, no ERP, numerous manual entries' }, { value: 0, labelFr: 'Excel + email comme outils principaux, pas d\'applications métier', labelEn: 'Excel + email as main tools, no business applications' }] },
    { id: 'md-app-2', questionFr: 'Les données sont-elles centralisées, fiables et accessibles pour la prise de décision ?', questionEn: 'Is data centralized, reliable and accessible for decision-making?', options: [{ value: 100, labelFr: 'Data warehouse/lake, BI self-service, gouvernance données, qualité mesurée, indicateurs temps réel', labelEn: 'Data warehouse/lake, self-service BI, data governance, measured quality, real-time indicators' }, { value: 60, labelFr: 'Base de données centralisée, reporting périodique, qualité partielle', labelEn: 'Centralized database, periodic reporting, partial quality' }, { value: 25, labelFr: 'Données en silos, reporting Excel manuel, données non fiables', labelEn: 'Data in silos, manual Excel reporting, unreliable data' }, { value: 0, labelFr: 'Aucune centralisation, données inexploitables', labelEn: 'No centralization, unusable data' }] },
  ]},
  { id: 'usages', titleFr: 'Usages & Adoption', titleEn: 'Usage & Adoption', descriptionFr: 'Culture digitale, formation, support, satisfaction utilisateurs, télétravail', descriptionEn: 'Digital culture, training, support, user satisfaction, remote work', icon: 'ri-user-settings-line', color: '#059669', weight: 25, questions: [
    { id: 'md-usa-1', questionFr: 'Le taux d\'adoption des outils digitaux par les collaborateurs est-il élevé ?', questionEn: 'Is the adoption rate of digital tools by employees high?', options: [{ value: 100, labelFr: 'Adoption > 80%, formation systématique, support dédié, feedback loop, amélioration continue', labelEn: 'Adoption > 80%, systematic training, dedicated support, feedback loop, continuous improvement' }, { value: 60, labelFr: 'Adoption 50-80%, formation ponctuelle, support basique', labelEn: 'Adoption 50-80%, occasional training, basic support' }, { value: 25, labelFr: 'Adoption < 50%, résistance au changement, pas de formation structurée', labelEn: 'Adoption < 50%, resistance to change, no structured training' }, { value: 0, labelFr: 'Outils non adoptés, les collaborateurs contournent les systèmes', labelEn: 'Tools not adopted, employees bypass systems' }] },
  ]},
  { id: 'pilotage', titleFr: 'Pilotage & Stratégie SI', titleEn: 'IT Steering & Strategy', descriptionFr: 'Roadmap SI, budget, gouvernance, innovation, alignement métier', descriptionEn: 'IT roadmap, budget, governance, innovation, business alignment', icon: 'ri-compass-3-line', color: '#d97706', weight: 25, questions: [
    { id: 'md-pil-1', questionFr: 'Disposez-vous d\'un schéma directeur SI aligné sur la stratégie d\'entreprise ?', questionEn: 'Do you have an IT master plan aligned with business strategy?', options: [{ value: 100, labelFr: 'SDI 3-5 ans documenté, aligné stratégie, budget validé, comité de pilotage trimestriel', labelEn: '3-5 year IT master plan documented, strategy-aligned, validated budget, quarterly steering committee' }, { value: 60, labelFr: 'SDI défini mais non formalisé, alignement partiel, budget annuel', labelEn: 'IT plan defined but not formalized, partial alignment, annual budget' }, { value: 25, labelFr: 'Pas de SDI, projets IT décidés au coup par coup', labelEn: 'No IT master plan, IT projects decided ad hoc' }, { value: 0, labelFr: 'Aucune stratégie SI, le SI évolue sans gouvernance', labelEn: 'No IT strategy, IS evolves without governance' }] },
  ]},
];

export function getMaturiteDigitaleScoreColor(s: number): string { if (s >= 80) return '#059669'; if (s >= 60) return '#0ea5e9'; if (s >= 40) return '#d97706'; return '#dc2626'; }
export function getMaturiteDigitaleScoreLabel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'SI Optimisé':'Optimized IS'; if (s>=60) return f?'SI Structuré':'Structured IS'; if (s>=40) return f?'SI en Transition':'IS in Transition'; return f?'SI Obsolète':'Obsolete IS'; }
export function getMaturiteDigitaleLevel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Niveau 4 — Excellence SI':'Level 4 — IS Excellence'; if (s>=60) return f?'Niveau 3 — SI Performant':'Level 3 — Performing IS'; if (s>=40) return f?'Niveau 2 — SI Basique':'Level 2 — Basic IS'; return f?'Niveau 1 — SI Critique':'Level 1 — Critical IS'; }
export function getMaturiteDigitaleReadiness(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Votre système d\'information est un actif stratégique optimisé. Continuez à innover et à renforcer la cybersécurité.':'Your information system is an optimized strategic asset. Continue innovating and strengthening cybersecurity.'; if (s>=60) return f?'Votre SI est structuré et performant. Améliorez l\'adoption utilisateur et modernisez les briques les plus obsolètes.':'Your IS is structured and performing. Improve user adoption and modernize the most obsolete components.'; if (s>=40) return f?'Votre SI est en transition. Priorisez la modernisation de l\'infrastructure et la centralisation des données.':'Your IS is in transition. Prioritize infrastructure modernization and data centralization.'; return f?'Votre SI est obsolète et présente des risques critiques. Une refonte urgente est nécessaire pour sécuriser et moderniser.':'Your IS is obsolete and presents critical risks. Urgent overhaul is needed to secure and modernize.'; }

export function getMaturiteDigitaleRisks(pa: Record<string,number>, gs: number, lang: string): string[] {
  const f=!lang.startsWith('en'); const r:string[]=[];
  if ((pa['infrastructure']??0)<50) r.push(f?'RISQUE CRITIQUE — Infrastructure obsolète : risque de panne, perte de données, cyberattaque — la continuité d\'activité est menacée':'CRITICAL RISK — Obsolete infrastructure: breakdown, data loss, cyberattack risk — business continuity is threatened');
  if ((pa['applications']??0)<50) r.push(f?'RISQUE MAJEUR — Applications inadaptées : processus non couverts, données non fiables, inefficience chronique':'MAJOR RISK — Inadequate applications: uncovered processes, unreliable data, chronic inefficiency');
  if ((pa['usages']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Faible adoption : investissements IT sans retour, shadow IT, résistance au changement':'HIGH RISK — Low adoption: IT investments without return, shadow IT, resistance to change');
  if ((pa['pilotage']??0)<50) r.push(f?'RISQUE MAJEUR — Absence de pilotage SI : pas de roadmap, budget non maîtrisé, dérive technologique':'MAJOR RISK — No IT steering: no roadmap, uncontrolled budget, technology drift');
  return r;
}

export function getMaturiteDigitaleRecommendations(pa: Record<string,number>, gs: number, lang: string): {title:string;axis?:string;items:string[]}[] {
  const f=!lang.startsWith('en'); const recs:{title:string;axis?:string;items:string[]}[]=[];
  if ((pa['infrastructure']??0)<60) recs.push({title:f?'Moderniser l\'Infrastructure':'Modernize Infrastructure',axis:'infrastructure',items:f?['Migrer vers le cloud avec un plan de disaster recovery','Mettre en place une cybersécurité proportionnée (EDR, SIEM, audits)','Garantir une haute disponibilité (>99.9%) avec redondance']:['Migrate to cloud with disaster recovery plan','Implement proportionate cybersecurity (EDR, SIEM, audits)','Guarantee high availability (>99.9%) with redundancy']});
  if ((pa['applications']??0)<60) recs.push({title:f?'Intégrer les Applications':'Integrate Applications',axis:'applications',items:f?['Déployer un ERP intégré couvrant les processus clés','Centraliser les données dans un data warehouse avec BI','Automatiser les flux entre applications pour éliminer les saisies manuelles']:['Deploy an integrated ERP covering key processes','Centralize data in a data warehouse with BI','Automate flows between applications to eliminate manual entries']});
  if ((pa['usages']??0)<60) recs.push({title:f?'Améliorer l\'Adoption':'Improve Adoption',axis:'usages',items:f?['Mettre en place un plan de formation et d\'accompagnement au changement','Désigner des ambassadeurs digitaux dans chaque service','Mesurer et communiquer les bénéfices de la digitalisation']:['Implement a training and change management plan','Designate digital ambassadors in each department','Measure and communicate digitization benefits']});
  if ((pa['pilotage']??0)<60) recs.push({title:f?'Structurer le Pilotage SI':'Structure IT Steering',axis:'pilotage',items:f?['Élaborer un schéma directeur SI 3-5 ans aligné sur la stratégie','Mettre en place un comité de pilotage SI trimestriel','Définir et suivre des KPI de performance du SI']:['Develop a 3-5 year IT master plan aligned with strategy','Set up a quarterly IT steering committee','Define and track IS performance KPIs']});
  if (recs.length===0) recs.push({title:f?'Maintenir l\'Excellence du SI':'Maintain IS Excellence',items:f?['Explorer l\'IA et l\'automatisation avancée','Renforcer la cybersécurité avec des tests Red Team','Partager les bonnes pratiques de gouvernance SI']:['Explore AI and advanced automation','Strengthen cybersecurity with Red Team tests','Share IT governance best practices']});
  return recs;
}