const common = {
  faq: { title: 'Häufig gestellte Fragen', badge: 'FAQ', description: 'Finden Sie Antworten auf die häufigsten Fragen zu unseren Dienstleistungen.' },
  contact: { title: 'Kontaktieren Sie uns', subtitle: 'Sprechen Sie mit uns über Ihr strategisches Projekt', name: 'Vollständiger Name', email: 'E-Mail', phone: 'Telefon', company: 'Organisation', message: 'Nachricht', submit: 'Senden', sending: 'Wird gesendet…', success: 'Nachricht erfolgreich gesendet!', error: 'Ein Fehler ist aufgetreten.', address: 'Adresse', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Ihr strategischer Partner für Beratung, Finanzprüfung, Governance und digitale Transformation', quickLinks: 'Schnelllinks', services: 'Dienstleistungen', about: 'Über uns', blog: 'Blog', contact: 'Kontakt', legalLinks: 'Rechtliches', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen', followUs: 'Folgen Sie uns', rights: 'Alle Rechte vorbehalten.' },
  common: { learnMore: 'Mehr erfahren' },
  cta: { diagnostic_free: 'Kostenlose Diagnose', diagnostic_subtitle: 'Antwort innerhalb von 2h · Unverbindlich' },
  leadMagnet: { whitepaper: { title: 'Laden Sie unser Whitepaper herunter', description: 'Tiefgehende Analyse und umsetzbare Empfehlungen.', button: 'Whitepaper herunterladen' }, webinar: { title: 'Nehmen Sie an unserem Webinar teil', description: 'Tauschen Sie sich live mit unseren Experten aus.', button: 'Für Webinar anmelden' }, diagnostic: { title: 'Kostenlose strategische Diagnose', description: '30 Minuten mit einem Experten zur Analyse Ihrer Situation.', button: 'Diagnose starten' }, newsletter: { title: 'Erhalten Sie unseren strategischen Newsletter', description: 'Exklusive Analysen direkt in Ihr Postfach.', button: 'Newsletter abonnieren' } },
  monitoring: { title: 'Technisches Monitoring', subtitle: '404-Fehler und Antwortzeiten', loading: 'Daten werden geladen…', retry: 'Wiederholen', timeRange: { '24h': '24 Std.', '7d': '7 Tage', '30d': '30 Tage' }, stats: { total404: '404-Fehler', total404Sub: 'Fehlende Seiten', totalErrors: 'HTTP/JS-Fehler', totalErrorsSub: 'Anfragen und Skripte', avgResponse: 'Ø API-Zeit', avgResponseSub: 'ms', avgPageLoad: 'Seitenaufbau', avgPageLoadSub: 'ms' }, notFound: { title: 'Top 404 URLs', subtitle: 'Am häufigsten fehlende Seiten', url: 'URL', count: 'Vorkommen', empty: 'Keine Fehler erkannt' }, performance: { title: 'API-Antwortzeit', subtitle: 'Durchschnitt und Maximum', tooltipAvg: 'Ø', tooltipMax: 'Max', tooltipCount: 'Anfragen', empty: 'Keine Daten' }, topErrors: { title: 'Häufigste Fehler', subtitle: 'Am häufigsten auftretende Fehler', empty: 'Keine Fehler' }, errorLog: { title: 'Fehlerprotokoll', subtitle: 'Aktuelle Fehler', type: 'Typ', message: 'Nachricht', url: 'URL', date: 'Datum', empty: 'Keine aktuellen Fehler' }, navigation: { title: 'Navigation', subtitle: 'Seitenladezeiten', empty: 'Keine Daten' } },
  dashboard: { login: { title: 'Dashboard', subtitle: 'Administratorzugriff', passwordLabel: 'Passwort', passwordPlaceholder: 'Passwort eingeben', loginButton: 'Anmelden', incorrectPassword: 'Falsches Passwort' }, header: { title: 'Dashboard', subtitle: 'Conversion- und Leistungsverfolgung', timeRange: { '7d': '7 Tage', '30d': '30 Tage', '90d': '90 Tage', all: 'Alle' }, refreshButton: 'Aktualisieren' }, loading: 'Daten werden geladen…', kpis: { totalLeads: { title: 'Gesamt-Leads', subtitle: 'neu' } }, pipeline: { title: 'Conversion-Pipeline' }, sources: { title: 'Akquisequellen' }, formTypes: { title: 'Leistung nach Formulartyp', ofTotal: 'der Gesamtzahl' }, recentLeads: { title: 'Aktuelle Leads', table: { date: 'Datum', contact: 'Kontakt', organization: 'Organisation', type: 'Typ', score: 'Punktzahl', status: 'Status', source: 'Quelle' } }, status: { new: 'Neu', meeting_scheduled: 'Termin vereinbart', qualified: 'Qualifiziert', converted: 'Konvertiert', lost: 'Verloren' }, formType: { contact: 'Kontakt', diagnostic: 'Diagnose', expert: 'Experte', newsletter: 'Newsletter' }, metrics: { toolCompletions: { title: 'Abgeschlossene Tools', subtitle: 'Diagnosen' } }, diagnostics: { title: 'Aktuelle Diagnosen', table: { date: 'Datum', tool: 'Tool', score: 'Punktzahl' } }, downloads: { title: 'Aktuelle Downloads', table: { date: 'Datum', resource: 'Ressource', contact: 'Kontakt', country: 'Land' }, unknownResource: 'Unbekannte Ressource' }, noData: 'Keine Daten', retry: 'Wiederholen' },
};

export default common;