import type { DiagnosticAxisConfig } from '../components/types';

export const KPI_QUALITE_AXES: DiagnosticAxisConfig[] = [
  { id: 'satisfaction', titleFr: 'Satisfaction Client', titleEn: 'Customer Satisfaction', descriptionFr: 'NPS, CSAT, réclamations, délais de réponse, fidélisation', descriptionEn: 'NPS, CSAT, complaints, response times, retention', icon: 'ri-emotion-happy-line', color: '#059669', weight: 25, questions: [
    { id: 'kq-sat-1', questionFr: 'Mesurez-vous la satisfaction client avec des indicateurs formalisés (NPS, CSAT) et un plan d\'amélioration continue ?', questionEn: 'Do you measure customer satisfaction with formalized indicators (NPS, CSAT) and a continuous improvement plan?', options: [{ value: 100, labelFr: 'NPS > 50, CSAT > 90%, enquêtes trimestrielles, plan d\'action documenté, boucle d\'amélioration fermée', labelEn: 'NPS > 50, CSAT > 90%, quarterly surveys, documented action plan, closed improvement loop' }, { value: 60, labelFr: 'Enquête satisfaction annuelle, NPS 20-50, plan d\'action partiel', labelEn: 'Annual satisfaction survey, NPS 20-50, partial action plan' }, { value: 25, labelFr: 'Satisfaction mesurée de manière informelle, pas d\'indicateurs standardisés', labelEn: 'Satisfaction measured informally, no standardized indicators' }, { value: 0, labelFr: 'Aucune mesure de la satisfaction client', labelEn: 'No customer satisfaction measurement' }] },
    { id: 'kq-sat-2', questionFr: 'Gérez-vous les réclamations clients avec un processus structuré et des délais de résolution garantis ?', questionEn: 'Do you manage customer complaints with a structured process and guaranteed resolution times?', options: [{ value: 100, labelFr: 'Système de ticketing, SLA définis (< 24h accusé réception, < 5j résolution), analyse des causes racines, rapport trimestriel', labelEn: 'Ticketing system, defined SLAs (< 24h acknowledgment, < 5d resolution), root cause analysis, quarterly report' }, { value: 60, labelFr: 'Processus de réclamation documenté mais délais non garantis', labelEn: 'Documented complaint process but non-guaranteed timelines' }, { value: 25, labelFr: 'Gestion informelle des réclamations, pas de suivi', labelEn: 'Informal complaint management, no tracking' }, { value: 0, labelFr: 'Aucune gestion des réclamations', labelEn: 'No complaint management' }] },
  ]},
  { id: 'processus', titleFr: 'Performance des Processus', titleEn: 'Process Performance', descriptionFr: 'Efficacité, délais, taux d\'erreur, productivité, standardisation', descriptionEn: 'Efficiency, lead times, error rate, productivity, standardization', icon: 'ri-settings-line', color: '#0ea5e9', weight: 25, questions: [
    { id: 'kq-pro-1', questionFr: 'Suivez-vous des KPIs de performance pour vos processus clés (délais, qualité, productivité) ?', questionEn: 'Do you track performance KPIs for your key processes (lead times, quality, productivity)?', options: [{ value: 100, labelFr: 'KPIs documentés par processus, tableau de bord temps réel, objectifs d\'amélioration, revue mensuelle', labelEn: 'Documented KPIs per process, real-time dashboard, improvement objectives, monthly review' }, { value: 60, labelFr: 'Quelques KPIs suivis, pas de tableau de bord structuré, revue irrégulière', labelEn: 'Some KPIs tracked, no structured dashboard, irregular review' }, { value: 25, labelFr: 'Pas de KPIs formalisés, perception subjective de la performance', labelEn: 'No formalized KPIs, subjective performance perception' }, { value: 0, labelFr: 'Aucun suivi de la performance des processus', labelEn: 'No process performance tracking' }] },
  ]},
  { id: 'conformite', titleFr: 'Conformité & Audit', titleEn: 'Compliance & Audit', descriptionFr: 'Audits qualité, certifications, conformité réglementaire, non-conformités', descriptionEn: 'Quality audits, certifications, regulatory compliance, non-conformities', icon: 'ri-shield-check-line', color: '#7c3aed', weight: 25, questions: [
    { id: 'kq-con-1', questionFr: 'Disposez-vous d\'un système de management de la qualité certifié ou en cours de certification ?', questionEn: 'Do you have a certified or in-progress quality management system?', options: [{ value: 100, labelFr: 'ISO 9001 certifiée, audits internes/externes réguliers, plan d\'actions correctives, revue de direction annuelle', labelEn: 'ISO 9001 certified, regular internal/external audits, corrective action plan, annual management review' }, { value: 60, labelFr: 'Démarche qualité formalisée mais non certifiée, quelques audits', labelEn: 'Formalized quality approach but not certified, some audits' }, { value: 25, labelFr: 'Procédures qualité basiques, pas d\'audits structurés', labelEn: 'Basic quality procedures, no structured audits' }, { value: 0, labelFr: 'Aucune démarche qualité', labelEn: 'No quality approach' }] },
  ]},
  { id: 'amelioration', titleFr: 'Amélioration Continue', titleEn: 'Continuous Improvement', descriptionFr: 'Lean, Six Sigma, résolution de problèmes, innovation, culture qualité', descriptionEn: 'Lean, Six Sigma, problem solving, innovation, quality culture', icon: 'ri-arrow-up-circle-line', color: '#d97706', weight: 25, questions: [
    { id: 'kq-am-1', questionFr: 'Avez-vous une démarche structurée d\'amélioration continue (Lean, Six Sigma, Kaizen) ?', questionEn: 'Do you have a structured continuous improvement approach (Lean, Six Sigma, Kaizen)?', options: [{ value: 100, labelFr: 'Programme Lean/Six Sigma déployé, ceintures vertes/noires certifiées, projets d\'amélioration mesurés, culture Kaizen', labelEn: 'Deployed Lean/Six Sigma program, certified green/black belts, measured improvement projects, Kaizen culture' }, { value: 60, labelFr: 'Quelques initiatives d\'amélioration, pas de méthodologie structurée', labelEn: 'Some improvement initiatives, no structured methodology' }, { value: 25, labelFr: 'Amélioration ponctuelle, résolution de problèmes au cas par cas', labelEn: 'Ad hoc improvement, case-by-case problem resolution' }, { value: 0, labelFr: 'Aucune démarche d\'amélioration continue', labelEn: 'No continuous improvement approach' }] },
  ]},
];

export function getKpiQualiteScoreColor(s: number): string { if (s >= 80) return '#059669'; if (s >= 60) return '#0ea5e9'; if (s >= 40) return '#d97706'; return '#dc2626'; }
export function getKpiQualiteScoreLabel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Excellence Qualité':'Quality Excellence'; if (s>=60) return f?'Qualité Structurée':'Structured Quality'; if (s>=40) return f?'Qualité Basique':'Basic Quality'; return f?'Qualité Insuffisante':'Insufficient Quality'; }
export function getKpiQualiteLevel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Niveau 4 — Qualité Totale':'Level 4 — Total Quality'; if (s>=60) return f?'Niveau 3 — Qualité Gérée':'Level 3 — Managed Quality'; if (s>=40) return f?'Niveau 2 — Qualité Contrôlée':'Level 2 — Controlled Quality'; return f?'Niveau 1 — Qualité Non Maîtrisée':'Level 1 — Uncontrolled Quality'; }
export function getKpiQualiteReadiness(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Votre système qualité est excellent. Continuez à innover dans vos pratiques et visez des certifications de niveau supérieur.':'Your quality system is excellent. Continue innovating in your practices and target higher-level certifications.'; if (s>=60) return f?'Votre qualité est bien gérée. Renforcez l\'amélioration continue et visez la certification pour atteindre l\'excellence.':'Your quality is well managed. Strengthen continuous improvement and target certification to reach excellence.'; if (s>=40) return f?'Votre qualité est basique. Structurez votre démarche, définissez des KPIs et engagez-vous dans une certification.':'Your quality is basic. Structure your approach, define KPIs and commit to certification.'; return f?'Votre qualité n\'est pas maîtrisée. Commencez par mesurer la satisfaction client et documenter vos processus.':'Your quality is uncontrolled. Start by measuring customer satisfaction and documenting your processes.'; }
export function getKpiQualiteRisks(pa: Record<string,number>, gs: number, lang: string): string[] {
  const f=!lang.startsWith('en'); const r:string[]=[];
  if ((pa['satisfaction']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Insatisfaction client non détectée : pas de mesure, pas d\'alerte — attrition silencieuse et risque réputationnel':'HIGH RISK — Undetected customer dissatisfaction: no measurement, no alert — silent attrition and reputational risk');
  if ((pa['processus']??0)<50) r.push(f?'RISQUE MAJEUR — Processus non pilotés : pas de KPIs, inefficience chronique — gaspillage de ressources et qualité aléatoire':'MAJOR RISK — Non-steered processes: no KPIs, chronic inefficiency — resource waste and random quality');
  if ((pa['conformite']??0)<50) r.push(f?'RISQUE MAJEUR — Absence de certification : pas de reconnaissance externe, non-conformités non détectées — perte d\'appels d\'offres':'MAJOR RISK — No certification: no external recognition, undetected non-conformities — loss of tenders');
  if ((pa['amelioration']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Absence d\'amélioration continue : stagnation, problèmes récurrents — perte de compétitivité à moyen terme':'HIGH RISK — No continuous improvement: stagnation, recurring problems — medium-term competitiveness loss');
  return r;
}
export function getKpiQualiteRecommendations(pa: Record<string,number>, gs: number, lang: string): {title:string;axis?:string;items:string[]}[] {
  const f=!lang.startsWith('en'); const recs:{title:string;axis?:string;items:string[]}[]=[];
  if ((pa['satisfaction']??0)<60) recs.push({title:f?'Mesurer la Satisfaction':'Measure Satisfaction',axis:'satisfaction',items:f?['Déployer une enquête NPS trimestrielle avec plan d\'action','Mettre en place un système de gestion des réclamations avec SLAs','Analyser les causes racines des insatisfactions']:['Deploy quarterly NPS survey with action plan','Implement complaint management system with SLAs','Analyze root causes of dissatisfaction']});
  if ((pa['processus']??0)<60) recs.push({title:f?'Piloter les Processus':'Steer Processes',axis:'processus',items:f?['Définir des KPIs de performance pour chaque processus clé','Construire un tableau de bord qualité avec objectifs','Mettre en place des revues de performance mensuelles']:['Define performance KPIs for each key process','Build a quality dashboard with objectives','Implement monthly performance reviews']});
  if ((pa['conformite']??0)<60) recs.push({title:f?'Structurer la Conformité':'Structure Compliance',axis:'conformite',items:f?['Engager une démarche de certification ISO 9001','Mettre en place un programme d\'audits internes réguliers','Documenter et suivre les actions correctives']:['Engage ISO 9001 certification process','Implement regular internal audit program','Document and track corrective actions']});
  if ((pa['amelioration']??0)<60) recs.push({title:f?'Développer l\'Amélioration Continue':'Develop Continuous Improvement',axis:'amelioration',items:f?['Former des ceintures vertes/jaunes Lean Six Sigma','Lancer des chantiers d\'amélioration sur les processus prioritaires','Instaurer une culture de résolution de problèmes (A3, PDCA)']:['Train Lean Six Sigma green/yellow belts','Launch improvement projects on priority processes','Institute a problem-solving culture (A3, PDCA)']});
  if (recs.length===0) recs.push({title:f?'Maintenir l\'Excellence Qualité':'Maintain Quality Excellence',items:f?['Viser des certifications avancées (ISO 45001, ISO 14001)','Déployer le Lean Six Sigma au niveau organisationnel','Partager les bonnes pratiques qualité avec l\'écosystème']:['Target advanced certifications (ISO 45001, ISO 14001)','Deploy Lean Six Sigma organization-wide','Share quality best practices with the ecosystem']});
  return recs;
}