import { GeoPageData } from '@/pages/geo-hub/types';

export const cartographieRisquesGeoData: GeoPageData = {
  slug: 'cartographie-risques-entreprise',
  h1Fr: 'Comment réaliser une cartographie des risques en Afrique : guide COSO, ISO 31000 et Bâle II/III 2026',
  h1En: 'How to Conduct a Risk Mapping in Africa: COSO, ISO 31000 and Basel II/III Guide 2026',
  metaTitleFr: 'Cartographie des risques Afrique 2026 — Guide COSO, ISO 31000, Bâle II/III | KHEPRA',
  metaTitleEn: 'Risk Mapping Africa 2026 — COSO, ISO 31000, Basel II/III Guide | KHEPRA',
  metaDescriptionFr: 'Guide complet pour réaliser une cartographie des risques en Afrique : méthodologie COSO, ISO 31000, Bâle II/III, matrice de criticité, prioritisation, plan d\'action. Expertise KHEPRA, 22 ans, 500+ missions.',
  metaDescriptionEn: 'Complete guide to conduct a risk mapping in Africa: COSO methodology, ISO 31000, Basel II/III, criticality matrix, prioritization, action plan. KHEPRA expertise, 22 years, 500+ missions.',
  keywordsFr: [
    'cartographie des risques Afrique',
    'COSO Afrique',
    'ISO 31000 risques',
    'Bâle II/III risques',
    'matrice risques entreprise',
    'gestion des risques PME Afrique',
    'audit risques internes',
    'plan d\'action risques',
    'risques opérationnels banque',
    'KHEPRA cartographie risques',
  ],
  keywordsEn: [
    'risk mapping Africa',
    'COSO Africa',
    'ISO 31000 risk',
    'Basel II/III risk',
    'risk matrix company',
    'risk management SME Africa',
    'risk audit internal',
    'risk action plan',
    'operational risks bank',
    'KHEPRA risk mapping',
  ],
  summaryPointsFr: [
    'Une cartographie des risques efficace repose sur 3 piliers : identification, évaluation et traitement des risques.',
    'Les référentiels COSO, ISO 31000 et Bâle II/III sont les standards internationaux les plus reconnus en Afrique.',
    'Délai moyen : 4 à 8 semaines pour une cartographie complète.',
    '80% des institutions financières africaines ne disposent pas d\'une cartographie actualisée des risques.',
    'KHEPRA a réalisé 200+ cartographies des risques en Afrique avec une réduction moyenne de 35% des incidents.',
  ],
  summaryPointsEn: [
    'An effective risk mapping rests on 3 pillars: identification, assessment and treatment of risks.',
    'COSO, ISO 31000 and Basel II/III are the most recognized international standards in Africa.',
    'Average timeline: 4 to 8 weeks for a complete risk mapping.',
    '80% of African financial institutions do not have an up-to-date risk mapping.',
    'KHEPRA has conducted 200+ risk mappings in Africa with an average 35% reduction in incidents.',
  ],
  definitions: [
    {
      term: 'COSO',
      termEn: 'COSO',
      definition: 'Committee of Sponsoring Organizations of the Treadway Commission. Cadre de référence international pour le contrôle interne et la gestion des risques. Édite 5 composantes : environnement de contrôle, évaluation des risques, activités de contrôle, information et communication, surveillance. En Afrique, le cadre COSO est adopté par les banques et SFD pour répondre aux exigences BCEAO/COBAC.',
      definitionEn: 'Committee of Sponsoring Organizations of the Treadway Commission. International reference framework for internal control and risk management. Publishes 5 components: control environment, risk assessment, control activities, information and communication, monitoring. In Africa, the COSO framework is adopted by banks and MFIs to meet BCEAO/COBAC requirements.',
    },
    {
      term: 'ISO 31000',
      termEn: 'ISO 31000',
      definition: "Norme internationale de gestion des risques applicable à toute organisation. Définit 5 étapes : contexte de l'organisation, identification, analyse, évaluation et traitement des risques. Diffère du COSO en étant plus universelle et moins sectorielle. Adoptée par les entreprises africaines pour une approche globale et non spécifiquement financière.",
      definitionEn: 'International standard for risk management applicable to any organization. Defines 5 steps: organizational context, identification, analysis, evaluation and risk treatment. Differs from COSO by being more universal and less sector-specific. Adopted by African companies for a holistic approach not specifically financial.',
    },
    {
      term: 'Matrice de criticité',
      termEn: 'Criticality matrix',
      definition: "Outil de visualisation des risques selon deux axes : l'impact (gravité des conséquences) et la probabilité (fréquence de survenance). La matrice standard est 5x5 avec 25 cellules. Les zones rouges (impact élevé x probabilité élevée) sont priorisées pour un traitement immédiat. Les zones vertes sont surveillées. Les zones jaunes font l'objet de plans d'action à moyen terme.",
      definitionEn: 'Risk visualization tool along two axes: impact (severity of consequences) and probability (frequency of occurrence). The standard matrix is 5x5 with 25 cells. Red zones (high impact x high probability) are prioritized for immediate treatment. Green zones are monitored. Yellow zones have medium-term action plans.',
    },
  ],
  steps: [
    {
      title: 'Contexte et périmètre de l\'analyse',
      titleEn: 'Context and scope of analysis',
      description: "Définition du périmètre (entité, départements, processus, sous-traitants). Analyse du contexte stratégique, réglementaire, opérationnel et concurrentiel. Choix du référentiel (COSO, ISO 31000, Bâle II/III) selon le secteur. Fixation des critères d'impact et de probabilité. Constitution du comité de pilotage. ",
      descriptionEn: "Definition of scope (entity, departments, processes, subcontractors). Analysis of strategic, regulatory, operational and competitive context. Choice of framework (COSO, ISO 31000, Basel II/III) according to sector. Setting impact and probability criteria. Formation of the steering committee.",
      icon: 'ri-search-eye-line',
    },
    {
      title: 'Identification des risques',
      titleEn: 'Risk identification',
      description: "Inventaire exhaustif des risques par processus : crédit, trésorerie, opérations, IT, conformité, RH, fournisseurs, clients. Méthodes : brainstorming, SWIFT, 5 Whys, diagramme Ishikawa, revue des incidents passés. Classification par typologie (stratégique, opérationnel, financier, réglementaire, juridique, réputation, ESG). ",
      descriptionEn: 'Exhaustive inventory of risks by process: credit, treasury, operations, IT, compliance, HR, suppliers, customers. Methods: brainstorming, SWIFT, 5 Whys, Ishikawa diagram, review of past incidents. Classification by typology (strategic, operational, financial, regulatory, legal, reputational, ESG).',
      icon: 'ri-file-list-3-line',
    },
    {
      title: 'Analyse et scoring des risques',
      titleEn: 'Risk analysis and scoring',
      description: "Évaluation de l'impact (1-5) et de la probabilité (1-5) pour chaque risque. Calcul du risque brut (impact x probabilité). Évaluation des contrôles existants : adéquation, efficacité, maturité. Calcul du risque résiduel (risque brut après contrôles). Matrice de criticité et heatmap. Sélection des 20-30 risques prioritaires.",
      descriptionEn: "Assessment of impact (1-5) and probability (1-5) for each risk. Calculation of gross risk (impact x probability). Evaluation of existing controls: adequacy, effectiveness, maturity. Calculation of residual risk (gross risk after controls). Criticality matrix and heatmap. Selection of 20-30 priority risks.",
      icon: 'ri-bar-chart-2-line',
    },
    {
      title: 'Traitement et plan d\'action',
      titleEn: 'Treatment and action plan',
      description: "Définition des 4 stratégies de traitement : éviter, réduire, transférer (assurance), accepter. Plan d'action détaillé : responsable, échéance, budget, indicateur de performance. Mise en place des nouveaux contrôles. Plan de communication et de formation. Validation par le Conseil d'Administration et le Comité des Risques.",
      descriptionEn: 'Definition of 4 treatment strategies: avoid, reduce, transfer (insurance), accept. Detailed action plan: responsible person, deadline, budget, performance indicator. Implementation of new controls. Communication and training plan. Validation by the Board of Directors and the Risk Committee.',
      icon: 'ri-tools-line',
    },
    {
      title: 'Surveillance et reporting',
      titleEn: 'Monitoring and reporting',
      description: "Mise en place des KPI de risques et des indicateurs d'alerte précoce. Fréquence des revues : mensuelle (risques critiques), trimestrielle (tous les risques). Reporting au CA, au Comité des Risques et aux régulateurs (BCEAO, COBAC). Mise à jour annuelle de la cartographie. Alertes automatiques si un risque dépasse un seuil de vigilance.",
      descriptionEn: 'Implementation of risk KPIs and early warning indicators. Review frequency: monthly (critical risks), quarterly (all risks). Reporting to the board, Risk Committee and regulators (BCEAO, COBAC). Annual update of the risk mapping. Automatic alerts if a risk exceeds a vigilance threshold.',
      icon: 'ri-line-chart-line',
    },
    {
      title: 'Intégration dans la gouvernance et le contrôle interne',
      titleEn: 'Integration into governance and internal control',
      description: "Intégration de la cartographie dans le dispositif de 3 lignes de défense (1re ligne : opérations, 2e ligne : conformité/risques, 3e ligne : audit interne). Lien avec le budget, les plans stratégiques et les PCA. Revue par le Comité des Risques et l'Audit Interne. Documentation pour les missions BCEAO/COBAC.",
      descriptionEn: 'Integration of the risk mapping into the 3 lines of defense (1st line: operations, 2nd line: compliance/risk, 3rd line: internal audit). Link with budget, strategic plans and BCP. Review by the Risk Committee and Internal Audit. Documentation for BCEAO/COBAC missions.',
      icon: 'ri-shield-check-line',
    },
  ],
  references: [
    {
      text: 'COSO ERM Framework — Enterprise Risk Management, 2017',
      textEn: 'COSO ERM Framework — Enterprise Risk Management, 2017',
    },
    {
      text: 'ISO 31000:2018 — Management du risque, lignes directrices',
      textEn: 'ISO 31000:2018 — Risk management, guidelines',
    },
    {
      text: 'Accord de Bâle II — Comité de Bâle sur le contrôle bancaire (CBCB), 2004',
      textEn: 'Basel II Accord — Basel Committee on Banking Supervision (BCBS), 2004',
    },
    {
      text: 'Accord de Bâle III — CBCB, 2010 (révisions 2017-2027)',
      textEn: 'Basel III Accord — BCBS, 2010 (revisions 2017-2027)',
    },
    {
      text: 'Circulaire N°03-2017/CB/C relative aux systèmes de contrôle interne des établissements (UEMOA)',
      textEn: 'Circular N°03-2017/CB/C on internal control systems of institutions (WAEMU)',
    },
    {
      text: 'Règlement COBAC R-2001/07 relatif au système de contrôle interne des établissements de crédit (CEMAC)',
      textEn: 'COBAC Regulation R-2001/07 on the internal control system of credit institutions (CEMAC)',
    },
  ],
  faqs: [
    {
      question: 'Quelle est la différence entre COSO et ISO 31000 ?',
      questionEn: 'What is the difference between COSO and ISO 31000?',
      answer: "COSO est un cadre américain orienté vers le contrôle interne et la gouvernance d'entreprise, initialement conçu pour les entreprises cotées. Il est très adopté par les banques et SFD africains pour répondre aux exigences BCEAO/COBAC. ISO 31000 est une norme internationale plus universelle, applicable à toute organisation, moins sectorielle et plus orientée vers la gestion globale du risque. En Afrique, les banques préfèrent souvent COSO pour les inspections réglementaires, tandis que les entreprises non-financières choisissent ISO 31000 pour sa flexibilité.",
      answerEn: "COSO is an American framework oriented towards internal control and corporate governance, originally designed for listed companies. It is widely adopted by African banks and MFIs to meet BCEAO/COBAC requirements. ISO 31000 is a more universal international standard, applicable to any organization, less sector-specific and more oriented towards holistic risk management. In Africa, banks often prefer COSO for regulatory inspections, while non-financial companies choose ISO 31000 for its flexibility.",
    },
    {
      question: 'Quelle est la fréquence de mise à jour de la cartographie des risques ?',
      questionEn: 'What is the frequency of risk mapping updates?',
      answer: "La cartographie des risques doit être révisée annuellement (minimum) et à chaque événement majeur : fusion/acquisition, lancement de nouveau produit, changement de réglementaire, incident critique, changement de dirigeant. Les risques critiques doivent être revus mensuellement. Les banques sous surveillance renforcée de la BCEAO/COBAC doivent mettre à jour leurs cartographies trimestriellement. KHEPRA recommande une revue à 360° tous les 6 mois.",
      answerEn: "The risk mapping must be reviewed annually (minimum) and at each major event: merger/acquisition, new product launch, regulatory change, critical incident, management change. Critical risks must be reviewed monthly. Banks under enhanced supervision by BCEAO/COBAC must update their mappings quarterly. KHEPRA recommends a 360° review every 6 months.",
    },
    {
      question: "Qu'est-ce qu'un risque résiduel et comment le calculer ?",
      questionEn: 'What is a residual risk and how to calculate it?',
      answer: "Le risque résiduel est le risque qui persiste après application des contrôles existants. Il se calcule par la formule : Risque résiduel = Risque brut (impact x probabilité) − Effet des contrôles. Les contrôles sont évalués selon leur adéquation (couvrent-ils le risque ?), leur efficacité (fonctionnent-ils ?) et leur maturité (durée, fiabilité). Si le risque résiduel reste supérieur à un seuil de tolérance, des mesures correctives doivent être prises.",
      answerEn: "Residual risk is the risk that persists after application of existing controls. It is calculated by the formula: Residual Risk = Gross Risk (impact x probability) − Effect of Controls. Controls are evaluated according to their adequacy (do they cover the risk?), effectiveness (do they work?) and maturity (duration, reliability). If residual risk remains above a tolerance threshold, corrective measures must be taken.",
    },
    {
      question: "Quelles sont les 10 catégories de risques d'une banque africaine ?",
      questionEn: 'What are the 10 risk categories of an African bank?',
      answer: "Les 10 catégories de risques d'une banque selon le référentiel BCEAO/Bâle sont : (1) Risque de crédit — défaut des emprunteurs. (2) Risque de marché — cours, taux, change. (3) Risque de liquidité — incapacité de faire face aux sorties. (4) Risque opérationnel — erreurs, fraudes, systèmes. (5) Risque de conformité — non-respect des lois. (6) Risque de réputation — image, communication. (7) Risque stratégique — choix d'orientation. (8) Risque juridique — litiges, contrats. (9) Risque ESG — environnement, social, gouvernance. (10) Risque de cyber — attaques, piratage. Chaque catégorie est décomposée en sous-risques.",
      answerEn: "The 10 risk categories of a bank according to the BCEAO/Basel framework are: (1) Credit risk — borrower default. (2) Market risk — prices, rates, exchange. (3) Liquidity risk — inability to meet outflows. (4) Operational risk — errors, fraud, systems. (5) Compliance risk — non-compliance with laws. (6) Reputational risk — image, communication. (7) Strategic risk — directional choices. (8) Legal risk — litigation, contracts. (9) ESG risk — environment, social, governance. (10) Cyber risk — attacks, hacking. Each category is broken down into sub-risks.",
    },
    {
      question: "Comment prioriser les risques dans une matrice 5x5 ?",
      questionEn: 'How to prioritize risks in a 5x5 matrix?',
      answer: "La matrice de criticité 5x5 est construite avec 5 niveaux d'impact (1:négligeable, 2:mineur, 3:modéré, 4:majeur, 5:catastrophique) et 5 niveaux de probabilité (1:rare, 2:improbable, 3:possible, 4:probable, 5:quasi-certain). Les risques sont classés en 4 zones : (1) Rouge (20-25) — traitement immédiat, reporting mensuel. (2) Orange (12-18) — plan d'action à 3 mois, suivi trimestriel. (3) Jaune (6-9) — surveillance, plan d'action à 6 mois. (4) Vert (1-4) — acceptation, revue annuelle. Les risques rouges sont portés au Comité des Risques et à la Direction Générale immédiatement.",
      answerEn: "The 5x5 criticality matrix is built with 5 impact levels (1:negligible, 2:minor, 3:moderate, 4:major, 5:catastrophic) and 5 probability levels (1:rare, 2:unlikely, 3:possible, 4:probable, 5:almost certain). Risks are classified into 4 zones: (1) Red (20-25) — immediate treatment, monthly reporting. (2) Orange (12-18) — 3-month action plan, quarterly monitoring. (3) Yellow (6-9) — monitoring, 6-month action plan. (4) Green (1-4) — acceptance, annual review. Red risks are immediately brought to the Risk Committee and General Management.",
    },
    {
      question: "Qu'est-ce que les 3 lignes de défense et leur lien avec la cartographie ?",
      questionEn: 'What are the 3 lines of defense and their link with the risk mapping?',
      answer: "Les 3 lignes de défense sont un modèle de gouvernance des risques : (1) 1re ligne — les opérationnels qui gèrent les risques au quotidien (gestionnaires de crédit, commerciaux, IT). Ils identifient et signalent les risques. (2) 2e ligne — les fonctions de conformité et gestion des risques qui établissent la cartographie, les politiques et le suivi. (3) 3e ligne — l'audit interne qui évalue l'efficacité des 2 premières lignes. La cartographie des risques est l'outil central de la 2e ligne et doit être intégrée dans les 3 lignes. La Circulaire BCEAO 03-2017 et le Règlement COBAC R-2001/07 imposent les 3 lignes.",
      answerEn: "The 3 lines of defense are a risk governance model: (1) 1st line — operational staff who manage risks daily (credit managers, sales, IT). They identify and report risks. (2) 2nd line — compliance and risk management functions who establish the risk mapping, policies and monitoring. (3) 3rd line — internal audit who assess the effectiveness of the first two lines. The risk mapping is the central tool of the 2nd line and must be integrated across all 3 lines. BCEAO Circular 03-2017 and COBAC Regulation R-2001/07 mandate the 3 lines.",
    },
    {
      question: 'Quel est le coût d\'une cartographie des risques par KHEPRA ?',
      questionEn: 'What is the cost of a risk mapping by KHEPRA?',
      answer: "Le coût d'une cartographie des risques KHEPRA varie selon la taille et la complexité : (1) PME non-financière (20-50 employés) — 8 000€ à 15 000€, livrable en 4 semaines. (2) SFD/EMF (10-50 points de service) — 15 000€ à 30 000€, livrable en 6 semaines. (3) Banque de taille moyenne — 30 000€ à 60 000€, livrable en 8 semaines. (4) Grand groupe avec filiales — 60 000€ à 150 000€, livrable en 12 semaines. Le forfait inclut : identification, analyse, matrice, plan d'action, formation et intégration dans les 3 lignes de défense.",
      answerEn: "The cost of a KHEPRA risk mapping varies by size and complexity: (1) Non-financial SME (20-50 employees) — €8,000 to €15,000, deliverable in 4 weeks. (2) MFI (10-50 service points) — €15,000 to €30,000, deliverable in 6 weeks. (3) Medium-sized bank — €30,000 to €60,000, deliverable in 8 weeks. (4) Large group with subsidiaries — €60,000 to €150,000, deliverable in 12 weeks. The package includes: identification, analysis, matrix, action plan, training and integration into the 3 lines of defense.",
    },
    {
      question: "Comment la cartographie des risques s'intègre-t-elle aux PCA et ORSA ?",
      questionEn: 'How does risk mapping integrate with BCP and ORSA?',
      answer: "La cartographie des risques est le socle de deux dispositifs réglementaires : (1) PCA (Plan de Continuité d'Activité) — les risques rouges identifiés dans la cartographie déterminent les fonctions critiques à protéger. Le PCA prévoit les scénarios de crise pour les risques les plus menaçants. (2) ORSA (Own Risk and Solvency Assessment) — requis par les banques systémiques, c'est l'auto-évaluation du risque global qui s'appuie directement sur la cartographie des risques et les scénarios de stress. La cartographie alimente les deux dispositifs en données structurées.",
      answerEn: "The risk mapping is the foundation of two regulatory frameworks: (1) BCP (Business Continuity Plan) — red risks identified in the mapping determine the critical functions to protect. The BCP provides crisis scenarios for the most threatening risks. (2) ORSA (Own Risk and Solvency Assessment) — required for systemic banks, it is the overall risk self-assessment that directly relies on the risk mapping and stress scenarios. The mapping feeds both frameworks with structured data.",
    },
    {
      question: "Quels sont les KPI de risques les plus utilisés en Afrique ?",
      questionEn: 'What are the most used risk KPIs in Africa?',
      answer: "Les 10 KPI de risques les plus utilisés par les institutions financières africaines sont : (1) Taux de créances douteuses (TCD) / NPL ratio. (2) Ratio de couverture des créances douteuses. (3) Ratio de solvabilité (Bâle III). (4) Ratio LCR (liquidité). (5) Nombre d'incidents opérationnels mensuels. (6) Taux de réalisation du plan d'action risques. (7) Nombre de risques rouges. (8) Retard de reporting des risques. (9) Taux de formation du personnel aux risques. (10) Nombre de déclarations LBC/FT (alertes). KHEPRA met en place un tableau de bord avec ces 10 KPI.",
      answerEn: "The 10 most used risk KPIs by African financial institutions are: (1) Non-Performing Loan (NPL) ratio. (2) NPL coverage ratio. (3) Solvency ratio (Basel III). (4) LCR ratio (liquidity). (5) Number of monthly operational incidents. (6) Risk action plan completion rate. (7) Number of red risks. (8) Risk reporting delays. (9) Staff risk training rate. (10) Number of AML/CFT declarations (alerts). KHEPRA implements a dashboard with these 10 KPIs.",
    },
    {
      question: "Quels sont les outils de cartographie des risques utilisés par KHEPRA ?",
      questionEn: 'What risk mapping tools does KHEPRA use?',
      answer: "KHEPRA utilise une suite d'outils adaptés aux réalités africaines : (1) Excel/Google Sheets — matrices et heatmaps pour les petites structures. (2) Power BI / Tableau — dashboards interactifs pour les banques. (3) Outils dédiés (ARMIS, OpenPages, MetricStream) pour les grandes institutions. (4) KHEPRA Risk Map — outil propriétaire développé en interne, avec scoring automatique, alertes et reporting. (5) Spreadsheets avancés — modèles avec macros pour le calcul automatique des risques résiduels et des KPI. L'outil choisi dépend du budget, de la maturité IT et de la taille de l'institution.",
      answerEn: "KHEPRA uses a suite of tools adapted to African realities: (1) Excel/Google Sheets — matrices and heatmaps for small structures. (2) Power BI / Tableau — interactive dashboards for banks. (3) Dedicated tools (ARMIS, OpenPages, MetricStream) for large institutions. (4) KHEPRA Risk Map — proprietary tool developed internally, with automatic scoring, alerts and reporting. (5) Advanced spreadsheets — models with macros for automatic calculation of residual risks and KPIs. The chosen tool depends on budget, IT maturity and institution size.",
    },
  ],
  internalLinks: [
    {
      label: 'Hub Connaissance — Risques & Due Diligence',
      labelEn: 'Knowledge Hub — Risk & Due Diligence',
      href: '/knowledge-hub/due-diligence',
    },
    {
      label: "Service Gestion des Risques — KHEPRA",
      labelEn: 'Risk Management Service — KHEPRA',
      href: '/services',
    },
    {
      label: 'Diagnostic risques — Outil en ligne gratuit',
      labelEn: 'Risk diagnostic — Free online tool',
      href: '/tools/diagnostic-risques',
    },
    {
      label: 'Série 3 Lignes de Défense — Circulaire BCEAO 03-2017',
      labelEn: '3 Lines of Defense Series — BCEAO Circular 03-2017',
      href: '/blog/3-lignes-defense-circulaire-03-2017',
    },
    {
      label: 'Conformité BCEAO — Guide complet',
      labelEn: 'BCEAO Compliance — Complete Guide',
      href: '/geo-hub/mise-en-conformite-bceao',
    },
    {
      label: 'Préparer une mission d\'inspection BCEAO — Checklist',
      labelEn: 'How to Prepare for a BCEAO Inspection Mission — Checklist',
      href: '/geo-hub/preparer-mission-bceao',
    },
  ],
  ctaVariant: 'diagnostic',
  ctaContextFr: 'Cartographiez vos risques avec KHEPRA',
  ctaContextEn: 'Map your risks with KHEPRA',
  peopleAlsoAsk: [
    {
      question: 'Quelle est la différence entre COSO et ISO 31000 ?',
      questionEn: 'What is the difference between COSO and ISO 31000?',
      answer: 'COSO est un cadre américain orienté contrôle interne et gouvernance, très adopté par les banques et SFD africains pour les inspections BCEAO/COBAC. ISO 31000 est une norme internationale plus universelle, applicable à toute organisation, moins sectorielle et plus orientée gestion globale du risque.',
      answerEn: 'COSO is an American framework oriented towards internal control and governance, widely adopted by African banks and MFIs for BCEAO/COBAC inspections. ISO 31000 is a more universal international standard, applicable to any organization, less sector-specific and more oriented towards holistic risk management.',
    },
    {
      question: "Qu'est-ce qu'un risque résiduel et comment le calculer ?",
      questionEn: 'What is residual risk and how to calculate it?',
      answer: 'Le risque résiduel est le risque persistant après application des contrôles. Formule : Risque résiduel = Risque brut (impact x probabilité) − Effet des contrôles. Les contrôles sont évalués selon adéquation, efficacité et maturité. Si le risque résiduel dépasse le seuil de tolérance, des mesures correctives sont requises.',
      answerEn: 'Residual risk is the risk that persists after applying controls. Formula: Residual Risk = Gross Risk (impact x probability) − Effect of Controls. Controls are evaluated by adequacy, effectiveness and maturity. If residual risk exceeds the tolerance threshold, corrective measures are required.',
    },
    {
      question: "Quelles sont les 10 catégories de risques d'une banque africaine ?",
      questionEn: 'What are the 10 risk categories of an African bank?',
      answer: 'Les 10 catégories sont : (1) crédit, (2) marché, (3) liquidité, (4) opérationnel, (5) conformité, (6) réputation, (7) stratégique, (8) juridique, (9) ESG, (10) cyber. Chaque catégorie est décomposée en sous-risques selon le référentiel BCEAO/Bâle.',
      answerEn: 'The 10 categories are: (1) credit, (2) market, (3) liquidity, (4) operational, (5) compliance, (6) reputational, (7) strategic, (8) legal, (9) ESG, (10) cyber. Each category is broken down into sub-risks according to the BCEAO/Basel framework.',
    },
    {
      question: "Qu'est-ce que les 3 lignes de défense en gestion des risques ?",
      questionEn: 'What are the 3 lines of defense in risk management?',
      answer: 'Les 3 lignes sont : (1) 1re ligne — opérationnels gérant les risques quotidiens. (2) 2e ligne — conformité/risques établissant la cartographie et les politiques. (3) 3e ligne — audit interne évaluant l\'efficacité des 2 premières lignes. La cartographie est l\'outil central de la 2e ligne.',
      answerEn: 'The 3 lines are: (1) 1st line — operational staff managing daily risks. (2) 2nd line — compliance/risk functions establishing the mapping and policies. (3) 3rd line — internal audit assessing the effectiveness of the first two lines. The mapping is the central tool of the 2nd line.',
    },
    {
      question: 'Quel est le coût d\'une cartographie des risques par KHEPRA ?',
      questionEn: 'What is the cost of a risk mapping by KHEPRA?',
      answer: 'Le coût varie : PME (20-50 employés) 8 000€-15 000€, SFD/EMF 15 000€-30 000€, banque moyenne 30 000€-60 000€, grand groupe 60 000€-150 000€. Le forfait inclut identification, analyse, matrice, plan d\'action, formation et intégration dans les 3 lignes de défense.',
      answerEn: 'Cost varies: SME (20-50 employees) €8,000-€15,000, MFI €15,000-€30,000, medium bank €30,000-€60,000, large group €60,000-€150,000. The package includes identification, analysis, matrix, action plan, training and integration into the 3 lines of defense.',
    },
    {
      question: "Quels sont les risques émergents en Afrique que les cartographies traditionnelles ne capturent pas ?",
      questionEn: "What are the emerging risks in Africa that traditional risk mappings don't capture?",
      answer: "Les 6 risques émergents sous-estimés en Afrique sont : (1) Risque climatique physique — inondations, sécheresses, cyclones impactant les chaînes d'approvisionnement et les actifs. (2) Risque de transition — coût de la migration vers une économie bas carbone (taxe carbone, normes). (3) Risque cyber — multiplication des ransomwares ciblant les banques et PME africaines (+200% en 2024-2025). (4) Risque de change — volatilité accrue du FCFA face au dollar, pressions sur la parité fixe. (5) Risque géopolitique — instabilité au Sahel, sanctions CEDEAO, insécurité dans le Golfe de Guinée. (6) Risque d'IA — biais algorithmiques, perte d'emplois, conformité des modèles. KHEPRA intègre ces 6 risques dans ses cartographies avancées.",
      answerEn: "The 6 underestimated emerging risks in Africa are: (1) Physical climate risk — floods, droughts, cyclones impacting supply chains and assets. (2) Transition risk — cost of migrating to a low-carbon economy (carbon tax, standards). (3) Cyber risk — multiplication of ransomware targeting African banks and SMEs (+200% in 2024-2025). (4) Currency risk — increased FCFA volatility against the dollar, pressure on the fixed parity. (5) Geopolitical risk — Sahel instability, ECOWAS sanctions, Gulf of Guinea insecurity. (6) AI risk — algorithmic bias, job losses, model compliance. KHEPRA integrates these 6 risks into its advanced mappings.",
    },
    {
      question: "Comment lier la cartographie des risques au plan stratégique de l'entreprise ?",
      questionEn: "How to link risk mapping to the company's strategic plan?",
      answer: "Le lien entre cartographie des risques et plan stratégique s'articule en 4 étapes : (1) Alignement — les objectifs stratégiques (croissance, rentabilité, innovation) sont croisés avec les risques identifiés dans la cartographie. Chaque objectif a un profil de risque. (2) Appétit au risque — le CA définit le niveau de risque acceptable pour chaque objectif stratégique (ex : risque de crédit max 5% NPL). (3) Budget — les plans d'action de traitement des risques sont intégrés au budget annuel (ligne 'gestion des risques'). (4) KPI — les indicateurs de risques deviennent des KPI stratégiques suivis par le CA (ex : score de risque global, nombre de risques rouges). Cette intégration transforme la cartographie d'un exercice de conformité en un outil de pilotage stratégique.",
      answerEn: "The link between risk mapping and strategic plan is structured in 4 steps: (1) Alignment — strategic objectives (growth, profitability, innovation) are cross-referenced with risks identified in the mapping. Each objective has a risk profile. (2) Risk appetite — the board defines the acceptable risk level for each strategic objective (e.g., credit risk max 5% NPL). (3) Budget — risk treatment action plans are integrated into the annual budget ('risk management' line). (4) KPIs — risk indicators become strategic KPIs monitored by the board (e.g., overall risk score, number of red risks). This integration transforms mapping from a compliance exercise into a strategic management tool.",
    },
    {
      question: "Qu'est-ce que l'analyse de scénarios (scenario analysis) et comment l'appliquer en Afrique ?",
      questionEn: "What is scenario analysis and how to apply it in Africa?",
      answer: "L'analyse de scénarios est une technique de gestion des risques qui consiste à simuler des situations extrêmes pour évaluer leur impact. En Afrique, 5 scénarios sont pertinents : (1) Dévaluation du FCFA de 20% — impact sur la dette en devises, le coût des importations, la solvabilité. (2) Défaut souverain — un État UEMOA suspend le service de sa dette, impact sur les banques détentrices de titres souverains. (3) Crise politique majeure — fermeture des frontières, couvre-feu, paralysie économique pendant 3 mois. (4) Cyberattaque massive — paralysie du système d'information pendant 7 jours, perte de données. (5) Pandémie ou catastrophe naturelle — interruption d'activité 3 mois. Chaque scénario est modélisé avec des hypothèses quantifiées et un plan de réponse. La BCEAO exige ces stress tests pour les banques systémiques.",
      answerEn: "Scenario analysis is a risk management technique that simulates extreme situations to evaluate their impact. In Africa, 5 scenarios are relevant: (1) 20% FCFA devaluation — impact on foreign currency debt, import costs, solvency. (2) Sovereign default — a WAEMU State suspends its debt service, impact on banks holding sovereign securities. (3) Major political crisis — border closure, curfew, economic paralysis for 3 months. (4) Massive cyberattack — information system paralysis for 7 days, data loss. (5) Pandemic or natural disaster — 3-month business interruption. Each scenario is modeled with quantified assumptions and a response plan. BCEAO requires these stress tests for systemic banks.",
    },
    {
      question: "Comment former les équipes à la culture du risque en Afrique ?",
      questionEn: "How to train teams in risk culture in Africa?",
      answer: "La formation à la culture du risque en Afrique repose sur 5 piliers : (1) Sensibilisation — sessions trimestrielles de 2h pour tous les employés sur les risques opérationnels, la fraude, la cybersécurité. (2) Formation métier — les équipes crédit, conformité, IT reçoivent une formation technique approfondie (40h/an). (3) Risk champions — désignation de 1 référent risque par département, formé et responsable de la remontée des incidents. (4) Simulations — exercices annuels de crise (PCA, cyberattaque, fraude) avec debriefing. (5) Incentives — intégration d'objectifs de gestion des risques dans les bonus (ex : zéro incident critique, 100% de déclarations LBC/FT). La culture du risque doit être portée par la direction générale et le CA pour être efficace.",
      answerEn: "Risk culture training in Africa rests on 5 pillars: (1) Awareness — quarterly 2-hour sessions for all employees on operational risks, fraud, cybersecurity. (2) Job-specific training — credit, compliance, IT teams receive in-depth technical training (40h/year). (3) Risk champions — designation of 1 risk referent per department, trained and responsible for incident escalation. (4) Simulations — annual crisis exercises (BCP, cyberattack, fraud) with debriefing. (5) Incentives — integration of risk management objectives into bonuses (e.g., zero critical incidents, 100% AML/CFT declarations). Risk culture must be driven by general management and the board to be effective.",
    },
    {
      question: "Quels sont les bénéfices concrets d'une cartographie des risques bien menée ?",
      questionEn: "What are the concrete benefits of a well-conducted risk mapping?",
      answer: "Les 7 bénéfices concrets d'une cartographie des risques bien menée sont : (1) Réduction des pertes — les entreprises avec cartographie réduisent leurs incidents de 35% en moyenne. (2) Conformité réglementaire — 100% de conformité aux exigences BCEAO/COBAC. (3) Prime d'assurance — réduction de 10-20% des primes grâce à la démonstration d'une gestion proactive. (4) Notation bancaire — amélioration du score de crédit, accès à des taux préférentiels. (5) Décision d'investissement — les investisseurs valorisent les entreprises avec risk management mature. (6) Résilience — capacité à absorber les chocs sans rupture d'activité. (7) Culture d'entreprise — responsabilisation des équipes, transparence, amélioration continue. KHEPRA mesure ces bénéfices chez tous ses clients.",
      answerEn: "The 7 concrete benefits of a well-conducted risk mapping are: (1) Loss reduction — companies with mapping reduce their incidents by 35% on average. (2) Regulatory compliance — 100% compliance with BCEAO/COBAC requirements. (3) Insurance premium — 10-20% reduction in premiums through demonstration of proactive management. (4) Bank rating — improved credit score, access to preferential rates. (5) Investment decision — investors value companies with mature risk management. (6) Resilience — ability to absorb shocks without business disruption. (7) Corporate culture — team empowerment, transparency, continuous improvement. KHEPRA measures these benefits for all its clients.",
    },
    {
      question: "Qu'est-ce que le risque de réputation et comment le gérer en Afrique à l'ère des réseaux sociaux ?",
      questionEn: "What is reputational risk and how to manage it in Africa in the age of social media?",
      answer: "Le risque de réputation est la menace qu'un événement négatif (scandale, fraude, accident, déclaration maladroite) détruise la confiance des parties prenantes. En Afrique, il est amplifié par les réseaux sociaux (WhatsApp, Facebook, TikTok) où l'information circule instantanément sans vérification. Gestion en 5 étapes : (1) Veille — monitoring permanent des mentions de l'entreprise sur les réseaux sociaux et médias. (2) Procédure de crise — cellule de crise (DG, communication, juridique), messages clés pré-rédigés, porte-parole formé. (3) Réactivité — réponse dans l'heure sur les réseaux sociaux, communiqué de presse sous 4h. (4) Transparence — reconnaissance des faits, excuses si nécessaire, plan d'action correctif. (5) Reconstruction — actions positives, témoignages, communication proactive. KHEPRA prépare des plans de gestion de crise réputationnelle.",
      answerEn: "Reputational risk is the threat that a negative event (scandal, fraud, accident, clumsy statement) destroys stakeholder trust. In Africa, it is amplified by social media (WhatsApp, Facebook, TikTok) where information circulates instantly without verification. Management in 5 steps: (1) Monitoring — permanent monitoring of company mentions on social media and media. (2) Crisis procedure — crisis unit (CEO, communication, legal), pre-drafted key messages, trained spokesperson. (3) Responsiveness — response within the hour on social media, press release within 4h. (4) Transparency — acknowledgment of facts, apology if necessary, corrective action plan. (5) Reconstruction — positive actions, testimonials, proactive communication. KHEPRA prepares reputational crisis management plans.",
    },
    {
      question: "Comment prioriser les risques quand tout semble critique ? La méthode MoSCoW appliquée aux risques.",
      questionEn: "How to prioritize risks when everything seems critical? The MoSCoW method applied to risks.",
      answer: "Face à un portefeuille de 50+ risques, la priorisation est essentielle. La méthode MoSCoW adaptée aux risques : (1) Must have (risques critiques) — impact > 4 ET probabilité > 3 sur la matrice 5x5. Menacent la survie de l'entreprise. Plan d'action sous 30 jours. Budget illimité. (2) Should have (risques majeurs) — impact > 3 ET probabilité > 2. Impact fort sur les objectifs. Plan d'action sous 90 jours. Budget dédié. (3) Could have (risques modérés) — impact > 2 ET probabilité > 1. Traitement sous 6 mois. Budget limité. (4) Won't have (risques mineurs) — impact ≤ 2. Acceptation ou surveillance. Pas de budget. Cette méthode réduit de 50% le nombre de risques à traiter immédiatement et permet de concentrer les ressources sur l'essentiel.",
      answerEn: "Faced with a portfolio of 50+ risks, prioritization is essential. The MoSCoW method adapted to risks: (1) Must have (critical risks) — impact > 4 AND probability > 3 on the 5x5 matrix. Threaten the company's survival. Action plan within 30 days. Unlimited budget. (2) Should have (major risks) — impact > 3 AND probability > 2. Strong impact on objectives. Action plan within 90 days. Dedicated budget. (3) Could have (moderate risks) — impact > 2 AND probability > 1. Treatment within 6 months. Limited budget. (4) Won't have (minor risks) — impact ≤ 2. Acceptance or monitoring. No budget. This method reduces by 50% the number of risks to treat immediately and allows concentrating resources on essentials.",
    },
  ],
};