const common = {
  faq: { title: 'よくある質問', badge: 'FAQ', description: '当社のサービスに関するよくある質問への回答を見つけてください。' },
  contact: { title: 'お問い合わせ', subtitle: 'あなたの戦略的プロジェクトについてご相談ください', name: '氏名', email: 'メールアドレス', phone: '電話番号', company: '組織', message: 'メッセージ', submit: '送信', sending: '送信中…', success: 'メッセージが送信されました！', error: 'エラーが発生しました。', address: '住所', addressText: 'トーゴ、ロメ' },
  footer: { tagline: 'コンサルティング、財務監査、ガバナンス、デジタルトランスフォーメーションにおける戦略的パートナー', quickLinks: 'クイックリンク', services: 'サービス', about: '会社概要', blog: 'ブログ', contact: 'お問い合わせ', legalLinks: '法的事項', privacy: 'プライバシーポリシー', terms: '利用規約', followUs: 'フォローする', rights: '全著作権所有。' },
  common: { learnMore: '詳細を見る' },
  cta: { diagnostic_free: '無料診断', diagnostic_subtitle: '2時間以内に回答 · 義務なし' },
  leadMagnet: { whitepaper: { title: 'ホワイトペーパーをダウンロード', description: '詳細な分析と実用的な推奨事項。', button: 'ホワイトペーパーをダウンロード' }, webinar: { title: '次回のウェビナーに参加', description: '専門家とライブで交流。', button: 'ウェビナーに登録' }, diagnostic: { title: '無料戦略診断', description: '専門家と30分間、状況を分析します。', button: '診断を開始' }, newsletter: { title: '戦略的ニュースレターを受け取る', description: '独占分析を直接受信トレイに。', button: 'ニュースレターを購読' } },
  monitoring: { title: '技術モニタリング', subtitle: '404エラーと応答時間', loading: 'データ読み込み中…', retry: '再試行', timeRange: { '24h': '24時間', '7d': '7日間', '30d': '30日間' }, stats: { total404: '404エラー', total404Sub: '欠落ページ', totalErrors: 'HTTP/JSエラー', totalErrorsSub: 'リクエストとスクリプト', avgResponse: '平均API時間', avgResponseSub: 'ms', avgPageLoad: 'ページ読み込み', avgPageLoadSub: 'ms' }, notFound: { title: 'トップ404 URL', subtitle: '最も頻繁に欠落するページ', url: 'URL', count: '発生回数', empty: 'エラーは検出されていません' }, performance: { title: 'API応答時間', subtitle: '平均値と最大値', tooltipAvg: '平均', tooltipMax: '最大', tooltipCount: 'リクエスト', empty: 'データなし' }, topErrors: { title: '主なエラー', subtitle: '最も頻繁なエラー', empty: 'エラーなし' }, errorLog: { title: 'エラーログ', subtitle: '最近のエラー', type: 'タイプ', message: 'メッセージ', url: 'URL', date: '日付', empty: '最近のエラーなし' }, navigation: { title: 'ナビゲーション', subtitle: 'ページ読み込み時間', empty: 'データなし' } },
  dashboard: { login: { title: 'ダッシュボード', subtitle: '管理者アクセス', passwordLabel: 'パスワード', passwordPlaceholder: 'パスワードを入力', loginButton: 'ログイン', incorrectPassword: 'パスワードが正しくありません' }, header: { title: 'ダッシュボード', subtitle: 'コンバージョンとパフォーマンスの追跡', timeRange: { '7d': '7日間', '30d': '30日間', '90d': '90日間', all: 'すべて' }, refreshButton: '更新' }, loading: 'データ読み込み中…', kpis: { totalLeads: { title: '総リード', subtitle: '新規' } }, pipeline: { title: 'コンバージョンパイプライン' }, sources: { title: '獲得ソース' }, formTypes: { title: 'フォームタイプ別パフォーマンス', ofTotal: '全体の' }, recentLeads: { title: '最近のリード', table: { date: '日付', contact: '連絡先', organization: '組織', type: 'タイプ', score: 'スコア', status: 'ステータス', source: 'ソース' } }, status: { new: '新規', meeting_scheduled: '会議予定', qualified: '適格', converted: '変換済み', lost: '失注' }, formType: { contact: 'お問い合わせ', diagnostic: '診断', expert: '専門家', newsletter: 'ニュースレター' }, metrics: { toolCompletions: { title: '完了ツール', subtitle: '診断' } }, diagnostics: { title: '最近の診断', table: { date: '日付', tool: 'ツール', score: 'スコア' } }, downloads: { title: '最近のダウンロード', table: { date: '日付', resource: 'リソース', contact: '連絡先', country: '国' }, unknownResource: '不明なリソース' }, noData: 'データなし', retry: '再試行' },
};

export default common;