const common = {
  faq: {
    title: 'Sogs-n-togs sẽn sokd wʋsg', badge: 'FAQ',
    description: 'Ra-yã nes sẽn leokd sogs-n-togs sẽn sokd wʋsg n kẽnd tõnd sagls sẽn yaa baas-tẽnga, gesg laodse, naam sẽn be ligd rota, teed pĩnd sẽn toeemdao wã zugu, la tõnd tʋʋm zĩisi sẽn be Afriki.',
    q1: 'Bõe yĩng tɩ y tõe n yãk KHEPRA EXPERTS n yaa sagend sẽn be Afriki ?',
    a1: 'KHEPRA EXPERTS yaa Afriki sagend sẽn tũud a toore, n tar yʋʋm 22 minim n tũ Afriki Tẽng-sʋka la Tẽng-sʋg-sʋka.',
    q2: 'Yãmb sõngda organisasyõ bʋs sẽn be sagl pʋgẽ ?',
    a2: 'Tõnd sõngda PME, startups, ligd-bõn-pʋsʋm zĩisi, kompaani kãsemsa, NGO, gomnaam zĩisi la dũniyã gill organisasyõ n be Afriki.',
  },
  contact: { title: 'Tãase ne tõndo', subtitle: 'Bɩ d gom y sagl baas-tẽnga, gesg laodse maa organisasyõ toeemdao wã yelle', name: 'Yʋʋr fãa', email: 'E-meel', phone: 'Telefoon', company: 'Organisasyõ', message: 'Koe-mooneg', submit: 'Tʋmse', sending: 'Tʋmsdame…', success: 'Koe-mooneg tʋmsa neere ! D na n leoka yãmb n zems wagd 24.', error: 'Zabg n zĩndi. Bɩ y mak n leoke.', address: 'Adrɛs', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Yãmb sagend sẽn be sagl, gesg laodse, naam la teed pĩnd toeemdao wã yĩng n na n tall lebg sẽn kõn sɛɛm Afriki', quickLinks: 'Soaya sẽn yaa Tao-Tao', services: 'Tʋʋm sõma', about: 'Tõnd yell', blog: 'Blog', contact: 'Tãase', legalLinks: 'Tõod yell', privacy: 'Soll sẽn gũud y nens yembdo', terms: 'Tʋʋmd wã tõod', followUs: 'Tũ-y tõndo', rights: 'Pãng fãa gũudame.' },
  common: { learnMore: 'Bãng n paase' },
  cta: { diagnostic_free: 'Gesg sẽn ya zaalem', diagnostic_subtitle: 'Leokr n be wagd 2 pʋgẽ · Pʋleng ka be ye' },
  leadMagnet: { whitepaper: { title: 'Zẽk-y tõnd Gaf Pɛɛlga', description: 'Gesg sẽn yaa zulmẽ la noy sẽn tõe n tall n tũ.', button: 'Zẽk Gaf Pɛɛlga' }, webinar: { title: 'Kẽ-y tõnd Webinaire sẽn Wate', description: 'Gom-y ne tõnd bãngdb n tar sõmblem.', button: 'Gʋls-y n yiis y yʋʋr Webinaire wã yĩng' }, diagnostic: { title: 'Gesg Baas-tẽng sẽn ya Zaalem', description: 'Minit 30 ne bãngd n na n ges y sẽn be zĩig ninga.', button: 'Sɩng-y gesga' }, newsletter: { title: 'Deeg-y tõnd Kiba-kẽndr sẽn yaa Baas-tẽng', description: 'Gesg sẽn yaa a ye tãa, y e-meel pʋgẽ.', button: 'Gʋls-y n yiis y yʋʋr Kiba-kẽndrã yĩng' } },
  monitoring: { title: 'Teknik gũusg', subtitle: 'Zabg 404 la leokr wakato', loading: 'Dõnɛɛ wã loedgame…', retry: 'Mak-y n leoke', timeRange: { '24h': 'Wagd 24', '7d': 'Daar 7', '30d': 'Daar 30' }, stats: { total404: 'Zabg 404', total404Sub: 'Pɛger sẽn ka be', totalErrors: 'Zabg HTTP/JS', totalErrorsSub: 'g la gʋls-biis', avgResponse: 'Sʋka API wakato', avgResponseSub: 'ms', avgPageLoad: 'Pɛger loedre', avgPageLoadSub: 'ms' }, notFound: { title: 'URL 404 sẽn yaa Yĩngri', subtitle: 'Pɛger sẽn ka tar n yaa wʋsg', url: 'URL', count: 'Yɩɩm', empty: 'Zabg 404 ka be ye' }, performance: { title: 'API Leokr Wakato', subtitle: 'Sʋka la yĩngri', tooltipAvg: 'Sʋka', tooltipMax: 'Yĩngri', tooltipCount: 'ga', empty: 'Dõnɛɛ ka be ye' }, topErrors: { title: 'Zabg sẽn ya wʋsg', subtitle: 'Zabg sẽn tar n yaa wʋsgo', empty: 'Zabg ka be ye' }, errorLog: { title: 'Zabg gʋlsg sebr', subtitle: 'Zabg sẽn yaa yaoolem', type: 'Sõor bude', message: 'Koe-mooneg', url: 'URL', date: 'Daare', empty: 'Zabg yaoolem ka be ye' }, navigation: { title: 'Kẽndr', subtitle: 'Pɛger loedr wakato', empty: 'Dõnɛɛ ka be ye' } },
  dashboard: { login: { title: 'Ges-taabl', subtitle: 'Kẽndr bõn naand-sãambã yĩng bala', passwordLabel: 'Gʋls sẽn solgda', passwordPlaceholder: 'Kẽes-y gʋls sẽn solgdã', loginButton: 'Kẽ-y', incorrectPassword: 'Gʋls sẽn solgdã pa zems ye' }, header: { title: 'Ges-taabl', subtitle: 'Teed toeemdao la tʋʋmd wã gũusgu', timeRange: { '7d': 'Daar 7 sẽn looge', '30d': 'Daar 30 sẽn looge', '90d': 'Daar 90 sẽn looge', all: 'Wakat fãa' }, refreshButton: 'Leok-y' }, loading: 'Dõnɛɛ wã loedgame…', kpis: { totalLeads: { title: 'Leeds fãa', subtitle: 'paalse' } }, pipeline: { title: 'Teed toeemd wã so-bãndi' }, sources: { title: 'Bõn-paam zĩisi' }, formTypes: { title: 'Tʋʋmd sẽn zems formuleer soab fãa', ofTotal: 'fãa pʋgẽ' }, recentLeads: { title: 'Leeds sẽn yaa yaoolem', table: { date: 'Daare', contact: 'Soab', organization: 'Organisasyõ', type: 'Sõor bude', score: 'Nõmba', status: 'Sẽn be', source: 'Zĩig' } }, status: { new: 'Paalg', meeting_scheduled: 'Tigiss n yeelame', qualified: 'Sõma n beeme', converted: 'Toeemame', lost: 'Meneme' }, formType: { contact: 'Tãasgo', diagnostic: 'Gesgo', expert: 'Bãngda', newsletter: 'Kiba-kẽndre' }, metrics: { toolCompletions: { title: 'Gese-paam tʋʋm sõma', subtitle: 'Gesg tʋma' } }, diagnostics: { title: 'Yaoolem Gesga', table: { date: 'Daare', tool: 'Teedo', score: 'Nõmba' } }, downloads: { title: 'Yaoolem Zẽkra', table: { date: 'Daare', resource: 'Bõn-naandga', contact: 'Soaba', country: 'Tẽnga' }, unknownResource: 'Bõn-naandg sẽn ka bãngd ye' }, noData: 'Dõnɛɛ ka be wakat kãng pʋgẽ ye', retry: 'Mak-y n leoke' },
};
export default common;



