export const CONTROLE_DATA = {
  fr: {
    seo: {
      title: 'Contrôle interne et gestion de trésorerie PME Afrique 2025 | KHEPRA EXPERTS',
      description: "Comment mettre en place un contrôle interne efficace et maîtriser sa trésorerie pour sécuriser la croissance des PME en Afrique de l'Ouest. Réduire les fraudes, optimiser le BFR, améliorer la rentabilité.",
      keywords: 'contrôle interne, gestion trésorerie, PME Afrique, audit, fraude, BFR, rapprochement bancaire, BCEAO, DAF externalisé, Togo, Bénin, Côte d\'Ivoire',
    },
    badge: 'Thought Leadership — Senior Partner',
    title: 'Contrôle interne et gestion de la trésorerie :\nles deux piliers de la performance financière des PME africaines',
    excerpt: "Le contrôle interne et la gestion de la trésorerie sont les deux piliers fondamentaux de la performance financière. En Afrique de l'Ouest, maîtriser ces deux dimensions n'est pas seulement une bonne pratique : c'est une condition de survie et de croissance pour les PME.",
    breadcrumb: { home: 'Accueil', blog: 'Blog', current: 'Contrôle interne & Trésorerie' },
    date: '20 avril 2025',
    readTime: '12 min de lecture',
    authorRole: 'Directeur Associé & Fondateur, KHEPRA EXPERTS',
    allArticles: 'Tous les articles',
    sections: [
      { id: 'enjeux', title: 'Enjeux du contrôle interne', icon: 'ri-shield-check-line' },
      { id: 'principes', title: 'Principes fondamentaux', icon: 'ri-list-check-2' },
      { id: 'tresorerie', title: 'Maîtriser la trésorerie', icon: 'ri-money-dollar-circle-line' },
      { id: 'bfr', title: 'Optimiser le BFR', icon: 'ri-arrow-left-right-line' },
      { id: 'outils', title: 'Outils & tableau de bord', icon: 'ri-dashboard-line' },
      { id: 'faq', title: 'Questions fréquentes', icon: 'ri-chat-3-line' },
    ],
    tagsLabel: ['Contrôle interne', 'Trésorerie', 'PME', 'Finance', 'Gouvernance', 'Audit', 'DAF externalisé'],
    risks: [
      { icon: 'ri-spy-line', color: 'text-red-600', bg: 'bg-red-50', border: 'border-red-200', title: 'Fraudes internes', value: '5 à 8%', desc: 'du CA perdu en moyenne sans contrôle interne structuré' },
      { icon: 'ri-error-warning-line', color: 'text-amber-600', bg: 'bg-amber-50', border: 'border-amber-200', title: 'Erreurs comptables', value: 'Décisions', desc: 'stratégiques erronées basées sur des données fausses' },
      { icon: 'ri-government-line', color: 'text-orange-600', bg: 'bg-orange-50', border: 'border-orange-200', title: 'Non-conformités', value: 'Sanctions', desc: 'fiscales et administratives évitables' },
      { icon: 'ri-bank-line', color: 'text-rose-600', bg: 'bg-rose-50', border: 'border-rose-200', title: 'Perte de confiance', value: 'Accès', desc: 'au financement compromis pour les investisseurs' },
    ],
    principles: [
      { num: '01', icon: 'ri-group-line', title: 'Séparation des tâches', desc: "Les fonctions d'autorisation, d'exécution, d'enregistrement et de contrôle doivent être exercées par des personnes différentes pour les processus sensibles." },
      { num: '02', icon: 'ri-file-text-line', title: 'Documentation des processus', desc: "Chaque processus clé doit être décrit par écrit : qui fait quoi, quand, comment, avec quelles autorisations. Indispensable pour les audits et due diligences." },
      { num: '03', icon: 'ri-eye-line', title: 'Contrôles préventifs & détectifs', desc: "Les contrôles préventifs empêchent les erreurs avant qu'elles surviennent (validations, autorisations). Les contrôles détectifs les identifient après coup (rapprochements, revues)." },
      { num: '04', icon: 'ri-refresh-line', title: 'Rapprochement bancaire régulier', desc: "Mensuel au minimum, hebdomadaire pour les entreprises à fort volume. Permet de détecter erreurs, prélèvements non autorisés et fraudes." },
    ],
    bfrLeviers: [
      {
        icon: 'ri-user-received-line', color: 'text-emerald-600', bg: 'bg-emerald-50', border: 'border-emerald-200',
        title: 'Réduire les délais clients',
        actions: ['Facturation immédiate à la livraison', 'Relances systématiques à J+30, J+45, J+60', 'Escompte pour paiement anticipé', 'Acomptes sur commandes importantes'],
      },
      {
        icon: 'ri-store-line', color: 'text-amber-600', bg: 'bg-amber-50', border: 'border-amber-200',
        title: 'Allonger les délais fournisseurs',
        actions: ['Négocier des délais de paiement à 60-90 jours', 'Centraliser les achats pour plus de pouvoir', 'Utiliser les facilités de paiement proposées', 'Prioriser les fournisseurs offrant les meilleures conditions'],
      },
      {
        icon: 'ri-archive-line', color: 'text-brand-600', bg: 'bg-brand-50', border: 'border-brand-200',
        title: 'Optimiser les stocks',
        actions: ['Identifier et liquider les stocks dormants', 'Mettre en place un suivi de la rotation des stocks', 'Adopter une politique de réapprovisionnement juste-à-temps', 'Négocier des livraisons plus fréquentes en petites quantités'],
      },
    ],
    faq: [
      { q: "Qu'est-ce que le contrôle interne en entreprise ?", a: "Le contrôle interne est l'ensemble des dispositifs mis en place par une organisation pour maîtriser ses activités, protéger ses actifs, garantir la fiabilité de ses informations financières et assurer sa conformité aux réglementations." },
      { q: "Comment réduire le besoin en fonds de roulement (BFR) ?", a: "Le BFR peut être réduit en agissant sur trois leviers : réduire les délais de paiement clients, allonger les délais de paiement fournisseurs, et optimiser la gestion des stocks. Une réduction du BFR de 30 jours libère des liquidités équivalentes à un mois de CA." },
      { q: "Quelle est la fréquence recommandée pour le rapprochement bancaire ?", a: "Le rapprochement bancaire doit être réalisé mensuellement au minimum, voire hebdomadairement pour les entreprises à fort volume. Ce contrôle permet de détecter les erreurs, les prélèvements non autorisés et les fraudes." },
      { q: "Comment un DAF externalisé peut-il améliorer le contrôle interne et la trésorerie ?", a: "Un DAF externalisé réalise un diagnostic du contrôle interne, identifie les zones de risque et met en place des procédures adaptées. Les PME accompagnées constatent une réduction des fraudes de 60 à 80% et une amélioration du BFR de 15 à 30%." },
      { q: "Quels outils numériques recommandez-vous pour la gestion de trésorerie ?", a: "Les logiciels Sage, QuickBooks ou Odoo permettent d'automatiser les rapprochements bancaires et de générer des tableaux de bord en temps réel. L'investissement dans ces outils est rapidement rentabilisé." },
      { q: "Comment détecter une fraude interne dans une PME africaine ?", a: "Les principaux signaux d'alerte d'une fraude interne sont : des écarts inexpliqués entre la caisse physique et le journal, des doubles paiements détectés lors des rapprochements bancaires, des achats non autorisés ou sans justificatifs, une rotation anormale du personnel dans les fonctions sensibles (caisse, comptabilité), et des fournisseurs nouveaux sans référence. La mise en place d'une séparation des tâches — une personne autorise, une autre exécute, une troisième enregistre — est la mesure préventive la plus efficace." },
      { q: "Qu'est-ce que le ratio de liquidité et pourquoi est-il important pour une PME ?", a: "Le ratio de liquidité générale (actifs courants / passifs courants) mesure la capacité d'une entreprise à honorer ses obligations à court terme. Un ratio inférieur à 1 signale un risque de crise de trésorerie. Un ratio entre 1,2 et 2 est généralement considéré comme sain pour une PME africaine. Au-delà, l'entreprise dispose d'un coussin de sécurité mais pourrait sous-employer ses ressources. Le suivi mensuel de ce ratio est un élément fondamental du tableau de bord de trésorerie." },
      { q: "Quelle est la différence entre trésorerie et rentabilité dans une PME ?", a: "Une entreprise peut être rentable et mourir d'une crise de trésorerie : c'est le paradoxe de la croissance. La rentabilité mesure si l'entreprise génère des profits sur une période. La trésorerie mesure les liquidités disponibles à un instant T. Une PME africaine en forte croissance peut être très rentable (gros chiffre d'affaires, bonne marge) mais manquer de liquidités si ses clients paient à 90 jours et ses fournisseurs exigent un paiement à 30 jours. C'est pourquoi le plan de trésorerie prévisionnel sur 13 semaines est indispensable, même pour une entreprise profitable." },
      { q: "Comment présenter le contrôle interne et la trésorerie dans un dossier de levée de fonds ?", a: "Les investisseurs et banques analysent systématiquement la qualité du contrôle interne et de la gestion de trésorerie lors d'une due diligence. Pour un dossier de levée de fonds convaincant, il faut présenter : un historique de 3 ans d'états financiers certifiés (SYSCOHADA), un plan de trésorerie sur 3 à 5 ans avec des hypothèses documentées, une description du système de contrôle interne (séparation des tâches, procédures d'approbation), les indicateurs clés de performance financière (DSO, DPO, ratio de liquidité), et idéalement un rapport de commissariat aux comptes sans réserve." },
    ],
    kpis: [
      { icon: 'ri-line-chart-line', label: 'CA réalisé vs budget', color: 'text-emerald-600' },
      { icon: 'ri-percent-line', label: 'Marge brute & nette', color: 'text-amber-600' },
      { icon: 'ri-time-line', label: 'Délai de recouvrement', color: 'text-brand-600' },
      { icon: 'ri-bank-line', label: 'Solde de trésorerie', color: 'text-teal-600' },
      { icon: 'ri-funds-line', label: 'Prévision 13 semaines', color: 'text-orange-600' },
      { icon: 'ri-scales-3-line', label: "Ratio d'endettement", color: 'text-rose-600' },
    ],
    clusterBadge: 'Article lié — Cluster Finance',
    clusterTitle: 'Direction Financière Externalisée (DAF) : le levier stratégique des PME africaines',
    clusterDesc: 'Découvrez comment un DAF externalisé met en place le contrôle interne et optimise la trésorerie de votre organisation.',
    clusterCta: "Lire l'article",
    section1Title: 'Les risques d\'un contrôle interne défaillant',
    section1p1: "Une entreprise peut être rentable sur le papier et mourir d'une crise de trésorerie ou d'une fraude non détectée. C'est le paradoxe que vivent chaque année des centaines de PME africaines prometteuses.",
    section2Title: 'Les 4 principes fondamentaux du contrôle interne',
    section3Title: 'Maîtriser la trésorerie : anticiper plutôt que subir',
    section3p1: "La gestion de la trésorerie commence par la mise en place d'un <strong>plan de trésorerie prévisionnel</strong>. Ce document, mis à jour hebdomadairement, projette les encaissements et décaissements sur les 13 prochaines semaines.",
    section3actions: [
      'Mettre en place un tableau de bord de trésorerie hebdomadaire (encaissements prévus, décaissements, solde)',
      'Réaliser un rapprochement bancaire mensuel systématique pour détecter les anomalies',
      'Identifier les 5 plus gros clients en retard de paiement et lancer des relances immédiates',
    ],
    section3actionsBadge: 'Les 3 actions immédiates pour améliorer votre trésorerie',
    section3p2: "La qualité de la relation avec sa banque peut faire la différence entre obtenir ou non un financement en période de besoin.",
    section4Title: 'Optimiser le Besoin en Fonds de Roulement (BFR)',
    section4p1: "Le BFR représente le décalage entre les encaissements et les décaissements liés au cycle d'exploitation. <strong>Une réduction du BFR de 30 jours libère des liquidités équivalentes à un mois de chiffre d'affaires</strong>.",
    section5Title: 'Outils numériques & tableau de bord financier',
    section5p1: "Les outils numériques transforment la gestion de la trésorerie et du contrôle interne. Les logiciels de comptabilité modernes — <strong>Sage, QuickBooks, Odoo</strong> — permettent d'automatiser les rapprochements bancaires et de générer des tableaux de bord en temps réel.",
    kpiTitle: 'Tableau de bord financier mensuel — indicateurs clés',
    section5p2: "Ce tableau de bord doit être présenté à la direction chaque mois, avec une analyse des écarts et des actions correctives proposées.",
    section6Title: 'Questions fréquentes',
    diagBadge: 'Offre exclusive KHEPRA EXPERTS',
    diagTitle: 'Diagnostic Financier Gratuit — 30 minutes',
    diagDesc: 'Évaluez votre contrôle interne et votre gestion de trésorerie avec un expert KHEPRA. Sans engagement. Diagnostic gratuit.',
    ctaFreeDiag: 'Réserver mon diagnostic gratuit',
    ctaWhatsapp: 'WhatsApp',
    ctaFinalTitle: 'Renforcez votre contrôle interne et votre trésorerie',
    ctaFinalDesc: 'Découvrez notre offre de Direction Financière Externalisée et réservez votre diagnostic gratuit de 30 minutes avec un expert KHEPRA EXPERTS.',
    ctaBtn1: "Voir l'offre complète",
    ctaBtn2: 'Article DAF externalisée',
    sidebarTitle: 'DAF Externalisé KHEPRA',
    sidebarDesc: 'Contrôle interne, trésorerie, conformité BCEAO. Diagnostic gratuit 30 min.',
    sidebarWhatsapp: 'WhatsApp direct',
    sidebarContact: 'Contact direct',
    tocTitle: 'Sommaire',
    relatedTitle: 'Articles liés — Cluster Finance',
    shareTitle: 'Contrôle interne et gestion de la trésorerie : les deux piliers de la performance financière des PME africaines',
    shareExcerpt: "Comment mettre en place un contrôle interne efficace et maîtriser sa trésorerie pour sécuriser la croissance des PME en Afrique de l'Ouest.",
    relatedArticles: [
      { href: '/blog/daf-externalise-pilotage-financier-pme-afrique/', title: 'Direction Financière Externalisée (DAF) : le levier stratégique des PME africaines en 2025', category: 'Finance', readTime: '14 min' },
      { href: '/blog/modelisation-financiere-pme-africaines-syscohada/', title: 'Modélisation financière : prévoir pour décider', category: 'Finance', readTime: '10 min' },
      { href: '/blog/gouvernance-pme-ohada-ausc-investisseurs/', title: "Les clés d'une gouvernance efficace pour les PME africaines", category: 'Gouvernance', readTime: '8 min' },
      { href: '/blog/risques-financiers-pme-afrique-francophone-bceao-cobac/', title: 'Gestion des risques : anticiper pour mieux performer', category: 'Gouvernance', readTime: '11 min' },
    ],
  },

  en: {
    seo: {
      title: 'Internal Control & Treasury Management for African SMEs 2025 | KHEPRA EXPERTS',
      description: 'How to build effective internal control and master cash flow to secure SME growth in West Africa. Reduce fraud, optimize working capital, improve profitability.',
      keywords: 'internal control, treasury management, SME Africa, audit, fraud, WCR, bank reconciliation, BCEAO, outsourced CFO, Togo, Benin, Ivory Coast',
    },
    badge: 'Thought Leadership — Senior Partner',
    title: 'Internal Control & Treasury Management:\nThe Two Pillars of Financial Performance for African SMEs',
    excerpt: 'Internal control and treasury management are the two fundamental pillars of financial performance. In West Africa, mastering these two dimensions is not just best practice — it is a survival and growth imperative for SMEs.',
    breadcrumb: { home: 'Home', blog: 'Blog', current: 'Internal Control & Treasury' },
    date: 'April 20, 2025',
    readTime: '12 min read',
    authorRole: 'Associate Director & Founder, KHEPRA EXPERTS',
    allArticles: 'All articles',
    sections: [
      { id: 'enjeux', title: 'Internal Control Risks', icon: 'ri-shield-check-line' },
      { id: 'principes', title: 'Core Principles', icon: 'ri-list-check-2' },
      { id: 'tresorerie', title: 'Mastering Treasury', icon: 'ri-money-dollar-circle-line' },
      { id: 'bfr', title: 'Optimizing WCR', icon: 'ri-arrow-left-right-line' },
      { id: 'outils', title: 'Tools & Dashboard', icon: 'ri-dashboard-line' },
      { id: 'faq', title: 'FAQ', icon: 'ri-chat-3-line' },
    ],
    tagsLabel: ['Internal Control', 'Treasury', 'SME', 'Finance', 'Governance', 'Audit', 'Outsourced CFO'],
    risks: [
      { icon: 'ri-spy-line', color: 'text-red-600', bg: 'bg-red-50', border: 'border-red-200', title: 'Internal Fraud', value: '5 to 8%', desc: 'of revenue lost on average without structured internal control' },
      { icon: 'ri-error-warning-line', color: 'text-amber-600', bg: 'bg-amber-50', border: 'border-amber-200', title: 'Accounting Errors', value: 'Wrong', desc: 'strategic decisions based on inaccurate financial data' },
      { icon: 'ri-government-line', color: 'text-orange-600', bg: 'bg-orange-50', border: 'border-orange-200', title: 'Non-compliance', value: 'Penalties', desc: 'tax and administrative sanctions that could be avoided' },
      { icon: 'ri-bank-line', color: 'text-rose-600', bg: 'bg-rose-50', border: 'border-rose-200', title: 'Loss of Credibility', value: 'Access', desc: 'to financing compromised for investors and lenders' },
    ],
    principles: [
      { num: '01', icon: 'ri-group-line', title: 'Segregation of Duties', desc: 'Authorization, execution, recording and control functions must be performed by different people for sensitive processes: payments, procurement, inventory.' },
      { num: '02', icon: 'ri-file-text-line', title: 'Process Documentation', desc: 'Each key process must be documented in writing: who does what, when, how, with what authorizations. Essential for audits and due diligence.' },
      { num: '03', icon: 'ri-eye-line', title: 'Preventive & Detective Controls', desc: 'Preventive controls stop errors before they occur (validations, approvals). Detective controls identify them after the fact (reconciliations, reviews).' },
      { num: '04', icon: 'ri-refresh-line', title: 'Regular Bank Reconciliation', desc: 'Monthly at minimum, weekly for high-volume companies. Detects errors, unauthorized withdrawals and fraud before they accumulate.' },
    ],
    bfrLeviers: [
      {
        icon: 'ri-user-received-line', color: 'text-emerald-600', bg: 'bg-emerald-50', border: 'border-emerald-200',
        title: 'Reduce Customer Payment Delays',
        actions: ['Invoice immediately upon delivery', 'Systematic reminders at D+30, D+45, D+60', 'Early payment discount', 'Deposits on large orders'],
      },
      {
        icon: 'ri-store-line', color: 'text-amber-600', bg: 'bg-amber-50', border: 'border-amber-200',
        title: 'Extend Supplier Payment Terms',
        actions: ['Negotiate 60–90 day payment terms', 'Centralize purchases for greater bargaining power', 'Use payment facilities offered', 'Prioritize suppliers with best conditions'],
      },
      {
        icon: 'ri-archive-line', color: 'text-brand-600', bg: 'bg-brand-50', border: 'border-brand-200',
        title: 'Optimize Inventory',
        actions: ['Identify and liquidate dormant stock', 'Implement stock turnover tracking', 'Adopt just-in-time replenishment policy', 'Negotiate more frequent deliveries in smaller quantities'],
      },
    ],
    faq: [
      { q: 'What is internal control in a company?', a: 'Internal control is the set of mechanisms put in place by an organization to manage its activities, protect its assets, ensure the reliability of financial information and ensure regulatory compliance. It includes segregation of duties, process documentation, preventive and detective controls.' },
      { q: 'How to reduce working capital requirements (WCR)?', a: 'WCR can be reduced by acting on three levers: reducing customer payment delays (fast invoicing, systematic reminders), extending supplier payment terms, and optimizing inventory management. A 30-day WCR reduction frees up liquidity equivalent to one month of revenue.' },
      { q: 'What is the recommended frequency for bank reconciliation?', a: 'Bank reconciliation should be performed at least monthly, or weekly for high-volume companies. This simple control detects data entry errors, outstanding checks, unauthorized debits and fraud before they accumulate.' },
      { q: 'How can an outsourced CFO improve internal control and treasury?', a: 'An outsourced CFO conducts an internal control diagnostic, identifies priority risk areas and implements tailored procedures. Supported SMEs typically see a 60–80% fraud reduction and 15–30% WCR improvement.' },
      { q: 'What digital tools do you recommend for treasury management?', a: 'Modern accounting software like Sage, QuickBooks or Odoo automates bank reconciliations and generates real-time dashboards. Electronic payment solutions reduce cash-related risks. The investment in these tools pays off quickly.' },
    ],
    kpis: [
      { icon: 'ri-line-chart-line', label: 'Actual vs. budget revenue', color: 'text-emerald-600' },
      { icon: 'ri-percent-line', label: 'Gross & net margin', color: 'text-amber-600' },
      { icon: 'ri-time-line', label: 'Collection period', color: 'text-brand-600' },
      { icon: 'ri-bank-line', label: 'Cash balance', color: 'text-teal-600' },
      { icon: 'ri-funds-line', label: '13-week forecast', color: 'text-orange-600' },
      { icon: 'ri-scales-3-line', label: 'Debt ratio', color: 'text-rose-600' },
    ],
    clusterBadge: 'Related Article — Finance Cluster',
    clusterTitle: 'Outsourced CFO (DAF): The Strategic Lever for African SMEs',
    clusterDesc: 'Discover how an outsourced CFO implements internal control and optimizes treasury management for your organization.',
    clusterCta: 'Read the article',
    section1Title: 'The Risks of Deficient Internal Control',
    section1p1: 'A company can be profitable on paper and die from a cash flow crisis or undetected fraud. This is the paradox faced every year by hundreds of promising African SMEs.',
    section2Title: 'The 4 Core Principles of Internal Control',
    section3Title: 'Mastering Treasury: Anticipate Rather Than React',
    section3p1: 'Treasury management starts with setting up a <strong>cash flow forecast</strong>. This document, updated weekly, projects inflows and outflows over the next 13 weeks.',
    section3actions: [
      'Set up a weekly treasury dashboard (expected inflows, outflows, balance)',
      'Perform systematic monthly bank reconciliation to detect anomalies',
      'Identify the 5 largest late-paying customers and launch immediate reminders',
    ],
    section3actionsBadge: 'The 3 immediate actions to improve your treasury',
    section3p2: 'The quality of your banking relationship can make the difference between obtaining or not obtaining financing in times of need.',
    section4Title: 'Optimizing Working Capital Requirements (WCR)',
    section4p1: 'WCR represents the gap between inflows and outflows linked to the operating cycle. <strong>A 30-day WCR reduction frees up liquidity equivalent to one month of revenue</strong>.',
    section5Title: 'Digital Tools & Financial Dashboard',
    section5p1: 'Digital tools are transforming treasury and internal control management. Modern accounting software — <strong>Sage, QuickBooks, Odoo</strong> — automates bank reconciliations and generates real-time dashboards.',
    kpiTitle: 'Monthly financial dashboard — key indicators',
    section5p2: 'This dashboard should be presented to management monthly, with variance analysis and proposed corrective actions.',
    section6Title: 'Frequently Asked Questions',
    diagBadge: 'Exclusive KHEPRA EXPERTS Offer',
    diagTitle: 'Free Financial Diagnosis — 30 minutes',
    diagDesc: 'Assess your internal control and treasury management with a KHEPRA expert. No commitment. Free diagnosis.',
    ctaFreeDiag: 'Book My Free Diagnosis',
    ctaWhatsapp: 'WhatsApp',
    ctaFinalTitle: 'Strengthen Your Internal Control and Treasury',
    ctaFinalDesc: 'Discover our Outsourced Financial Management offer and book your free 30-minute diagnosis with a KHEPRA EXPERTS expert.',
    ctaBtn1: 'View Full Offer',
    ctaBtn2: 'Outsourced CFO Article',
    sidebarTitle: 'Outsourced CFO — KHEPRA',
    sidebarDesc: 'Internal control, treasury, BCEAO compliance. Free 30-min diagnosis.',
    sidebarWhatsapp: 'WhatsApp Direct',
    sidebarContact: 'Direct Contact',
    tocTitle: 'Table of Contents',
    relatedTitle: 'Related Articles — Finance Cluster',
    shareTitle: 'Internal Control & Treasury Management: The Two Pillars of Financial Performance for African SMEs',
    shareExcerpt: 'How to build effective internal control and master cash flow to secure SME growth in West Africa.',
    relatedArticles: [
      { href: '/blog/daf-externalise-pilotage-financier-pme-afrique/', title: 'Outsourced CFO (DAF): The Strategic Lever for African SMEs in 2025', category: 'Finance', readTime: '14 min' },
      { href: '/blog/modelisation-financiere-pme-africaines-syscohada/', title: 'Financial Modeling: Forecast to Decide', category: 'Finance', readTime: '10 min' },
      { href: '/blog/gouvernance-pme-ohada-ausc-investisseurs/', title: 'Keys to Effective Governance for African SMEs', category: 'Governance', readTime: '8 min' },
      { href: '/blog/risques-financiers-pme-afrique-francophone-bceao-cobac/', title: 'Risk Management: Anticipate to Outperform', category: 'Governance', readTime: '11 min' },
    ],
  },
};
