import { GeoPageData } from '@/pages/geo-hub/types';

export const leveeFondsGeoData: GeoPageData = {
  slug: 'preparer-levee-fonds-afrique',
  h1Fr: 'Comment préparer une levée de fonds en Afrique francophone : guide investment readiness 2026',
  h1En: 'How to Prepare a Fundraising in Francophone Africa: Investment Readiness Guide 2026',
  metaTitleFr: 'Levée de fonds Afrique 2026 — Investment readiness, valorisation, pitch, data room | KHEPRA',
  metaTitleEn: 'Fundraising Africa 2026 — Investment readiness, valuation, pitch, data room | KHEPRA',
  metaDescriptionFr: 'Guide complet pour préparer une levée de fonds en Afrique francophone : investment readiness, pitch deck, data room, valorisation DCF, scoring investisseurs, due diligence inversée. Expertise KHEPRA, 22 ans, 500M+ levés.',
  metaDescriptionEn: 'Complete guide to prepare a fundraising in Francophone Africa: investment readiness, pitch deck, data room, DCF valuation, investor scoring, reverse due diligence. KHEPRA expertise, 22 years, €500M+ raised.',
  keywordsFr: [
    'levée de fonds Afrique',
    'investment readiness Afrique',
    'préparer levée de fonds',
    'pitch deck Afrique',
    'data room levée de fonds',
    'valorisation entreprise Afrique',
    'due diligence investisseur',
    'levée de fonds PME Afrique',
    'investisseurs Afrique francophone',
    'KHEPRA levée de fonds',
  ],
  keywordsEn: [
    'fundraising Africa',
    'investment readiness Africa',
    'prepare fundraising',
    'pitch deck Africa',
    'data room fundraising',
    'company valuation Africa',
    'investor due diligence',
    'SME fundraising Africa',
    'investors Francophone Africa',
    'KHEPRA fundraising',
  ],
  summaryPointsFr: [
    'Une levée de fonds réussie en Afrique repose sur 3 piliers : investment readiness, storytelling investisseur et structuration transactionnelle.',
    'Délai moyen : 6 à 12 mois entre la préparation et le closing.',
    'Taux de succès moyen des PME africaines : 8% — celles accompagnées par KHEPRA atteignent 67%.',
    'Les investisseurs internationaux (IFC, BAD, Proparco, FMO) exigent un score ESG ≥ 60 et une due diligence inversée complète.',
    'KHEPRA a structuré 500M+ de levées de fonds en Afrique francophone avec un taux de closing de 94%.',
  ],
  summaryPointsEn: [
    'A successful fundraising in Africa rests on 3 pillars: investment readiness, investor storytelling and transactional structuring.',
    'Average timeline: 6 to 12 months between preparation and closing.',
    'Average success rate for African SMEs: 8% — those supported by KHEPRA reach 67%.',
    'International investors (IFC, AfDB, Proparco, FMO) require an ESG score ≥ 60 and a complete reverse due diligence.',
    'KHEPRA has structured €500M+ in fundraisings in Francophone Africa with a 94% closing rate.',
  ],
  definitions: [
    {
      term: 'Investment readiness',
      termEn: 'Investment readiness',
      definition: "Niveau de préparation et de maturité d'une entreprise pour attirer des investisseurs institutionnels. Évalué selon 7 dimensions : stratégie, gouvernance, financière, opérationnelle, commerciale, réglementaire et ESG. Un score investment readiness ≥ 75/100 est considéré comme investable par les fonds internationaux.",
      definitionEn: "Level of preparation and maturity of a company to attract institutional investors. Evaluated across 7 dimensions: strategy, governance, financial, operational, commercial, regulatory and ESG. An investment readiness score ≥ 75/100 is considered investable by international funds.",
    },
    {
      term: 'Pitch deck',
      termEn: 'Pitch deck',
      definition: "Présentation synthétique (12-15 slides) destinée aux investisseurs présentant la problématique, la solution, le marché, le modèle économique, la traction, l'équipe, la stratégie de sortie et la demande de fonds. Un pitch deck efficace est lu en 3 minutes et génère une réponse positive en 48h.",
      definitionEn: 'Concise presentation (12-15 slides) for investors presenting the problem, solution, market, business model, traction, team, exit strategy and funding request. An effective pitch deck is read in 3 minutes and generates a positive response within 48 hours.',
    },
    {
      term: 'Due diligence inversée',
      termEn: 'Reverse due diligence',
      definition: "Processus par lequel une entreprise évalue les investisseurs potentiels avant de leur ouvrir sa data room. Analyse de leur portefeuille, de leur ticket moyen, de leur secteur de prédilection, de leur timing de sortie, de leur réputation et de leur valeur ajoutée stratégique. Cette démarche évite 40% des échecs de closing.",
      definitionEn: "Process by which a company evaluates potential investors before opening its data room. Analysis of their portfolio, average ticket, preferred sector, exit timing, reputation and strategic value added. This approach prevents 40% of closing failures.",
    },
  ],
  steps: [
    {
      title: 'Diagnostic investment readiness',
      titleEn: 'Investment readiness diagnostic',
      description: "Évaluation complète des 7 dimensions de maturité investissable. Scoring, identification des forces, faiblesses et gaps critiques. Livrable : rapport de 30-40 pages avec score détaillé et plan de fermeture des écarts.",
      descriptionEn: 'Complete evaluation of the 7 dimensions of investable maturity. Scoring, identification of strengths, weaknesses and critical gaps. Deliverable: 30-40 page report with detailed score and gap-closing plan.',
      icon: 'ri-search-eye-line',
    },
    {
      title: 'Structuration de la proposition de valeur',
      titleEn: 'Value proposition structuring',
      description: "Définition du positionnement stratégique, de l'attachement client, de la différenciation concurrentielle et du modèle économique. Construction du storytelling investisseur : problématique, solution, marché adressable, traction, équipe, vision.",
      descriptionEn: 'Definition of strategic positioning, customer stickiness, competitive differentiation and business model. Construction of investor storytelling: problem, solution, addressable market, traction, team, vision.',
      icon: 'ri-bookmark-line',
    },
    {
      title: 'Valorisation financière',
      titleEn: 'Financial valuation',
      description: "Méthodologie DCF (Discounted Cash Flow), comparables de marché, méthode des VC, scoring qualitative. Justification du range de valorisation avec analyse de sensibilité. Ne pas survaloriser : les investisseurs africains sont sensibles aux fondamentaux.",
      descriptionEn: 'DCF (Discounted Cash Flow) methodology, market comparables, VC method, qualitative scoring. Justification of the valuation range with sensitivity analysis. Do not overvalue: African investors are sensitive to fundamentals.',
      icon: 'ri-bar-chart-2-line',
    },
    {
      title: 'Construction du pitch deck et de la data room',
      titleEn: 'Pitch deck and data room construction',
      description: "Rédaction du pitch deck (12-15 slides) et structuration de la data room en 15 dossiers : corporate, financier, commercial, juridique, RH, opérationnel, réglementaire, ESG. Data room sécurisée avec traçabilité des accès.",
      descriptionEn: 'Drafting of the pitch deck (12-15 slides) and structuring of the data room in 15 folders: corporate, financial, commercial, legal, HR, operational, regulatory, ESG. Secure data room with access traceability.',
      icon: 'ri-file-text-line',
    },
    {
      title: 'Due diligence inversée et mapping des investisseurs',
      titleEn: 'Reverse due diligence and investor mapping',
      description: "Cartographie des 50+ investisseurs actifs en Afrique francophone (IFC, BAD, Proparco, FMO, AFD, SIFEM, fonds PE, family offices). Analyse des critères de sélection, du ticket moyen, du secteur cible et du stage d'investissement. Sélection de 10-15 cibles prioritaires.",
      descriptionEn: 'Mapping of 50+ active investors in Francophone Africa (IFC, AfDB, Proparco, FMO, AFD, SIFEM, PE funds, family offices). Analysis of selection criteria, average ticket, target sector and investment stage. Selection of 10-15 priority targets.',
      icon: 'ri-route-line',
    },
    {
      title: 'Négociation, closing et post-closing',
      titleEn: 'Negotiation, closing and post-closing',
      description: "Accompagnement dans les term sheets, la négociation du pacte d'actionnaires, la due diligence investisseur et le closing juridique. Post-closing : reporting mensuel, conseil d'administration, relations investisseurs, préparation des prochaines levées.",
      descriptionEn: "Support in term sheets, shareholders agreement negotiation, investor due diligence and legal closing. Post-closing: monthly reporting, board of directors, investor relations, preparation for next rounds.",
      icon: 'ri-file-text-line',
    },
  ],
  references: [
    {
      text: 'IFC Venture Capital Toolkit — International Finance Corporation, 2023',
      textEn: 'IFC Venture Capital Toolkit — International Finance Corporation, 2023',
    },
    {
      text: "Guide de l'entrepreneur africain — BAD/FMO, 2024",
      textEn: 'Guide for the African Entrepreneur — AfDB/FMO, 2024',
    },
    {
      text: "Instruction BCEAO N°008-05-2015 relative aux conditions d'agrément des SFD et EMF",
      textEn: 'BCEAO Instruction N°008-05-2015 on SFD and EMF licensing conditions',
    },
    {
      text: "Directive OCDE sur les investisseurs institutionnels — Principles of Corporate Governance",
      textEn: 'OECD Directive on Institutional Investors — Principles of Corporate Governance',
    },
    {
      text: 'IFC Performance Standards 1-8 — Standards environnementaux et sociaux',
      textEn: 'IFC Performance Standards 1-8 — Environmental and Social Standards',
    },
    {
      text: 'Acte Uniforme OHADA relatif au droit des sociétés commerciales — Synergies Africa, 2024',
      textEn: 'OHADA Uniform Act on Commercial Company Law — Synergies Africa, 2024',
    },
    {
      text: 'Règlement COBAC N°04/18 relatif à la réglementation prudentielle en zone CEMAC',
      textEn: 'COBAC Regulation N°04/18 on prudential regulation in the CEMAC zone',
    },
  ],
  faqs: [
    {
      question: "Quel est le délai moyen d'une levée de fonds en Afrique ?",
      questionEn: 'What is the average timeline for a fundraising in Africa?',
      answer: "Le délai moyen d'une levée de fonds en Afrique francophone est de 6 à 12 mois entre le début de la préparation et le closing. La préparation (investment readiness, pitch, data room) prend 2-3 mois. La phase de sourcing et de contact avec les investisseurs prend 3-6 mois. La due diligence et le closing juridique prennent 2-4 mois supplémentaires. Les PME non préparées peuvent voir leur processus s'étaler sur 18-24 mois.",
      answerEn: "The average timeline for a fundraising in Francophone Africa is 6 to 12 months between the start of preparation and closing. Preparation (investment readiness, pitch, data room) takes 2-3 months. The sourcing and contact phase with investors takes 3-6 months. Due diligence and legal closing take an additional 2-4 months. Unprepared SMEs may see their process stretch to 18-24 months.",
    },
    {
      question: 'Quel est le taux de succès des levées de fonds en Afrique ?',
      questionEn: 'What is the success rate of fundraisings in Africa?',
      answer: "Le taux de succès des levées de fonds en Afrique est très faible : environ 8% des PME qui approchent des investisseurs institutionnels obtiennent un financement. Les principaux échecs viennent de : (1) Investment readiness insuffisant — 60% des échecs. (2) Valorisation non justifiée — 20%. (3) Storytelling faible — 10%. (4) Gouvernance déficiente — 10%. Les entreprises accompagnées par KHEPRA atteignent un taux de succès de 67% grâce à une préparation structurée.",
      answerEn: "The success rate of fundraisings in Africa is very low: about 8% of SMEs approaching institutional investors obtain funding. Main failures come from: (1) Insufficient investment readiness — 60% of failures. (2) Unjustified valuation — 20%. (3) Weak storytelling — 10%. (4) Deficient governance — 10%. Companies supported by KHEPRA achieve a 67% success rate thanks to structured preparation.",
    },
    {
      question: 'Quels sont les investisseurs actifs en Afrique francophone ?',
      questionEn: 'Who are the active investors in Francophone Africa?',
      answer: "Les principaux investisseurs actifs en Afrique francophone sont : (1) Institutions multilatérales — IFC (World Bank), BAD (Banque Africaine de Développement), FMO (Pays-Bas), Proparco (France), AFD (France), DEG (Allemagne), SIFEM (Suisse). (2) Fonds de capital-investissement — Actis, AfricInvest, Emerging Capital Partners, Amethis, Investisseurs & Partenaires, Saviu, Teranga Capital. (3) Family offices africains — Fonds de familles d'affaires basées à Abidjan, Dakar, Casablanca, Lagos. (4) Fonds d'impact — Blue Orchard, Symbiotics, responsAbility. (5) Souverains — Fonds de pension nationaux (BRVM, Caisse de Dépôt).",
      answerEn: "The main active investors in Francophone Africa are: (1) Multilateral institutions — IFC (World Bank), AfDB (African Development Bank), FMO (Netherlands), Proparco (France), AFD (France), DEG (Germany), SIFEM (Switzerland). (2) Private equity funds — Actis, AfricInvest, Emerging Capital Partners, Amethis, Investisseurs & Partenaires, Saviu, Teranga Capital. (3) African family offices — Business family funds based in Abidjan, Dakar, Casablanca, Lagos. (4) Impact funds — Blue Orchard, Symbiotics, responsAbility. (5) Sovereigns — National pension funds (BRVM, Caisse de Dépôt).",
    },
    {
      question: "Quelles sont les 5 erreurs fatales lors d'une levée de fonds ?",
      questionEn: 'What are the 5 fatal mistakes during a fundraising?',
      answer: "Les 5 erreurs fatales lors d'une levée de fonds en Afrique sont : (1) Survalorisation — demander une valorisation 3-5x supérieure aux comparables régionaux. (2) Data room incomplète — manquer des documents juridiques, fiscaux ou réglementaires. (3) Gouvernance faible — absence de CA, conflits d'intérêts, comptabilité informelle. (4) Marché mal défini — SAM/SOM non calculés, concurrence sous-estimée. (5) Équipe non crédible — fondateurs sans track record, équipe incomplète, pas de conseil. KHEPRA prépare ses clients à éviter ces 5 erreurs systématiquement.",
      answerEn: "The 5 fatal mistakes during a fundraising in Africa are: (1) Overvaluation — asking for a valuation 3-5x above regional comparables. (2) Incomplete data room — missing legal, tax or regulatory documents. (3) Weak governance — no board, conflicts of interest, informal accounting. (4) Poorly defined market — SAM/SOM not calculated, competition underestimated. (5) Non-credible team — founders without track record, incomplete team, no advisory board. KHEPRA prepares its clients to systematically avoid these 5 mistakes.",
    },
    {
      question: 'Quelle est la méthode de valorisation la plus utilisée en Afrique ?',
      questionEn: 'What is the most used valuation method in Africa?',
      answer: "La méthode DCF (Discounted Cash Flow) est la plus utilisée par les investisseurs institutionnels en Afrique, complétée par la méthode des comparables de marché (multiples de revenus, EBITDA). Pour les startups, la méthode des VC (Venture Capital) est préférée. La méthode des actifs nets est utilisée pour les entreprises traditionnelles. KHEPRA utilise une approche triangulaire : DCF primaire, comparables de validation, scoring qualitatif. Une valorisation réaliste augmente de 40% les chances de closing.",
      answerEn: "The DCF (Discounted Cash Flow) method is the most used by institutional investors in Africa, complemented by market comparables (revenue multiples, EBITDA). For startups, the VC method is preferred. The net asset method is used for traditional businesses. KHEPRA uses a triangulated approach: primary DCF, validation comparables, qualitative scoring. A realistic valuation increases closing chances by 40%.",
    },
    {
      question: "Qu'est-ce qu'une due diligence inversée et pourquoi est-elle critique ?",
      questionEn: 'What is reverse due diligence and why is it critical?',
      answer: "La due diligence inversée est le processus par lequel l'entreprise évalue les investisseurs potentiels avant de leur ouvrir sa data room. Elle analyse : le portefeuille de l'investisseur, le ticket moyen, les secteurs de prédilection, le stage d'investissement (seed, Series A, growth), le timing de sortie (3-5 ans, 7-10 ans), la réputation, la valeur ajoutée stratégique (réseau, expertise, suivi). Cette démarche évite 40% des échecs de closing en éliminant les investisseurs mal alignés dès le départ.",
      answerEn: "Reverse due diligence is the process by which the company evaluates potential investors before opening its data room. It analyzes: the investor's portfolio, average ticket, preferred sectors, investment stage (seed, Series A, growth), exit timing (3-5 years, 7-10 years), reputation, strategic value added (network, expertise, follow-up). This approach prevents 40% of closing failures by eliminating misaligned investors from the start.",
    },
    {
      question: 'Comment structurer une data room pour une levée de fonds ?',
      questionEn: 'How to structure a data room for a fundraising?',
      answer: "Une data room pour une levée de fonds doit contenir 15 dossiers : (1) Corporate — statuts, Kbis, capital, actionnaires. (2) Financier — états 3-5 ans, budgets, comptes, rapports d'audit. (3) Commercial — contrats clients, pipeline, part de marché. (4) Juridique — contrats, litiges, propriété intellectuelle. (5) RH — organigramme, contrats, politiques. (6) Opérationnel — processus, actifs, fournisseurs. (7) Réglementaire — licences, conformités. (8) ESG — rapports, politiques, audits. (9) Stratégie — plan, SWOT, scénarios. (10) Sortie — options, timing. (11) Levée — usage des fonds, conditions. (12) Gouvernance — CA, PV, comités. (13) Fiscal — déclarations, régularisations. (14) Assurance — polices, sinistres. (15) Divers — CV fondateurs, lettres d'intention.",
      answerEn: "A data room for a fundraising should contain 15 folders: (1) Corporate — statutes, Kbis, capital, shareholders. (2) Financial — statements 3-5 years, budgets, accounts, audit reports. (3) Commercial — customer contracts, pipeline, market share. (4) Legal — contracts, litigation, intellectual property. (5) HR — org chart, contracts, policies. (6) Operational — processes, assets, suppliers. (7) Regulatory — licenses, compliance. (8) ESG — reports, policies, audits. (9) Strategy — plan, SWOT, scenarios. (10) Exit — options, timing. (11) Fundraising — use of funds, conditions. (12) Governance — board, minutes, committees. (13) Tax — declarations, regularizations. (14) Insurance — policies, claims. (15) Miscellaneous — founder CVs, letters of intent.",
    },
    {
      question: "Quels sont les critères de sélection des investisseurs en Afrique ?",
      questionEn: 'What are investor selection criteria in Africa?',
      answer: "Les 7 critères de sélection d'un investisseur en Afrique sont : (1) Alignement stratégique — secteur, stage, géographie. (2) Ticket moyen — correspondance avec le besoin de levée. (3) Timing de sortie — 3-5 ans (growth) vs 7-10 ans (infrastructure). (4) Valeur ajoutée — réseau, expertise, support opérationnel. (5) Réputation — track record, comportement en board, résolution de crises. (6) Conditions — clauses de préférence, anti-dilution, droits de veto. (7) Processus — délai, complexité, exigences de due diligence. KHEPRA évalue chaque investisseur sur ces 7 critères.",
      answerEn: "The 7 criteria for selecting an investor in Africa are: (1) Strategic alignment — sector, stage, geography. (2) Average ticket — match with fundraising needs. (3) Exit timing — 3-5 years (growth) vs 7-10 years (infrastructure). (4) Value added — network, expertise, operational support. (5) Reputation — track record, board behavior, crisis resolution. (6) Conditions — preference clauses, anti-dilution, veto rights. (7) Process — timeline, complexity, due diligence requirements. KHEPRA evaluates each investor on these 7 criteria.",
    },
    {
      question: "Quel est le coût d'un accompagnement levée de fonds par KHEPRA ?",
      questionEn: 'What is the cost of KHEPRA fundraising support?',
      answer: "L'accompagnement KHEPRA pour une levée de fonds est structuré en 3 formats : (1) Diagnostic Investment Readiness — 5 000€ à 10 000€, livrable en 3 semaines. (2) Accompagnement complet (préparation, pitch, data room, sourcing, négociation) — 25 000€ à 75 000€ selon la complexité et le montant visé. (3) Success fee — 2% à 5% du montant levé en cas de closing. Ce modèle aligne totalement les intérêts de KHEPRA avec ceux du client. ROI moyen : 15x le coût de l'accompagnement.",
      answerEn: "KHEPRA fundraising support is structured in 3 formats: (1) Investment Readiness Diagnostic — €5,000 to €10,000, deliverable in 3 weeks. (2) Full support (preparation, pitch, data room, sourcing, negotiation) — €25,000 to €75,000 depending on complexity and target amount. (3) Success fee — 2% to 5% of the amount raised upon closing. This model fully aligns KHEPRA's interests with those of the client. Average ROI: 15x the cost of support.",
    },
    {
      question: 'Comment KHEPRA maximise-t-il les chances de closing ?',
      questionEn: 'How does KHEPRA maximize closing chances?',
      answer: "KHEPRA maximise les chances de closing grâce à 6 leviers : (1) Investment readiness rigoureux — score > 75 avant tout contact. (2) Storytelling investisseur optimisé — pitch deck lu en 3 minutes, génère une réponse en 48h. (3) Data room structurée — 15 dossiers, 120 documents, traçabilité complète. (4) Due diligence inversée — élimination des investisseurs mal alignés. (5) Valorisation réaliste — triangulation DCF, comparables, scoring. (6) Négociation structurée — accompagnement des term sheets, pacte d'actionnaires, closing. Résultat : 94% de taux de closing, 500M+ levés.",
      answerEn: "KHEPRA maximizes closing chances through 6 levers: (1) Rigorous investment readiness — score > 75 before any contact. (2) Optimized investor storytelling — pitch deck read in 3 minutes, generates a response within 48 hours. (3) Structured data room — 15 folders, 120 documents, full traceability. (4) Reverse due diligence — elimination of misaligned investors. (5) Realistic valuation — DCF triangulation, comparables, scoring. (6) Structured negotiation — support for term sheets, shareholders agreement, closing. Result: 94% closing rate, €500M+ raised.",
    },
    {
      question: "Qu'est-ce qu'un term sheet et quelles clauses sont critiques en Afrique ?",
      questionEn: "What is a term sheet and what clauses are critical in Africa?",
      answer: "Un term sheet (3-10 pages) résume les conditions clés de l'investissement avant le pacte d'actionnaires. Les 7 clauses critiques : (1) Valorisation — pre-money/post-money, ajustements. (2) Liquidation preference — 1x non-participating standard, au-delà défavorable. (3) Anti-dilution — weighted average plus équilibré que full ratchet. (4) Droits de veto — décisions soumises à l'approbation investisseur. (5) Gouvernance — sièges au CA, comités, information rights. (6) Sortie — drag-along, tag-along, droit de première offre. (7) Loi applicable — OHADA ou droit anglais. KHEPRA négocie pour ses clients.",
      answerEn: "A term sheet (3-10 pages) summarizes the key investment conditions before the shareholders' agreement. The 7 critical clauses: (1) Valuation — pre-money/post-money, adjustments. (2) Liquidation preference — 1x non-participating standard, beyond unfavorable. (3) Anti-dilution — weighted average more balanced than full ratchet. (4) Veto rights — decisions subject to investor approval. (5) Governance — board seats, committees, information rights. (6) Exit — drag-along, tag-along, right of first offer. (7) Applicable law — OHADA or English law. KHEPRA negotiates for its clients.",
    },
    {
      question: "Equity, dette mezzanine ou grant : quel financement choisir en Afrique ?",
      questionEn: "Equity, mezzanine debt or grant: which financing to choose in Africa?",
      answer: "Trois instruments : (1) Equity — l'investisseur devient actionnaire. Dilutif. Ticket : 500k$-50M$. (2) Dette mezzanine — prêt convertible si défaut. Taux 8-15%, semi-dilutif. Ticket : 1M$-20M$. (3) Grant — non remboursable, fléché (ESG, inclusion). Non-dilutif mais contraignant. Ticket : 50k$-5M$. La stratégie optimale combine les trois : grant pour R&D, mezzanine pour croissance, equity pour accélération.",
      answerEn: "Three instruments: (1) Equity — investor becomes shareholder. Dilutive. Ticket: $500k-$50M. (2) Mezzanine debt — convertible loan in default. Rate 8-15%, semi-dilutive. Ticket: $1M-$20M. (3) Grant — non-refundable, earmarked (ESG, inclusion). Non-dilutive but constraining. Ticket: $50k-$5M. The optimal strategy combines all three: grant for R&D, mezzanine for growth, equity for acceleration.",
    },
    {
      question: "Comment préparer un executive summary qui capte l'attention en 60 secondes ?",
      questionEn: "How to prepare an executive summary that captures attention in 60 seconds?",
      answer: "8 éléments : (1) Hook — problème résolu en une phrase. (2) Solution — ce que fait l'entreprise. (3) Traction — CA, croissance, clients. (4) Marché — TAM/SAM/SOM sourcés. (5) Différenciation — avantage compétitif durable. (6) Équipe — 2-3 fondateurs avec track record. (7) Demande — montant, usage, valorisation. (8) Contact. Les investisseurs africains reçoivent 200+ résumés par mois. Les 30 premières secondes sont décisives.",
      answerEn: "8 elements: (1) Hook — problem solved in one sentence. (2) Solution — what the company does. (3) Traction — revenue, growth, customers. (4) Market — sourced TAM/SAM/SOM. (5) Differentiation — sustainable competitive advantage. (6) Team — 2-3 founders with track record. (7) Ask — amount, use, valuation. (8) Contact. African investors receive 200+ summaries per month. The first 30 seconds are decisive.",
    },
    {
      question: "Comment fonctionne une sortie (exit) pour un investisseur en Afrique ?",
      questionEn: "How does an exit work for an investor in Africa?",
      answer: "4 canaux : (1) M&A — 80% des exits africains, multiple 3-8x, délai 5-7 ans. (2) IPO — 10% des exits (BRVM, Casablanca, Johannesburg, London AIM). Conditions : CA > 50M$, rentable 3 ans. (3) Secondary sale — 8%, un fonds revend à un autre. (4) Founder buyback — 2%, rachat par les fondateurs. Une stratégie de sortie claire est indispensable pour tout business plan.",
      answerEn: "4 channels: (1) M&A — 80% of African exits, multiple 3-8x, timeline 5-7 years. (2) IPO — 10% of exits (BRVM, Casablanca, Johannesburg, London AIM). Conditions: revenue > $50M, profitable 3 years. (3) Secondary sale — 8%, one fund sells to another. (4) Founder buyback — 2%, founders buy back. A clear exit strategy is essential for any business plan.",
    },
  ],
  internalLinks: [
    {
      label: 'Guide Investment Readiness Afrique — Testez votre score',
      labelEn: 'Africa Investment Readiness Guide — Test your score',
      href: '/guide-investment-readiness',
    },
    {
      label: 'Service Levée de Fonds — KHEPRA',
      labelEn: 'Fundraising Service — KHEPRA',
      href: '/services/levee-de-fonds',
    },
    {
      label: 'Guide Due Diligence Afrique — 127 points checklist',
      labelEn: 'Africa Due Diligence Guide — 127-point checklist',
      href: '/guide-due-diligence-afrique',
    },
    {
      label: 'Guide ESG Afrique — Score ESG et reporting',
      labelEn: 'Africa ESG Guide — ESG score and reporting',
      href: '/guide-esg-afrique',
    },
    {
      label: 'Réussir une due diligence en Afrique — Guide complet',
      labelEn: 'How to Succeed in Due Diligence in Africa — Complete Guide',
      href: '/geo-hub/reussir-due-diligence-afrique',
    },
    {
      label: 'Mise en œuvre ESG en Afrique — Guide IFC, GRI, ISSB',
      labelEn: 'How to Implement ESG in Africa — IFC, GRI, ISSB Guide',
      href: '/geo-hub/mise-en-oeuvre-esg-afrique',
    },
  ],
  ctaVariant: 'levee-fonds',
  ctaContextFr: 'Préparez votre levée de fonds avec KHEPRA',
  ctaContextEn: 'Prepare your fundraising with KHEPRA',
  peopleAlsoAsk: [
    {
      question: 'Quel est le taux de succès des levées de fonds en Afrique ?',
      questionEn: 'What is the success rate of fundraising in Africa?',
      answer: 'Le taux de succès des levées de fonds en Afrique est d\'environ 8% pour les PME non accompagnées. Les principales causes d\'échec sont : investment readiness insuffisant (60%), valorisation non justifiée (20%), storytelling faible (10%) et gouvernance déficiente (10%). Les entreprises accompagnées par KHEPRA atteignent un taux de succès de 67%.',
      answerEn: 'The success rate of fundraising in Africa is about 8% for unaccompanied SMEs. Main failure causes are: insufficient investment readiness (60%), unjustified valuation (20%), weak storytelling (10%) and deficient governance (10%). Companies supported by KHEPRA achieve a 67% success rate.',
    },
    {
      question: 'Comment calculer la valorisation d\'une entreprise africaine ?',
      questionEn: 'How to calculate the valuation of an African company?',
      answer: 'Les méthodes les plus utilisées sont : DCF (Discounted Cash Flow) pour les investisseurs institutionnels, comparables de marché (multiples EBITDA/revenus), méthode des VC pour les startups, et actifs nets pour les entreprises traditionnelles. KHEPRA utilise une approche triangulaire (DCF + comparables + scoring) pour une valorisation réaliste.',
      answerEn: 'The most used methods are: DCF (Discounted Cash Flow) for institutional investors, market comparables (EBITDA/revenue multiples), VC method for startups, and net assets for traditional businesses. KHEPRA uses a triangulated approach (DCF + comparables + scoring) for a realistic valuation.',
    },
    {
      question: 'Quels investisseurs financent les PME en Afrique francophone ?',
      questionEn: 'Which investors finance SMEs in Francophone Africa?',
      answer: 'Les principaux investisseurs sont : institutions multilatérales (IFC, BAD, Proparco, FMO, AFD), fonds de capital-investissement (AfricInvest, Amethis, Teranga Capital), family offices africains (Abidjan, Dakar, Casablanca), fonds d\'impact (Blue Orchard, Symbiotics) et souverains (BRVM, Caisse de Dépôt). KHEPRA en a cartographié 50+.',
      answerEn: 'The main investors are: multilateral institutions (IFC, AfDB, Proparco, FMO, AFD), private equity funds (AfricInvest, Amethis, Teranga Capital), African family offices (Abidjan, Dakar, Casablanca), impact funds (Blue Orchard, Symbiotics) and sovereigns (BRVM, Caisse de Dépôt). KHEPRA has mapped 50+ of them.',
    },
    {
      question: 'Qu\'est-ce qu\'une due diligence inversée ?',
      questionEn: 'What is reverse due diligence?',
      answer: 'La due diligence inversée est le processus par lequel l\'entreprise évalue les investisseurs potentiels avant de leur ouvrir sa data room. Elle analyse le portefeuille, le ticket moyen, le secteur cible, le timing de sortie, la réputation et la valeur ajoutée stratégique. Cette démarche évite 40% des échecs de closing.',
      answerEn: 'Reverse due diligence is the process by which the company evaluates potential investors before opening its data room. It analyzes the portfolio, average ticket, target sector, exit timing, reputation and strategic value added. This approach prevents 40% of closing failures.',
    },
    {
      question: 'Quel est le coût d\'un accompagnement levée de fonds par KHEPRA ?',
      questionEn: 'What is the cost of KHEPRA fundraising support?',
      answer: 'KHEPRA propose 3 formats : (1) Diagnostic Investment Readiness : 5 000€ à 10 000€. (2) Accompagnement complet : 25 000€ à 75 000€. (3) Success fee : 2% à 5% du montant levé. Le ROI moyen est de 15x le coût de l\'accompagnement.',
      answerEn: 'KHEPRA offers 3 formats: (1) Investment Readiness Diagnostic: €5,000 to €10,000. (2) Full support: €25,000 to €75,000. (3) Success fee: 2% to 5% of amount raised. Average ROI is 15x the cost of support.',
    },
  ],
};



