// ============================================================================
// KOS AUTO-EXPANSION ACADEMY™ — Q4 2026
// Université Autonome KHEPRA EXPERTS — Zéro dépendance externe
// ============================================================================

export interface AcademyModule {
  id: string;
  title: string;
  domain: string;
  icon: string;
  color: string;
  level: 'Foundation' | 'Practitioner' | 'Expert' | 'Master';
  duration: string;
  lessons: number;
  enrollees: number;
  completionRate: number;
  certificationCode: string;
  status: 'live' | 'draft' | 'coming_soon';
  autoGenerated: boolean;
  lastUpdated: string;
  description: string;
  syllabus: string[];
  kpiImpact: string;
  cpd_hours: number;
}

export interface AcademyLearner {
  id: string;
  name: string;
  role: string;
  organization: string;
  country: string;
  modulesCompleted: number;
  modulesEnrolled: number;
  totalCpdHours: number;
  currentModule: string;
  progression: number;
  certifications: string[];
  lastActivity: string;
  score: number;
  status: 'active' | 'inactive' | 'completed';
}

export interface AcademyCertification {
  id: string;
  code: string;
  title: string;
  domain: string;
  level: string;
  issuedCount: number;
  passRate: number;
  validityMonths: number;
  recognition: string[];
  icon: string;
  color: string;
  lastIssued: string;
  autoGenerated: boolean;
}

export interface AcademyProductionPipeline {
  id: string;
  moduleTitle: string;
  domain: string;
  stage: 'scripting' | 'validation' | 'recording' | 'review' | 'published';
  progress: number;
  agentAssigned: string;
  estimatedDelivery: string;
  autoGenerated: boolean;
  priority: 'P0' | 'P1' | 'P2';
  kpiTarget: string;
}

export interface AcademyKPI {
  id: string;
  name: string;
  icon: string;
  color: string;
  current: number;
  target: number;
  unit: string;
  trend: 'up' | 'down' | 'stable';
  history: { month: string; value: number }[];
}

// ============================================================================
// MODULES
// ============================================================================
export const ACADEMY_MODULES: AcademyModule[] = [
  {
    id: 'mod-001',
    title: 'Fondamentaux de la Réglementation Bancaire UEMOA',
    domain: 'Conformité Réglementaire',
    icon: 'ri-bank-line',
    color: 'primary',
    level: 'Foundation',
    duration: '8h',
    lessons: 12,
    enrollees: 487,
    completionRate: 78,
    certificationCode: 'KOS-CRB-F01',
    status: 'live',
    autoGenerated: true,
    lastUpdated: '2026-06-20',
    description: 'Maîtrisez les textes fondamentaux BCEAO : instructions, circulaires, ratios prudentiels, dispositif de supervision bancaire UEMOA.',
    syllabus: [
      'Architecture institutionnelle BCEAO et UMOA',
      'Ratio de solvabilité et capital réglementaire',
      'Dispositif prudentiel — Bâle II/III adaptation africaine',
      'Instructions aux SFD : catalogue des 22 textes',
      'Circulaire 01-2017 — Gouvernance bancaire',
      'Notification et reporting périodique BCEAO',
      'Agrément et conditions d\'exercice',
      'Sanctions et procédures d\'inspection',
    ],
    kpiImpact: '+42% réussite pré-inspection BCEAO',
    cpd_hours: 8,
  },
  {
    id: 'mod-002',
    title: 'LBC/FT & Conformité GAFI — Niveau Expert',
    domain: 'AML & Conformité',
    icon: 'ri-shield-user-line',
    color: 'accent',
    level: 'Expert',
    duration: '14h',
    lessons: 20,
    enrollees: 312,
    completionRate: 65,
    certificationCode: 'KOS-AMLE-E02',
    status: 'live',
    autoGenerated: true,
    lastUpdated: '2026-06-22',
    description: 'Les 40 Recommandations GAFI, KYC/CDD renforcé, déclarations CENUREF/CENTIF, reporting de transactions suspectes, gestion des listes de sanctions.',
    syllabus: [
      'Les 40 Recommandations GAFI 2012 révisées 2026',
      'KYC/CDD — Processus et seuils BCEAO',
      'Customer Risk Assessment — Méthodologie',
      'Déclarations CENUREF et CENTIF',
      'Gel des avoirs — Listes ONU, OFAC, UE',
      'Formation équipes opérationnelles',
      'Contrôle interne LBC/FT',
      'Tendances : Crypto-actifs et nouveaux risques 2026',
    ],
    kpiImpact: '-65% alertes faux positifs, +90% qualité dossiers SAR',
    cpd_hours: 14,
  },
  {
    id: 'mod-003',
    title: 'Prix de Transfert & BEPS — Documentation Complète',
    domain: 'Fiscalité Internationale',
    icon: 'ri-exchange-dollar-line',
    color: 'secondary',
    level: 'Master',
    duration: '18h',
    lessons: 24,
    enrollees: 189,
    completionRate: 52,
    certificationCode: 'KOS-BEPS-M03',
    status: 'live',
    autoGenerated: false,
    lastUpdated: '2026-06-18',
    description: 'Documentation Master File & Local File conforme OCDE BEPS Action 13, benchmarking transactionnel, défense fiscale, spécificités africaines.',
    syllabus: [
      'BEPS Actions 1-15 : Vue d\'ensemble',
      'BEPS Action 13 : Master File & Local File',
      'Méthodes de prix de transfert — OCDE',
      'Benchmarking : Sources africaines et disponibilité',
      'Pilier 2 — Impôt minimum mondial 15%',
      'Documentation pays africains (UEMOA, CEMAC)',
      'Contrôle fiscal et contentieux',
      'Pratique : Rédaction dossier complet',
    ],
    kpiImpact: '+85% robustesse dossier fiscalité internationale',
    cpd_hours: 18,
  },
  {
    id: 'mod-004',
    title: 'Gouvernance d\'Entreprise Big Four — Pratique OHADA',
    domain: 'Gouvernance',
    icon: 'ri-government-line',
    color: 'primary',
    level: 'Practitioner',
    duration: '10h',
    lessons: 15,
    enrollees: 256,
    completionRate: 82,
    certificationCode: 'KOS-GOV-P04',
    status: 'live',
    autoGenerated: true,
    lastUpdated: '2026-06-21',
    description: 'Structure et animation du Conseil d\'Administration, Comités Spécialisés BCEAO, indépendance des administrateurs, charte de gouvernance, évaluation CA.',
    syllabus: [
      'AUSC-GIE OHADA révisé : droits des actionnaires',
      'Architecture de gouvernance Big Four',
      'Comités Spécialisés — Circulaire 01-2017',
      'Administrateurs indépendants — Critères BCEAO',
      'Rémunérations et politique incitatrice',
      'Procès-verbaux et documentation CA',
      'Évaluation annuelle du Conseil',
      'Planification de la succession',
    ],
    kpiImpact: '+70% conformité gouvernance, 3 inspections COBAC passées sans réserve',
    cpd_hours: 10,
  },
  {
    id: 'mod-005',
    title: 'ESG & Finance Durable en Afrique — ISSB 2026',
    domain: 'ESG & Durabilité',
    icon: 'ri-leaf-line',
    color: 'accent',
    level: 'Expert',
    duration: '12h',
    lessons: 18,
    enrollees: 143,
    completionRate: 48,
    certificationCode: 'KOS-ESGE-E05',
    status: 'live',
    autoGenerated: true,
    lastUpdated: '2026-06-24',
    description: 'IFRS S1 & S2, GRI Standards, Taxonomie verte UEMOA, Bilan Carbone Scope 1/2/3, reporting ESG board-ready, stress tests climatiques Pilier 2.',
    syllabus: [
      'Architecture ISSB : S1 Général + S2 Climat',
      'GRI 2021 — Standards applicables Afrique',
      'Taxonomie verte UEMOA (mars 2026)',
      'Bilan Carbone : GHG Protocol & Scope 3',
      'Stress Tests Climatiques — Guide BCEAO/COBAC',
      'Rapport ESG Board-Ready : Template Big Four',
      'Due Diligence ESG — Standards IFC PS',
      'Alignement SDG et rapport impact',
    ],
    kpiImpact: '+60% qualité rapport ESG, accès financement vert BEI/AFD',
    cpd_hours: 12,
  },
  {
    id: 'mod-006',
    title: 'Audit Interne & Contrôle — Référentiel COSO 2024',
    domain: 'Audit & Risques',
    icon: 'ri-search-eye-line',
    color: 'secondary',
    level: 'Expert',
    duration: '16h',
    lessons: 22,
    enrollees: 198,
    completionRate: 60,
    certificationCode: 'KOS-AUDI-E06',
    status: 'live',
    autoGenerated: false,
    lastUpdated: '2026-06-19',
    description: 'COSO 2013/2024, normes IIA, cartographie des risques, programme d\'audit, revue de la qualité, rapport d\'audit Big Four, plans de remédiation.',
    syllabus: [
      'COSO Integrated Framework 2024',
      'Standards Internationaux IIA 2024',
      'Cartographie des risques — Méthodologie',
      'Programme d\'audit annuel basé sur les risques',
      'Techniques d\'audit : entretiens, tests, revues',
      'Rapport d\'audit Big Four : structure et communication',
      'Suivi des recommandations et remédiation',
      'Revue Qualité — Auto-évaluation DAI',
    ],
    kpiImpact: '+80% efficacité DAI, zéro réserve Comité d\'Audit',
    cpd_hours: 16,
  },
  {
    id: 'mod-007',
    title: 'Microfinance & SFD — Conformité BCEAO Complète',
    domain: 'Microfinance',
    icon: 'ri-hand-coin-line',
    color: 'primary',
    level: 'Master',
    duration: '20h',
    lessons: 28,
    enrollees: 321,
    completionRate: 73,
    certificationCode: 'KOS-MFIN-M07',
    status: 'live',
    autoGenerated: true,
    lastUpdated: '2026-06-23',
    description: 'Les 22 Instructions BCEAO applicables aux SFD, agrément, modifications statutaires, gouvernance SFD, reporting réglementaire, Finance Islamique SFD.',
    syllabus: [
      'Architecture légale SFD — Loi PARMEC',
      'Procédure d\'agrément : dossier complet',
      'Instructions 001-002/2017 : modifications statutaires',
      'Instruction 003/2018 : Finance Islamique SFD',
      'Ratio et indicateurs de performance SFD (SIG)',
      'Reporting périodique — Instructions 018-020-2010',
      'Transformation SFD : étapes et contraintes',
      'Avoirs dormants et provisions — Instructions BCEAO',
    ],
    kpiImpact: '+95% conformité SFD, dossier d\'agrément approuvé 1ère soumission',
    cpd_hours: 20,
  },
  {
    id: 'mod-008',
    title: 'Transformation Digitale & Résilience Opérationnelle',
    domain: 'Digital & Tech',
    icon: 'ri-computer-line',
    color: 'accent',
    level: 'Practitioner',
    duration: '10h',
    lessons: 14,
    enrollees: 174,
    completionRate: 58,
    certificationCode: 'KOS-DIGT-P08',
    status: 'live',
    autoGenerated: true,
    lastUpdated: '2026-06-22',
    description: 'Cybersécurité bancaire Directive COBAC 2027, DORA adaptation africaine, ISO 27001 pratique, résilience opérationnelle, PCA/PRA, gestion des incidents.',
    syllabus: [
      'Directive COBAC 2027 : Cybersécurité bancaire',
      'DORA — Application CEMAC/UEMOA',
      'ISO 27001:2022 — Contrôles Annexe A',
      'Cybersécurité : OWASP, SOC, WAF',
      'PCA/PRA — Tests et documentation',
      'Gestion des incidents cyber : playbooks',
      'Gouvernance des données : RGPD appliqué Afrique',
      'FinTech & Innovation : cadre réglementaire 2026',
    ],
    kpiImpact: 'ISO 27001 certifié, zéro incident critique 12 mois',
    cpd_hours: 10,
  },
];

// ============================================================================
// LEARNERS
// ============================================================================
export const ACADEMY_LEARNERS: AcademyLearner[] = [
  {
    id: 'lrn-001', name: 'Aminata Koné', role: 'Chief Compliance Officer', organization: 'Banque Internationale UEMOA',
    country: 'Côte d\'Ivoire', modulesCompleted: 6, modulesEnrolled: 8, totalCpdHours: 78,
    currentModule: 'LBC/FT & Conformité GAFI', progression: 72, certifications: ['KOS-CRB-F01', 'KOS-GOV-P04', 'KOS-MFIN-M07'],
    lastActivity: '2026-06-24', score: 94, status: 'active',
  },
  {
    id: 'lrn-002', name: 'Ibrahima Diallo', role: 'Directeur Audit Interne', organization: 'Groupe Bancaire CEMAC',
    country: 'Cameroun', modulesCompleted: 5, modulesEnrolled: 7, totalCpdHours: 66,
    currentModule: 'Audit Interne & Contrôle — COSO 2024', progression: 45, certifications: ['KOS-CRB-F01', 'KOS-AMLE-E02'],
    lastActivity: '2026-06-23', score: 88, status: 'active',
  },
  {
    id: 'lrn-003', name: 'Fatoumata Traoré', role: 'Directrice Générale', organization: 'SFD MicroFinance UEMOA',
    country: 'Sénégal', modulesCompleted: 7, modulesEnrolled: 8, totalCpdHours: 102,
    currentModule: 'ESG & Finance Durable — ISSB 2026', progression: 88, certifications: ['KOS-MFIN-M07', 'KOS-GOV-P04', 'KOS-CRB-F01', 'KOS-AMLE-E02'],
    lastActivity: '2026-06-24', score: 97, status: 'active',
  },
  {
    id: 'lrn-004', name: 'Moussa Barry', role: 'Responsable Conformité', organization: 'FinTech Paiement CEMAC',
    country: 'Gabon', modulesCompleted: 3, modulesEnrolled: 5, totalCpdHours: 38,
    currentModule: 'Transformation Digitale & Résilience', progression: 62, certifications: ['KOS-CRB-F01'],
    lastActivity: '2026-06-22', score: 79, status: 'active',
  },
  {
    id: 'lrn-005', name: 'Sékou Camara', role: 'Directeur des Risques', organization: 'Banque Commerciale UEMOA',
    country: 'Guinée', modulesCompleted: 4, modulesEnrolled: 6, totalCpdHours: 56,
    currentModule: 'Prix de Transfert & BEPS', progression: 30, certifications: ['KOS-CRB-F01', 'KOS-GOV-P04'],
    lastActivity: '2026-06-20', score: 85, status: 'active',
  },
  {
    id: 'lrn-006', name: 'Aïcha Sow', role: 'Head of Internal Audit', organization: 'Assurance CIMA',
    country: 'Sénégal', modulesCompleted: 8, modulesEnrolled: 8, totalCpdHours: 128,
    currentModule: 'Complété', progression: 100, certifications: ['KOS-CRB-F01', 'KOS-AMLE-E02', 'KOS-GOV-P04', 'KOS-AUDI-E06', 'KOS-ESGE-E05'],
    lastActivity: '2026-06-24', score: 99, status: 'completed',
  },
  {
    id: 'lrn-007', name: 'Pascal Zongo', role: 'Expert Fiscalité', organization: 'Cabinet Conseil Ouagadougou',
    country: 'Burkina Faso', modulesCompleted: 2, modulesEnrolled: 4, totalCpdHours: 32,
    currentModule: 'Prix de Transfert & BEPS', progression: 55, certifications: ['KOS-BEPS-M03'],
    lastActivity: '2026-06-21', score: 82, status: 'active',
  },
  {
    id: 'lrn-008', name: 'Nafissatou Keita', role: 'Risk Manager', organization: 'Banque de Développement ECOWAS',
    country: 'Côte d\'Ivoire', modulesCompleted: 6, modulesEnrolled: 8, totalCpdHours: 84,
    currentModule: 'ESG & Finance Durable — ISSB 2026', progression: 65, certifications: ['KOS-CRB-F01', 'KOS-AMLE-E02', 'KOS-MFIN-M07'],
    lastActivity: '2026-06-24', score: 91, status: 'active',
  },
];

// ============================================================================
// CERTIFICATIONS
// ============================================================================
export const ACADEMY_CERTIFICATIONS: AcademyCertification[] = [
  {
    id: 'cert-001', code: 'KOS-CRB-F01',
    title: 'Certified Regulatory Banking Practitioner (UEMOA)',
    domain: 'Conformité Réglementaire', level: 'Foundation',
    issuedCount: 312, passRate: 89, validityMonths: 24,
    recognition: ['BCEAO', 'Commission Bancaire UMOA', 'GIABA'],
    icon: 'ri-bank-line', color: 'primary', lastIssued: '2026-06-24', autoGenerated: true,
  },
  {
    id: 'cert-002', code: 'KOS-AMLE-E02',
    title: 'Certified AML/CFT Expert — Africa Standards',
    domain: 'AML & Conformité', level: 'Expert',
    issuedCount: 187, passRate: 74, validityMonths: 18,
    recognition: ['GAFI/FATF', 'GIABA', 'GABAC', 'CENTIF'],
    icon: 'ri-shield-user-line', color: 'accent', lastIssued: '2026-06-23', autoGenerated: true,
  },
  {
    id: 'cert-003', code: 'KOS-BEPS-M03',
    title: 'BEPS Master — Transfer Pricing Africa Documentation',
    domain: 'Fiscalité Internationale', level: 'Master',
    issuedCount: 94, passRate: 68, validityMonths: 24,
    recognition: ['OCDE', 'CIR Sénégal', 'ANASIT Côte d\'Ivoire'],
    icon: 'ri-exchange-dollar-line', color: 'secondary', lastIssued: '2026-06-18', autoGenerated: false,
  },
  {
    id: 'cert-004', code: 'KOS-GOV-P04',
    title: 'Corporate Governance Practitioner (OHADA)',
    domain: 'Gouvernance', level: 'Practitioner',
    issuedCount: 198, passRate: 85, validityMonths: 24,
    recognition: ['OHADA', 'COBAC', 'Commission Bancaire UMOA'],
    icon: 'ri-government-line', color: 'primary', lastIssued: '2026-06-22', autoGenerated: true,
  },
  {
    id: 'cert-005', code: 'KOS-ESGE-E05',
    title: 'ESG & Sustainable Finance Expert (ISSB Africa)',
    domain: 'ESG & Durabilité', level: 'Expert',
    issuedCount: 67, passRate: 71, validityMonths: 18,
    recognition: ['ISSB', 'GRI', 'Banque Mondiale IFC', 'AFD'],
    icon: 'ri-leaf-line', color: 'accent', lastIssued: '2026-06-24', autoGenerated: true,
  },
  {
    id: 'cert-006', code: 'KOS-AUDI-E06',
    title: 'Certified Internal Auditor — COSO Africa Framework',
    domain: 'Audit & Risques', level: 'Expert',
    issuedCount: 123, passRate: 77, validityMonths: 24,
    recognition: ['IIA', 'COSO', 'COBAC'],
    icon: 'ri-search-eye-line', color: 'secondary', lastIssued: '2026-06-20', autoGenerated: false,
  },
  {
    id: 'cert-007', code: 'KOS-MFIN-M07',
    title: 'Microfinance Master — Conformité BCEAO 22 Instructions',
    domain: 'Microfinance', level: 'Master',
    issuedCount: 241, passRate: 82, validityMonths: 24,
    recognition: ['BCEAO', 'Commission Bancaire UMOA', 'ARM', 'AFMIN'],
    icon: 'ri-hand-coin-line', color: 'primary', lastIssued: '2026-06-23', autoGenerated: true,
  },
  {
    id: 'cert-008', code: 'KOS-DIGT-P08',
    title: 'Digital Resilience Practitioner — COBAC 2027 Standard',
    domain: 'Digital & Tech', level: 'Practitioner',
    issuedCount: 88, passRate: 79, validityMonths: 18,
    recognition: ['COBAC', 'BCEAO', 'ISO 27001 Preparedness'],
    icon: 'ri-computer-line', color: 'accent', lastIssued: '2026-06-22', autoGenerated: true,
  },
];

// ============================================================================
// PRODUCTION PIPELINE
// ============================================================================
export const ACADEMY_PIPELINE: AcademyProductionPipeline[] = [
  {
    id: 'pipe-001', moduleTitle: 'Finance Islamique UEMOA/CEMAC — Niveau Master',
    domain: 'Conformité Réglementaire', stage: 'validation', progress: 72,
    agentAssigned: 'KOS Knowledge Factory Agent™', estimatedDelivery: '2026-07-15',
    autoGenerated: true, priority: 'P0', kpiTarget: 'Lancement Q3 2026 — Module KOS auto-appris 24 Juin',
  },
  {
    id: 'pipe-002', moduleTitle: 'Cyber Résilience Bancaire DORA-COBAC 2027',
    domain: 'Digital & Tech', stage: 'scripting', progress: 35,
    agentAssigned: 'KOS Blog Writing Agent™', estimatedDelivery: '2026-07-30',
    autoGenerated: true, priority: 'P0', kpiTarget: 'Lancement Q3 2026 — Module KOS auto-appris 24 Juin',
  },
  {
    id: 'pipe-003', moduleTitle: 'Climate Stress Testing Pilier 2 — BCEAO/COBAC/NGFS',
    domain: 'ESG & Durabilité', stage: 'scripting', progress: 25,
    agentAssigned: 'KOS Knowledge Factory Agent™', estimatedDelivery: '2026-08-15',
    autoGenerated: true, priority: 'P1', kpiTarget: 'Lancement Q3 2026 — Module KOS auto-appris 24 Juin',
  },
  {
    id: 'pipe-004', moduleTitle: 'Tokenisation & Actifs Numériques — Cadre AMF-UMOA',
    domain: 'FinTech & Digital', stage: 'scripting', progress: 18,
    agentAssigned: 'KOS Regulatory Intelligence Agent™', estimatedDelivery: '2026-08-30',
    autoGenerated: true, priority: 'P1', kpiTarget: 'Lancement Q3 2026 — Module KOS auto-appris 24 Juin',
  },
  {
    id: 'pipe-005', moduleTitle: 'Monnaies Numériques Banque Centrale (e-CFA/CBDC)',
    domain: 'Politique Monétaire', stage: 'scripting', progress: 12,
    agentAssigned: 'KOS Regulatory Intelligence Agent™', estimatedDelivery: '2026-09-15',
    autoGenerated: true, priority: 'P2', kpiTarget: 'Lancement Q4 2026',
  },
  {
    id: 'pipe-006', moduleTitle: 'Agrément FinTech Établissement de Paiement — Dossier Complet',
    domain: 'FinTech & Digital', stage: 'review', progress: 88,
    agentAssigned: 'KOS Senior Compliance Auditor™', estimatedDelivery: '2026-07-05',
    autoGenerated: false, priority: 'P0', kpiTarget: 'Lancement immédiat — Demande forte marché',
  },
  {
    id: 'pipe-007', moduleTitle: 'Gestion Actif-Passif (ALM) Bancaire UEMOA',
    domain: 'Finance Bancaire', stage: 'validation', progress: 65,
    agentAssigned: 'KOS Knowledge Factory Agent™', estimatedDelivery: '2026-07-20',
    autoGenerated: false, priority: 'P1', kpiTarget: 'Demande DGs banques commerciales',
  },
  {
    id: 'pipe-008', moduleTitle: 'Résilience Opérationnelle — ISO 22301 Bancaire Afrique',
    domain: 'Risk Management', stage: 'published', progress: 100,
    agentAssigned: 'KOS Senior Compliance Auditor™', estimatedDelivery: '2026-06-28',
    autoGenerated: false, priority: 'P0', kpiTarget: 'Publié — 52 pré-inscrits',
  },
];

// ============================================================================
// KPIs
// ============================================================================
export const ACADEMY_KPIS: AcademyKPI[] = [
  {
    id: 'kpi-learners', name: 'Apprenants Actifs', icon: 'ri-user-heart-line', color: 'primary',
    current: 2080, target: 5000, unit: '', trend: 'up',
    history: [
      { month: 'Jan', value: 120 }, { month: 'Fév', value: 280 }, { month: 'Mar', value: 520 },
      { month: 'Avr', value: 890 }, { month: 'Mai', value: 1420 }, { month: 'Juin', value: 2080 },
    ],
  },
  {
    id: 'kpi-modules', name: 'Modules Publiés', icon: 'ri-book-open-line', color: 'accent',
    current: 8, target: 20, unit: '', trend: 'up',
    history: [
      { month: 'Jan', value: 0 }, { month: 'Fév', value: 2 }, { month: 'Mar', value: 4 },
      { month: 'Avr', value: 5 }, { month: 'Mai', value: 7 }, { month: 'Juin', value: 8 },
    ],
  },
  {
    id: 'kpi-certs', name: 'Certifications Délivrées', icon: 'ri-award-line', color: 'secondary',
    current: 1310, target: 3000, unit: '', trend: 'up',
    history: [
      { month: 'Jan', value: 0 }, { month: 'Fév', value: 48 }, { month: 'Mar', value: 185 },
      { month: 'Avr', value: 420 }, { month: 'Mai', value: 820 }, { month: 'Juin', value: 1310 },
    ],
  },
  {
    id: 'kpi-completion', name: 'Taux de Complétion', icon: 'ri-percent-line', color: 'primary',
    current: 67, target: 80, unit: '%', trend: 'up',
    history: [
      { month: 'Jan', value: 45 }, { month: 'Fév', value: 52 }, { month: 'Mar', value: 58 },
      { month: 'Avr', value: 62 }, { month: 'Mai', value: 65 }, { month: 'Juin', value: 67 },
    ],
  },
  {
    id: 'kpi-nps', name: 'NPS Academy', icon: 'ri-emotion-happy-line', color: 'accent',
    current: 9.2, target: 9.5, unit: '/10', trend: 'up',
    history: [
      { month: 'Jan', value: 7.8 }, { month: 'Fév', value: 8.2 }, { month: 'Mar', value: 8.5 },
      { month: 'Avr', value: 8.8 }, { month: 'Mai', value: 9.0 }, { month: 'Juin', value: 9.2 },
    ],
  },
  {
    id: 'kpi-cpd', name: 'Heures CPD Délivrées', icon: 'ri-time-line', color: 'secondary',
    current: 84600, target: 200000, unit: 'h', trend: 'up',
    history: [
      { month: 'Jan', value: 1800 }, { month: 'Fév', value: 8400 }, { month: 'Mar', value: 22500 },
      { month: 'Avr', value: 41200 }, { month: 'Mai', value: 62800 }, { month: 'Juin', value: 84600 },
    ],
  },
];

// ============================================================================
// GLOBAL STATS
// ============================================================================
export const ACADEMY_GLOBAL_STATS = {
  totalLearners: 2080,
  activeLearners: 1847,
  completedLearners: 233,
  totalModules: 8,
  liveModules: 8,
  modulesInPipeline: 8,
  totalCertifications: 1310,
  certificationTypes: 8,
  avgCompletionRate: 67,
  avgNPS: 9.2,
  totalCpdHours: 84600,
  countries: 17,
  institutions: 312,
  autoGeneratedContent: '78%',
  zeroExternalDependencies: true,
  launchDate: '2026-04-01',
  q4Target: 'Academy Auto-Générée — 5 000 apprenants, 20 modules, 3 000 certifications',
  trajectoryNote: 'Trajectoire Q4 2026 : 5K apprenants · 20 modules · 3K certifications · 17 pays · 100% auto-généré',
};