import type { DiagnosticAxisConfig } from '';

const PRIMARY = '#0ea5e9';

export const TRANSFO_DIGITALE_AXES: DiagnosticAxisConfig[] = [
  {
    id: 'strategie-digitale', titleFr: 'Stratégie Digitale', titleEn: 'Digital Strategy',
    descriptionFr: 'Vision digitale, roadmap, budget, alignement métier, sponsorship direction',
    descriptionEn: 'Digital vision, roadmap, budget, business alignment, executive sponsorship',
    icon: 'ri-road-map-line', color: '#0ea5e9', weight: 25,
    questions: [
      { id: 'td-sd-1', questionFr: "L'organisation dispose-t-elle d'une stratégie de transformation digitale formalisée avec une vision claire à 3-5 ans ?", questionEn: 'Does the organization have a formalized digital transformation strategy with a clear 3-5 year vision?', options: [{ value: 100, labelFr: 'Stratégie digitale documentée, approuvée par le Conseil, avec roadmap, budget dédié et KPI de succès', labelEn: 'Documented digital strategy, Board-approved, with roadmap, dedicated budget and success KPIs' }, { value: 60, labelFr: 'Stratégie définie mais non formalisée, budget partiel, sponsorship irrégulier', labelEn: 'Strategy defined but not formalized, partial budget, irregular sponsorship' }, { value: 25, labelFr: 'Quelques initiatives digitales isolées sans stratégie globale', labelEn: 'Some isolated digital initiatives without global strategy' }, { value: 0, labelFr: 'Aucune stratégie digitale, transformation non priorisée', labelEn: 'No digital strategy, transformation not prioritized' }] },
      { id: 'td-sd-2', questionFr: 'La transformation digitale est-elle pilotée au plus haut niveau (DG, CDO) avec des objectifs alignés sur la stratégie métier ?', questionEn: 'Is digital transformation driven at the highest level (CEO, CDO) with objectives aligned to business strategy?', options: [{ value: 100, labelFr: 'CDO ou équivalent nommé, comité de pilotage trimestriel, KPI digitaux intégrés au tableau de bord DG', labelEn: 'CDO or equivalent appointed, quarterly steering committee, digital KPIs integrated into CEO dashboard' }, { value: 60, labelFr: 'Responsable digital nommé mais sans comité de pilotage structuré, reporting ponctuel', labelEn: 'Digital manager appointed but no structured steering committee, ad hoc reporting' }, { value: 25, labelFr: 'Pilotage délégué à la DSI sans implication de la DG, pas d\'alignement métier', labelEn: 'Delegated to IT without CEO involvement, no business alignment' }, { value: 0, labelFr: 'Aucun pilotage, initiatives digitales portées par des individus sans mandat', labelEn: 'No steering, digital initiatives carried by individuals without mandate' }] },
      { id: 'td-sd-3', questionFr: 'Un budget dédié à la transformation digitale est-il alloué annuellement avec un suivi du ROI ?', questionEn: 'Is a dedicated digital transformation budget allocated annually with ROI tracking?', options: [{ value: 100, labelFr: 'Budget > 3% du CA, suivi ROI par initiative, comité d\'investissement digital, réallocation agile', labelEn: 'Budget > 3% revenue, ROI tracking per initiative, digital investment committee, agile reallocation' }, { value: 60, labelFr: 'Budget 1-3% du CA, suivi ROI partiel, allocation annuelle rigide', labelEn: 'Budget 1-3% revenue, partial ROI tracking, rigid annual allocation' }, { value: 25, labelFr: 'Budget < 1% du CA, pas de suivi ROI, investissements au coup par coup', labelEn: 'Budget < 1% revenue, no ROI tracking, ad hoc investments' }, { value: 0, labelFr: 'Pas de budget dédié, chaque projet digital financé sur les fonds propres sans vision', labelEn: 'No dedicated budget, each digital project self-funded without vision' }] },
    ],
  },
  {
    id: 'technologie', titleFr: 'Infrastructure Technologique', titleEn: 'Technology Infrastructure',
    descriptionFr: 'Cloud, architecture, cybersécurité, intégration, données, modernisation SI',
    descriptionEn: 'Cloud, architecture, cybersecurity, integration, data, IS modernization',
    icon: 'ri-cloud-line', color: '#7c3aed', weight: 25,
    questions: [
      { id: 'td-te-1', questionFr: "L'infrastructure IT est-elle modernisée (cloud, API-first, microservices) par rapport à vos pairs ?", questionEn: 'Is the IT infrastructure modernized (cloud, API-first, microservices) compared to your peers?', options: [{ value: 100, labelFr: 'Cloud-native ou hybride, architecture microservices, API gateway, CI/CD, infrastructure as code', labelEn: 'Cloud-native or hybrid, microservices architecture, API gateway, CI/CD, infrastructure as code' }, { value: 60, labelFr: 'Migration cloud en cours, API en développement, automatisation partielle', labelEn: 'Cloud migration ongoing, API in development, partial automation' }, { value: 25, labelFr: 'Infrastructure on-premise majoritaire, début de réflexion cloud', labelEn: 'Mostly on-premise infrastructure, early cloud consideration' }, { value: 0, labelFr: 'Infrastructure obsolète, pas de projet de modernisation', labelEn: 'Obsolete infrastructure, no modernization plan' }] },
      { id: 'td-te-2', questionFr: 'La cybersécurité est-elle gérée de manière proactive avec une protection adaptée aux menaces actuelles ?', questionEn: 'Is cybersecurity proactively managed with protection adapted to current threats?', options: [{ value: 100, labelFr: 'SOC 24/7, ISO 27001 ou équivalent, tests d\'intrusion réguliers, plan de réponse incident, formation continue du personnel', labelEn: 'SOC 24/7, ISO 27001 or equivalent, regular penetration tests, incident response plan, continuous staff training' }, { value: 60, labelFr: 'Périmètre de sécurité standard, quelques audits, pas de SOC dédié', labelEn: 'Standard security perimeter, some audits, no dedicated SOC' }, { value: 25, labelFr: 'Sécurité de base (antivirus, pare-feu), pas de stratégie cybersécurité formalisée', labelEn: 'Basic security (antivirus, firewall), no formalized cybersecurity strategy' }, { value: 0, labelFr: 'Cybersécurité inexistante ou obsolète, vulnérabilités critiques non corrigées', labelEn: 'Non-existent or obsolete cybersecurity, unpatched critical vulnerabilities' }] },
      { id: 'td-te-3', questionFr: 'La gestion des données est-elle mature : gouvernance, qualité, accessibilité, analytics avancé ?', questionEn: 'Is data management mature: governance, quality, accessibility, advanced analytics?', options: [{ value: 100, labelFr: 'Data governance en place, data quality monitoring, data lake/warehouse, BI self-service, IA/ML en production', labelEn: 'Data governance in place, data quality monitoring, data lake/warehouse, self-service BI, AI/ML in production' }, { value: 60, labelFr: 'Reporting BI centralisé, qualité données suivie, gouvernance partielle', labelEn: 'Centralized BI reporting, data quality tracked, partial governance' }, { value: 25, labelFr: 'Données en silos, reporting Excel, pas de gouvernance', labelEn: 'Data in silos, Excel reporting, no governance' }, { value: 0, labelFr: 'Données non fiables, inaccessibles, aucune capacité analytique', labelEn: 'Unreliable, inaccessible data, zero analytical capability' }] },
    ],
  },
  {
    id: 'processus-digital', titleFr: 'Digitalisation des Processus', titleEn: 'Process Digitization',
    descriptionFr: 'Automatisation, dématérialisation, expérience client digitale, workflow, signature électronique',
    descriptionEn: 'Automation, dematerialization, digital customer experience, workflow, e-signature',
    icon: 'ri-git-branch-line', color: '#059669', weight: 25,
    questions: [
      { id: 'td-pd-1', questionFr: 'Les processus métier clés sont-ils digitalisés de bout en bout (zéro papier, zéro ressaisie) ?', questionEn: 'Are key business processes digitized end-to-end (zero paper, zero re-entry)?', options: [{ value: 100, labelFr: '> 80% des processus digitalisés, workflow automatisés, signature électronique, archivage numérique certifié', labelEn: '> 80% digitized processes, automated workflows, e-signature, certified digital archiving' }, { value: 60, labelFr: '40-80% des processus digitalisés, persistance de quelques étapes papier', labelEn: '40-80% digitized processes, some paper steps persist' }, { value: 25, labelFr: '< 40% des processus digitalisés, nombreux traitements manuels', labelEn: '< 40% digitized processes, numerous manual treatments' }, { value: 0, labelFr: 'Processus entièrement papier, aucune digitalisation', labelEn: 'Fully paper processes, no digitization' }] },
      { id: 'td-pd-2', questionFr: "L'expérience client est-elle digitalisée : portail self-service, parcours omnicanal, chatbot ?", questionEn: 'Is customer experience digitized: self-service portal, omnichannel journey, chatbot?', options: [{ value: 100, labelFr: 'Portail client complet, parcours omnicanal fluide, chatbot/IA conversationnelle, NPS digital mesuré', labelEn: 'Complete client portal, smooth omnichannel journey, conversational AI/chatbot, measured digital NPS' }, { value: 60, labelFr: 'Portail client basique, parcours multicanal mais non intégré, FAQ en ligne', labelEn: 'Basic client portal, multi-channel but non-integrated journey, online FAQ' }, { value: 25, labelFr: 'Présence en ligne basique, pas de self-service, relation client majoritairement physique/téléphone', labelEn: 'Basic online presence, no self-service, mainly physical/phone client relationship' }, { value: 0, labelFr: 'Aucune digitalisation de l\'expérience client, 100% présentiel', labelEn: 'No customer experience digitization, 100% in-person' }] },
    ],
  },
  {
    id: 'culture-competences', titleFr: 'Culture & Compétences Digitales', titleEn: 'Digital Culture & Skills',
    descriptionFr: 'Formation, acculturation, recrutement tech, gestion du changement, agilité',
    descriptionEn: 'Training, acculturation, tech recruitment, change management, agility',
    icon: 'ri-user-star-line', color: '#d97706', weight: 25,
    questions: [
      { id: 'td-cc-1', questionFr: "Un programme de montée en compétences digitales est-il déployé pour l'ensemble des collaborateurs ?", questionEn: 'Is a digital upskilling program deployed for all employees?', options: [{ value: 100, labelFr: 'Plan de formation digital pour 100% des collaborateurs, parcours personnalisés, certifications, budget formation > 2% masse salariale', labelEn: 'Digital training plan for 100% employees, personalized paths, certifications, training budget > 2% payroll' }, { value: 60, labelFr: 'Formations digitales disponibles mais non obligatoires, taux de complétion < 50%', labelEn: 'Digital training available but non-mandatory, completion rate < 50%' }, { value: 25, labelFr: 'Quelques formations ponctuelles, pas de plan structuré de montée en compétences', labelEn: 'Some ad hoc training, no structured upskilling plan' }, { value: 0, labelFr: 'Aucune formation digitale, fossé de compétences technologiques', labelEn: 'No digital training, technology skills gap' }] },
      { id: 'td-cc-2', questionFr: "L'organisation a-t-elle adopté des méthodes agiles et une culture de l'innovation (test & learn, droit à l'erreur) ?", questionEn: 'Has the organization adopted agile methods and an innovation culture (test & learn, right to fail)?', options: [{ value: 100, labelFr: 'Agilité déployée au-delà de l\'IT, squads/tribus, cycles itératifs, culture test & learn, célébration des échecs apprenants', labelEn: 'Agility deployed beyond IT, squads/tribes, iterative cycles, test & learn culture, celebration of learning failures' }, { value: 60, labelFr: 'Agilité dans les équipes IT uniquement, début d\'adoption dans le métier', labelEn: 'Agility in IT teams only, early business adoption' }, { value: 25, labelFr: 'Méthodes traditionnelles (cycle en V), résistance au changement, aversion au risque', labelEn: 'Traditional methods (waterfall), resistance to change, risk aversion' }, { value: 0, labelFr: 'Culture rigide, hostilité à l\'innovation, sanction de l\'échec', labelEn: 'Rigid culture, hostility to innovation, failure sanction' }] },
      { id: 'td-cc-3', questionFr: "L'organisation attire-t-elle et retient-elle les talents digitaux (data scientists, devs, UX, cybersécurité) ?", questionEn: 'Does the organization attract and retain digital talent (data scientists, devs, UX, cybersecurity)?', options: [{ value: 100, labelFr: 'Marque employeur tech attractive, rémunération compétitive, stack technologique moderne, télétravail, plan de carrière tech', labelEn: 'Attractive tech employer brand, competitive compensation, modern tech stack, remote work, tech career path' }, { value: 60, labelFr: 'Quelques profils tech recrutés mais turnover élevé, difficultés à pourvoir les postes clés', labelEn: 'Some tech profiles recruited but high turnover, difficulty filling key positions' }, { value: 25, labelFr: 'Pas de politique de recrutement tech, dépendance aux prestataires externes', labelEn: 'No tech recruitment policy, dependence on external providers' }, { value: 0, labelFr: 'Aucun talent digital, fuite des compétences, obsolescence technique', labelEn: 'No digital talent, brain drain, technical obsolescence' }] },
    ],
  },
];

export function getTransfoDigitaleScoreColor(s: number): string { if (s >= 80) return '#059669'; if (s >= 60) return '#0ea5e9'; if (s >= 40) return '#d97706'; return '#dc2626'; }
export function getTransfoDigitaleScoreLabel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Leader Digital':'Digital Leader'; if (s>=60) return f?'Digital Avancé':'Advanced Digital'; if (s>=40) return f?'Digital Émergent':'Emerging Digital'; return f?'Retard Digital':'Digital Laggard'; }
export function getTransfoDigitaleLevel(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Niveau 4 — Digital Native':'Level 4 — Digital Native'; if (s>=60) return f?'Niveau 3 — Digital Adopter':'Level 3 — Digital Adopter'; if (s>=40) return f?'Niveau 2 — Digital Explorer':'Level 2 — Digital Explorer'; return f?'Niveau 1 — Digital Beginner':'Level 1 — Digital Beginner'; }
export function getTransfoDigitaleReadiness(s: number, lang: string): string { const f=!lang.startsWith('en'); if (s>=80) return f?'Votre organisation est un leader digital. Continuez à innover et à anticiper les ruptures technologiques pour maintenir votre avantage concurrentiel.':'Your organization is a digital leader. Continue innovating and anticipating technological disruptions to maintain your competitive advantage.'; if (s>=60) return f?'Votre transformation digitale est bien engagée. Consolidez vos acquis sur les axes les plus faibles et accélérez sur l\'innovation pour atteindre le leadership.':'Your digital transformation is well underway. Consolidate your gains on the weakest axes and accelerate innovation to reach leadership.'; if (s>=40) return f?'Votre transformation digitale est émergente. Structurer votre stratégie, moderniser votre infrastructure et développer les compétences sont les priorités.':'Your digital transformation is emerging. Structuring your strategy, modernizing your infrastructure and developing skills are priorities.'; return f?'Votre organisation accuse un retard digital critique. Sans action urgente, le fossé technologique avec vos concurrents deviendra insurmontable.':'Your organization has a critical digital lag. Without urgent action, the technology gap with your competitors will become insurmountable.'; }

export function getTransfoDigitaleRisks(perAxis: Record<string,number>, gs: number, lang: string): string[] {
  const f=!lang.startsWith('en'); const r:string[]=[];
  if ((perAxis['strategie-digitale']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Absence de stratégie digitale : pas de vision, pas de budget, pas de pilotage — la transformation ne se fera pas':'HIGH RISK — No digital strategy: no vision, no budget, no steering — transformation will not happen');
  if ((perAxis['technologie']??0)<50) r.push(f?'RISQUE CRITIQUE — Infrastructure obsolète : pas de cloud, cybersécurité défaillante, données non exploitables — risque de panne, cyberattaque et perte de compétitivité':'CRITICAL RISK — Obsolete infrastructure: no cloud, failing cybersecurity, unusable data — breakdown, cyberattack and competitiveness loss risk');
  if ((perAxis['processus-digital']??0)<50) r.push(f?'RISQUE MAJEUR — Processus non digitalisés : inefficience opérationnelle, expérience client dégradée, coûts excessifs':'MAJOR RISK — Non-digitized processes: operational inefficiency, degraded customer experience, excessive costs');
  if ((perAxis['culture-competences']??0)<50) r.push(f?'RISQUE ÉLEVÉ — Déficit de culture et compétences digitales : incapacité à exécuter la transformation, fuite des talents, résistance au changement':'HIGH RISK — Digital culture and skills deficit: inability to execute transformation, brain drain, resistance to change');
  return r;
}

export function getTransfoDigitaleRecommendations(perAxis: Record<string,number>, gs: number, lang: string): {title:string;axis?:string;items:string[]}[] {
  const f=!lang.startsWith('en'); const recs:{title:string;axis?:string;items:string[]}[]=[];
  if ((perAxis['strategie-digitale']??0)<60) recs.push({title:f?'Définir la Stratégie Digitale':'Define Digital Strategy',axis:'strategie-digitale',items:f?['Formaliser une stratégie digitale à 3-5 ans avec vision, objectifs et KPI','Nommer un CDO ou sponsor exécutif avec mandat et budget','Allouer un budget dédié (>3% du CA) avec suivi du ROI']:['Formalize a 3-5 year digital strategy with vision, objectives and KPIs','Appoint a CDO or executive sponsor with mandate and budget','Allocate dedicated budget (>3% revenue) with ROI tracking']});
  if ((perAxis['technologie']??0)<60) recs.push({title:f?'Moderniser l\'Infrastructure':'Modernize Infrastructure',axis:'technologie',items:f?['Lancer une migration cloud avec architecture API-first','Mettre en place un SOC et viser la certification ISO 27001','Structurer la gouvernance des données avec un data lake et de la BI self-service']:['Launch cloud migration with API-first architecture','Set up a SOC and target ISO 27001 certification','Structure data governance with a data lake and self-service BI']});
  if ((perAxis['processus-digital']??0)<60) recs.push({title:f?'Digitaliser les Processus':'Digitize Processes',axis:'processus-digital',items:f?['Identifier et digitaliser les processus prioritaires avec workflow automatisés','Déployer un portail client self-service avec parcours omnicanal','Dématérialiser 100% des documents avec signature électronique']:['Identify and digitize priority processes with automated workflows','Deploy a self-service client portal with omnichannel journey','Dematerialize 100% of documents with e-signature']});
  if ((perAxis['culture-competences']??0)<60) recs.push({title:f?'Développer la Culture Digitale':'Develop Digital Culture',axis:'culture-competences',items:f?['Déployer un plan de formation digital pour 100% des collaborateurs','Adopter les méthodes agiles au-delà de l\'IT','Créer une marque employeur tech attractive pour recruter les talents']:['Deploy a digital training plan for 100% of employees','Adopt agile methods beyond IT','Create an attractive tech employer brand to recruit talent']});
  if (recs.length===0) recs.push({title:f?'Maintenir le Leadership Digital':'Maintain Digital Leadership',items:f?['Investir dans l\'innovation de rupture (IA, blockchain, IoT)','Développer un écosystème de partenaires tech','Partager votre expérience de transformation digitale']:['Invest in disruptive innovation (AI, blockchain, IoT)','Develop a tech partner ecosystem','Share your digital transformation experience']});
  return recs;
}


export const getTransfoDigitaleScoreColor = { id: 1, label: "Stub data" }; // stub
export const getTransfoDigitaleScoreLabel = { id: 1, label: "Stub data" }; // stub
export const getTransfoDigitaleLevel = { id: 1, label: "Stub data" }; // stub
export const getTransfoDigitaleReadiness = { id: 1, label: "Stub data" }; // stub
export const getTransfoDigitaleRisks = { id: 1, label: "Stub data" }; // stub
export const getTransfoDigitaleRecommendations = { id: 1, label: "Stub data" }; // stub



