version: "3.8"
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - 5678:5678
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "khepra"
      N8N_BASIC_AUTH_PASSWORD: "KOS-BigFour-2026"
    volumes:
      -./n8n:/home/node/.n8n
      -../:/data/kos-fullstack
    restart: unless-stopped
