const common = {
  faq: {
    title: 'Laaj yi gën a laaj', badge: 'FAQ',
    description: 'Gisal tontu yi ñu gën a laaj ci sunu yitteefi ag cëslaay bu xellu, kontaab bu ñu xool, nguur gu koom-koom, soppi gu njëkkal ak sunu barab yi ñuy def ak jëfandikook ay toolukaay yu bees ci Afrig.',
    q1: 'Lu tax nga war a tànn KHEPRA EXPERTS niki ab cëslaay bu koom-koom ci Afrig ?',
    a1: 'KHEPRA EXPERTS mooy ab cëslaay bu Afrig bu ñu tànn, am na lu ëpp 22 at ci xam-xamu ligeey ci Afrig gu Sowwu ak gu Diggu. Nu bokkal xam-xamu deret yi (Togo, Gabon, UEMOA, CEMAC) ak xam-xamu adduna bu yàgg ci nguur gu koom-koom, kontaab bu koom-koom, toftali ak BCEAO ak soppi gu njëkkal.',
    q2: 'Ban xeeti mbootaay yi ngeen di jàppe ci cëslaay bu xellu ?',
    a2: 'Nu ngiy jàppe PME, startups, cëru koomi nataal, mbootaay yu mag, ONG, cëru yu njëkk ak mbootaay yu adduna ci Afrig.',
  },
  contact: { title: 'Jokkoo ak Ñun', subtitle: 'Waxal ci sa poroje bu xellu, kontaab bu koom-koom wala soppi gu koom-koom', name: 'Turam bu ànd', email: 'Imeel', phone: 'Telfon', company: 'Mbootaay', message: 'Bataaxal', submit: 'Yonnee', sending: 'Di yonnee…', success: 'Bataaxal bi yonnee nañu ko ! Dinañu tontu ci 24 waxtu.', error: 'Dafa am njuréef. Tëtalal ñaari yoon.', address: 'Adarees', addressText: 'Lomé, Togo' },
  footer: { tagline: 'Sa àndandoo bu xellu ci cëslaay, kontaab bu koom-koom, nguur ak soppi gu njëkkal ngir cëgg gu yàgg ci Afrig', quickLinks: 'Yoon yu Nelaw', services: 'Cër yu Jëm', about: 'Ci Wàllu Ñun', blog: 'Blog', contact: 'Jokkoo', legalLinks: 'Yoonu Yonni', privacy: 'Politig bu Sutura', terms: 'Digal yi', followUs: 'Toppal Ñu', rights: 'Sañ-sañ yi ñépp aaru nañu.' },
  common: { learnMore: 'Jàng lu ëpp' },
  cta: { diagnostic_free: 'Diagnostic bu amul njëg', diagnostic_subtitle: 'Tontu ci 2 waxtu · Amul yéene' },
  leadMagnet: { whitepaper: { title: 'Yokkal Sunu Xët wu Weex', description: 'Xoolal bu xóot ak digal yi am solo.', button: 'Yokkal Xët wi Weex' }, webinar: { title: 'Dugal ci Sunu Webinaire bu Ñëw', description: 'Waxale ci yoon ak sunu xam-xamkat yi.', button: 'Saytu ci Webinaire bi' }, diagnostic: { title: 'Diagnostic bu Xellu bu Amul Njëg', description: '30 simili ak ab xam-xamkat ngir xool sa nekkiin.', button: 'Tàmbali diagnostic bi' }, newsletter: { title: 'Nangu Sunu Bataaxal bu Xellu', description: 'Xoolal yu ñuy jox, ci sa imeel.', button: 'Saytu ci Bataaxal bi' } },
  monitoring: { title: 'Toppatoo bu Xarala', subtitle: 'Njuréef 404 ak yoonu tontu', loading: 'Di yebbi dooné…', retry: 'Tëtalal', timeRange: { '24h': '24 waxtu', '7d': '7 fan', '30d': '30 fan' }, stats: { total404: 'Njuréef 404', total404Sub: 'Xët yi amul', totalErrors: 'Njuréef HTTP/JS', totalErrorsSub: 'Cëri laaj ak script', avgResponse: 'Diggante bi API', avgResponseSub: 'ms', avgPageLoad: 'Yebbi xët', avgPageLoadSub: 'ms' }, notFound: { title: 'URL 404 yi ëpp', subtitle: 'Xët yi ñu gën a wuute', url: 'URL', count: 'Yoon', empty: 'Amul njuréef 404' }, performance: { title: 'Waxtu Tontu API', subtitle: 'Diggante ak ëpp', tooltipAvg: 'Digg', tooltipMax: 'Ëpp', tooltipCount: 'Cëri laaj', empty: 'Amul dooné' }, topErrors: { title: 'Njuréef yi ëpp', subtitle: 'Njuréef yi gën a wuute', empty: 'Amul njuréef' }, errorLog: { title: 'Teral njuréef', subtitle: 'Njuréef yi mujj', type: 'Melo', message: 'Bataaxal', url: 'URL', date: 'Bés', empty: 'Amul njuréef bu mujj' }, navigation: { title: 'Yëngu', subtitle: 'Waxtu yebbi xët', empty: 'Amul dooné' } },
  dashboard: { login: { title: 'Tableau de bord', subtitle: 'Jotale doolekat yi rekk', passwordLabel: 'Baati mbëjfeppal', passwordPlaceholder: 'Dugalal baati mbëjfeppal bi', loginButton: 'Dugg', incorrectPassword: 'Baati mbëjfeppal bi dafa juum' }, header: { title: 'Tableau de bord', subtitle: 'Toppatoo soppi ak liggéey', timeRange: { '7d': '7 fan', '30d': '30 fan', '90d': '90 fan', all: 'Lépp' }, refreshButton: 'Yeesal' }, loading: 'Di yebbi dooné…', kpis: { totalLeads: { title: 'Leads yi Lépp', subtitle: 'yu bees' } }, pipeline: { title: 'Pipelineu soppi' }, sources: { title: 'Kaw yi' }, formTypes: { title: 'Liggéey ci melo formulaire', ofTotal: 'ci lépp' }, recentLeads: { title: 'Leads yu mujj', table: { date: 'Bés', contact: 'Jokkoo', organization: 'Mbootaay', type: 'Melo', score: 'Lim', status: 'Nekkiin', source: 'Kaw' } }, status: { new: 'Bees', meeting_scheduled: 'Daje def nañu ko', qualified: 'Mooy am solo', converted: 'Soppi nañu ko', lost: 'Rébb na' }, formType: { contact: 'Jokkoo', diagnostic: 'Diagnostic', expert: 'Xam-xamkat', newsletter: 'Bataaxal' }, metrics: { toolCompletions: { title: 'Jumtukaay yi ñu jeexal', subtitle: 'Diagnostic yi' } }, diagnostics: { title: 'Diagnostic yu mujj', table: { date: 'Bés', tool: 'Jumtukaay', score: 'Lim' } }, downloads: { title: 'Yokkal yi mujj', table: { date: 'Bés', resource: 'Jëfandikukaay', contact: 'Jokkoo', country: 'Réew' }, unknownResource: 'Jëfandikukaay buñ xamul' }, noData: 'Amul dooné', retry: 'Tëtalal' },
};
export default common;