const common = {
  faq: { title: '常见问题', badge: 'FAQ', description: '查找关于我们服务的最常见问题的答案。' },
  contact: { title: '联系我们', subtitle: '与我们讨论您的战略项目', name: '全名', email: '电子邮件', phone: '电话', company: '组织', message: '留言', submit: '发送', sending: '发送中…', success: '消息发送成功！', error: '发生错误。', address: '地址', addressText: '多哥洛美' },
  footer: { tagline: '您在咨询、财务审计、治理和数字化转型方面的战略合作伙伴', quickLinks: '快速链接', services: '服务', about: '关于我们', blog: '博客', contact: '联系我们', legalLinks: '法律', privacy: '隐私政策', terms: '使用条款', followUs: '关注我们', rights: '版权所有。' },
  common: { learnMore: '了解更多' },
  cta: { diagnostic_free: '免费诊断', diagnostic_subtitle: '2小时内回复 · 无义务' },
  leadMagnet: { whitepaper: { title: '下载我们的白皮书', description: '深入分析和可操作的建议。', button: '下载白皮书' }, webinar: { title: '加入我们的网络研讨会', description: '与我们的专家实时交流。', button: '注册网络研讨会' }, diagnostic: { title: '免费战略诊断', description: '与专家交流30分钟，分析您的情况。', button: '开始诊断' }, newsletter: { title: '接收我们的战略通讯', description: '独家分析直接发送到您的邮箱。', button: '订阅通讯' } },
  monitoring: { title: '技术监控', subtitle: '404错误和响应时间', loading: '加载数据中…', retry: '重试', timeRange: { '24h': '24小时', '7d': '7天', '30d': '30天' }, stats: { total404: '404错误', total404Sub: '缺失页面', totalErrors: 'HTTP/JS错误', totalErrorsSub: '请求和脚本', avgResponse: '平均API时间', avgResponseSub: '毫秒', avgPageLoad: '页面加载', avgPageLoadSub: '毫秒' }, notFound: { title: '热门404 URL', subtitle: '最常缺失的页面', url: 'URL', count: '次数', empty: '未检测到错误' }, performance: { title: 'API响应时间', subtitle: '平均值和最大值', tooltipAvg: '平均', tooltipMax: '最大', tooltipCount: '请求', empty: '无数据' }, topErrors: { title: '主要错误', subtitle: '最常见错误', empty: '无错误' }, errorLog: { title: '错误日志', subtitle: '最近错误', type: '类型', message: '消息', url: 'URL', date: '日期', empty: '无最近错误' }, navigation: { title: '导航', subtitle: '页面加载时间', empty: '无数据' } },
  dashboard: { login: { title: '仪表板', subtitle: '管理员访问', passwordLabel: '密码', passwordPlaceholder: '输入密码', loginButton: '登录', incorrectPassword: '密码不正确' }, header: { title: '仪表板', subtitle: '转化和性能跟踪', timeRange: { '7d': '7天', '30d': '30天', '90d': '90天', all: '全部' }, refreshButton: '刷新' }, loading: '加载数据中…', kpis: { totalLeads: { title: '总线索', subtitle: '新' } }, pipeline: { title: '转化管道' }, sources: { title: '获取来源' }, formTypes: { title: '按表单类型表现', ofTotal: '占总计' }, recentLeads: { title: '最近线索', table: { date: '日期', contact: '联系人', organization: '组织', type: '类型', score: '分数', status: '状态', source: '来源' } }, status: { new: '新', meeting_scheduled: '已安排会议', qualified: '合格', converted: '已转化', lost: '丢失' }, formType: { contact: '联系', diagnostic: '诊断', expert: '专家', newsletter: '通讯' }, metrics: { toolCompletions: { title: '已完成工具', subtitle: '诊断' } }, diagnostics: { title: '最近诊断', table: { date: '日期', tool: '工具', score: '分数' } }, downloads: { title: '最近下载', table: { date: '日期', resource: '资源', contact: '联系人', country: '国家' }, unknownResource: '未知资源' }, noData: '无数据', retry: '重试' },
};

export default common;