import { useState, useCallback } from 'react';
import { supabase } from '@/lib/supabase';

interface AISummaryResponse {
  success?: boolean;
  summary?: string;
  keywords?: string[];
  title?: string;
  tokens_used?: number;
  model?: string;
  engine?: string;
  method?: string;
  autonomous?: boolean;
  error?: string;
  status?: string;
  message?: string;
}

interface ArticleAISummaryProps {
  articleContent: string | string[];
  articleTitle: string;
  articleId: string;
  isEn?: boolean;
  className?: string;
}

export default function ArticleAISummary({ articleContent, articleTitle, articleId, isEn = false, className = '' }: ArticleAISummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [keywords, setKeywords] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generated, setGenerated] = useState(false);
  const [engine, setEngine] = useState<string>('kos-automaton-v2');

  const generateSummary = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const { data, error: fnError } = await supabase.functions.invoke('kos-automaton-engine', {
        body: {
          operation: 'summarize',
          content: articleContent,
          titre: articleTitle,
          langue: isEn ? 'en' : 'fr',
        },
      });

      if (fnError) {
        const msg = fnError.message || '';
        throw new Error(msg || 'Erreur edge function');
      }

      const response = data as AISummaryResponse;

      if (response.error) {
        throw new Error(response.error);
      }

      if (response.summary) {
        setSummary(response.summary);
        setKeywords(response.keywords || []);
        setEngine(response.engine || 'kos-automaton-v2');
        setGenerated(true);
      } else {
        throw new Error('Réponse vide du moteur KOS Automaton');
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Erreur inconnue';
      setError(message);
    } finally {
      setLoading(false);
    }
  }, [articleContent, articleTitle, isEn]);

  if (generated && summary) {
    return (
      <div className={`rounded-2xl border border-primary-200 bg-gradient-to-br from-primary-50/60 to-background-50 p-5 sm:p-6 ${className}`}>
        <div className="flex items-center gap-2 mb-3">
          <div className="w-8 h-8 rounded-lg bg-primary-500 flex items-center justify-center">
            <i className="ri-brain-line text-white text-sm" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-foreground-950">
              {isEn ? 'Executive Summary' : 'Résumé Exécutif'}
            </h4>
            <p className="text-[10px] text-foreground-400">
              {isEn
                ? `Generated by KOS Automaton — 100% autonomous, zero external dependency`
                : `Généré par KOS Automaton — 100% autonome, zéro dépendance externe`}
            </p>
          </div>
        </div>
        <div className="text-sm text-foreground-700 leading-relaxed whitespace-pre-line">
          {summary}
        </div>
        {keywords.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mt-3 pt-3 border-t border-primary-100">
            {keywords.slice(0, 6).map((kw) => (
              <span
                key={kw}
                className="px-2.5 py-0.5 bg-primary-100/70 text-primary-800 rounded-md text-xs font-medium whitespace-nowrap"
              >
                {kw}
              </span>
            ))}
          </div>
        )}
        <div className="mt-3 flex items-center gap-2 text-[10px] text-foreground-400">
          <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-background-100 rounded-full">
            <i className="ri-sparkling-line text-xs"></i>
            {engine}
          </span>
          <span>{isEn ? 'Extractive • TF-IDF • Zero API cost' : 'Extractif • TF-IDF • Zéro coût API'}</span>
        </div>
      </div>
    );
  }

  return (
    <div className={`rounded-2xl border border-background-200 bg-background-50 p-5 sm:p-6 ${className}`}>
      <div className="flex items-center gap-3 mb-4">
        <div className="w-8 h-8 rounded-lg bg-secondary-100 flex items-center justify-center">
          <i className="ri-sparkling-line text-foreground-500 text-sm" />
        </div>
        <div>
          <h4 className="text-sm font-bold text-foreground-950">
            {isEn ? 'Executive Summary' : 'Résumé Exécutif'}
          </h4>
          <p className="text-[10px] text-foreground-400">
            {isEn ? 'Powered by KOS Automaton — 100% internal' : 'Propulsé par KOS Automaton — 100% interne'}
          </p>
        </div>
      </div>

      <p className="text-xs text-foreground-500 mb-4 leading-relaxed">
        {isEn
          ? 'Generate an executive summary of this article in 3 key points. Extractive AI — zero external API, fully autonomous.'
          : 'Générez un résumé exécutif de cet article en 3 points clés. IA extractive — zéro API externe, 100% autonome.'}
      </p>

      {error && (
        <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-xs text-red-700 flex items-start gap-2">
          <i className="ri-error-warning-line mt-0.5 flex-shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <button
        onClick={generateSummary}
        disabled={loading}
        className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary-500 text-white font-semibold text-sm hover:bg-primary-600 transition-all disabled:opacity-60 disabled:cursor-not-allowed cursor-pointer whitespace-nowrap"
      >
        {loading ? (
          <>
            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
            {isEn ? 'Generating...' : 'Génération en cours...'}
          </>
        ) : (
          <>
            <i className="ri-brain-line" />
            {isEn ? 'Generate Summary' : 'Générer le Résumé'}
          </>
        )}
      </button>
    </div>
  );
}



